/**
 * v2 rewrite batch 5: data-science Weeks 23-27
 *  W23: Energy Forecast v0.3 — Prophet model
 *  W24: Energy Forecast v0.4 — LSTM (PyTorch)
 *  W25: MLOps — MLflow + drift monitoring
 *  W26: Cloud + BigQuery for Data Scientists
 *  W27: Energy Forecast v1.0 — Ship + retro
 */

import { rewriteWeek } from "../rewrite-week";

// ─── W23 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 23, {
  context: `ARIMA gave you a model that understood the weekly cycle and the slow trend. It missed the spikes. This week you try a different tool -- one built specifically for the kind of messy, holiday-interrupted, seasonality-stacked time series that real businesses actually have.

Prophet was released by Facebook's Core Data Science team in 2017. The team built it because they needed a forecasting model that non-specialists could tune, that handled missing data gracefully, that understood holidays automatically, and that did not require the analyst to manually identify trend changepoints. AEP hourly electricity demand is exactly the kind of series Prophet was designed for: strong daily seasonality, strong weekly seasonality, an annual seasonal pattern, and demand that drops sharply on Thanksgiving and Christmas because factories shut down.

The key conceptual shift from ARIMA is that Prophet is additive decomposition turned into a fitting problem. You tell it your seasonality periods, your holiday calendar, and whether the trend is linear or logistic, and it fits those components simultaneously using Stan (a probabilistic programming language) under the hood. You do not difference the series yourself or choose p and q parameters -- you choose whether the trend looks linear or curved, and whether the seasonality should be additive (the amplitude is constant) or multiplicative (the amplitude grows with the level). For electricity demand, multiplicative usually wins because summer peaks are larger than winter peaks in absolute megawatt terms.

The holidays argument is the part that reliably surprises people. You pass a dataframe of holiday dates, and Prophet learns a separate effect for each holiday -- Thanksgiving demand might be 15% below a normal Thursday, Christmas might be 25% below. That granularity is something ARIMA cannot express without feature engineering. AEP's own forecasting team uses holiday adjustments as a matter of course, because missing them produces the most embarrassing and predictable forecast errors.

By Sunday: a fitted Prophet model with US holidays included, a components plot showing trend + weekly + yearly + holiday effects separately, and an updated README table comparing MAE for persistence, ARIMA, and Prophet on the same test set. The comparison table is the deliverable -- three models, one honest scoreboard.`,

  pre_flight: `Before fitting Prophet, look up the US federal holidays for 2017 (the last full year in your test window). Write down the three holidays you expect to have the biggest impact on AEP demand -- and your prediction of whether each one pushes demand up or down relative to a normal day. Factories, offices, and commercial buildings shutting down is the mechanism. After you fit the model, the components plot will show you the actual estimated effect for each holiday. Check your predictions against it.`,

  mastery_questions: [
    `Install prophet and prepare your DataFrame in the format Prophet requires: two columns named ds (datetime) and y (the value). Use the daily resampled series. Paste the head of the prepared DataFrame and df.dtypes. The ds column must be datetime, not a string -- Prophet will silently misbehave if you pass strings. Fit the model with model.fit(df_train) and paste the output lines confirming the Stan optimiser converged. If it did not converge, the fit is unreliable.`,
    `Create the US holidays DataFrame with make_holidays_df(year_list=[2004,2005,...,2018], country='US') and pass it as the holidays argument when initialising Prophet. Refit and paste the first 10 rows of the holidays DataFrame. Now look at the components plot (model.plot_components(forecast)) and find the holiday subplot. Which holiday has the largest negative effect on demand? Is it the one you predicted in pre-flight? Write one sentence about the mechanism -- why that specific holiday causes the dip.`,
    `Fit two versions of the model: one with seasonality_mode='additive' and one with 'multiplicative'. Generate forecasts for both. Paste the test-set MAE for each. Which wins on the AEP data? Now explain in one sentence why multiplicative seasonality makes physical sense for electricity demand (hint: the absolute swing in megawatts between a summer weekday peak and a summer overnight trough is larger than the equivalent swing in winter).`,
    `Generate a 90-day forecast and plot it against actuals using model.plot(forecast). Paste the plot. The shaded band is Prophet's uncertainty interval -- wider means less confident. Where does it widen most? (Usually: further into the forecast, and around holidays where historical patterns are sparse.) Compare the forecast visually to your ARIMA forecast from week 22. Where does Prophet track better? Where does ARIMA track better?`,
    `Update the README comparison table with all three models: persistence baseline, ARIMA, Prophet. Columns: model, MAE, RMSE, notes. Paste the table. Write one honest sentence under it summarising which model you would choose for production and why -- factoring in accuracy, interpretability, and maintenance complexity. "Prophet wins on MAE" is a complete answer only if it also wins on every other axis. Usually it does not.`,
  ],

  common_mistakes: [
    `Passing the hourly series directly to Prophet. Prophet on hourly data with yearly seasonality requires fourier_order tuning that takes significant compute and expertise. Resample to daily, fit on daily, then extrapolate back to hourly if needed.`,
    `Not checking for Stan convergence. Prophet prints warnings when the optimiser does not converge. A non-converged fit produces a forecast that looks plausible but is not reliable. Always read the fit output, not just the chart.`,
    `Forgetting to call make_future_dataframe before generating a forecast. Prophet requires you to create a future DataFrame explicitly: future = model.make_future_dataframe(periods=90). Calling predict on anything else produces an error or an empty result.`,
    `Using additive seasonality when the series has growth. If the level of the series changes significantly over the training window (AEP demand fell from 2008 to 2018), multiplicative seasonality better represents the changing amplitude of peaks and troughs.`,
    `Comparing models on different test sets. All three models (persistence, ARIMA, Prophet) must be evaluated on the exact same held-out window to produce a fair comparison table. If you used different split dates, the comparison is meaningless.`,
  ],

  debug_help: `Two Prophet-specific issues. First: "ValueError: Found NaN in column y." Prophet will not fit on NaN values. Run df['y'].isna().sum() before fitting, and either drop or forward-fill any gaps. Second: the components plot shows a holiday effect of exactly zero for some holidays. This means those dates did not appear in the training set -- either the holiday happened only in the test window, or the date format did not match. Check that your holiday dates align with the ds column format (both should be pandas Timestamps, not strings). If holiday effects look suspiciously uniform across all holidays, your make_holidays_df call may be passing the wrong country code.`,

  ai_assist: `Use Claude to explain the difference between Prophet's Fourier series representation of seasonality and ARIMA's autoregressive representation. Ask "why does Prophet use Fourier terms for seasonality instead of ARIMA-style lags?" The answer changes how you think about both models. Do NOT ask Claude to choose your seasonality mode or changepoint parameters -- those decisions depend on your specific series, and making them yourself with a reasoning sentence ("I chose multiplicative because the peak amplitude scales with the level") is what you will be asked to defend.`,

  stretch: [
    `Add changepoint detection visualisation: model.plot(forecast) marks trend changepoints with vertical lines. Do the detected changepoints correspond to real events -- the 2008 financial crisis (manufacturing slowdown), the 2012-2014 period (energy efficiency push)? Matching changepoints to real events is how you validate that the model is picking up real signal.`,
    `Fit Prophet on a retail time series (the classic "Air Passengers" dataset or any Kaggle sales dataset) and compare the holiday effects. The holiday pattern for retail is the opposite of energy -- Christmas causes demand spikes, not drops. Seeing both directions makes the holiday component intuitive.`,
    `Read the original Prophet paper: "Forecasting at Scale" by Taylor and Letham (2018). It is short, practical, and explains the design tradeoffs that make Prophet what it is. Knowing the paper is knowing why the defaults are the defaults.`,
  ],
});

// ─── W24 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 24, {
  context: `You have now fitted ARIMA and Prophet on the same series. Both are classical models -- they decompose the signal into interpretable components and fit them explicitly. This week you try the deep learning approach: an LSTM (Long Short-Term Memory network), which learns the pattern instead of decomposing it.

The sales pitch for LSTMs in time series forecasting is compelling. They can theoretically learn arbitrary long-range dependencies without you specifying a lag order. They are expressive enough to capture non-linear interactions between past values. They power the time series layers inside many production forecasting systems at Amazon and Google. All of that is true.

The honest version is also true. LSTMs on univariate energy demand data with a few years of history often do not beat a well-tuned ARIMA or Prophet. The reason is data scale: deep learning models need a lot of data to outperform classical methods, and 121,000 hourly rows sounds like a lot until you consider that an LSTM trained on this will see fewer unique seasonal cycles than a classical model would use. The value of this week is not "LSTM wins" -- it is learning to build a sliding-window dataset, write a training loop in PyTorch, and understand when deep learning is and is not the right tool.

The sliding-window setup is the non-obvious part. You cannot feed an LSTM a raw time series directly. You reshape it into sequences: take the last N hours as input, predict the next hour as output. With N=168 (one week of hourly data), each training example is a 168-step sequence. You slide that window across the entire training set, generating thousands of (input, target) pairs. That reshaping step is where most bugs live.

By Sunday: a trained LSTM model, a forecast plotted against actuals, and honest MAE and RMSE numbers added to the comparison table. If the LSTM loses to Prophet or ARIMA on this dataset, you document that. The notebook that shows an LSTM finishing third but explains why is more impressive than one that cherry-picks metrics to hide it.`,

  pre_flight: `Before writing any PyTorch code, draw the data flow on paper. Raw series → sliding window reshape → (X_train, y_train) → LSTM → single-step prediction → denormalise → compare to actual. For each step, write the shape: if your window is 168 and you have 30,000 training hours, what is the shape of X_train? (30000 - 168, 168, 1). Getting the shapes right before touching code saves two hours of dimension mismatch errors.`,

  mastery_questions: [
    `Write the sliding-window function: given a series and a window size, return X (each window as a row) and y (the value immediately after each window). Use window_size=168 (one week hourly). Paste the function and the resulting X_train.shape and y_train.shape. Now normalise using MinMaxScaler fit on training data only (not the full series -- fitting on the full series leaks test statistics into training). Paste the scaler.fit call and confirm the scaler was fit on X_train before transforming X_test.`,
    `Define your LSTM model as a PyTorch nn.Module. At minimum: one LSTM layer (hidden_size=64 or 128), one linear layer to project from hidden to output. Paste the class definition. Then write the training loop: forward pass, MSE loss, backward pass, optimizer.step(). Train for 20 epochs. Paste the loss at epoch 1 and epoch 20. If the loss at epoch 20 is higher than at epoch 1, your learning rate is too high or your data has not been normalised -- name which and fix it.`,
    `Generate predictions on the test set. Remember to denormalise with scaler.inverse_transform before comparing to actuals. Paste the MAE and RMSE. Add them to the comparison table. Where in the forecast horizon does the LSTM do best -- the first few days or further out? (LSTMs often do better on short horizons where the sliding window is densely informative, and worse further out where the error compounds.)`,
    `Plot LSTM predictions against actuals for a two-week window. On the same plot, overlay ARIMA predictions for the same window. Paste the plot. Write one specific sentence about a moment where the LSTM tracks better, and one where ARIMA tracks better. If one model handles holiday dips and the other handles weekday spikes, that tells you something useful about what each architecture learned.`,
    `Update the README comparison table: persistence, ARIMA, Prophet, LSTM -- all on the same test window, MAE and RMSE for each. Paste the table. Now write a two-sentence production recommendation: given these four numbers, which model would you deploy for AEP day-ahead forecasting, and what is the one factor that could change that answer? The answer is not necessarily "the best MAE" -- interpretability and operational simplicity matter, and a model that fails silently is worse than a slightly less accurate one that fails visibly.`,
  ],

  common_mistakes: [
    `Fitting the MinMaxScaler on the full dataset before splitting. The scaler's min and max will include test data statistics, leaking future information into the normalisation. Always fit on training data only, then transform train and test separately.`,
    `Reshaping X for the LSTM incorrectly. PyTorch's LSTM expects (batch_size, sequence_length, input_size). If you pass (batch_size, sequence_length) without the third dimension, you get a confusing error about expected 3D input. Add .unsqueeze(-1) to your input tensor.`,
    `Using the same window for training and test without respecting the time boundary. Every test window must start after the last training observation. If your sliding window overlaps the train/test boundary, you are feeding the model future training data during evaluation.`,
    `Training for too many epochs on a small dataset and overfitting. Watch validation loss alongside training loss. When validation loss starts climbing while training loss continues falling, stop. Continuing to train is not improving the model -- it is memorising training sequences.`,
    `Comparing LSTM to ARIMA without matching the forecast horizon. If ARIMA was evaluated on 90-day ahead forecasts and LSTM on 1-day ahead, the comparison is not fair. Both must predict the same horizon on the same test period.`,
  ],

  debug_help: `Three errors specific to this week. First: "RuntimeError: Expected 3D input, got 2D." Your X tensor is missing the feature dimension. Add x = x.unsqueeze(-1) before passing to the LSTM. Second: loss is NaN from epoch 1. Almost always means unnormalised data -- electricity values in the thousands multiplied through an LSTM produce gradients that overflow. Normalise first, then train. Third: predictions are a flat line near the mean of the series. This means the model learned to predict the mean (a safe but useless strategy). Try increasing hidden_size, reducing learning rate, or checking that your y_train is normalised consistently with X_train.`,

  ai_assist: `Use Claude to explain what the LSTM's hidden state actually stores -- in plain English, not equations. "What information does an LSTM hidden state carry between timesteps, and why does that make it suitable for time series?" Once you understand it, you can explain your model to a non-technical stakeholder in one sentence. Do NOT ask Claude to write the training loop. Writing a PyTorch training loop from scratch -- even a simple one -- is the single most important skill you build this week, and copying one blindly means you will not know how to debug it when it fails.`,

  stretch: [
    `Try a multi-layer LSTM (num_layers=2) and compare test MAE to the single-layer version. The improvement (or lack of it) on this dataset is informative -- more layers help when there is more complex temporal structure to learn.`,
    `Replace your LSTM with a simple 1D CNN + linear head. Convolutional models for time series are faster to train and often competitive. Knowing both architectures -- and when one beats the other -- is more useful than defaulting to LSTM.`,
    `Read "Are Transformers Effective for Time Series Forecasting?" (Zeng et al., 2023). The finding is surprising: on many standard benchmarks, a single linear layer beats attention-based transformers. Knowing this paper protects you from following hype uncritically.`,
  ],
});

// ─── W25 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 25, {
  context: `You have trained four models and compared them in a table. That is good science. The problem is that it is a snapshot -- the table reflects how those models performed the day you evaluated them. In production, data drifts. The distribution of AEP electricity demand in 2024 looks different from 2018 because of electric vehicles, distributed solar, remote work, and grid-scale batteries. A model trained on 2004-2017 data and deployed in 2024 is degrading silently, and without monitoring you will not know until someone calls you.

MLflow is the experiment tracking layer. Every time you train a model, MLflow logs the parameters (window size, LSTM hidden units, ARIMA order), the metrics (MAE, RMSE), and the model artifact itself. You can compare 20 training runs in a browser UI, tag one as "prod," and roll back to a previous version if the new model fails. Databricks and many large tech companies use MLflow as the standard experiment tracking layer. The alternative -- keeping notes in a notebook or a Slack message -- sounds fine until the third time you cannot remember which hyperparameter produced your best result.

Evidently is the drift monitoring layer. It compares a reference dataset (your training data) to a production dataset (recent incoming data) and reports whether the input distribution has shifted. If the distribution of hourly temperatures underlying electricity demand has shifted -- say, five consecutive years of hotter summers -- Evidently will flag it before the model's accuracy quietly collapses. This is the kind of monitoring that the ML team at any serious company runs on every production model, because the cost of a drifted model making bad decisions is always higher than the cost of checking.

By Sunday: every model training run from this project logged in MLflow with params and metrics, the best model tagged as "prod," and an Evidently drift report comparing your 2004-2015 training distribution to your 2016-2018 test distribution. The report will probably flag drift -- the series did shift during that window. Document what you found.`,

  pre_flight: `Before touching MLflow, open the experiment tracking you have been doing so far -- probably scattered across notebook cells and the README table. Write down what information you would lose if you had to recreate this project from scratch tomorrow. That list is exactly what MLflow will capture going forward. The discipline of experiment tracking is easier to appreciate after you have lost something you cannot reconstruct.`,

  mastery_questions: [
    `Install mlflow and initialise a local experiment. Wrap one of your model training runs (pick ARIMA or Prophet) with mlflow.start_run(). Log at least three parameters (e.g., model_type, window_size, seasonal_period) and two metrics (MAE, RMSE) using mlflow.log_param and mlflow.log_metric. Paste the run ID. Open the MLflow UI (mlflow ui in the terminal, then http://localhost:5000) and paste a screenshot or describe what you see in the run detail page.`,
    `Log all four models (persistence, ARIMA, Prophet, LSTM) as separate MLflow runs in the same experiment. For each, log the params and test-set metrics. Paste the experiment comparison view (the table in the MLflow UI showing all four runs side by side). Now tag the best-performing model run with mlflow.set_tag("stage", "prod"). This tag is how production systems know which model to load.`,
    `Save the Prophet model artifact to MLflow using mlflow.prophet.log_model (or mlflow.pyfunc.log_model for custom models). Paste the artifact URI. Now load it back using mlflow.pyfunc.load_model(artifact_uri) and run one prediction. Paste the prediction. This round-trip -- train, log, load, predict -- is the MLflow workflow that underpins every ML deployment you will encounter at companies using Databricks or Azure ML.`,
    `Install evidently and run a DataDriftPreset report. Your reference dataset is the training window (2004-2015 daily demand). Your current dataset is the test window (2016-2018). Paste the overall drift score and which features (if any) are flagged as drifted. If the report shows drift, write one sentence about what real-world change between 2015 and 2018 could explain it. If it shows no drift, write one sentence about why that might still be misleading (hint: overall distribution can be stable while tail behaviour shifts).`,
    `Set up a simple drift alarm: if the Evidently drift score crosses a threshold you define, print an alert message (in production this would be a Slack message or a PagerDuty call). Paste the alarm logic. Write one sentence about what you would do if this alarm fired in a real deployment -- not "retrain the model" in the abstract, but specifically: who gets notified, what data do you pull, what decision criteria determine whether to retrain or roll back.`,
  ],

  common_mistakes: [
    `Running MLflow tracking without setting an experiment name. All runs land in the "Default" experiment, which becomes unmanageable after 10 runs. Always call mlflow.set_experiment("energy-forecast") before logging anything.`,
    `Logging metrics after the run context closes. mlflow.log_metric must be called inside the with mlflow.start_run(): block, or the metrics are silently dropped.`,
    `Comparing Evidently drift on raw hourly data instead of daily. The reference and current datasets should match the granularity at which your model was trained. Drift detected on hourly data may not mean anything for a daily model.`,
    `Treating "no drift detected" as a green light to stop monitoring. Evidently checks distribution-level drift; it does not check model performance drift. A model can be accurate on the new distribution while the new distribution is still meaningfully different. Always pair distribution drift with performance monitoring.`,
    `Not versioning the MLflow tracking directory. The local mlruns/ folder is the experiment database. If you delete it or do not commit it, you lose all your run history. Either commit it (fine for small projects) or point MLflow at a persistent backend (Postgres or S3 for team use).`,
  ],

  debug_help: `Two specific issues. First: MLflow UI shows runs but no metrics. Usually means you called mlflow.log_metric outside the run context (after the with block closed). Move all logging calls inside the with block and rerun. Second: Evidently raises "Column not found" or produces an empty report. This means the column names in your reference and current DataFrames do not match. Both must have the same column named consistently (e.g., 'AEP_MW'). Run reference.columns and current.columns side by side and align them before passing to the report.`,

  ai_assist: `Use Claude to explain the difference between data drift, concept drift, and model performance drift -- three distinct failure modes that all get lumped together as "the model degraded." Understanding the difference changes what you monitor and what you do when an alarm fires. Do NOT ask Claude to write your drift alarm logic -- that logic encodes a business decision (what threshold is worth waking someone up at 3am?), and that decision belongs to you and the stakeholder, not to a language model.`,

  stretch: [
    `Set up MLflow tracking against a remote server by pointing MLFLOW_TRACKING_URI at a DagsHub or HuggingFace Spaces backend. Now your experiment history is accessible from any machine -- which is the minimum viable setup for any team project.`,
    `Add a model registry step: promote your "prod"-tagged model to the MLflow Model Registry and add a version description. The Model Registry is the difference between "I have a tagged run" and "I have a versioned, auditable artifact I can roll back to."`,
    `Read Chip Huyen's "Designing Machine Learning Systems" Chapter 8 (Data Distribution Shifts). It is the best practical treatment of drift types and monitoring strategies available, and it is what the interviewers at ML-heavy companies expect you to have read.`,
  ],
});

// ─── W26 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 26, {
  context: `Everything you have built so far runs on your laptop. That is fine for a project. It is not fine for a job. At some point in your first data science role you will be handed a dataset that is 200GB, a model that needs to run on a schedule, or a pipeline that needs to be reproducible on a machine that is not yours. That is what cloud infrastructure solves, and this week you get your first real exposure to it.

The AWS piece is practical and focused. You will create an account (if you do not have one), set up MFA and a billing alarm immediately -- AWS bills have surprised many engineers who left a GPU instance running over a weekend -- and install the AWS CLI. Then you will upload your best Energy Forecast model artifact to an S3 bucket and write a script that loads it from S3 using boto3. That pattern -- model stored in cloud object storage, loaded on demand by application code -- is how every production ML system you will encounter manages model artifacts. Hugging Face's model hub, MLflow's remote artifact store, and SageMaker all use S3 as the underlying layer.

The BigQuery piece is a different kind of cloud skill. BigQuery is Google's serverless analytics database, and it is where many large organisations run their analytical SQL workloads. The reason data scientists need BigQuery specifically is that it scales to petabytes without any infrastructure to manage -- you write SQL, BigQuery figures out the execution. Google makes several public datasets available in BigQuery for free, and you will use one of them to run a real analytical query at a scale that would crash pandas.

The goal this week is not to become a cloud engineer. It is to understand the two things data scientists most commonly need from the cloud: object storage (for models and data), and scalable querying (for analysis at sizes that do not fit in memory). Both of those come up in the first month of most DS roles.

By Sunday: a model artifact in S3, a working boto3 load script, a BigQuery query that returns a result you could not get on a laptop, and a one-page "cloud hygiene" note in your repo covering MFA, billing alarms, and IAM principles.`,

  pre_flight: `Before creating the AWS account, set aside a credit card you are comfortable being charged on and write down a hard monthly spend limit (e.g., $10). AWS free tier covers most of what you need this week, but a misconfigured resource can exceed it. Setting the billing alarm before doing anything else is the same discipline that every AWS solutions architect certifies engineers on before giving them production access. Do that first, not last.`,

  mastery_questions: [
    `Create an S3 bucket with a unique name (no public access -- leave all public access blocked by default). Upload your best Energy Forecast model artifact to the bucket using the AWS CLI: aws s3 cp ./model-artifact s3://your-bucket-name/models/energy-forecast-v1/. Paste the CLI command and the output confirming the upload. Now list the bucket contents with aws s3 ls s3://your-bucket-name/models/ and paste the result. This is the same command ML engineers at every AWS shop run to confirm a model deployment landed correctly.`,
    `Write a Python script that loads the model artifact from S3 using boto3. Paste the script. Now time the download: how many seconds does it take to pull the artifact to your local machine over your connection? In production this download happens inside the same AWS region (milliseconds), not over the public internet (seconds). That latency difference is why production inference services run inside the same region as their artifact store.`,
    `Set up a BigQuery project in Google Cloud Console (free tier). Open the BigQuery console and run a query on a public dataset -- start with bigquery-public-data.usa_names.usa_1910_current: SELECT name, SUM(number) as total FROM bigquery-public-data.usa_names.usa_1910_current GROUP BY name ORDER BY total DESC LIMIT 10. Paste the result and the bytes processed. Now run the same aggregation using a WHERE clause to filter to one state. Paste the bytes processed for that filtered query. Why is it smaller? (Hint: BigQuery is columnar -- filtering before aggregating reduces the scan.)`,
    `Write a BigQuery query that would take more than your laptop's RAM to process locally -- try one of the Wikipedia or GitHub public datasets at petabyte scale. Paste the query, the bytes processed, and the result. Now explain in one sentence why BigQuery can do this without you provisioning a cluster: it dynamically distributes the query across thousands of worker nodes managed entirely by Google. That sentence is the answer to "why BigQuery over Spark on EC2?" in 80% of conversations.`,
    `Write the one-page cloud hygiene note (CLOUD-HYGIENE.md) for your repo. Cover: MFA on the root account, creating an IAM user for daily use (never use root credentials in code), setting a billing alarm, principle of least privilege (your IAM user should only have permissions it needs). Paste the file. This document exists in the onboarding repo of every well-run engineering team. Writing it for yourself is the first step to writing it for a team.`,
  ],

  common_mistakes: [
    `Hardcoding AWS credentials in Python scripts or Jupyter notebooks. If the notebook goes to GitHub, your credentials go public. Use environment variables (os.environ['AWS_ACCESS_KEY_ID']) or AWS credential profiles (~/.aws/credentials) instead.`,
    `Forgetting to set a bucket region. S3 buckets without an explicit region default to us-east-1, but data transfer costs and latency are real if your compute is in a different region. Always specify the region explicitly when creating a bucket.`,
    `Using the root AWS account for daily work. Root has unlimited permissions and cannot be scoped. Create an IAM user with the minimum permissions needed (S3 read/write to your specific bucket), give that user programmatic access, and use those credentials.`,
    `Running large BigQuery queries without checking the estimated bytes first. The BQ console shows "This query will process X GB" before you run it. Free tier gives you 1TB per month -- a single careless query on a petabyte table can consume your monthly quota. Always check the estimate first.`,
    `Leaving S3 buckets with public read access by default. AWS now blocks this during bucket creation by default, but older workflows enable it for "convenience." A public S3 bucket containing model artifacts that include training data is a GDPR incident waiting to happen.`,
  ],

  debug_help: `Two specific issues. First: "NoCredentialsError" from boto3. Either you did not run aws configure, or the credentials file at ~/.aws/credentials is malformed. Run aws sts get-caller-identity from the terminal -- if that works, boto3 will work too. Second: BigQuery "Access Denied" error on a public dataset. You need to enable billing on your project even for free-tier queries -- BigQuery requires a billing account to be attached before it will process any query, even queries within the free 1TB limit. Enable billing in Cloud Console and retry.`,

  ai_assist: `Use Claude to explain IAM policies in plain English -- specifically, how to read a JSON IAM policy document and understand what permissions it grants. "What does this IAM policy actually allow?" with the JSON pasted is a genuinely useful prompt because IAM policy syntax is dense. Do NOT use Claude to generate IAM policies for you without understanding them. An AI-generated policy that is too permissive is worse than no policy -- it gives a false sense of security.`,

  stretch: [
    `Set up an S3 lifecycle policy that automatically deletes objects older than 90 days from a "staging" prefix. This is how production systems keep storage costs from growing indefinitely as model iterations accumulate.`,
    `Run a BigQuery ML query: CREATE MODEL my_dataset.my_model OPTIONS(model_type='linear_reg') AS SELECT ... You are training a linear regression model inside the database, with no Python, no sklearn. BigQuery ML exists, is used in production, and occasionally outperforms offline models on very large datasets.`,
    `Read the AWS Well-Architected Framework's "Operational Excellence" pillar (free, 30 minutes). The five design principles it describes are the mental model every senior engineer uses when evaluating cloud architecture decisions.`,
  ],
});

// ─── W27 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 27, {
  context: `Energy Forecast has been running since week 21. You built four models, compared them honestly, added MLflow tracking, set up drift monitoring, and put artifacts in the cloud. This week you ship it the same way you shipped Reddit Sentiment -- with a blog post, a demo video, and a public dashboard.

The production model decision is the first real deliverable. You have four candidates: persistence, ARIMA, Prophet, LSTM. They have different MAE numbers, different interpretability levels, different maintenance burdens, and different failure modes. The right choice is not automatically the lowest MAE. If Prophet and ARIMA are within 5% of each other on MAE but ARIMA is faster, has no dependencies on Stan, and is easier to retrain on new data, ARIMA might be the production choice. Writing out that reasoning explicitly is the skill -- the analysis behind the model selection, not just the number.

The Streamlit dashboard for Energy Forecast is simpler than Reddit Sentiment's because you are not hitting a live API -- you are generating a forecast for future dates using the fitted model. The user picks a date range, the app generates the forecast with confidence intervals, and the chart appears. The time-series snapshot pattern from week 18 applies here too: log each forecast request with the timestamp and the requested range, so you can audit what the model predicted versus what actually happened.

The retro this time should feel different from week 20's. You have now shipped two complete projects. The patterns that show up in both retros are the ones worth paying attention to -- the skills you underestimated, the steps that always take longer than planned, the decisions you made in week 1 that constrained week 6. Those recurring patterns are what you should fix in Project 4.

By Sunday: best model deployed in a Streamlit dashboard at a public URL, a published blog post that covers the full arc from EDA to deployment, a demo video, and a RETRO.md that names at least one thing you would change that is different from the week 20 retro. The project is done when a stranger can use the dashboard, read the post, and understand what you built without you in the room.`,

  pre_flight: `Make the production model decision before opening your laptop. Read the README comparison table. For each model, write one sentence about its biggest operational risk -- not its MAE, but the thing most likely to go wrong in production. ARIMA's biggest risk is different from LSTM's biggest risk. The model with the lowest operational risk for a solo-maintained project is not always the one with the lowest MAE.`,

  mastery_questions: [
    `Write a one-page model selection memo (MODEL-SELECTION.md). Structure: candidates considered, metrics for each (MAE, RMSE, training time, inference time), the decision, and the reasoning. The reasoning should include at least one non-accuracy factor -- interpretability, maintenance complexity, dependency footprint, or failure mode. Paste the file. A team that inherits your project six months from now should be able to read this file and understand why you chose the model you chose, without needing to rerun all the experiments.`,
    `Deploy the chosen model in a Streamlit dashboard. The user selects a date range, the app generates a forecast with 95% confidence intervals, and the chart renders. Paste the URL. Now log each forecast request to a CSV (timestamp, requested_start, requested_end, model_version). Paste three sample rows from the log. This audit trail is what lets you answer "what did the model predict for last week's peak?" six months later.`,
    `Write and publish the blog post. This one should cover the full arc: why energy forecasting matters, the four models you tried, the honest comparison, the production decision, and one thing you learned that surprised you. Minimum 700 words. Paste the URL. The "one thing that surprised you" sentence is the most-read part -- readers skip to it, and it should be specific ("LSTM finished third on this dataset, behind a 50-year-old classical model, because we had fewer than 15 years of data and LSTMs need more").`,
    `Record the demo video. Three to five minutes. Open the live dashboard, generate a forecast for the next 30 days, show the confidence intervals, then pull up the MLflow comparison table and walk through why you chose the production model. Paste the URL. The MLflow table in the video is the detail that signals to a technical interviewer that you ran a real experiment and did not just train one model.`,
    `Write RETRO.md for Energy Forecast. Three sections: What worked, What did not, What is different from the week-20 retro. The third section is the most important -- if the same things went wrong twice, you have identified a habit to change. If different things went wrong, your problem-solving is growing. Paste the file.`,
  ],

  common_mistakes: [
    `Choosing the production model solely by MAE without mentioning the trade-offs. "Prophet wins" is a one-sentence conclusion that does not demonstrate the thinking a senior interviewer is looking for. The reasoning is the answer, not the number.`,
    `Deploying the Streamlit dashboard without testing it on a date range outside the training window. The model is predicting the future -- make sure the app correctly handles dates past the last training observation and does not silently return training-period fitted values instead of forecasts.`,
    `Writing the blog post before deciding on the production model. The post should reflect the actual decision, not a draft that gets revised. Write the MODEL-SELECTION.md first, then write the post.`,
    `Making the demo video before the dashboard is stable. Record once, when everything works. A video where you apologise for a broken chart is worse than no video.`,
    `Writing a retro that avoids naming the specific thing that went wrong. "The modelling phase took longer than expected" is not a retro entry. "I spent 3 days debugging the LSTM's flat-line predictions before realising the data was not normalised" is.`,
  ],

  debug_help: `The most common blocker this week is the same one as week 20: the blog post. The same advice applies. A 700-word draft posted on Thursday that you polish on Friday is infinitely more useful than a draft you never publish because it is not quite right. The second most common blocker is the Streamlit dashboard generating errors for future dates -- usually because the model's make_future_dataframe call or the sliding window function was not designed to handle dates past the training window. Add a simple check: if the requested end date is more than 90 days past the last training observation, show a warning that the forecast confidence intervals are unreliable at that horizon.`,

  ai_assist: `Use Claude to proofread the blog post for clarity -- specifically, ask it to flag any sentence that assumes the reader already knows what ARIMA or Prophet is. "Identify sentences where I assume background knowledge the reader might not have, and suggest how to briefly explain the concept in context." Then decide for each flag whether to add the explanation or trust the reader's patience. The post should be readable by a smart non-technical person, not just by other data scientists.`,

  stretch: [
    `Set up a GitHub Action that retrains the production model on new data monthly and logs the new run to MLflow. If the new model's MAE is more than 5% worse than the tagged "prod" model, the action sends a GitHub issue as the alert. This is a minimal automated retraining pipeline -- the same pattern used in production at most data-driven companies.`,
    `Add an "actual vs. forecast" section to the dashboard that shows, for past forecast windows, how close the predictions were to the actual AEP values (downloadable from the EIA website). The model accountability loop -- prediction, then measurement of accuracy -- is what earns trust with stakeholders over time.`,
    `Write a one-sentence executive summary of Energy Forecast: what it does, what it achieved, and what it would take to put it in production at a real utility. The constraint on the last part is not technical. Knowing the non-technical constraints on ML deployment is what makes a data scientist useful beyond the notebook.`,
  ],
});
