import { rewriteWeek } from "../rewrite-week";

// devops-cloud W6-W10

rewriteWeek("devops-cloud", 6, {
  context: `Docker Compose is the tool for running multi-container applications locally. Your production application is rarely just one process — it is a web server, a database, a cache, maybe a background worker. Docker Compose lets you define all of these as services in a single YAML file and start them all with docker compose up. Each service runs in its own container; they communicate over a shared Docker network.

The inner loop in software development is the cycle of: edit code, see the change, iterate. The inner loop speed determines how fast you can develop. With Docker Compose and volume mounts, you can have the best of both worlds: a consistent, containerised environment (no "works on my machine") and fast iteration (changes to source code are reflected immediately without rebuilding the image, because the source code directory is mounted from the host into the container).

docker-compose.yml structure: services (each service is a container), networks (custom networks for container communication), volumes (persistent storage). Key service options: image or build (pre-built image or build from Dockerfile), ports (host:container port mapping), environment (environment variables), depends_on (service startup order), volumes (volume mounts).

Health checks in Docker Compose: the depends_on option only waits for the container to start — not for the application inside to be ready. Your Node app starting before PostgreSQL is ready causes connection errors. Add a healthcheck to the postgres service (pg_isready -U postgres) and use depends_on with condition: service_healthy.

The production question: Docker Compose is for local development and single-server deployments. For production with multiple servers, you use Kubernetes (W9). But for a small application on a single server, Docker Compose in production is completely valid — many successful startups run on Docker Compose for years.`,

  pre_flight: `Have Docker Desktop installed from W5. Know the basic YAML syntax for Docker Compose (indentation, lists, key-value pairs). Read the Docker Compose getting started guide. Know that docker compose up starts all services, docker compose down stops and removes them, docker compose logs follows logs from all services, docker compose ps lists running services.`,

  mastery_questions: [
    `Your docker-compose.yml has a Node.js service that depends on PostgreSQL. You run docker compose up and your Node app crashes with "Connection refused" immediately. What happened and how do you fix it? depends_on: [postgres] only waits for the postgres container to start — not for PostgreSQL to be ready to accept connections. PostgreSQL takes a few seconds to initialise on first run. Your app starts, tries to connect, gets refused, and crashes. Fix: add a healthcheck to the postgres service: healthcheck: { test: ["CMD-SHELL", "pg_isready -U postgres"], interval: 5s, timeout: 5s, retries: 5 }. Then in your app service: depends_on: { postgres: { condition: service_healthy } }. Docker Compose waits for the healthcheck to pass before starting the app.`,
    `You want to mount your source code into the container so changes are reflected immediately without rebuilding. How do you configure this, and what is the limitation? Add a volume mount in the service definition: volumes: ["./src:/app/src"]. The host directory ./src is mounted into /app/src in the container. When you edit a file in ./src on your host, the container immediately sees the change. The limitation: for Node.js, the process must detect the file change and restart. Use nodemon (not node) as the dev start command — it watches for file changes and restarts automatically. Your Dockerfile CMD uses node for production; docker-compose.yml overrides with command: npx nodemon server.js for development.`,
    `Your docker-compose.yml has three services: app, postgres, redis. You run docker compose up and a few minutes later the app container restarts unexpectedly. How do you investigate? Run docker compose logs app to see the container's stdout/stderr output. The crash reason is almost always in the last few lines before the restart. Also run docker stats to see memory usage — if the container hit its memory limit, it was OOM-killed (you will see the container status as "OOMKilled" in docker inspect [container_id]). Check docker compose ps for the number of restarts (Restarts: 3 means it has crashed and restarted 3 times). Set restart: on-failure in the service definition so the container restarts automatically after a crash.`,
    `How do you manage sensitive configuration (database passwords, API keys) in Docker Compose for local development? Options: .env file in the same directory as docker-compose.yml. Docker Compose reads it automatically and substitutes variables: environment: { POSTGRES_PASSWORD: \${DB_PASSWORD} }. The .env file is excluded from git (add to .gitignore). Add a .env.example with placeholder values that is committed to git, so teammates know what variables to set. For production, use Docker secrets (docker secret create) or a vault service — not .env files.`,
  ],

  common_mistakes: [
    `Using depends_on without health checks. depends_on only waits for container start, not application readiness. Always pair depends_on with healthchecks for databases and other services that take time to initialise.`,
    `Using bind mounts (volume mounts) in production. Volume mounts are excellent for development (live reload). In production, your application code should be inside the Docker image (COPY in Dockerfile) — not mounted from the host. A host directory is not immutable and version-controlled.`,
    `Storing sensitive environment variables in docker-compose.yml directly. Values in docker-compose.yml are committed to git. Move secrets to a .env file (gitignored). Use \${VARIABLE} interpolation.`,
    `Not setting memory limits on services. Without limits, one runaway service can consume all host memory and crash every other service. Set deploy: resources: limits: memory: 512m for each service in production Docker Compose deployments.`,
    `Running database containers with no persistent volume. A postgres container without a volume loses all data when the container is removed (docker compose down). Mount a named volume: volumes: { postgres_data: {} } and reference it in the postgres service.`,
  ],

  debug_help: `Cannot connect between services: use the service name as the hostname. If your postgres service is named postgres, connect at postgres:5432 from the app service. The services are on the same Docker network and DNS resolves service names. localhost inside a container refers to the container itself, not the host or other containers. Port is accessible from host but not between containers: for host access, use ports. For container-to-container communication, do not use ports — use the service name on the container port directly. Volume changes not reflected: if you mounted a directory and changes are not showing, check whether the file watcher (nodemon) is using polling mode (necessary on Windows and some Docker Desktop configurations): nodemon --legacy-watch. Build cache not invalidating despite file changes: if you are using docker compose build, clear the cache with docker compose build --no-cache.`,

  ai_assist: [
    `"Write a docker-compose.yml for a Node.js app with PostgreSQL and Redis. Include: a healthcheck on postgres (pg_isready), depends_on with service_healthy condition, a named volume for postgres data, environment variables loaded from .env, a source code bind mount for development (./src:/app/src), and nodemon as the dev command for the app service."`,
    `"Write a docker-compose.override.yml for development that overrides the production docker-compose.yml. The override adds: source code volume mounts, environment variables set to development values, port mappings for local access, and overrides the CMD to use nodemon."`,
    `"Explain Docker named volumes vs bind mounts. When do I use each? Show the syntax for both in docker-compose.yml. What happens to named volume data when I run docker compose down vs docker compose down -v?"`,
  ],

  stretch: [
    `Add pgAdmin to your Docker Compose stack as a service for database management. Mount the pgAdmin config directory as a volume so your server connection is pre-configured. This pattern (adding developer tools as Docker Compose services) is standard — it eliminates per-developer tool installation.`,
    `Set up a Makefile (or package.json scripts) that wraps Docker Compose commands: make dev (docker compose up), make down (docker compose down), make logs (docker compose logs -f), make shell-app (docker compose exec app sh), make shell-db (docker compose exec postgres psql -U postgres). This gives your team a consistent, documented interface to the development environment.`,
    `Run a full Docker Compose stack on a DigitalOcean server in "production" mode (no volume mounts, no nodemon, restart: always). Use docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d. This demonstrates the pattern of a base compose file with environment-specific overrides.`,
  ],
});

rewriteWeek("devops-cloud", 7, {
  context: `Every container image you run in production is a potential security vulnerability. The base image (node:20-alpine) contains the entire Alpine Linux operating system plus Node.js — hundreds of packages, any of which might have a known CVE (Common Vulnerabilities and Exposures). Your application code adds more dependencies. Image hardening and security scanning are the practices that reduce this attack surface.

Image hardening: making the image as small and secure as possible. Use minimal base images (Alpine or Distroless). Remove build tools from the final image (multi-stage builds). Do not install packages you do not use. Run as a non-root user. Do not include secrets in the image (they end up in docker history and any image layer inspector). Read-only filesystem (--read-only flag at runtime) prevents attackers from modifying files inside a running container.

Distroless images: built by Google. They contain only the application runtime (Node.js) and its dependencies — no shell, no package manager, no system utilities. This is the most secure image type. The tradeoff: debugging is harder (no shell to exec into). Use Distroless in production; use a regular Alpine image in development.

Software supply chain security is the practice of ensuring the code and dependencies you are running are what you think they are. npm packages can be compromised (malicious code added to a legitimate package — the left-pad incident, the event-stream incident). Docker images from Docker Hub may be modified. Practices: pin image versions exactly (sha256 digest, not just a tag), use npm ci (installs exactly what is in package-lock.json), audit dependencies regularly (npm audit), and use a Software Bill of Materials (SBOM) to track what is in your image.

Trivy is a free, comprehensive vulnerability scanner for container images, filesystems, and Kubernetes. Run trivy image myapp:1.0.0 to scan for CVEs in the image. Trivy checks the base image, installed packages, and language-specific dependencies (npm, pip, Gemfile). It categorises findings by severity: CRITICAL, HIGH, MEDIUM, LOW, UNKNOWN. Fix CRITICAL and HIGH; evaluate MEDIUM; document why you accepted LOW.`,

  pre_flight: `Install Trivy: https://aquasecurity.github.io/trivy/latest/getting-started/installation/. On macOS: brew install aquasecurity/trivy/trivy. Know how to run docker history [image] (shows layers and their sizes). Know what a CVE is and how to look up a CVE number at cve.mitre.org or nvd.nist.gov. Read about the 2021 Log4Shell vulnerability (CVE-2021-44228) as an example of a critical CVE in a widely-used library.`,

  mastery_questions: [
    `Trivy finds a CRITICAL CVE in your base image node:20.10-alpine. The CVE is in libssl (the OpenSSL library). How do you fix it? Check if the fix is available: a newer version of Alpine (or the specific Alpine libssl package) that patches the CVE. Update your base image to the latest patch version: FROM node:20-alpine (the floating tag) or a specific Alpine patch version that includes the fix. Rebuild your image: docker build --no-cache (the no-cache ensures the latest package versions are pulled). Run Trivy again to confirm the CVE is gone. If no fix is available yet, document the exception: when the CVE was identified, when a fix is expected, and the compensating controls (network isolation, least-privilege user).`,
    `You are scanning your Docker image with Trivy and it finds vulnerabilities in your npm dependencies, not just the OS. A HIGH severity CVE in an npm package you use directly. What do you do? Check the CVE details — which version introduced the vulnerability and which version fixes it. Run npm audit to see the full picture. Update the package: npm update [package-name] or pin a specific fixed version in package.json. If the package has no fix available yet, check whether the vulnerable code path is actually reachable in your application (an XSS vulnerability in a server-side library is not exploitable). Document your risk assessment. If the vulnerability is reachable and no fix exists, consider an alternative package.`,
    `What is a Software Bill of Materials (SBOM) and why does it matter for container security? An SBOM is a complete list of every component in your software — every OS package, every language dependency, and their versions. For containers: every package in the Docker image. When a new CVE is published, you can immediately check your SBOM to see if any of your running containers include the vulnerable package. Without an SBOM, you must scan each container individually. With an SBOM stored in your registry, you can query across all images. Generate an SBOM with Syft (by the same team as Grype/Trivy): syft myapp:1.0.0 -o cyclonedx-json > sbom.json.`,
    `Explain why pinning a Docker image tag (node:20-alpine) is not the same as pinning the image digest. A tag like node:20-alpine is mutable — Docker Hub can update what image the tag points to. Today, node:20-alpine might be Alpine 3.19. Next week, it might be Alpine 3.20. If you rebuild your image after the update, you get a different base image than before — potentially with breaking changes or new vulnerabilities. Pinning by digest: FROM node:20-alpine@sha256:abc123... is immutable. The sha256 digest is the hash of the image contents. The image with that exact digest will never change. Pinning by digest is the reproducible build standard.`,
  ],

  common_mistakes: [
    `Using FROM ubuntu or FROM node with no version tag. latest and versionless tags float — they change without notice. Always pin to at least the major version (node:20-alpine). For production, pin to the digest.`,
    `Running containers as root in production. Add USER appuser (after RUN addgroup and adduser) before CMD. Running as a non-root user is the single most impactful security control for containers.`,
    `Ignoring Trivy scan results because they are "too many." Triage by severity. CRITICAL: fix before deploying. HIGH: fix within a sprint. MEDIUM/LOW: document and plan. If you ignore all findings, the scan is theatre.`,
    `Including .env files or credentials in Docker build context. They end up in the image. Use .dockerignore to exclude them. Use build args (--build-arg) or runtime environment variables — never bake secrets into the image.`,
    `Not scanning images in CI. Manual scans are forgotten. Add Trivy to your CI pipeline as a job that fails if CRITICAL or HIGH severity findings exist. This makes scanning mandatory, not optional.`,
  ],

  debug_help: `Trivy returns false positives: a CVE is marked in a library but you do not use the vulnerable function. Document the exception with trivy's --ignore-unfixed flag or a .trivyignore file with the CVE ID and a justification comment. Distroless image cannot be debugged: you cannot exec into a Distroless container because there is no shell. For debugging, use a debug variant (gcr.io/distroless/nodejs:debug) which includes busybox, or use ephemeral debug containers (kubectl debug). Docker build fails after switching to non-root user: some operations (writing to certain directories, binding to low ports) require root. Move the USER instruction as late as possible — only switch to non-root for the CMD. Ensure the application's working directory is writable by the non-root user.`,

  ai_assist: [
    `"Write a hardened Dockerfile for a Node.js production application. Requirements: multi-stage build (builder and production stages), Distroless base image for production stage (gcr.io/distroless/nodejs20-debian12), non-root user, read-only filesystem (note the implications), no curl/wget, pinned base image versions. Explain each security decision."`,
    `"Write a GitHub Actions workflow step that runs Trivy on a built Docker image. It should: fail the pipeline if CRITICAL or HIGH vulnerabilities are found, save the scan results as a GitHub Actions artifact, and post a summary comment on the PR with the vulnerability counts by severity."`,
    `"Generate a .trivyignore file template and explain how to use it. Show how to ignore a specific CVE with a justification comment, an expiry date, and the affected package."`,
  ],

  stretch: [
    `Generate an SBOM for your Docker image using Syft and attach it to your Docker image in the registry using the Cosign tool. This implements the SLSA (Supply-chain Levels for Software Artifacts) framework's requirement for provenance attestation. When someone pulls your image, they can verify its SBOM is attached and signed.`,
    `Implement image signing with Cosign (by Sigstore). Sign your image after pushing to the registry: cosign sign myrepo/myimage:1.0.0. In your deployment pipeline, verify the signature before deploying: cosign verify. This ensures only images signed by your CI system can be deployed — a supply chain attack that pushes a modified image to your registry would not pass signature verification.`,
    `Research and write a report: the event-stream NPM supply chain attack (2018) and the SolarWinds attack (2020). What happened? How was it detected? What supply chain security controls would have caught it? Apply at least one specific control to your own project.`,
  ],
});

rewriteWeek("devops-cloud", 8, {
  context: `Docker is a tool, not a standard. The Open Container Initiative (OCI) defines the standards: the image format and the runtime specification. Docker implements these standards, but so do alternatives: containerd (the container runtime used by Kubernetes), podman (daemon-less, rootless Docker alternative), and runc (the low-level OCI runtime used by Docker and containerd). Understanding the container runtime landscape matters because in production, you are often not using Docker directly — you are using whatever the Kubernetes cluster uses.

containerd is the industry standard container runtime. Docker uses containerd internally. Kubernetes uses containerd. containerd manages the container lifecycle: pulling images, creating containers, starting and stopping them. The Docker CLI sits on top of containerd and adds features like Docker Compose, multi-platform build, and build caching. When you use Kubernetes, you are interacting with containerd directly (via the kubelet), not Docker.

podman is a Docker-compatible CLI that does not require a daemon. Docker uses a central daemon (dockerd) that runs as root. This daemon is a single point of failure and a security risk (if it is compromised, the attacker has root). podman runs containers as the current user (rootless). The CLI is compatible: you can alias docker=podman and most Docker commands work. In enterprise environments (especially Red Hat/OpenShift), podman is the standard.

OCI image format: Docker images are OCI images. An OCI image is a directory structure: a manifest (list of layers), config (the image configuration: environment, CMD, etc.), and layers (tarballs of filesystem changes). When you push an image to a registry, you push the manifest and layers. When you pull, you download the layers and reassemble the filesystem. This is why you can pull images on any OCI-compatible runtime — the format is standardised.

Container networking deep dive: each container gets a virtual network interface (veth pair). One end is in the container; the other is on the host, connected to a bridge network (docker0 by default). The bridge connects all containers and the host. NAT (Network Address Translation) handles communication between the bridge network and the outside world. User-defined networks add DNS resolution (containers can reach each other by name). Host networking (--network=host) removes the isolation — the container shares the host's network namespace.`,

  pre_flight: `Install containerd and nerdctl (a Docker-compatible CLI for containerd): brew install lima && limactl start default (on macOS). Or use containerd directly on Linux. Install podman: podman.io/getting-started/installation. Try running the same commands with podman that you use with docker. Read the OCI Runtime Specification at opencontainers.org/about/overview.`,

  mastery_questions: [
    `What is the difference between a container runtime, a container engine, and a container orchestrator? Container runtime: the low-level component that creates and runs containers using OS primitives (namespaces, cgroups). Examples: runc, crun. Container engine: higher-level software that manages images, volumes, networks, and uses the runtime. Examples: containerd, docker. Container orchestrator: manages multiple containers across multiple servers, handles scheduling, scaling, service discovery. Examples: Kubernetes, Docker Swarm, Nomad. The relationship: Kubernetes (orchestrator) talks to containerd (engine) which uses runc (runtime) to actually run each container.`,
    `You are moving from Docker to containerd in a Kubernetes cluster. A developer reports that docker build commands no longer work on the nodes. What happened and what is the fix? Kubernetes uses containerd as the runtime, not the Docker daemon. Docker CLI commands (docker build, docker ps) talk to the Docker daemon — which is not installed or running on the nodes. Developers should not need to SSH into nodes to build or run containers. Builds happen in CI (GitHub Actions, etc.) using Docker or BuildKit, images are pushed to a registry, and Kubernetes pulls from the registry. If you need to interact with containers on a node, use crictl (the CRI-compatible CLI for containerd and other CRI runtimes).`,
    `Explain rootless containers. Why do they exist and what are their tradeoffs? Rootless containers run the container runtime and containers as a non-root user. Docker requires root for the daemon (dockerd) — this is a security risk because any container escape could give an attacker host root. Podman and containerd's rootless mode use user namespaces to simulate root inside the container while actually running as a non-root user on the host. Tradeoffs: rootless cannot bind to privileged ports (< 1024) without sysctl adjustments. Network performance may be slightly lower (user-space networking). Some operations that require real root are not possible in rootless mode.`,
    `What is a container registry and how does image distribution work? A container registry stores OCI images. Docker Hub is the public default. You push: docker push myrepo/myimage:1.0.0. The Docker CLI pushes the image layers to the registry. You pull: docker pull myrepo/myimage:1.0.0 on another machine — the layers are downloaded and reassembled. Registries support content-addressable storage: layers are stored once and shared across images that use the same layer. Private registries (AWS ECR, Google Artifact Registry, GitHub Container Registry) require authentication. The registry URL is the image name prefix: ghcr.io/myuser/myimage is on GitHub's registry.`,
  ],

  common_mistakes: [
    `Assuming Docker and Kubernetes use the same container runtime. Kubernetes does not use the Docker daemon. It uses the Container Runtime Interface (CRI). containerd and CRI-O are CRI implementations. Docker images work in Kubernetes because they are OCI images — the image format is the same.`,
    `Building images on Kubernetes nodes. Nodes should only run containers, not build them. Building images requires more privileges, more resources, and is not the node's job. Build in CI, push to a registry, pull in Kubernetes.`,
    `Using Docker Hub as your only registry in production. Docker Hub has rate limits (100 pulls per 6 hours for unauthenticated). In production, your Kubernetes cluster pulling images from Docker Hub can hit these limits and fail to start pods. Use a private registry or mirror Docker Hub behind a pull-through cache.`,
    `Not understanding the CRI-O vs containerd choice. If you are using OpenShift, CRI-O is the runtime. If you are using standard Kubernetes (EKS, GKE, AKS, or self-managed), containerd is the default. The Kubernetes API is the same; the underlying runtime differences rarely affect application code.`,
    `Ignoring container image garbage collection. Over time, unused images accumulate on nodes (especially after frequent deployments). Configure kubelet garbage collection (or containerd's image cleanup policy) to automatically remove images not used by any running container.`,
  ],

  debug_help: `crictl commands fail with "unable to connect to CRI runtime": specify the runtime endpoint: crictl --runtime-endpoint unix:///run/containerd/containerd.sock ps. The socket path varies by runtime and distribution. podman rootless cannot bind port 80: ports below 1024 require root (or the net.ipv4.ip_unprivileged_port_start sysctl). Map to a high port in podman (8080:80) and use a firewall rule or nginx on the host to forward port 80 to 8080. Image pull fails in Kubernetes with "ImagePullBackOff": check the error with kubectl describe pod [pod-name] — it shows the specific pull error (authentication failure, rate limit, image not found). For private registries, configure an imagePullSecret on the pod or service account.`,

  ai_assist: [
    `"Explain the OCI image format. What is in an image manifest, what is in an image config, and what is a layer? How are layers stored in a registry to enable deduplication? Walk through what happens when you push and then pull an image."`,
    `"Compare Docker, Podman, and containerd for a development team. Which should they use on their laptops? Which will Kubernetes use in production? What is the operational impact of this difference? Show the command equivalents."`,
    `"Write a nerdctl (or podman) command to: pull an image from Docker Hub, tag it for a private GitHub Container Registry, authenticate to ghcr.io, push it, and verify the push succeeded. Include the authentication setup for GitHub Container Registry."`,
  ],

  stretch: [
    `Set up a local container registry with Docker Registry (docker pull registry:2 && docker run -p 5000:5000 registry). Push an image to localhost:5000/myimage:latest. Configure Docker to trust this insecure registry (docker daemon config). This is the foundation of air-gapped container deployments.`,
    `Explore BuildKit, the modern Docker build system. Build a multi-platform image (linux/amd64 and linux/arm64) using docker buildx build --platform linux/amd64,linux/arm64. Push it to a registry and observe that the same image tag serves both architectures. This is how Docker Hub serves images for Apple Silicon and Intel Macs.`,
    `Learn about container security context. Run a container with --security-opt=no-new-privileges and --cap-drop=ALL. Then add back only the capabilities your application needs (--cap-add=NET_BIND_SERVICE to bind to low ports). This principle of least privilege for Linux capabilities is the basis of Kubernetes security contexts.`,
  ],
});

rewriteWeek("devops-cloud", 9, {
  context: `Kubernetes is the operating system for containers at scale. The core problem it solves: you have 10 containers (your app, the database, the cache, the background workers, the metrics collector) running across 5 servers. How do you decide which container runs on which server? How do you restart crashed containers? How do you update containers without downtime? How do you expose services on the network? Kubernetes answers all of these questions with a declarative API.

The key mental model: you tell Kubernetes what you want (desired state), and Kubernetes continuously works to make the actual state match the desired state. You do not say "start container X on server 3." You say "I want 3 replicas of container X." Kubernetes decides where to place them (the scheduler), starts them, monitors them, and restarts them if they crash (the controller manager).

The building blocks. Pod: the smallest deployable unit — one or more containers that share network and storage. Usually one container per pod. Deployment: manages a set of replicas of a pod. It ensures the desired number are running and handles rolling updates. Service: gives pods a stable network endpoint. Pods come and go (they restart, move to different nodes); a Service has a stable IP and DNS name that load-balances across the current pod set. ConfigMap: external configuration (non-sensitive) mounted as files or environment variables. Secret: sensitive configuration, encoded in base64 and stored in Kubernetes' etcd (with encryption at rest if configured).

Nodes and the control plane: a Kubernetes cluster has worker nodes (where your pods run) and the control plane (where the Kubernetes API server, scheduler, and controller manager run). kubectl communicates with the API server. The API server stores desired state in etcd. The scheduler assigns pods to nodes. The kubelet on each node pulls the assigned pods and runs them via containerd.

kubectl is your primary tool for interacting with Kubernetes: kubectl get pods, kubectl describe pod [name], kubectl logs [pod-name], kubectl apply -f manifest.yaml, kubectl delete -f manifest.yaml. Everything in Kubernetes is defined in YAML manifests.`,

  pre_flight: `Install kubectl: kubectl.io/docs/tasks/tools. Install minikube (for local Kubernetes): minikube.sigs.k8s.io/docs/start. Start a local cluster: minikube start. Verify: kubectl cluster-info. Install k9s (TUI for Kubernetes): k9scli.io — much faster than typing kubectl commands. Read the Kubernetes concepts documentation: pods, deployments, services, and configmaps. Run kubectl get nodes and kubectl get pods --all-namespaces to see the cluster state.`,

  mastery_questions: [
    `What is the difference between a Pod and a Deployment? A Pod is a single instance of your application running in a container (or group of containers). If a Pod crashes, it is gone — Kubernetes does not automatically replace it (unless something else manages it). A Deployment is a controller that manages a set of Pod replicas. You specify replicas: 3 and the Deployment ensures 3 identical Pods are always running. If one crashes, the Deployment creates a replacement. When you update the image, the Deployment performs a rolling update (starts new Pods with the new image, terminates old ones, always maintaining a minimum number of running Pods during the update). Use Deployments for stateless applications. Use StatefulSets for stateful applications (databases) where each Pod has a stable identity and persistent storage.`,
    `You have 3 replicas of your app Pod. A user makes a request. How does the request reach the correct Pod? A Service with selector: app: myapp matches all Pods with the label app: myapp. The Service gets a ClusterIP (a stable virtual IP within the cluster) and a DNS name (myapp.default.svc.cluster.local). kube-proxy on each node programs iptables rules that load-balance traffic to the ClusterIP across the 3 pod IPs (round-robin by default). When a Pod is replaced, its new IP is automatically added to the Service's endpoint list. The user's request hits the Service IP; iptables forwards it to one of the Pod IPs.`,
    `A Pod is in CrashLoopBackOff status. What does this mean and how do you investigate? The container is crashing repeatedly. Kubernetes restarts it, but exponentially backs off between restarts (1s, 2s, 4s, 8s... up to 5 minutes). To investigate: kubectl logs [pod-name] — see the last crash output. kubectl logs [pod-name] --previous — see the output from the previous crash (the container that crashed). kubectl describe pod [pod-name] — see events (why the container started, what happened). The most common causes: incorrect environment variables (missing DATABASE_URL), the application crashing on startup due to a bug, or a misconfigured liveness probe that is killing the container before it finishes starting.`,
    `What is a Namespace in Kubernetes and why do you use them? A Namespace is a virtual cluster within a physical cluster. Resources (Pods, Deployments, Services) are isolated per namespace. The default namespace is default. Kubernetes system components run in kube-system. You create namespaces to separate environments (dev, staging, production) or teams (team-a, team-b) within the same physical cluster. Resource quotas can be applied per namespace (team-a can use at most 4 CPU and 8GB RAM). RBAC (Role-Based Access Control) can be scoped to namespaces (team-a members can only manage resources in the team-a namespace).`,
  ],

  common_mistakes: [
    `Running stateful applications (databases) as simple Deployments. Deployments assume stateless pods — any pod can be replaced by any other pod. Databases need stable network identities (Pod 0 is the primary, Pod 1 is the replica) and stable persistent volumes. Use StatefulSets with PersistentVolumeClaims for databases. Or better: use managed databases (RDS, Cloud SQL) outside Kubernetes.`,
    `Not setting resource requests and limits on every container. Without requests, the scheduler cannot make good placement decisions (it does not know how much CPU/memory your container needs). Without limits, one container can consume all resources on a node and starve others. Set both for every container.`,
    `Using kubectl edit to make ad-hoc changes to running resources. Changes made with kubectl edit are not tracked in git and will be overwritten the next time you apply your manifests. Always make changes in your YAML files and apply them. kubectl edit is for emergency debugging only.`,
    `Not understanding the difference between kubectl apply and kubectl replace. apply is declarative and idempotent — it computes the difference between your manifest and the current state. replace replaces the entire resource. Use apply for normal operations. replace is for cases where apply cannot merge (rare). Never use kubectl create for resources you manage with manifests — it fails if the resource already exists.`,
    `Exposing a Service as NodePort for external access in production. NodePort opens a port on every node (30000-32767 range). This is fine for testing but not for production. Use a LoadBalancer Service (which provisions a cloud load balancer) or an Ingress controller for HTTP/HTTPS traffic.`,
  ],

  debug_help: `Pod is stuck in Pending: kubectl describe pod [name] > Events section. "0/2 nodes are available: 2 Insufficient memory" means the Pod's requested memory exceeds what any node has available. Reduce the resource request or add a node. Pod is in ImagePullBackOff: the container image cannot be pulled. Check the image name and tag. For private registries, check that the imagePullSecret is configured correctly. kubectl commands time out: check kubectl cluster-info — is the cluster reachable? For minikube, ensure minikube status shows the cluster is running. Service is not routing to Pods: check that the Service selector (matchLabels) matches the Pod labels exactly. kubectl get endpoints [service-name] shows which Pod IPs are in the endpoint list. If it is empty, the selector does not match.`,

  ai_assist: [
    `"Write Kubernetes YAML manifests for a Node.js application: a Deployment with 3 replicas, resource requests (100m CPU, 128Mi memory) and limits (500m CPU, 256Mi memory), environment variables from a ConfigMap and a Secret, a liveness probe (GET /health every 15s) and a readiness probe (GET /ready every 5s). And a Service of type ClusterIP on port 80 targeting the Deployment."`,
    `"Explain the Kubernetes scheduler. When a Pod is created, what factors does the scheduler use to decide which node to place it on? What are node selectors, node affinity, pod affinity, and taints/tolerations? Give a concrete example of when you would use each."`,
    `"Write a kubectl cheat sheet for the 20 most-used commands in daily Kubernetes operations: getting resource status, describing resources, viewing logs, exec-ing into pods, port forwarding, applying and deleting manifests, scaling deployments, and rollback."`,
  ],

  stretch: [
    `Deploy a complete multi-tier application (web app + PostgreSQL + Redis) to your local minikube cluster. Use a Deployment for the web app, a StatefulSet for PostgreSQL, a Deployment for Redis, Services connecting them, ConfigMaps for non-sensitive config, and Secrets for passwords. Expose the web app with a NodePort Service and access it in your browser.`,
    `Learn the Kubernetes RBAC system. Create a service account for a hypothetical CI system. Grant it permission to: get, list, watch Deployments in the production namespace, and update images in those Deployments. Restrict it from accessing Secrets. Test that it can update the Deployment but not read secrets with kubectl auth can-i.`,
    `Set up cluster monitoring on minikube: deploy the kube-prometheus-stack using Helm (covered next week). Access the Grafana dashboard and explore the default dashboards — node CPU/memory, Pod status, and the number of API server requests. This is a preview of W19's observability content.`,
  ],
});

rewriteWeek("devops-cloud", 10, {
  context: `Running Kubernetes in development (W9) teaches the concepts. Running it in production teaches the hard lessons. Production Kubernetes requires four things that are unnecessary in local testing: probes (how the cluster knows your pod is healthy), resource management (how the scheduler places pods and prevents noisy neighbours), autoscaling (how the cluster handles traffic spikes without over-provisioning), and storage (how stateful applications persist data across pod restarts).

Probes: Kubernetes has three probe types. Liveness probe: "is the container still alive?" If this fails, Kubernetes restarts the container. Use for detecting deadlocks or unresponsive states. Readiness probe: "is the container ready to serve traffic?" If this fails, the pod is removed from the Service's endpoint list — it stops receiving traffic but is not restarted. Use for slow startup or temporary unavailability (running a database migration). Startup probe: "has the container started yet?" Delays the liveness probe for slow-starting applications. A misconfigured liveness probe that fires too early will kill healthy pods in a restart loop.

Resource requests and limits. Requests: what the scheduler guarantees each pod. The node must have at least this much free. Limits: the maximum a pod can use. On CPU: exceeding the limit causes throttling (the pod is slowed down). On memory: exceeding the limit causes an OOMKill (the pod is killed). The ratio between requests and limits is the resource "burstiness" — a pod that requests 100m CPU but has a 1000m limit can burst 10x when resources are available.

Horizontal Pod Autoscaler (HPA): automatically scales the number of replicas based on CPU utilisation (or custom metrics). When average CPU usage across pods exceeds 70%, HPA adds more replicas. When it drops below 50%, HPA removes replicas. HPA requires the metrics-server add-on in minikube (minikube addons enable metrics-server).

PersistentVolumes and PersistentVolumeClaims: the Kubernetes storage model. A PersistentVolume (PV) is a piece of storage provisioned by an admin or dynamically by a StorageClass. A PersistentVolumeClaim (PVC) is a request for storage by a pod. The PVC binds to a PV of sufficient size and access mode. The pod mounts the PVC as a directory. When the pod restarts or moves to a different node (for RWO volumes — only possible within the same zone), the PVC follows.`,

  pre_flight: `Enable the metrics-server add-on in minikube: minikube addons enable metrics-server. Run kubectl top nodes and kubectl top pods to verify metrics are available. Read the Kubernetes documentation on probes, resource management, and HPA. Understand what QoS classes are in Kubernetes (Guaranteed, Burstable, BestEffort) and how they affect OOM kill priority.`,

  mastery_questions: [
    `You have a web application that takes 45 seconds to start (it runs database migrations on startup). You configure a liveness probe that checks /health every 10 seconds with a failure threshold of 3. What happens? The liveness probe starts immediately. After 30 seconds (3 failures × 10 seconds), Kubernetes determines the container is unhealthy and restarts it. The container restarts, takes another 45 seconds to start... and is killed again. This is a crash loop. The fix: add a startupProbe with failureThreshold: 60 and periodSeconds: 5 (total of 5 minutes for startup). The liveness probe is suspended until the startup probe succeeds. Once the app has started, liveness probe takes over.`,
    `An HPA is configured to scale between 2 and 10 replicas, targeting 70% CPU. Current CPU is 40% with 3 replicas. The CPU suddenly spikes to 200%. What happens? HPA reacts within 30-60 seconds (the HPA sync interval). It calculates the desired replicas: ceil(3 × (200/70)) = ceil(8.57) = 9 replicas. It scales up to 9. The new pods take time to start (30-60 seconds for a typical Node app). During this window, the existing 3 pods handle 200% CPU (they are throttled). Once the 9 pods are ready, each handles 200/9 = 22% CPU (well below the 70% target). HPA will then scale down after the scale-down stabilisation window (5 minutes by default) to prevent flapping.`,
    `A StatefulSet pod is in Pending because "0/1 nodes are schedulable: 1 node(s) had untolerated taint". What is a taint and how do you fix it? A taint is a marker on a node that prevents pods from being scheduled there unless the pod has a matching toleration. Taints are used to reserve nodes for specific workloads: a GPU node might have a taint nvidia.com/gpu=present:NoSchedule. Only pods with a toleration for that taint can schedule there. To fix: either add a toleration to the pod spec (allows it to run on the tainted node), or identify a different untainted node for the pod. In minikube, the control plane node is often tainted NoSchedule — your workloads should run on worker nodes.`,
    `What is the difference between a PersistentVolume access mode ReadWriteOnce (RWO) and ReadWriteMany (RWX)? ReadWriteOnce: the volume can be mounted read-write by a single node at a time. All pods on that node can read and write, but pods on other nodes cannot mount it. This is typical for block storage (AWS EBS, GCP Persistent Disk). ReadWriteMany: the volume can be mounted read-write by multiple nodes simultaneously. Required for scenarios where multiple pods on different nodes need to read and write the same data (a shared file store). RWX requires a distributed filesystem: NFS, AWS EFS, Azure Files. Block storage does not support RWX.`,
  ],

  common_mistakes: [
    `Setting the liveness probe to the same endpoint and timing as the readiness probe. They serve different purposes. The liveness probe should be lightweight (just checks if the process is alive). The readiness probe checks actual readiness (database connection). If the database goes down, the readiness probe should fail (removing the pod from the load balancer), but the liveness probe should continue to pass (do not restart the pod — the database is the problem, not the pod).`,
    `Not setting resource requests, which leads to Burstable or BestEffort QoS class. Pods without both requests and limits are BestEffort — the first to be OOM-killed when the node runs low on memory. Set both requests and limits on every container. Set them equal for predictable performance (Guaranteed QoS class).`,
    `Scaling down too aggressively. HPA's default scale-down behaviour removes one pod per minute. This is slow but prevents cascading failures. Do not set aggressively short stabilizationWindowSeconds on scale-down — a traffic spike that ends can cause premature scale-down, then another spike can overwhelm the under-provisioned fleet.`,
    `Using a Deployment with RWO PersistentVolumes for a stateful workload. If the pod is rescheduled to a different node, the EBS volume (RWO) cannot follow — it is in the old node's availability zone. Use a StatefulSet with PVCs for stateful workloads, and use storage in the same zone as the node.`,
    `Not setting PodDisruptionBudgets. When a node is drained (for maintenance, upgrade, or scaling down), Kubernetes evicts pods. Without a PodDisruptionBudget (PDB), all pods of a Deployment could be evicted simultaneously — causing an outage. Set a PDB: minAvailable: 1 ensures at least one replica is always running during voluntary disruptions.`,
  ],

  debug_help: `HPA is not scaling: verify that metrics-server is running (kubectl get pods -n kube-system | grep metrics-server). HPA requires the metrics API. Check kubectl describe hpa [name] for events. HPA will not scale if the current metric is within the target range (it is working correctly). Pod is OOMKilled: kubectl describe pod [name] shows "OOMKilled" in the container state. Increase the memory limit or profile the application for memory leaks. PVC is stuck in Pending: kubectl describe pvc [name] for the reason. Common causes: no available PV that matches the size and access mode, or the StorageClass is not configured. In minikube, use storageClassName: standard.`,

  ai_assist: [
    `"Write Kubernetes YAML for a Node.js Deployment with: a startup probe (GET /health, failureThreshold: 30, periodSeconds: 5 — allows 2.5 minutes for startup), a liveness probe (GET /health, after startup succeeds), and a readiness probe (GET /ready, which checks database connectivity). Set resource requests and limits appropriately for a typical Node web server."`,
    `"Write a HorizontalPodAutoscaler for a Deployment that scales between 2 and 20 replicas based on CPU utilisation (target 60%) and custom metric http_requests_per_second (target 100 rps). Include the scale-down stabilization window of 5 minutes to prevent flapping."`,
    `"Write a PersistentVolumeClaim and the corresponding volume mount in a Pod spec for a PostgreSQL StatefulSet. The PVC requests 10Gi of storage with ReadWriteOnce access mode and uses the default StorageClass. Mount it at /var/lib/postgresql/data."`,
  ],

  stretch: [
    `Implement Vertical Pod Autoscaler (VPA) alongside HPA. VPA recommends and optionally adjusts resource requests based on actual usage. Run it in recommendation mode (updateMode: Off) for one week and see what resource requests it recommends. This gives you data-driven resource sizing instead of guessing.`,
    `Deploy a chaos engineering experiment using chaos-mesh or litmus. Configure a pod failure experiment that randomly kills pods in your Deployment at 5-minute intervals. Verify that your HPA and pod restart policies keep the application serving traffic during the failures. This proves your resilience configuration works.`,
    `Set up cluster autoscaling in minikube using minikube's autoscaler profile. Configure the Cluster Autoscaler to add nodes when pods are unschedulable and remove empty nodes. Observe the full autoscaling chain: load spikes → HPA adds pods → pods are unschedulable → Cluster Autoscaler adds a node → pods schedule.`,
  ],
});
