import { rewriteWeek } from "../rewrite-week";

// devops-cloud W1-W5

rewriteWeek("devops-cloud", 1, {
  context: `Before containers, Kubernetes, or Terraform, you need to understand what a server is: a computer running software that listens for network connections and responds to them. Strip away all the abstraction, and that is the whole thing. This week you operate a raw Linux server without any help from managed platforms. Everything you do manually this week is something you will later automate — but you cannot automate what you do not understand.

A VPS (Virtual Private Server) is a slice of a physical server running as an isolated virtual machine. You get root access. There is no UI. You interact via SSH. The operating system is Linux (Ubuntu is the standard choice — large community, long-term support releases, most documentation assumes it). You are responsible for everything: updates, firewall rules, web server configuration, process management.

SSH (Secure Shell) is how you connect. You authenticate with a key pair (more secure than a password). The private key stays on your machine; the public key goes on the server. When you SSH, you prove you have the private key without ever sending it.

What a web server is: nginx or Apache listens on port 80 (HTTP) and 443 (HTTPS). When a request arrives, it reads the request line (GET / HTTP/1.1), the Host header (which domain is being requested), and routes the request to the appropriate application (a Node process, a static file, a Python app). The web server is a reverse proxy — it sits in front of your application and handles the HTTP protocol details.

Process management: your Node.js application is a process. If it crashes, you want it to restart automatically. systemd is the Linux init system that manages processes — it can start a service on boot, restart it on crash, and provide logs. This week you manage your Node process with systemd.

The capstone project for this track is Edge Portfolio: a portfolio site deployed on real infrastructure, progressively hardened over the first 4 weeks.`,

  pre_flight: `Create an account on DigitalOcean, Hetzner, or Linode. Provision the smallest Ubuntu 22.04 LTS server (1 vCPU, 1GB RAM). Configure SSH key authentication (do not enable password auth). Note the server's IP address. Install nginx: sudo apt update && sudo apt install nginx. Know basic Linux commands: ls, cd, cat, sudo, systemctl, nano/vim. Read the SSH man page (man ssh) for key-based authentication.`,

  mastery_questions: [
    `You connect to your server via SSH and run ps aux. You see your Node app is running. You also see nginx. Describe the relationship between these two processes when a user visits your website. A user's browser sends a TCP request to your server's IP on port 80 or 443. nginx is listening on those ports — it receives the request. Based on its configuration (the server_name directive matching the requested domain), nginx forwards the request to your Node app (running on port 3000, for example) via proxy_pass http://localhost:3000. The Node app processes the request and sends a response back to nginx. nginx forwards the response to the user's browser. nginx is the front door; Node is the application behind it.`,
    `Your Node application crashes. A minute later, a user visits the site and gets a 502 Bad Gateway error from nginx. What is happening and how do you prevent automatic recovery? 502 Bad Gateway means nginx cannot connect to the upstream (your Node process). The process is gone. To restart it automatically, run it as a systemd service with Restart=on-failure in the service unit file. When Node crashes, systemd detects the exit and restarts the process within seconds. You configure a restart delay (RestartSec=5) to prevent a fast crash loop. Check the logs: journalctl -u your-service-name.`,
    `You want to restrict SSH access to your server so only your IP address can connect. How do you do this and what is the risk? Configure ufw (the Ubuntu firewall): ufw allow from YOUR_IP to any port 22, then ufw deny 22. This allows SSH only from your IP. The risk: if your IP changes (many home ISPs assign dynamic IPs), you are locked out. The mitigation: configure ufw before locking it down, ensure you have a recovery method (DigitalOcean/Hetzner console access that does not use SSH), and use a static IP or VPN if your IP changes frequently.`,
    `Explain what happens when you run sudo apt upgrade on your server. apt downloads the new package versions for all installed software from Ubuntu's package repositories. It installs them, replacing the old versions. For services like nginx, the service is restarted automatically after the upgrade. For the kernel, a reboot is required to load the new kernel. Security patches are released regularly — a server that has not been updated in 6 months is a server with known, unpatched vulnerabilities. Set up automatic security updates: sudo dpkg-reconfigure unattended-upgrades.`,
  ],

  common_mistakes: [
    `Leaving root SSH enabled with a password. Bots scan the internet and attempt to brute-force SSH passwords. Disable password authentication (PasswordAuthentication no in /etc/ssh/sshd_config). Use key-based auth only. Create a non-root user with sudo for daily operations.`,
    `Running your application as root. If the application has a vulnerability and is exploited, the attacker runs as root — they own the server. Create a dedicated user for your application with no sudo privileges.`,
    `Not configuring a firewall on day one. A fresh server exposes all ports by default. Run ufw allow 22, ufw allow 80, ufw allow 443, then ufw enable. Deny everything else. Every open port is an attack surface.`,
    `Making manual changes without documentation. "I changed something in nginx.conf last month and now I do not know why that line is there." Treat configuration files as code — commit them to a git repository. This is the foundation of "infrastructure as code."`,
    `Storing application secrets in environment variables set manually on the server. These are lost if the server is destroyed. Store configuration in a file (/etc/app/env) owned by root and readable by the app user, committed to version control without the secrets (use a template with placeholder values).`,
  ],

  debug_help: `SSH connection refused: check that the server is running (DigitalOcean console). Check that sshd is running: systemctl status ssh. Check ufw rules: ufw status. If you locked yourself out, use the hosting provider's web console. nginx returns 502: check that your application process is running (systemctl status your-app). Check nginx logs: tail -f /var/log/nginx/error.log. Check your app logs: journalctl -u your-app -f. DNS not pointing to server: new DNS records take 24-48 hours to propagate. Check current DNS resolution: dig your-domain.com A. Use a TTL checker to see what the world sees vs what you just set. systemd service does not start: check the service file syntax with systemctl cat your-app.service. Check the failure reason: journalctl -u your-app --since "1 hour ago".`,

  ai_assist: [
    `"Write a systemd service unit file for a Node.js application running as user 'appuser', working directory /home/appuser/app, command: node server.js. It should restart on failure with a 5-second delay, load environment variables from /etc/app/env, and start after the network is available."`,
    `"Write an nginx server block configuration for a Node.js app on port 3000. It should: listen on port 80, redirect HTTP to HTTPS, listen on port 443 with SSL cert paths, proxy requests to localhost:3000, set proxy headers (X-Real-IP, X-Forwarded-For), and serve static files from /home/appuser/app/public directly."`,
    `"Write a bash server hardening script for Ubuntu 22.04 that: creates a non-root user with sudo, disables root SSH login, disables password authentication, configures ufw to allow only SSH/HTTP/HTTPS, enables unattended-upgrades, and installs fail2ban."`,
  ],

  stretch: [
    `Set up a second server and configure nginx as a load balancer between the two application servers. The upstream block in nginx distributes requests round-robin. Test by stopping one server and verifying requests still succeed. This is horizontal scaling in its simplest form.`,
    `Configure log rotation for your application logs. Without rotation, log files grow until they fill the disk. logrotate is the standard tool — configure it to rotate daily, keep 7 days of logs, and compress old logs.`,
    `Set up a simple monitoring script: a cron job that pings your website every 5 minutes and sends an email (via sendmail or a simple SMTP library) if the response code is not 200. This is primitive uptime monitoring — the concept you will replace with Prometheus and Grafana in W19.`,
  ],
});

rewriteWeek("devops-cloud", 2, {
  context: `A server with an IP address works, but users do not navigate to IP addresses — they navigate to domain names. This week you configure a real domain name for Edge Portfolio and set up HTTPS, which is now required (browsers mark HTTP sites as "Not Secure", Google penalises HTTP sites in search rankings, and many APIs refuse to work without HTTPS).

DNS (Domain Name System) is the internet's phone book. When a user types your domain into a browser, the DNS resolver looks up the IP address for that domain. You control this mapping by configuring records at your domain registrar or a DNS provider (Cloudflare is the standard — free tier, fast propagation, and useful additional features).

DNS record types you need: A record maps a domain to an IPv4 address (yourdomain.com → 1.2.3.4). AAAA maps to an IPv6 address. CNAME (Canonical Name) maps a domain to another domain name (www → yourdomain.com). MX records specify mail servers. TXT records contain arbitrary text — used for domain ownership verification, SPF/DKIM for email, and other security records.

TTL (Time to Live): how long DNS resolvers cache your record. A low TTL (60 seconds) means changes propagate quickly but every DNS lookup hits your authoritative server. A high TTL (86400 — one day) means changes take a day to reach all users but DNS lookups are served from cache. Use low TTL when you are making changes; increase it after things are stable.

HTTPS via Let's Encrypt: Let's Encrypt is a free Certificate Authority. It issues SSL/TLS certificates that browsers trust. Certbot is the standard client — it authenticates your domain ownership (via a temporary file it places on your server, or via DNS), requests the certificate, installs it in nginx, and sets up automatic renewal. Certificates expire in 90 days. Certbot renews them automatically (via a cron job or systemd timer) before they expire.

HSTS (HTTP Strict Transport Security): a response header that tells browsers to always use HTTPS for your domain, even if the user types http://. Once a browser has seen the HSTS header, it refuses HTTP connections to your domain for the specified duration.`,

  pre_flight: `Buy a domain name (Namecheap or Cloudflare Registrar). Set the nameservers to Cloudflare's (if using Cloudflare DNS). Create an A record pointing your domain to your server IP. Wait for DNS propagation (check with: dig yourdomain.com A). Install Certbot: sudo apt install certbot python3-certbot-nginx. Make sure your domain resolves to your server before running certbot — it needs to make an HTTP request to your server for domain validation.`,

  mastery_questions: [
    `You run certbot --nginx -d yourdomain.com and get "Error: Failed to connect to host for DVSNI challenge." What is happening? Certbot's ACME HTTP-01 challenge works by: Certbot places a file at /.well-known/acme-challenge/[token] on your server. Let's Encrypt's servers make an HTTP request to http://yourdomain.com/.well-known/acme-challenge/[token]. If it matches, the domain is verified. This fails when: your A record does not point to this server (DNS not propagated, or pointing to the wrong IP), port 80 is blocked by ufw, or nginx is not running. Check each in order: dig yourdomain.com A, ufw status, systemctl status nginx.`,
    `Your Let's Encrypt certificate expires in 3 days. Certbot's automatic renewal has not worked. How do you manually renew it? Run: sudo certbot renew --force-renewal. This forces renewal even though the certificate is not yet within the usual 30-day renewal window. If it fails, check: does Certbot still have a working configuration file at /etc/letsencrypt/renewal/yourdomain.com.conf? Is port 80 open (required for the HTTP-01 challenge)? Has nginx configuration changed since the original certificate was issued? The renewal log is at /var/log/letsencrypt/letsencrypt.log.`,
    `What is the difference between a wildcard certificate and a single-domain certificate? A single-domain certificate is valid for one hostname (yourdomain.com) and optionally a second (www.yourdomain.com if you include both with -d). A wildcard certificate (*.yourdomain.com) is valid for any subdomain of yourdomain.com — api.yourdomain.com, blog.yourdomain.com, anything.yourdomain.com. Wildcard certificates require DNS-01 validation (proving domain ownership via a TXT record in DNS) instead of HTTP-01, because the challenge must be independent of the web server (there is no specific server to place a file on for "every subdomain"). Let's Encrypt supports wildcard certificates via the DNS-01 challenge.`,
    `Explain what HSTS preloading is and what the risk of setting it up incorrectly is. HSTS tells browsers "always use HTTPS for this domain." HSTS preloading takes it further — major browsers (Chrome, Firefox, Safari) maintain a hardcoded list of domains that always require HTTPS, regardless of whether the browser has previously visited the site. If your domain is on the preload list, it is enforced even on first visit. The risk: if you ever need to downgrade to HTTP (your HTTPS is broken, your certificate is invalid), HSTS-preloaded domains will be inaccessible in every browser until the preloading is removed — which takes months (the browser update cycle). Only preload if you are certain HTTPS is permanent.`,
  ],

  common_mistakes: [
    `Running certbot before DNS has propagated. Let's Encrypt's servers must be able to reach your server via the domain name. If the A record is not pointing to your server yet, the challenge fails. Use dig and external DNS checkers to verify before running certbot.`,
    `Not setting up automatic certificate renewal. Let's Encrypt certificates expire in 90 days. Certbot installs a cron job or systemd timer for renewal automatically, but verify it is working: sudo certbot renew --dry-run. A certificate that expires is an outage.`,
    `Using self-signed certificates in production. Self-signed certificates are not trusted by browsers — users see a security warning. They are fine for internal development. In production, use Let's Encrypt.`,
    `Not redirecting HTTP to HTTPS. If your site serves both HTTP and HTTPS, Google indexes both, creating duplicate content issues. Users on HTTP never get the security benefits of HTTPS. Set up a permanent redirect (301) from HTTP to HTTPS in nginx.`,
    `Setting an overly long HSTS max-age on a site that is not ready. If HSTS is set to one year and you have a certificate issue, users are locked out for a year. Start with max-age=300 (5 minutes) while testing, then increase to 31536000 (one year) once confident.`,
  ],

  debug_help: `Certificate not trusted by browser (shows "Not Secure" even with HTTPS): check that Let's Encrypt issued the certificate (not a self-signed one). Run: openssl s_client -connect yourdomain.com:443 and check the issuer. Mixed content warnings: your page loads over HTTPS but some resources (images, scripts) are loaded over HTTP. Find them in Chrome DevTools > Console (mixed content errors) and update the URLs to HTTPS. nginx HTTPS config not working after certbot: certbot modifies nginx config automatically. Check /etc/nginx/sites-available/default for the SSL configuration it added. If you have a custom nginx config file, certbot may have modified the wrong file. Domain resolves but times out: your ufw firewall may be blocking port 443. Run: sudo ufw allow 443 and then test again.`,

  ai_assist: [
    `"Write the complete nginx configuration for a Node.js app with: HTTP to HTTPS redirect, HTTPS with Let's Encrypt certificate at /etc/letsencrypt/live/yourdomain.com/, proxy to localhost:3000, HSTS header with 1 year max-age, security headers (X-Frame-Options, X-Content-Type-Options, Referrer-Policy), and gzip compression."`,
    `"Write a Cloudflare DNS configuration for: apex domain pointing to server IP (A record), www subdomain as CNAME to apex, and mail server MX record pointing to mail.yourdomain.com. Also explain which records should have Cloudflare proxying enabled and which should be DNS-only."`,
    `"Explain the ACME protocol that Let's Encrypt uses. Walk through the HTTP-01 challenge step by step: what Certbot sends, what Let's Encrypt verifies, what token is used, and how the certificate is issued."`,
  ],

  stretch: [
    `Set up Cloudflare in front of your server. Change your A record to Cloudflare's proxy mode (the orange cloud). Cloudflare now sits between your users and your server — it provides DDoS protection, CDN caching for static assets, and hides your server's real IP. Configure Cloudflare's SSL mode to "Full (strict)" to require a valid certificate between Cloudflare and your server.`,
    `Configure automated SSL certificate monitoring. Write a script (or use a service like SSL Labs' API) that checks your certificate expiry date weekly and sends a notification if it is less than 30 days away. This is a redundant layer on top of Certbot's auto-renewal.`,
    `Implement Certificate Transparency monitoring. CT logs record every certificate issued for your domain. Set up an alert (via Facebook's Cert Transparency Monitoring, or crt.sh) that notifies you when any certificate is issued for your domain. This catches certificate mis-issuance or phishing attempts.`,
  ],
});

rewriteWeek("devops-cloud", 3, {
  context: `Continuous Integration / Continuous Deployment is the practice that makes software teams move fast without breaking things. Before CI/CD: a developer writes code, tests it locally (maybe), and manually deploys to the server (SSH in, git pull, restart service, hope nothing broke). After CI/CD: every push to the repository automatically runs tests and (if they pass) deploys to the server. The human is removed from the deployment process. This sounds scary; it is actually what makes deployment less scary.

GitHub Actions is the CI/CD system built into GitHub. Every repository gets free minutes for public repos and a monthly quota for private repos. Workflows are YAML files in .github/workflows/ that define what happens when events occur (push to main, pull request opened, manual trigger). Each workflow runs on a virtual machine provided by GitHub (the runner). You choose the runner OS: ubuntu-latest, macos-latest, windows-latest.

The deployment step: after the code passes tests, you need to get the new code onto your server. Several approaches. Direct SSH deploy: the GitHub Action SSHs into your server, pulls the latest code, and restarts the service (simple, works for a single server). Container-based deploy: build a Docker image, push to a container registry, SSH into the server and pull the new image (more complex, but the image is tested and immutable). For now, direct SSH is fine.

Secrets management in GitHub Actions: never hardcode server credentials in your workflow file. Use repository secrets: Settings > Secrets and Variables > Actions > New Repository Secret. In the workflow, reference them as \${{ secrets.SSH_PRIVATE_KEY }}. These are encrypted and only exposed to workflows — GitHub employees cannot read them.

Deployment safety: a deploy script that runs git pull && npm install && npm run build && systemctl restart app has a window where the service is stopped and new code is not yet running. For a personal portfolio, this is acceptable (seconds of downtime). For production services, use zero-downtime deployment strategies: blue-green deployment, rolling updates, or at minimum: build first, then swap.`,

  pre_flight: `Your GitHub repository should contain your application code. Add a .github/workflows/ directory. Know YAML syntax (indentation is significant — use spaces, not tabs). Read the GitHub Actions quickstart guide. Add your server's SSH private key as a GitHub repository secret (SSH_PRIVATE_KEY). Add your server IP as a secret (SERVER_HOST). Add your deployment user as a secret (SERVER_USER).`,

  mastery_questions: [
    `Your CI/CD pipeline runs: checkout code, npm ci, npm test, ssh into server, git pull, npm ci, pm2 restart. The tests pass. The deploy SSH step fails because the server is temporarily unreachable. The pipeline fails but the server still has the old code. Is this a problem? No — this is the correct behaviour. The deployment gate (tests pass) protected the server from broken code. The server still runs the last working version. The failure alerts you (via GitHub's email notification or Sentry) to investigate the server connectivity. The pipeline is idempotent — re-running it (once the server is reachable) will deploy the same code again safely.`,
    `You want to deploy to production only when a commit is tagged (not on every push to main). How do you configure this in GitHub Actions? Use the on.push.tags trigger: on: { push: { tags: ['v*'] } }. This fires only when a tag matching v* (e.g., v1.0, v1.2.3) is pushed. Your release process: push code to main normally (no deploy). When ready to release, tag the commit: git tag v1.2.0 && git push origin v1.2.0. The tagged push triggers the deploy workflow.`,
    `You have a deploy workflow that SSHs into your server and runs git pull. The workflow uses an SSH key stored as a GitHub secret. How does the SSH connection work, and what must be configured on the server? The GitHub Actions workflow: (1) writes the private key to a temp file on the runner, (2) runs ssh -i /tmp/keyfile user@server 'git pull && npm ci && pm2 restart app', (3) deletes the key file. On the server: the public key (matching the private key in GitHub Secrets) must be in /home/user/.ssh/authorized_keys. The server's SSH daemon reads authorized_keys and allows the connection if the runner can prove it holds the corresponding private key.`,
    `What is the difference between CI and CD, and which part needs more discipline? CI (Continuous Integration) is running automated checks (tests, linting, type checking) on every code push. CD (Continuous Delivery/Deployment) is automatically deploying code that passes CI. CI catches bugs early; CD speeds up the release cycle. The part that needs more discipline: CD. Automated deploys to production mean a bad commit can break production without a human review step. Discipline: maintain a high-quality test suite (bugs that reach production should have a failing test that was not there), enforce PR reviews before merging to main, have a rollback procedure ready.`,
  ],

  common_mistakes: [
    `Committing secrets to the repository. Even "temporary" secrets in code end up in git history forever. Use GitHub Actions secrets for all credentials. Scan your repository with truffleHog or gitleaks to find any secrets already committed.`,
    `Not caching dependencies in CI. Running npm ci from scratch on every workflow run takes 30-90 seconds. Use actions/cache with the package-lock.json hash as the key — cache hits restore node_modules in under 10 seconds.`,
    `Deploying directly to main without a pull request or test gate. CD does not mean "push and it goes to production." CD means "code that passes CI is automatically deployed." The gate (passing tests) is essential. Without it, CD means "push and break production."`,
    `No rollback procedure. Every automated deployment should have a documented, tested rollback procedure. For a simple git pull deploy, rollback is git checkout [previous-commit] && pm2 restart app. Know it before you need it.`,
    `Using the same deployment user for all services. Create a specific deployment user with minimal permissions — can only write to the application directory, cannot sudo, cannot access other services. Compromise of this user only affects the specific application.`,
  ],

  debug_help: `GitHub Action fails at SSH step "Permission denied (publickey)": the SSH key stored in GitHub Secrets does not match the key in authorized_keys on the server. Generate a new key pair (ssh-keygen -t ed25519), add the public key to authorized_keys on the server, add the private key to GitHub Secrets. Workflow triggers but does not find secrets: check that the secret name in the workflow (\${{ secrets.SSH_KEY }}) matches the name in GitHub repository settings exactly (case-sensitive). Also check that the workflow file is in the default branch — secrets are available only to workflows triggered from the branch where the secret was added. git pull fails on server ("your local changes would be overwritten"): someone edited files directly on the server. Always make changes through git — never edit production files directly. Run git status on the server to see what changed, then git stash or git checkout -- . and re-deploy.`,

  ai_assist: [
    `"Write a GitHub Actions workflow for a Node.js app that: triggers on push to main, caches node_modules with actions/setup-node, runs npm ci, npm run lint, npm test, npm run build, then SSHs into a server using a private key from secrets, runs git pull and npm ci and pm2 restart app. Include error handling."`,
    `"Write a deployment script (deploy.sh) that runs on the server during a CI deploy. It should: pull latest code, install dependencies without devDependencies (npm ci --production), build the app, use pm2 to zero-downtime reload (pm2 reload app rather than restart), and notify a Slack webhook of the deployment status."`,
    `"Explain the difference between GitHub Actions' ubuntu-latest and self-hosted runners. When would I use a self-hosted runner? What are the security considerations for a self-hosted runner that deploys to production?"`,
  ],

  stretch: [
    `Add a staging environment. Your pipeline deploys to staging on every push to main, and to production only on version tags. The staging server is identical to production in configuration but uses a staging database and subdomain (staging.yourdomain.com). This gives you a place to test the full deployed application before it goes to real users.`,
    `Implement deployment notifications. After a successful deploy, your workflow posts a message to a Slack channel or sends an email: "Deployed v1.2.3 to production at 14:32 UTC. Commit: fix rate limiting on login." After a failed deploy: "Deploy failed at step 'SSH to server'. Check GitHub Actions logs." Use the Slack webhook action from the GitHub Marketplace.`,
    `Add a smoke test step to the workflow. After deployment, run a simple HTTP request against the production URL and check that the response code is 200. If the smoke test fails, trigger an automatic rollback (run the rollback SSH command). This catches cases where the deploy succeeds but the app crashes on startup.`,
  ],
});

rewriteWeek("devops-cloud", 4, {
  context: `You cannot improve what you cannot measure. Monitoring is the practice of collecting data about your system's health and setting up alerts so you know when something is wrong before your users do. In W1-W3, you built and deployed Edge Portfolio. In W4, you instrument it.

There are two types of monitoring. Black-box monitoring (also called synthetic monitoring or uptime monitoring) tests your system from the outside: an external service pings your URL every minute and alerts you if it does not get a 200 response. This is the first layer. It tells you the system is broken but not why.

White-box monitoring (also called telemetry) collects data from inside the system: the application exposes metrics (request count, error rate, latency), the server exposes system metrics (CPU, memory, disk), and you send logs to a centralised log management service. This tells you why the system is broken.

The four golden signals of service health (from Google's SRE book): Latency (how long does a request take?), Traffic (how many requests per second?), Errors (what rate of requests fail?), and Saturation (how full is the system — CPU, memory, disk?). An anomaly in any of these signals indicates a problem.

Structured logging: logs should be machine-parseable JSON, not free-text sentences. timestamp, level, message, requestId, userId, durationMs, statusCode as JSON fields allow you to query by any dimension. A free-text log ("Error: something went wrong for user 123") is useful when you are reading it; a structured log is useful when you are searching across millions of lines.

Uptime monitoring services: BetterUptime, UptimeRobot (free tier), Freshping. These send a request to your site every minute from multiple geographic locations and alert you (Slack, email, PagerDuty) if the response takes too long or is not 200. Your on-call starts with an uptime alert.

This week you set up uptime monitoring for Edge Portfolio, ship structured logging, and build a basic health check endpoint.`,

  pre_flight: `Create a BetterUptime account (betterstack.com) or UptimeRobot account (uptimerobot.com). Know what your site's normal response time is (open Chrome DevTools > Network > load your site > check the Time column). Install pino for structured logging: npm i pino pino-http. Know how to set environment variables on your server (/etc/app/env or pm2 ecosystem.config.js). Read the Google SRE book chapter on "Monitoring Distributed Systems" (available free online).`,

  mastery_questions: [
    `You get a BetterUptime alert at 3am: "Edge Portfolio is down." What is your runbook? Step 1: check BetterUptime for the error — what HTTP response code is it getting? Is it a timeout (no response) or an error (5xx)? Step 2: SSH into the server. Step 3: check if nginx is running (systemctl status nginx). Step 4: check if your app is running (systemctl status your-app or pm2 status). Step 5: check your app logs (journalctl -u your-app -f or pm2 logs). Step 6: check disk space (df -h) — a full disk causes everything to fail in unexpected ways. Step 7: check memory (free -h) — OOM can kill processes. Step 8: check nginx logs (/var/log/nginx/error.log). Most outages are one of: app crashed, disk full, OOM kill.`,
    `Your health check endpoint returns 200. But your application is in a degraded state — it cannot reach the database so reads work (from cache) but writes fail. How do you design the health check to detect this? A health check that only checks "is the server running?" misses partial failures. Design a comprehensive health check: check the database connection (run a simple query), check any caches (ping Redis), check any critical external dependencies. Return 200 if everything is healthy, 200 with a degraded status if non-critical dependencies are down, 503 if critical dependencies (database) are down. The uptime monitor should alert on 503, not just timeouts.`,
    `You are investigating a slow API endpoint. Structured logs show: most requests take 50-100ms, but some take 3000ms. How do you identify the cause? Filter logs by durationMs > 1000. Look at the request patterns — is it specific users, specific query parameters, specific times of day? If it is specific users, they may be running expensive queries. If it is specific times, it may correlate with a background job or another service's activity. Add more granular timing breadcrumbs to the slow code path: measure the database query time, the external API call time, the data processing time separately. The breakdown tells you where the 3 seconds went.`,
    `What is the difference between a log and a metric? A log is a record of a discrete event: "User 123 logged in at 14:32:05, from IP 1.2.3.4, took 45ms." Logs are append-only records of individual events. A metric is a numeric measurement aggregated over time: "In the last minute, 250 login requests, 2.4% error rate, p95 latency 120ms." Metrics are aggregations of many events. Logs are useful for investigating a specific incident. Metrics are useful for detecting trends and anomalies. A production system needs both.`,
  ],

  common_mistakes: [
    `Monitoring only from the inside. Your internal metrics show the application is healthy. But the CDN in front of it is caching a 500 error response. External (black-box) monitoring catches what internal monitoring misses.`,
    `Alert fatigue — too many alerts. If alerts fire for minor, expected events (a spike on Monday morning, a occasional slow response), you train yourself to ignore them. Alert only when action is required. Set thresholds that reflect real user impact.`,
    `Not testing your alerts. An alert that never fires might be silently broken. Deliberately trigger each alert type (take the server down, fill the disk, crash the app) and verify the notification arrives.`,
    `Free-text logs without structure. grep is not a log query language. Use structured JSON logs from day one so you can filter, aggregate, and query them efficiently.`,
    `No log retention policy. Logs accumulate. Without rotation and retention limits, logs fill the disk. Use logrotate or a log management service with a defined retention period (30 days for most applications, longer for compliance-heavy industries).`,
  ],

  debug_help: `Uptime monitor keeps alerting even though the site loads fine: the monitor may be checking from a different geographic location than your test. Check if there is a geographic issue — a CDN misconfiguration that only affects specific regions. Also check if the monitor is getting a redirect (301/302) instead of 200 — some monitors treat redirects as down. Pino logs are not appearing in log aggregation: check that the application writes to stdout (not a file) and that your log aggregation setup reads from stdout. On systemd, logs go to journald; forward them to your log service with a journald forwarder. Health check endpoint is slow: the health check should not do heavy database queries. Run a simple SELECT 1 and cache the result for 5 seconds. A health check that takes 2 seconds is not a health check — it is a load test.`,

  ai_assist: [
    `"Write a Node.js Express health check endpoint at GET /health that: checks database connectivity (run a SELECT 1 via your ORM), checks Redis connectivity (run PING), returns 200 with JSON { status: 'healthy', checks: { db: { status: 'ok', latencyMs: N }, redis: { status: 'ok', latencyMs: N } } } if all pass, 503 with the same structure (but failing check marked as 'error') if any critical check fails."`,
    `"Write a pino-http middleware setup for an Express app that: logs every request with method, url, statusCode, durationMs, userId (from req.user if set), and requestId (a UUID generated per request). Format as JSON in production, pretty-print in development."`,
    `"Write a BetterUptime alert escalation policy: first alert via Slack within 1 minute of downtime, if not acknowledged in 5 minutes escalate via SMS, if not acknowledged in 15 minutes escalate via phone call. Show the BetterUptime configuration steps and the API configuration."`,
  ],

  stretch: [
    `Set up the full ELK stack (Elasticsearch, Logstash, Kibana) on your server using Docker Compose. Ship your application logs from journald to Logstash. Create a Kibana dashboard with: request volume per minute, error rate, p95 latency, top 10 slow endpoints. This is the monitoring setup used by many mid-sized engineering teams.`,
    `Implement request tracing with correlation IDs. Each request gets a UUID (X-Request-ID header). Every log line in that request's lifecycle includes the correlation ID. Write a query in your log system that shows all log lines for a specific request ID. This is the foundation of distributed tracing.`,
    `Set up a weekly performance report. A script runs every Monday, queries your log aggregation service for the previous week's metrics (p50/p95/p99 latency, error rate, total requests, top 5 slowest endpoints), and emails a formatted summary. This gives you a weekly view of trends without needing to check dashboards.`,
  ],
});

rewriteWeek("devops-cloud", 5, {
  context: `Docker solves the "works on my machine" problem. Before Docker: your Node application runs on your macOS laptop (Node 20, specific npm packages, specific system libraries). On the Ubuntu 22.04 production server with Node 18, a different npm package version, and different system libraries — it behaves differently. Docker packages your application and all its dependencies (including the OS libraries) into an immutable image. The image runs identically on your laptop, on CI, and on production.

A container is a running instance of an image. An image is a template — the blueprint. A container is a running process using that blueprint. You can run multiple containers from the same image simultaneously (they share the image but each has its own file system layer and process namespace).

Namespaces and cgroups: Docker is not a virtual machine. It does not emulate hardware. It uses Linux kernel features. Namespaces isolate processes (a process inside a container sees only its own filesystem, network interface, and process tree). cgroups limit resources (this container gets at most 512MB RAM and 0.5 CPU cores). The container shares the host kernel — this is why Docker on macOS and Windows requires a Linux virtual machine underneath (Docker Desktop). The result is lighter and faster than a VM.

Dockerfile: the recipe for building an image. FROM declares the base image. COPY brings files from your build context into the image. RUN executes commands during the build. EXPOSE declares which port the container uses. CMD sets the default command when the container starts. Every Dockerfile instruction creates a new layer in the image. Layers are cached — if a layer has not changed since the last build, Docker reuses the cached layer (fast builds). Order your instructions from least-changing to most-changing to maximise cache hits.

Multi-stage builds: two FROM instructions in one Dockerfile. The first stage builds the application (installs devDependencies, compiles TypeScript). The second stage copies only the compiled output from the first stage and installs only production dependencies. The final image does not contain the build tools — it is smaller and more secure.`,

  pre_flight: `Install Docker Desktop on your machine (docker.com/products/docker-desktop). Run docker run hello-world to verify installation. Know the basic Docker commands: docker build, docker run, docker ps, docker stop, docker images, docker logs. Read the Dockerfile reference documentation. Know the difference between docker run and docker start. Read the Docker layer caching documentation.`,

  mastery_questions: [
    `You have a Node.js application. Write the conceptual Dockerfile and explain each instruction. FROM node:20-alpine — base image (Alpine Linux is small: 5MB vs 70MB for the Debian node image). WORKDIR /app — set the working directory for all subsequent commands. COPY package*.json ./ — copy package files first (before source code) to leverage layer caching. RUN npm ci --only=production — install dependencies. This layer is cached as long as package*.json does not change (even if your source code changes). COPY . . — copy source code. RUN npm run build (if applicable). EXPOSE 3000 — document the port (does not publish it). CMD ["node", "server.js"] — the command that runs when the container starts.`,
    `You build a Docker image and it is 800MB. The underlying Node Alpine base image is 170MB. Your application code is 1MB. Where did the other 629MB come from? node_modules. A full Node.js project with devDependencies installed can have hundreds of packages. Fixes: use a multi-stage build — in the build stage, install everything (including devDependencies). In the final stage, copy only the built artifacts and run npm ci --only=production. devDependencies (TypeScript compiler, testing frameworks, build tools) stay in the build stage and are not in the final image. Also check whether you are copying .git, test files, or documentation — add a .dockerignore file to exclude them.`,
    `What is a .dockerignore file and why is it critical? .dockerignore tells Docker which files to exclude from the build context (the directory sent to the Docker daemon when building). Without it, COPY . . copies everything including node_modules (which you do not want — you want Docker to install them cleanly), .git (large history), test files, and .env files (secrets). The build context is sent over a socket to the Docker daemon — a large context is slow. A .dockerignore with node_modules, .git, .env, *.log, coverage/ significantly reduces build time and prevents accidentally including secrets in the image.`,
    `You run a container with docker run -p 3000:3000 myapp. What does the -p flag do and what is the port mapping? -p HOST_PORT:CONTAINER_PORT publishes a container port to the host. EXPOSE 3000 in the Dockerfile documents that the container listens on port 3000 — it does not make it accessible. -p 3000:3000 maps port 3000 on the host to port 3000 in the container. Requests to localhost:3000 on the host are forwarded to port 3000 inside the container. You can map to a different host port: -p 8080:3000 maps host:8080 to container:3000. Multiple containers from the same image can each be mapped to different host ports.`,
  ],

  common_mistakes: [
    `Running as root inside the container. By default, Docker containers run as root. A vulnerability in your application could give an attacker root inside the container — and potentially root on the host. Add USER node (or a non-root user) to your Dockerfile before CMD.`,
    `Not using .dockerignore. node_modules gets copied into the image context, then Docker installs them again inside. You end up with two copies of node_modules. Worse: .env files with secrets get included. Always add .dockerignore before your first docker build.`,
    `Putting COPY . . before RUN npm install. This breaks layer caching — every source code change invalidates the npm install layer and forces a full reinstall. Copy package files first, run npm install, then copy source code.`,
    `Using the latest tag in production. FROM node:latest gives you whatever the latest Node version is today. Next month, latest might be Node 22 with breaking changes. Pin your base image version: FROM node:20.12-alpine3.19. Pin both the major and minor version.`,
    `Storing secrets in environment variables passed via docker run -e. These are visible in docker inspect, ps aux output, and docker history. Use Docker secrets (for Swarm), Kubernetes secrets, or a vault — not environment variables for sensitive values.`,
  ],

  debug_help: `Build fails with "COPY failed: file not found in build context": the file path in COPY is relative to the Dockerfile's location (the build context). Use docker build -f /path/to/Dockerfile . (the dot is the build context directory) and check that the file exists in that directory. Container starts but immediately exits: check docker logs [container_id]. A Node.js app that crashes on startup exits immediately. The CMD must be a foreground process — if it exits, the container exits. Do not use pm2 or background processes as CMD. Container is running but application is not accessible: check that you published the port (-p HOST:CONTAINER). Check that the application is binding to 0.0.0.0, not 127.0.0.1 (localhost binding inside the container is not accessible from outside).`,

  ai_assist: [
    `"Write a multi-stage Dockerfile for a Node.js TypeScript application. Stage 1 (build): install all dependencies including devDependencies, compile TypeScript to JavaScript. Stage 2 (production): start FROM node:20-alpine, copy compiled output from the build stage, run npm ci --only=production, add a non-root user, set USER and CMD. Include a .dockerignore file."`,
    `"Explain Docker layer caching. Given this Dockerfile: [paste a Dockerfile], identify which layers will be rebuilt when the source code changes vs when package.json changes. Reorder the instructions to maximise cache hits."`,
    `"Write a docker build command that: tags the image as myapp:1.0.0 and myapp:latest, passes a build arg BUILD_DATE, and uses BuildKit for faster builds. Then write the docker run command that runs it with the port mapped and the NODE_ENV environment variable set to production."`,
  ],

  stretch: [
    `Reduce your application's Docker image size to the minimum possible. Use a multi-stage build, Alpine base, --only=production install, and a non-root user. Measure before and after with docker images. Compare to using Distroless (gcr.io/distroless/nodejs) — no shell, no package manager, only Node and your application.`,
    `Implement Docker image vulnerability scanning with Trivy (free, runs locally): trivy image myapp:1.0.0. Fix the critical and high severity CVEs by either updating the base image or switching to a less vulnerable base. Add Trivy to your CI pipeline as a gate.`,
    `Learn how Docker networking works: create two containers (an app and a database), connect them on a user-defined bridge network, and verify they can communicate by hostname. Observe that containers on the default bridge network can only communicate by IP, while user-defined networks support DNS resolution by container name.`,
  ],
});
