import { rewriteWeek } from "../rewrite-week";

// devops-cloud W21-W24

rewriteWeek("devops-cloud", 21, {
  context: `Cloud bills grow in proportion to how little you pay attention to them. The discipline of managing cloud costs is called FinOps (Financial Operations). Most teams over-provision infrastructure by 30-50% "just in case" and then forget about it. A FinOps practice makes cost visible, allocates it to teams, and creates incentives to optimise.

The biggest cost levers in AWS (and broadly applicable): right-sizing instances (running a c5.4xlarge when a c5.xlarge handles the load), Reserved Instances or Savings Plans (committing to 1-3 years of a certain capacity for 30-60% savings), spot instances (unused AWS capacity at 70-90% discount — interruptible, suitable for batch jobs, CI runners, stateless workloads), NAT Gateway data processing ($0.045/GB processed — a hidden cost driver), EBS snapshots and unused volumes, data transfer costs (egress from AWS to the internet), and idle resources (development environments left running on weekends).

AWS Cost Explorer is your primary cost analysis tool. It shows cost by service, by region, by tag (if you have resource tagging), by linked account (if you have AWS Organizations), and over time. The Cost Anomaly Detection feature alerts you when spend deviates significantly from the baseline — catching accidental expensive resources within hours instead of at the monthly bill.

Resource tagging is the foundation of cost allocation. Without tags, you cannot determine which team, product, or environment is responsible for which costs. Define a tagging taxonomy before creating resources: Environment (prod/staging/dev), Team (infrastructure/frontend/data), Product (app/analytics). Enforce tags with AWS Config rules or SCPs (Service Control Policies) that deny resource creation without required tags.

Kubernetes cost allocation: a Kubernetes cluster pools resources across many workloads. OpenCost (open source) and Kubecost track per-namespace and per-deployment costs by combining Kubernetes resource requests with cloud instance pricing. This answers: "how much does the payments service cost per month to run?"`,

  pre_flight: `Enable AWS Cost Explorer (it takes 24 hours to populate). Set up a billing alert: AWS Console > Billing > Billing Preferences > Alert Preferences. Install the AWS CLI with Cost Explorer access. Create a budget in AWS Budgets with a monthly alert at 80% of your expected spend. Install kubecost in your Kubernetes cluster: helm install kubecost kubecost/cost-analyzer --namespace kubecost. Read the AWS FinOps whitepaper.`,

  mastery_questions: [
    `Your AWS bill this month was $4,200 — 40% higher than last month. How do you investigate? Open AWS Cost Explorer and compare this month to last month by service. Look for the service with the largest absolute increase. Then break that service down by resource type or usage type. Common culprits: EC2 (new instances, larger instances), RDS (new databases, more storage), NAT Gateway data processing (traffic surge), S3 (data accumulation, API calls). Use the Cost Anomaly Detection alerts — they show the specific resource ID and the day the anomaly started. Filter by tag to see which team or product drove the increase. Find the specific resource ID, check when it was created, and contact the responsible team.`,
    `You are running 10 EC2 instances of type m5.xlarge for your application tier. You analyse the CloudWatch CPU metrics and see average CPU is 8% with p99 of 22%. What action do you take? The instances are severely over-provisioned. You are paying for 4 vCPUs and 16GB RAM per instance but using less than a quarter. Right-size to m5.large (2 vCPUs, 8GB RAM) — the p99 CPU of 22% fits within the smaller instance. Running 10 m5.large costs ~60% less than 10 m5.xlarge. If you need the aggregate capacity, keep the count; if the load is low enough, reduce the count too. Validate in staging first. The AWS Compute Optimizer service provides automated right-sizing recommendations based on actual CloudWatch usage patterns.`,
    `Your team has a development environment that runs Monday-Friday. The RDS database and EC2 instances run 24/7 at a cost of $300/month. How do you reduce the cost without affecting developers? Schedule the instances to stop after business hours and start before. AWS Instance Scheduler (or a Lambda triggered by EventBridge) can stop EC2 instances at 7pm and start them at 7am, Monday-Friday. This gives 66% of the month off — reduces EC2 cost by ~66%. For RDS, use the RDS start/stop API on the same schedule. For EKS worker nodes, use the Cluster Autoscaler's scale-to-zero feature for the dev node group on weekends. Total savings: 50-60% of the dev environment cost.`,
    `What is a Reserved Instance vs a Savings Plan, and when do you use each? Reserved Instances (RI): commit to a specific instance type, family, region, and OS for 1 or 3 years. Get 30-60% discount. Convertible RIs can be exchanged for different instance types. Best for: workloads that need a specific instance type with known, stable resource requirements. Savings Plans: commit to a specific dollar amount of compute usage per hour for 1 or 3 years. The discount applies automatically to any eligible compute usage (EC2, Fargate, Lambda) that matches the commitment. More flexible than RIs. Compute Savings Plans apply to any EC2 instance in any family, size, region, or OS. Best for: flexible workloads where instance types change frequently.`,
  ],

  common_mistakes: [
    `Not tagging resources from day one. Adding tags retroactively is painful — many resources are already running without tags. Enforce tags at provisioning time using IAM policies (Deny resource creation without required tags), Terraform variables, or AWS Service Control Policies.`,
    `Paying on-demand prices for workloads that have been running for over a year. After a year, convert high-utilisation workloads to Reserved Instances or Savings Plans. On-demand is fine for unpredictable workloads; it is expensive waste for stable, long-running workloads.`,
    `Leaving development environments running on weekends and holidays. A dev database running 24/7 is paying for 168 hours when you use maybe 45. Schedule start/stop for dev environments.`,
    `Ignoring data transfer costs. Egress from AWS to the internet: $0.09/GB. NAT Gateway processing: $0.045/GB. VPC peering between regions: $0.02/GB in each direction. These add up. Use VPC endpoints for S3 and DynamoDB (free, eliminates NAT costs for these services). Use CloudFront to cache and reduce origin egress.`,
    `Not setting up cost anomaly detection. Without it, a developer accidentally creates a large EC2 instance or starts an expensive service and you find out at the monthly bill. Cost Anomaly Detection alerts within hours of unusual spend. Set the threshold to alert when spend is $10 above the baseline.`,
  ],

  debug_help: `Cost Explorer shows high EC2 costs but you cannot identify the instance: add cost allocation tags and filter by tag. If resources are not tagged, use the "Cost Explorer: Resource" view (enable it in preferences) which shows individual resource IDs and their costs. NAT Gateway costs are high: check VPC Flow Logs to see which resources are sending the most traffic through the NAT Gateway. Consider VPC endpoints for S3, DynamoDB, and other AWS services — traffic to these services via endpoint is free (no NAT processing fee). Kubecost shows inaccurate costs: verify that Kubecost's cloud integration is configured (it connects to AWS Cost and Usage Report for accurate pricing). Without cloud integration, Kubecost uses list prices which may differ from your actual discounted prices.`,

  ai_assist: [
    `"Write a Lambda function (Node.js) triggered by EventBridge Scheduler that stops EC2 instances and RDS databases tagged with Environment:dev at 7pm UTC Monday-Friday, and starts them at 7am UTC Monday-Friday. Use the AWS SDK v3. Include error handling and a CloudWatch metric for success/failure."`,
    `"Analyse this AWS Cost and Usage Report CSV: [paste sample]. Identify: the top 5 services by cost, month-over-month changes, resources without required tags, and potential savings opportunities (over-provisioned instances based on usage data)."`,
    `"Write a Terraform configuration for an AWS Budget with: monthly budget of $500, alert at 80% actual spend, alert at 100% forecasted spend. Add a Cost Anomaly Detection monitor with a threshold of $10 above baseline. Route both alerts to an SNS topic that sends to a Slack webhook."`,
  ],

  stretch: [
    `Implement a full FinOps review for your existing infrastructure. Using AWS Cost Explorer and Compute Optimizer: identify all over-provisioned instances, calculate potential savings from right-sizing, calculate savings from Reserved Instance commitments, and identify idle resources (instances with < 5% CPU for 2 weeks). Document the findings and implement the top 3 cost savings.`,
    `Set up OpenCost in your Kubernetes cluster and configure it with cloud integration for accurate AWS pricing. Create a monthly cost allocation report that shows cost per namespace, per deployment, and per team (via namespace labels). Build a Grafana dashboard that shows Kubernetes cost trends over time.`,
    `Implement spot instance usage for your Kubernetes node group. Create a node group with a mix of on-demand (2 nodes) and spot instances (up to 10 nodes). Configure the Cluster Autoscaler to use spot for burst capacity. Use the interruption handler (AWS Node Termination Handler) to gracefully drain spot instances when they are reclaimed. Measure the cost reduction over a 30-day period.`,
  ],
});

rewriteWeek("devops-cloud", 22, {
  context: `Disaster recovery is about business continuity when things go catastrophically wrong: a region goes down, data gets corrupted, a database is accidentally dropped, ransomware encrypts your storage. Most teams have backup policies they have never tested. The only backup that matters is one you have verified can be restored in the required time window.

Two key metrics define your DR requirements. RPO (Recovery Point Objective): the maximum age of data you can afford to lose. If your RPO is 1 hour, your backup frequency must be at least hourly — you can lose at most 1 hour of data. RTO (Recovery Time Objective): the maximum acceptable duration of downtime. If your RTO is 4 hours, your recovery procedure must restore service within 4 hours. Both are business decisions that inform technical choices.

Backup strategies. Database backups: PostgreSQL full backup (pg_dump) + WAL (Write-Ahead Log) archiving allows point-in-time recovery (PITR) — restore to any second in the archive window. RDS automated backups provide 35-day PITR. Restore testing: quarterly, actually restore from backup to a test environment and verify data integrity. Object storage: enable versioning and cross-region replication on S3 buckets that contain critical data. Kubernetes resources: use Velero to backup and restore Kubernetes resources and PersistentVolumes.

Multi-region active-passive: your primary region (us-east-1) serves all traffic. A secondary region (eu-west-1) has the infrastructure to serve traffic but is idle or serving only a fraction. In a primary region failure, DNS fails over to the secondary (Route 53 health checks + failover records). RTO is 5-15 minutes (DNS propagation time). The secondary region's database is a read replica that gets promoted to primary.

Multi-region active-active: both regions serve traffic simultaneously. Users in the US go to us-east-1; users in Europe go to eu-west-1. Each region has its own database. Data is replicated between regions (using CockroachDB, Cassandra, or synchronised PostgreSQL replicas). More complex and expensive, lower latency for geographically distributed users.

The disaster you have not planned for: what about accidental data deletion? A developer runs DELETE FROM users WHERE id > 0 (meant WHERE id = 123). PostgreSQL PITR can restore the database to 5 seconds before the query. But only if you have WAL archiving configured and the backup is available.`,

  pre_flight: `Enable automated backups on your RDS instance (if using RDS — modify the backup retention to 7 days and verify PITR is enabled). Set up Velero in your Kubernetes cluster: velero install --provider aws --backup-storage-location s3://your-backup-bucket/velero. Read the AWS Disaster Recovery whitepaper (four DR strategies: backup and restore, pilot light, warm standby, multi-site active-active). Calculate your application's RPO and RTO requirements.`,

  mastery_questions: [
    `A developer accidentally runs DROP TABLE users on the production PostgreSQL database. The error is caught 4 minutes after it happens. Your database is on RDS with automated backups and a 7-day retention. How do you recover and what data do you lose? PostgreSQL PITR: restore to a point-in-time 5 minutes before the DROP statement. RDS PITR: create a new RDS instance from the backup (Restore to point in time — specify the timestamp). This creates a new RDS instance (not an in-place restore). You then either: change your application's connection string to the new instance, or dump the users table from the restored instance and import it into the current instance. Data lost: the last 5 minutes of writes. How long the recovery takes: 15-30 minutes to restore a typical database, plus your connection string update and deployment.`,
    `Your primary region (us-east-1) is experiencing a broad AWS outage. Your RTO is 30 minutes. You have a warm standby in eu-west-1 (a running cluster with a read replica database). Walk through the failover procedure. Step 1: declare incident, notify stakeholders. Step 2: promote the eu-west-1 RDS read replica to primary (rds:PromoteReadReplica). This takes 3-5 minutes. Step 3: update application configuration (the database connection string environment variable). Deploy the updated configuration to eu-west-1's EKS cluster. Step 4: update Route 53 health check rules — the us-east-1 ALB is failing the health check, Route 53 automatically fails over DNS to the eu-west-1 ALB. Step 5: verify the application is serving traffic from eu-west-1. Total time: 10-20 minutes. Data lost since last replication from primary: typically seconds (async replication lag).`,
    `You have an S3 bucket containing user-uploaded files. A bug in your application deletes all files in the bucket. How do you prevent this and how do you recover? Prevention: enable S3 versioning — deletions create a delete marker; the file is not actually deleted. Enable MFA Delete — requires MFA to permanently delete objects. Use S3 Object Lock with a compliance retention policy — objects cannot be deleted for a specified period even by the root account. Recovery: with versioning enabled, remove the delete markers to restore all files: use the AWS CLI to list delete markers and remove them (batch operation). Without versioning, recovery depends on whether you have backups elsewhere (cross-region replication to another bucket).`,
    `What is the difference between a backup and high availability? They solve different problems. High availability (HA): the system stays available during component failures (node failure, database crash, AZ outage). HA is about redundancy and automatic failover. You do not lose time. Backup and recovery: you can restore the system after catastrophic failure (data corruption, accidental deletion, ransomware, multi-AZ failure). Backups accept some data loss (RPO) and recovery time (RTO). A system can have both: HA to handle common failures without interruption, and backups for catastrophic scenarios. Or just one: high-traffic sites often have HA but poor backup practices; small sites often have backups but no HA.`,
  ],

  common_mistakes: [
    `Never testing restores. A backup that has never been restored is not a backup — it is hope. Schedule quarterly restore tests. Document the restore procedure. Measure the actual RTO. The first time you test a restore should not be during an actual disaster.`,
    `Storing backups in the same region as the primary data. An AWS region outage would take down both your primary data and your backups. Cross-region replication (S3 CRR, RDS cross-region read replicas, backup to another region) ensures regional disasters do not eliminate backups.`,
    `Not encrypting backups. Backups contain all your user data. An unencrypted backup stored in S3 is readable by anyone with the bucket URL (if permissions are misconfigured). Enable server-side encryption for all backup storage.`,
    `RPO and RTO that do not match business requirements. If your backup frequency is daily (RPO = 24 hours) but the business requires maximum 1 hour of data loss, there is a gap. Have the RPO/RTO conversation with business stakeholders before designing your backup strategy.`,
    `Not accounting for restore time in the RTO. RTO includes: detecting the failure (monitoring alerts, time to be paged), diagnosing the issue, deciding to fail over or restore, running the restore procedure, verifying the restore, updating DNS or connection strings, and monitoring the restored system. Each step takes time. A database that takes 2 hours to restore from backup cannot meet a 1-hour RTO.`,
  ],

  debug_help: `RDS PITR fails: check that automated backups are enabled (the backup retention period is > 0). PITR requires at least one automated backup to exist. The restore target time must be within the backup window (up to retentionPeriod days ago). Velero backup fails: check the Velero pod logs (kubectl logs deployment/velero -n velero). Common causes: S3 permissions (the Velero ServiceAccount needs S3 read/write), PV snapshot permissions (needs ec2:CreateSnapshot). Velero restore is incomplete: Velero restores resources in dependency order (namespaces first, then PVCs, then Pods). If a PVC fails to restore (snapshot not available in the target region), dependent Pods will be pending. Check velero describe restore [restore-name] for detailed status of each resource.`,

  ai_assist: [
    `"Write an AWS Backup plan using Terraform that: backs up all RDS instances and EBS volumes with the tag BackupEnabled:true daily (retained for 35 days), weekly (retained for 3 months), and monthly (retained for 1 year). Copy weekly backups to a secondary region (eu-west-1). Enable notifications via SNS on backup failures."`,
    `"Write a disaster recovery runbook for an application running on EKS with an RDS PostgreSQL database. The runbook covers: (1) multi-AZ failure — automatic failover, (2) RDS accidental data deletion — PITR restore procedure, (3) full region failure — failover to secondary region. Include exact AWS CLI commands, estimated time for each step, and verification steps."`,
    `"Write a Velero backup and restore procedure for a Kubernetes cluster migration from us-east-1 to eu-west-1. Include: creating a backup with PV snapshots, verifying the backup, creating a new cluster in eu-west-1, configuring Velero to read from the us-east-1 backup bucket, restoring, and validating the restoration."`,
  ],

  stretch: [
    `Run a real disaster recovery exercise. Take a production database snapshot, restore it to a separate RDS instance, and measure actual restore time. Connect a staging version of your application to the restored database and verify all features work. Document the exact time for each step. Compare actual RTO to your stated target.`,
    `Implement database PITR with continuous WAL archiving for a self-managed PostgreSQL instance (not RDS). Set up pgBackRest to archive WAL to S3 and take base backups every 6 hours. Simulate data loss and restore to a specific point in time. This is the skill required for managing PostgreSQL in Kubernetes (with CloudNativePG or Patroni).`,
    `Build a chaos engineering experiment targeting storage. Use chaos-mesh to inject an S3 access failure for your application's file storage. Verify that the application degrades gracefully (returns an error, not a crash). Then restore S3 access and verify the application recovers without restart.`,
  ],
});

rewriteWeek("devops-cloud", 23, {
  context: `Cloud security posture is the aggregate security state of all your cloud resources. A misconfigured S3 bucket (public read on a bucket containing user data) has caused some of the largest data breaches in history. IAM misconfigurations (overly permissive roles, long-lived access keys, no MFA) are the leading cause of cloud account compromise. Network misconfigurations (security groups allowing 0.0.0.0/0 on sensitive ports) expose services that should be internal.

IAM best practices. The principle of least privilege: every user, service, and application should have exactly the permissions they need — no more. Avoid the AdministratorAccess policy except for break-glass accounts. Use IAM Roles for services (not long-lived access keys). Enable MFA for all human users (especially root and admin accounts). Rotate access keys regularly (or use OIDC/IRSA to eliminate long-lived keys entirely). Use the IAM Access Analyzer to identify resources accessible from outside your account.

Security scanning tools. Prowler is a free, open-source tool that scans your AWS account against hundreds of CIS AWS Benchmark checks, NIST, SOC2, and other compliance frameworks. It checks IAM policies, S3 bucket permissions, CloudTrail logging, VPC configurations, encryption settings, and more. AWS Security Hub aggregates findings from Prowler, AWS GuardDuty, AWS Inspector, and other security tools into one dashboard.

Network security. Security groups: allow inbound traffic from specific CIDR blocks or other security groups, not 0.0.0.0/0. Bastion hosts and Systems Manager Session Manager for SSH access (no public SSH port open). VPC design: public subnets only for load balancers; private subnets for compute and databases. VPC Flow Logs for auditing network traffic. AWS WAF in front of public-facing applications.

CloudTrail: records every API call to AWS. Who created that S3 bucket? Who changed the security group rule? Who deleted the IAM user? CloudTrail has the answer. Enable CloudTrail in every region, enable log file integrity validation, and store logs in a separate account that production has no access to (so an attacker who compromises production cannot tamper with the audit trail).`,

  pre_flight: `Install Prowler: pip install prowler or run as Docker. Run your first Prowler scan: prowler aws --severity critical high. Create an AWS Security Hub account and enable the CIS AWS Foundations Benchmark standard. Enable AWS GuardDuty (30-day free trial). Enable CloudTrail if not already enabled (it may be on by default; verify logs are being stored). Read the AWS Well-Architected Framework Security Pillar.`,

  mastery_questions: [
    `Prowler finds that your RDS database is publicly accessible (rds:DBInstancePubliclyAccessible = true). What does this mean, what is the risk, and how do you fix it? Publicly accessible means the RDS instance has a public IP address and could receive connections from the internet (depending on the security group). Risk: if the security group allows port 5432 from 0.0.0.0/0, anyone on the internet can attempt to connect to your database. Even with a strong password, this exposes you to brute-force attacks, credential stuffing, and CVE exploitation. Fix: modify the RDS instance to set PubliclyAccessible to false (removes the public IP). Move the database to a private subnet. Connect from your application via the VPC-internal hostname. If you need direct access for debugging, use a bastion host or AWS SSM Session Manager tunnel.`,
    `You have an IAM role with the policy Action: ["*"], Resource: "*" used by your application's EC2 instance. This role is required because the application accesses many AWS services. How do you reduce the risk? Replace the wildcard policy with a specific policy. Audit what API calls the application actually makes: use the IAM Access Advisor (IAM console > Roles > role name > Access Advisor tab) which shows last-used service data. Or enable CloudTrail and query for API calls made by this role's credentials. Identify the actual services and actions used. Create a least-privilege policy with only those actions on the required resources. The goal: if the EC2 instance is compromised, the attacker has access only to the specific S3 bucket and SQS queue your application uses — not to your entire AWS account.`,
    `Your CloudTrail shows that at 3:47am, someone accessed the AWS console and created an IAM user with administrator access. You did not authorise this. What do you do? This is an incident. Immediately: revoke the newly created IAM user's access (disable or delete). Revoke any access keys created for the new user. Check CloudTrail for what the attacker did with the new user's credentials. Identify the compromised account: which user or role made the 3:47am API calls? How did the attacker get those credentials? Remediation: rotate all access keys, enable MFA on all human users (if not already done), review and revoke any other changes made by the attacker, engage AWS Support if you suspect broader compromise.`,
    `What is the shared responsibility model in AWS, and how does it affect your security obligations? AWS is responsible for the security of the cloud (physical datacenters, hardware, global network, hypervisor). You are responsible for security in the cloud (your data, operating system, network configuration, IAM, application code). Practically: AWS ensures the EC2 hypervisor is secure; you are responsible for patching the OS on your EC2 instances. AWS ensures S3 infrastructure is secure; you are responsible for your S3 bucket permissions. AWS ensures the RDS software is patched; you are responsible for your database user permissions and connection encryption.`,
  ],

  common_mistakes: [
    `Creating IAM users with programmatic access for applications. Use IAM Roles instead (for EC2, ECS, Lambda) or OIDC (for GitHub Actions, Kubernetes). Long-lived access keys are credentials that can be stolen. IAM Roles use temporary credentials rotated automatically.`,
    `Leaving default security group rules (0.0.0.0/0 on all ports) in place. The default security group in a VPC allows all outbound and all inbound from other resources in the same security group — not from the internet. But a common mistake is creating a security group that allows 0.0.0.0/0 on 22 (SSH) or 5432 (PostgreSQL) "temporarily" and never restricting it.`,
    `Not enabling encryption at rest and in transit. All sensitive data stores should use encryption at rest (RDS encrypted, S3 SSE-S3 or SSE-KMS, EBS encrypted). All communication should use TLS. Enable S3 bucket policy to deny HTTP (non-HTTPS) access.`,
    `Not reviewing security findings regularly. Prowler and Security Hub findings accumulate. Without a regular review cycle, critical findings sit unresolved for months. Schedule a weekly 30-minute security findings review. Assign findings to the responsible team. Track remediation progress.`,
    `Root account usage. The AWS root account has unlimited access to everything and cannot be restricted with IAM. Use the root account only for initial setup and specific tasks that require root (changing the support plan, closing the account). Enable MFA on root, remove access keys, and create admin IAM users for daily operations.`,
  ],

  debug_help: `Prowler scan takes too long: scope it to specific checks with --service iam s3 cloudtrail or --compliance cis_level1_aws. GuardDuty is generating false positives (Pentest:IAMUser findings from your security scanning): suppress findings from known-good sources. In GuardDuty console, go to Findings, select the finding, and add a suppression rule. CloudTrail logs are not appearing in S3: check that the trail is enabled and the S3 bucket policy grants CloudTrail access. Common issue: the bucket policy was modified and removed CloudTrail's write permission. S3 Access Analyzer shows a bucket is public: check the bucket policy and ACL. The Access Analyzer checks both the bucket policy and the public access block settings. If the bucket is in a restricted account (S3 Block Public Access enabled at the account level), individual bucket policies cannot make buckets public.`,

  ai_assist: [
    `"Write an IAM policy (JSON) for a Node.js application that needs: read access to a specific S3 bucket (s3:GetObject, s3:ListBucket), publish to a specific SQS queue (sqs:SendMessage, sqs:GetQueueAttributes), and write CloudWatch metrics (cloudwatch:PutMetricData). Use specific resource ARNs, not wildcards. Add a condition that requires the requests to come from a specific VPC endpoint."`,
    `"Write a Terraform configuration for S3 bucket security: block all public access, enable default encryption (SSE-S3), enable versioning, add a bucket policy that denies non-HTTPS access and denies access to any principal except specific IAM roles, enable server access logging to a separate log bucket."`,
    `"Write an AWS Config rule (using the Terraform aws_config_config_rule resource) that alerts when any security group allows inbound traffic from 0.0.0.0/0 on ports 22 (SSH) or 3389 (RDP). Include an EventBridge rule that sends an SNS notification when the Config rule marks a resource as non-compliant."`,
  ],

  stretch: [
    `Run a full Prowler compliance scan against the CIS AWS Foundations Benchmark. Export the results as a CSV. Prioritise all CRITICAL and HIGH findings. Fix the top 10 by risk and document the remediation. Run Prowler again to verify the fixes. This is a cloud security assessment you can add to your portfolio.`,
    `Implement Infrastructure Security Scanning in your Terraform CI pipeline using Checkov (by Bridgecrew). Checkov scans Terraform plans and code for security misconfigurations (public S3 buckets, open security groups, unencrypted databases). Add it as a CI step that fails the pipeline on HIGH or CRITICAL findings.`,
    `Set up AWS Security Hub with automated remediation. When Security Hub finds a specific finding type (e.g., S3 bucket with public read), an EventBridge rule triggers a Lambda function that automatically remediates it (enable Block Public Access). This is security-as-code: compliance is enforced automatically, not manually.`,
  ],
});

rewriteWeek("devops-cloud", 24, {
  context: `This is the capstone week. The DevOps/Cloud track ends where most engineers are trying to get to: owning and operating real infrastructure that serves real users. Edge Portfolio has evolved from a manually managed server (W1) to a production-grade Kubernetes deployment with GitOps, observability, security scanning, and disaster recovery. This week you bring all the pieces together and document the architecture.

The capstone deliverable is not just a running system — it is a documented, reproducible, auditable infrastructure. Another engineer (your future self, a new team member, or a potential employer reviewing your portfolio) should be able to understand the architecture, reproduce it from scratch using your Terraform code, and operate it using your runbooks.

Architecture documentation: write an Architecture Decision Record (ADR) for each significant technical choice you made. Why Kubernetes over a simpler deployment? Why Terraform over manual setup? Why Flux over Argo CD? ADRs capture the reasoning behind decisions so future engineers understand why things are the way they are, not just how they work.

The infrastructure is code: every resource is in Terraform, every Kubernetes deployment is in the gitops repository, every secret is in the secrets manager, every alert has a runbook. Nothing exists that is not documented. Nothing is configured manually in the cloud console.

Operational readiness: before calling a system "production-ready," define and verify: the system can survive a single node failure without downtime (tested), the system can be restored from backup within the RTO (tested), alerts fire when the system is degraded (tested by injecting failures), the on-call runbook is complete and tested, the cost is within budget and monitored, and the security posture has been assessed (Prowler scan, findings addressed).`,

  pre_flight: `Review all the infrastructure you have built across W1-W23. List every component and verify it is defined in code (Terraform or Kubernetes manifests in git). Identify any manual configuration that exists only in the cloud console — bring it into code this week. Schedule the final operational readiness review: go through each operational readiness criterion and verify.`,

  mastery_questions: [
    `A new engineer joins the team and needs to understand your entire infrastructure. What documentation do you provide, and how do they reproduce it from scratch? Documentation: a README explaining the overall architecture with a diagram, the technology decisions and why (ADRs), the list of required tools and versions, the bootstrapping procedure (how to create a new environment from scratch). Reproduction: terraform init && terraform apply (creates all cloud resources). flux bootstrap (installs GitOps). helm upgrade --install (installs monitoring stack). The engineer should be able to stand up a complete replica of the infrastructure by following the runbook. If they cannot, the documentation is incomplete.`,
    `Looking back at 24 weeks, identify the three decisions that most affected your security posture, the three that most affected your operational efficiency, and the three that most affected your cost. Security: (1) Using IRSA instead of access keys — no long-lived credentials to steal. (2) Running containers as non-root — reduced blast radius of container escapes. (3) Enabling CloudTrail and GuardDuty — detect compromises quickly. Operational efficiency: (1) Kubernetes + HPA — automated scaling removes manual intervention. (2) GitOps with Flux — deployments are automatic and auditable. (3) kube-prometheus-stack — monitoring deployed in one command. Cost: (1) Right-sizing instances to actual usage. (2) Scheduling dev environments to stop on weekends. (3) Using Spot instances for CI runners and non-critical workloads.`,
    `Your Edge Portfolio is on Kubernetes, uses Terraform, has CI/CD, monitoring, and security scanning. A recruiter asks "what DevOps experience do you have?" How do you describe this project concisely? "I built and operate a production Kubernetes infrastructure for a portfolio website. The infrastructure is defined in Terraform (AWS EKS, VPC, IAM) and deployed via GitOps with Flux. CI/CD runs on GitHub Actions with OIDC authentication to AWS — no long-lived credentials. Deployments use Argo Rollouts for canary releases with automated Prometheus-based rollback. The observability stack is the Grafana LGTM stack (Loki, Grafana, Tempo, Mimir) deployed via Helm. Secrets are in AWS Secrets Manager, synced to Kubernetes via External Secrets Operator. I run monthly disaster recovery exercises and Prowler security scans. Costs are monitored with Kubecost and AWS Cost Anomaly Detection." Specific. Technical. Verifiable.`,
    `What are the three things you would add to this infrastructure next, in priority order? Priority 1: service mesh (Istio or Linkerd) for mTLS between services — currently all intra-cluster traffic is unencrypted. Priority 2: Velero backup with tested restore procedure — backup exists but the restore has not been tested under time pressure. Priority 3: multi-region active-passive — current infrastructure is single-region; an AWS us-east-1 outage would cause complete downtime. These priorities are based on: mTLS is a security gap (P1), untested backups are a reliability gap (P2), and single-region is a resilience gap (P3).`,
  ],

  common_mistakes: [
    `Declaring the infrastructure "done" without operational readiness testing. An infrastructure that has never been tested under failure conditions is infrastructure you do not trust. Run the chaos tests, the DR exercises, the load tests. Find the failures in a controlled environment.`,
    `Not documenting the manual steps. Every infrastructure has some manual setup (bootstrapping, secret seeding, one-time configuration). Document these explicitly in the runbook. A future engineer who cannot find these steps will spend hours debugging.`,
    `Keeping the infrastructure as a learning environment instead of treating it as production. If you built it to learn, make it real: point a real domain at it, publish it, tell people about it. The constraints of real users teach more than any tutorial.`,
    `Not adding the infrastructure to your portfolio. A portfolio project that is not visible is invisible to employers. Write a blog post about what you built and the decisions you made. Link to your public GitHub repository (gitops repo, Terraform code). Share the Grafana dashboard (public access enabled). This is the difference between "I know Kubernetes" and "here is my Kubernetes cluster — you can inspect it."`,
    `Not planning for what comes next. Infrastructure maintenance is ongoing. Define your maintenance schedule: monthly Kubernetes version review (update if a new patch is available), quarterly DR exercise (restore from backup and verify), monthly cost review (check for savings opportunities), weekly security findings review (Prowler, GuardDuty). Without a schedule, maintenance does not happen.`,
  ],

  debug_help: `Terraform apply fails because of circular dependency: use terraform graph | dot -Tsvg > graph.svg to visualise the resource dependency graph. Find the cycle and break it by using the depends_on meta-argument explicitly or refactoring the resources. Flux sync is failing for an unknown reason: run flux logs --all-namespaces to see logs from all Flux controllers. A common cause is a large GitRepository checkout timing out — increase the timeout in the GitRepository spec. Final operational readiness check fails: work through each criterion methodically. A failure is information — it tells you what to fix before calling the system production-ready. Do not lower the bar; fix the system.`,

  ai_assist: [
    `"Write an Architecture Decision Record (ADR) for choosing Kubernetes over Docker Compose for the Edge Portfolio deployment. Include: context (what problem are we solving), decision (we chose Kubernetes), status (accepted), consequences (pros: auto-scaling, self-healing, GitOps integration; cons: operational complexity, learning curve, cost for small projects), and alternatives considered (Docker Compose on a single server, managed container service like App Platform)."`,
    `"Write a production readiness checklist for the Edge Portfolio infrastructure. Organise it into sections: reliability (HA, backups, DR), security (IAM, network, scanning), observability (metrics, logs, traces, alerting), deployment safety (CI/CD, rollback procedure), cost (monitoring, optimisation), and documentation (runbooks, ADRs, architecture diagram). For each item, include the verification method."`,
    `"Write a 'Day 2 Operations' guide for the Edge Portfolio Kubernetes cluster. Cover: routine tasks (monthly certificate renewal check, Kubernetes version upgrades, Helm chart updates, Terraform drift detection), incident response (how to page, how to find relevant dashboards, how to escalate), and quarterly tasks (DR exercise, cost review, security audit)."`,
  ],

  stretch: [
    `Write a comprehensive post-mortem for an incident you intentionally created (inject a failure using chaos-mesh). Follow the blameless post-mortem format: what happened, timeline, root cause analysis (5 Whys), impact (users affected, duration), what went well (alerts fired within 2 minutes), what went poorly (no runbook for this specific failure), and action items. Publish the post-mortem publicly — transparency is an engineering virtue.`,
    `Contribute to the infrastructure community. Open source your Terraform modules (the VPC configuration, the EKS setup, the monitoring stack) on GitHub. Write a blog post on how to set up GitOps on EKS from scratch. Submit it to the HashiCorp or CNCF blog, or post on the r/devops subreddit. Teaching is the highest form of learning — articulating what you built forces a level of clarity that simply building does not.`,
    `Apply for the Certified Kubernetes Administrator (CKA) exam. The CKA is a practical, hands-on exam where you operate Kubernetes clusters under time pressure. The skills you have built over these 24 weeks — pods, deployments, services, RBAC, networking, storage, troubleshooting — are the exact skills tested. Schedule the exam within 30 days of completing this track while the knowledge is fresh.`,
  ],
});
