import { rewriteWeek } from "../rewrite-week";

// mobile-engineering W6-W10

rewriteWeek("mobile-engineering", 6, {
  context: `Animations and gestures are what separate apps that feel native from apps that feel like a website wrapped in a shell. On the web, animation is an enhancement. On mobile, it is part of the interaction model — the swipe to dismiss, the spring when you release a dragged element, the haptic tap on confirmation. Users feel the quality of your animations even when they cannot articulate it.

React Native Animated API is the built-in animation system. It works by driving native values that never cross the JavaScript bridge during animation — the animation runs on the UI thread. The key: Animated.Value is a mutable container, not a regular number. You connect it to component styles via Animated.View. You drive it with Animated.timing (linear/easing-based), Animated.spring (physics-based, bouncy), or Animated.decay (drag-and-release friction). Always use useNativeDriver: true when animating opacity and transform properties — it moves the animation to the GPU and keeps it smooth even when JavaScript is busy.

react-native-reanimated 2+ is the modern animation library. It moves animation logic to a worklet — a tiny JavaScript function that runs on the UI thread, not the main JavaScript thread. This means animations stay smooth even during heavy JavaScript work (network requests, complex state updates). The Shared Value (useSharedValue) is reanimated's equivalent of Animated.Value. useAnimatedStyle derives animated styles from shared values. runOnJS allows you to call a JavaScript function from a worklet when needed.

react-native-gesture-handler replaces React Native's default gesture system with a more powerful one that runs on the native thread. GestureDetector with Gesture.Pan(), Gesture.Tap(), Gesture.Pinch() gives you multi-gesture support and proper gesture priority. Combined with reanimated, this is the stack used in the most polished apps.

This week you add three animations to Hydra: a spring animation when a habit is checked off (the checkmark bounces in), a swipe-to-delete gesture on habit rows, and a smooth tab transition.`,

  pre_flight: `Install react-native-reanimated: npx expo install react-native-reanimated. Add the reanimated babel plugin to babel.config.js (required — see the docs). Install react-native-gesture-handler: npx expo install react-native-gesture-handler. Wrap your root App component in GestureHandlerRootView. Read the reanimated "Getting Started" guide. Run npx expo start and verify the app still works before adding animations.`,

  mastery_questions: [
    `What is the difference between useNativeDriver: true and false in React Native Animated, and why does it matter? useNativeDriver: true tells the Animated system to serialise the animation configuration and send it to the native thread once. The animation then runs entirely on the native thread without any communication back to JavaScript until it completes. This means even if the JavaScript thread is busy (loading data, running a reducer), the animation plays at 60fps. useNativeDriver: false runs the animation on the JavaScript thread — on every animation frame, JavaScript computes the new value and updates the component. Any JavaScript work pauses the animation. The constraint: useNativeDriver only works for opacity and transform. Width, height, and colour cannot use the native driver.`,
    `You want to animate a card that the user can drag horizontally. When released, it should spring back to centre if not dragged far enough, or fly off the screen if dragged past a threshold. How do you implement this with reanimated? Use useSharedValue for the x offset. Use Gesture.Pan() to track the drag — update the shared value in the onUpdate callback (runs on UI thread). In onEnd, check the velocity and position: if Math.abs(offset.value) > THRESHOLD || Math.abs(velocityX) > 500, animate off screen with withSpring or withTiming; otherwise spring back to 0 with withSpring(0). Use useAnimatedStyle to apply the transform. The key is that all of this runs on the UI thread — the gesture, the threshold check, the animation decision.`,
    `You add a Gesture.Tap to a button that is inside a Gesture.Pan scrollable area. The tap works, but the pan gesture also fires when the user taps. How do you fix this? Gesture priority. Use Gesture.Simultaneous or Gesture.Exclusive to define how gestures relate. In this case, you want the tap to win when it is a tap: Gesture.Exclusive(tapGesture, panGesture) — the exclusive combinator tries the first gesture; if it activates, the second is cancelled. Alternatively, set a minimum distance on the pan: Gesture.Pan().minDistance(10) — the pan only activates after the finger moves 10 points, giving the tap time to fire first.`,
    `What is a worklet in react-native-reanimated and how do you write one? A worklet is a JavaScript function that is transpiled by the reanimated babel plugin to run on the UI thread instead of the JavaScript thread. You mark a function as a worklet with the 'worklet' directive at the top of the function body: function myCalculation(x) { 'worklet'; return x * 2; }. Any function used inside useAnimatedStyle, useAnimatedScrollHandler, or gesture callbacks runs as a worklet automatically if it is inlined. The constraint: worklets cannot call most JavaScript APIs (setTimeout, fetch, console.log) — they only have access to a minimal runtime. Use runOnJS(myJSFunction)(arg) to call back to JavaScript from a worklet.`,
  ],

  common_mistakes: [
    `Forgetting the reanimated babel plugin. Without the plugin, reanimated's worklets do not get transpiled and you get cryptic runtime errors. The plugin must be the last item in the plugins array in babel.config.js. After adding it, clear the metro cache: npx expo start --clear.`,
    `Using useState to drive animations. React state updates go through the JavaScript thread and re-render cycle — they are not fast enough for per-frame animation. Use useSharedValue (reanimated) or Animated.Value (built-in) for values that change every animation frame.`,
    `Calling runOnJS inside a tight animation loop. runOnJS schedules a call on the JavaScript thread for the next frame. If your worklet calls runOnJS every frame, you are flooding the JavaScript thread with callbacks. Only call runOnJS for one-time events (gesture end, animation complete).`,
    `Not wrapping the root in GestureHandlerRootView. Without this wrapper, react-native-gesture-handler gestures will not work. The error is usually a vague touch-related crash. Wrap your root App component: return <GestureHandlerRootView style={{ flex: 1 }}><App /></GestureHandlerRootView>.`,
    `Over-animating. Animations that run constantly, transitions on every tiny state change, animations with no clear relationship to user action — these exhaust users. Animate in response to user actions. Keep durations short (150-300ms for most transitions). Respect the reduce motion accessibility setting.`,
  ],

  debug_help: `"ReanimatedError: Tried to synchronously call a non-worklet function on the UI thread": you are calling a regular JavaScript function from a worklet. Either mark the function as a worklet or wrap the call in runOnJS. Metro bundler cache issue after adding babel plugin: run npx expo start --clear to clear the cache. Gesture not recognised on Android: check that GestureHandlerRootView wraps the root and that you are not using old-style PanResponder alongside react-native-gesture-handler — they conflict. Animation is choppy: check whether useNativeDriver is enabled for the Animated API. For reanimated, check that you are not calling runOnJS on every frame. Spring animation never settles: set damping higher on withSpring (damping: 20, stiffness: 180) or use withTiming instead of withSpring for precise destination values.`,

  ai_assist: [
    `"Write a swipe-to-delete habit row using react-native-reanimated and react-native-gesture-handler. The user swipes left to reveal a red delete button. If released past a threshold, the row animates off screen and calls onDelete(id). If released short, it springs back. Include the animated styles and gesture handler."`,
    `"Write a bouncing checkmark animation for Hydra using react-native-reanimated. When isCompleted changes to true, the checkmark scales from 0 to 1.2 then back to 1 with a spring. When it changes back to false, it fades out. Use useAnimatedStyle and withSpring."`,
    `"How do I make my animations respect the user's Reduce Motion accessibility setting in React Native? Show how to detect the setting with AccessibilityInfo and conditionally skip or simplify animations."`,
  ],

  stretch: [
    `Add a shared element transition when navigating from HabitList to HabitDetail. The habit name text scales and moves to its position in the detail screen. This requires react-native-reanimated's shared element transition API (available in Expo Router or with react-navigation-shared-element).`,
    `Implement a drag-to-reorder habit list. Use react-native-draggable-flatlist — it wraps FlatList with drag handles. On reorder, update the order field in SQLite. This is a significantly complex gesture interaction that is worth the effort to implement correctly.`,
    `Add a confetti animation when the user completes all habits for the day. Use react-native-confetti-cannon or implement it yourself with Animated particles. Trigger it once per day on the completion of the last habit.`,
  ],
});

rewriteWeek("mobile-engineering", 7, {
  context: `Design systems on mobile are about consistency and speed. Every screen should feel like it belongs to the same app — same spacing scale, same colour palette, same typography, same component behaviour. A design system is not just a style guide document; it is code: a set of base components that enforce the system and make it impossible to accidentally use a spacing value that is not on the scale.

Dark mode on iOS and Android is user-controlled at the OS level. Users expect your app to respect their preference. React Native's useColorScheme hook returns 'light' or 'dark' based on the OS setting. A good dark mode is not just inverting colours — dark backgrounds should be very dark grey (#121212 or #1C1C1E) not pure black (#000000), and text should be slightly off-white (#E1E1E1) not pure white (#FFFFFF). Pure black on pure white feels harsh.

Theming architecture: define your design tokens as a TypeScript object — colours, spacing, typography, border radii. Create a light theme and a dark theme. Expose the current theme via a React context (ThemeContext) so any component can access it. Many teams use a custom hook: const { colors, spacing } = useTheme(). The alternative is a theming library — react-native-paper or NativeWind (Tailwind for React Native).

Typography: mobile apps should have a small, coherent set of text styles. Define them explicitly: header (24px, bold), title (18px, semibold), body (14px, regular), caption (12px, regular). Apply them via a Text component that accepts a variant prop. The OS handles the base font — San Francisco on iOS, Roboto on Android. If you need a custom font, use expo-font. Keep it to two weights maximum — loading many font files increases startup time.

Spacing scale: use multiples of 4 or 8 as your spacing unit. spacing.xs = 4, spacing.sm = 8, spacing.md = 16, spacing.lg = 24, spacing.xl = 32. Never use arbitrary values like padding: 13 — it breaks the visual rhythm. Standardising spacing is the single highest-impact thing you can do for visual consistency without a designer.`,

  pre_flight: `Install NativeWind: npx expo install nativewind tailwindcss. OR keep using StyleSheet and build a manual theme system. Read the design token documentation at Figma's design systems blog. Know how React Context works: createContext, Provider, useContext. Understand the useColorScheme hook. Have your colour palette chosen — use Coolors (coolors.co) to generate a harmonious palette with both light and dark variants.`,

  mastery_questions: [
    `A user's device is in dark mode. Your app does not respond to it — it always shows the light theme. What is wrong? You are not reading the color scheme. useColorScheme() from react-native returns 'light', 'dark', or null. You must use this value to select the appropriate theme. If you hardcode colours (backgroundColor: '#FFFFFF') instead of referencing theme tokens (backgroundColor: colors.background), dark mode has no effect. The fix: create a ThemeProvider that calls useColorScheme, selects the theme object (lightTheme or darkTheme), and provides it via context. All colour values in your components come from the theme, not hardcoded.`,
    `Your app has three different places that display product names: a list row (14px regular), a detail page header (22px bold), and a search result (13px regular). How do you standardise this? Define text variants in your design system: const textStyles = { body: { fontSize: 14, fontWeight: '400' }, title: { fontSize: 22, fontWeight: '700' }, caption: { fontSize: 13, fontWeight: '400' } }. Create a Text component that accepts a variant prop: <Text variant="title">. The component looks up the style from textStyles[variant] and applies it. This means a design change to "title" size propagates everywhere automatically.`,
    `You have a component that uses colors.primary for a button background. The colour is #6B46C1. On a white background it has a contrast ratio of 5.9:1 (accessible). On your dark theme, the background is #1C1C1E. The purple button on dark background has a contrast ratio of 3.1:1 (not accessible). How do you fix it? Define separate values in the light and dark themes: lightTheme.colors.primary = '#6B46C1', darkTheme.colors.primary = '#9B79E4' (a lighter purple that achieves 4.5:1 on #1C1C1E). The button component uses colors.primary from the theme — it automatically uses the right colour for each mode. Never hardcode a colour value assuming one background.`,
    `What is the performance tradeoff of using React Context for theming versus passing the theme as props? Context: the ThemeProvider holds the theme object in a React context. Any component that calls useTheme() re-renders when the theme changes (dark/light switch). This is fine because theme changes are rare (user switches the OS setting). The issue is unnecessary re-renders if the context holds other frequently-changing data. Solution: split your context — a ThemeContext for the colour tokens (changes rarely), separate contexts for other data. Props: prop-drilling the theme to every component is impractical for a deep component tree. Context is the right solution for global concerns like theming.`,
  ],

  common_mistakes: [
    `Hardcoding colours throughout the codebase. color: '#333333' appears in 30 different files. When the design changes or you add dark mode, you find them one by one. Every colour should reference a token: colors.textPrimary, colors.background, colors.accent.`,
    `Using arbitrary spacing values. padding: 13, marginBottom: 7. These do not fit any scale and make the UI look inconsistent. Enforce the spacing scale: xs=4, sm=8, md=16, lg=24, xl=32, xxl=48. If a value is not on the scale, question whether it is really needed.`,
    `Creating a "dark mode" by setting dark backgrounds only on containers but leaving text and icons hardcoded in dark colours. Dark mode is not just background changes — text, icons, borders, shadows, and interactive states all need dark variants.`,
    `Using font weight values that the font does not support. Not every font has all weights. React Native on iOS maps weight strings to specific font variants. If the font does not have 'semibold', it falls back to 'regular'. Check which weights your font family supports.`,
    `Not loading custom fonts before rendering. If you use a custom font and it has not loaded yet, text flashes in the system font first, then switches. Use expo-font's useFonts hook and show a SplashScreen until fonts are loaded.`,
  ],

  debug_help: `Colors look wrong in dark mode: verify that useColorScheme() is returning 'dark'. Some simulators require you to manually change the appearance: in iOS Simulator, go to Features > Toggle Appearance. Check that your ThemeProvider is wrapping the entire app in App.tsx. Custom font not applying: check that the font is loaded before the component tries to use it. Use expo-font useFonts and SplashScreen.preventAutoHideAsync() to hold the splash screen until fonts are ready. Text not following the spacing scale: add an ESLint rule (or a code review checklist) to flag hardcoded spacing values. StyleSheet values for spacing should always reference the spacing object. NativeWind class not applying: check that the tailwind.config.js content array includes your React Native file paths. Restart Metro with --clear after Tailwind config changes.`,

  ai_assist: [
    `"Create a design system for a React Native app with: a light and dark theme object (colors, spacing, typography, borderRadius), a ThemeProvider using React Context and useColorScheme, a useTheme hook, and a Text component that accepts a variant prop ('h1', 'h2', 'body', 'caption') and applies the correct typography style from the theme."`,
    `"Write a reusable Card component for React Native that uses the design system. It should have padding from the spacing scale, rounded corners from the borderRadius scale, a background from colors.surface, and an optional elevation/shadow. Show how it looks in both light and dark theme."`,
    `"Generate a colour palette for a habit tracking app with light and dark variants. For each semantic colour (background, surface, primary, secondary, text, textSecondary, border, error, success), provide the light and dark hex values. Verify each combination meets WCAG AA contrast ratio."`,
  ],

  stretch: [
    `Add a theme picker in Settings that lets the user choose light, dark, or system default. Store the preference in AsyncStorage. Override useColorScheme when the user has set an explicit preference. This is a common feature that requires coordinating context with persistent storage.`,
    `Build an Icon component backed by @expo/vector-icons that maps semantic icon names ('check', 'trash', 'settings', 'add') to vector icons and automatically uses the correct colour from the theme. This insulates your codebase from the specific icon library.`,
    `Implement dynamic type support. On iOS, the user can set the preferred text size in Settings > Display & Brightness > Text Size. Use useWindowDimensions and PixelRatio to scale your font sizes proportionally. Test that your layout does not break at the largest text size.`,
  ],
});

rewriteWeek("mobile-engineering", 8, {
  context: `Data that does not persist across app restarts is data the user has to re-enter. Local storage is how mobile apps remember state. There are three levels of local storage, each with different characteristics, and choosing the wrong one for your use case causes performance problems or data loss.

AsyncStorage is a simple key-value store backed by the device's file system. It is asynchronous (reads and writes are non-blocking I/O operations). It stores strings — you JSON.stringify objects before storing and JSON.parse after reading. It has no schema, no queries, and no transactions. Appropriate for: small amounts of configuration data (user preferences, theme setting, reminder time), simple flags (has the user seen the onboarding?). Not appropriate for: large datasets, structured data you want to query, data that updates frequently.

MMKV is a key-value store that works via memory-mapped files — reads are synchronous (no await required) and extremely fast (microseconds vs milliseconds). It uses the same API pattern as AsyncStorage but synchronously. Install via expo-community-flipper or react-native-mmkv. Appropriate for: same use cases as AsyncStorage, but where synchronous access is important (accessing values inside gesture handlers or worklets) or where you have many small reads.

SQLite is a relational database embedded in your app. It supports SQL queries, indexes, transactions, foreign keys, and can handle millions of rows efficiently. Reads and writes are asynchronous. Covered in W3. Appropriate for: structured data you need to query (habit history, order history, cached API responses).

Secure storage: AsyncStorage and MMKV store data in plaintext on the device. For sensitive data (auth tokens, API keys, biometric-protected secrets), use expo-secure-store, which uses iOS Keychain and Android Keystore — OS-level secure enclaves. Always store user credentials and tokens in secure storage.

This week you audit Hydra's storage: move all simple settings to MMKV (synchronous, fast), keep the completion history in SQLite, and move the auth token (if you add authentication) to expo-secure-store.`,

  pre_flight: `Install react-native-mmkv: npx expo install react-native-mmkv. Install expo-secure-store: npx expo install expo-secure-store. Read the react-native-mmkv documentation — note that it requires a development build (not Expo Go) because it contains native code. Build a development build: npx expo run:ios or npx expo run:android. Understand why MMKV requires a dev build: Expo Go only supports libraries that use Expo's managed APIs. Native libraries (non-Expo SDKs) require compiling the native code into your app.`,

  mastery_questions: [
    `You are storing a user auth token after login. It should persist across app restarts but should not be readable by other apps or accessible if the device is rooted. Which storage layer do you use and why? expo-secure-store. On iOS, it stores values in the Keychain — an OS-managed secure enclave that is inaccessible to other apps and survives app reinstalls (unless you delete it). On Android, it uses the Keystore system with encryption at rest. AsyncStorage and MMKV store data in plaintext in the app's sandbox — accessible to anyone who can read the device's storage (rooted devices, adb backup). Tokens are credentials — they get the most secure storage available.`,
    `You have a preference value (the user's chosen reminder hour) that you read synchronously inside an animation worklet. Which storage layer can you use? MMKV. It provides synchronous read access: const hour = storage.getNumber('reminderHour'). AsyncStorage and SQLite are asynchronous — you cannot await inside a reanimated worklet. MMKV's synchronous API works because it uses memory-mapped files — the data is mapped into process memory and reading it is a memory read, not a file I/O operation.`,
    `You want to cache API responses in local storage so the app works offline. The cache should expire after 24 hours. Which storage layer do you use and how do you implement expiry? For simple key-value caching of JSON responses: MMKV. Store the response as { data: responseData, expiry: Date.now() + 24 * 60 * 60 * 1000 }. On read, check if Date.now() > cachedValue.expiry and return null if expired. For complex caching with multiple related records and queries (e.g., cache a user's orders so the orders list shows instantly while the network request completes): SQLite with a cachedAt column and a WHERE cachedAt > NOW() - 24*60*60 filter.`,
    `AsyncStorage has a maximum value size limit. What is it and what happens when you exceed it? AsyncStorage has no strict size limit, but storing large values (multi-megabyte JSON blobs) causes significant read/write latency because it is serialised to disk as a single atomic operation. Reading a 10MB JSON blob on every app startup adds noticeable startup time. The pattern to avoid: storing an ever-growing array in one AsyncStorage key. Instead, store arrays in SQLite (each element is a row) and query only what you need. AsyncStorage for config; SQLite for datasets.`,
  ],

  common_mistakes: [
    `Awaiting AsyncStorage in the component render function. Async operations cannot run during synchronous render. Use useEffect to load from storage and useState to hold the value: const [value, setValue] = useState(null); useEffect(() => { AsyncStorage.getItem('key').then(setValue); }, []).`,
    `Not handling storage errors. Storage operations can fail (device storage full, corrupted database). Wrap storage calls in try/catch and have a fallback: if reading fails, use the default value. Log the error to Sentry.`,
    `Storing large objects in AsyncStorage without considering size. Storing a 5MB JSON object in AsyncStorage means reading 5MB from disk on every access. Break large data into smaller, independently readable pieces or use SQLite.`,
    `Using expo-secure-store for large data. Secure store is designed for small values (tokens, PINs, short strings). The Keychain on iOS has practical size limits and is not designed for bulk storage. Store large sensitive data encrypted in SQLite and store the encryption key in secure store.`,
    `Not migrating existing data when changing storage layers. If you move a preference from AsyncStorage to MMKV in an app update, existing users still have the data in AsyncStorage. Write a migration that runs once on the first launch of the new version: read from AsyncStorage, write to MMKV, delete from AsyncStorage.`,
  ],

  debug_help: `MMKV crashes on Expo Go: MMKV requires a development build, not Expo Go. Run npx expo run:ios or npx expo run:android to create a dev build. expo-secure-store returns null for an existing key: on iOS, the Keychain is partitioned by app — if you reinstalled the app without clearing the Keychain, the old value may be there under a different app identifier. Also check that you are using the same key string for get and set. SQLite database is not persisting: verify that you are passing the same database name to SQLite.openDatabaseAsync every time. A different name creates a different database file. AsyncStorage cannot find the module: ensure you installed @react-native-async-storage/async-storage, not the deprecated 'AsyncStorage' from react-native directly (it was removed in RN 0.60).`,

  ai_assist: [
    `"Write a storage service for Hydra that abstracts MMKV and AsyncStorage. The service has: getReminderHour(): number | null (synchronous, MMKV), setReminderHour(hour: number): void (synchronous, MMKV), getAuthToken(): Promise<string | null> (async, SecureStore), setAuthToken(token: string): Promise<void> (async, SecureStore). Include TypeScript types."`,
    `"Write a cache utility using MMKV that stores API responses with an expiry. Functions: setCache<T>(key: string, data: T, ttlMs: number): void and getCache<T>(key: string): T | null (returns null if expired or not found). Use JSON serialisation and store the expiry timestamp alongside the data."`,
    `"Write the storage migration function for Hydra. It reads the reminder hour from AsyncStorage (the old location), writes it to MMKV (the new location), and deletes the old AsyncStorage key. It should run once and mark itself as complete in MMKV so it does not run again."`,
  ],

  stretch: [
    `Implement a full SQLite migration system. Store the current schema version in MMKV. On startup, compare to the target version. Run pending migrations in order (v1: create tables, v2: add color column to habits). Never drop columns or tables in a migration — always add and migrate. This is production-grade database evolution.`,
    `Add data export functionality to Hydra's Settings screen. The user taps "Export Data" and gets a JSON file containing all their habits and completion history, which they can share via the iOS share sheet or save to Files. Use expo-sharing and expo-file-system.`,
    `Benchmark the three storage layers: measure read/write time for AsyncStorage, MMKV, and SQLite for 1, 100, and 1000 key-value pairs. Write the benchmark as a Hydra developer screen. The results will inform your storage decisions for future features.`,
  ],
});

rewriteWeek("mobile-engineering", 9, {
  context: `The camera is the most personal sensor on a mobile device. Camera and media capture features are what make mobile apps feel like mobile apps — not just web pages in a container. Permissions, preview, capture, processing: these are the four phases of every camera interaction.

expo-camera provides a camera preview component that shows the live camera feed. expo-image-picker provides the simpler flow: the OS camera app opens, the user takes the photo, the result (a URI) is returned to your app. Use expo-image-picker when you want the standard OS camera experience. Use expo-camera when you need a custom camera UI (overlays, real-time filters, barcode scanning in your own UI).

Permissions: camera access requires explicit user permission on both iOS and Android. Request with Camera.requestCameraPermissionsAsync(). On iOS, the permission dialog text is set in your app.json (ios.infoPlist.NSCameraUsageDescription). If denied, you must direct the user to Settings. The UX pattern is the same as notifications: explain why before requesting.

Media library access: after capturing, you may want to save to the user's photo library. This requires a separate permission: MediaLibrary.requestPermissionsAsync(). On iOS 14+, the user can grant access to specific photos, not the entire library — your picker gets a selection from what the user allows.

Image processing: captured images are full-resolution (12MP on modern phones — multi-megabyte files). You almost never want to upload a full-resolution image to your server. Process before upload: resize using expo-image-manipulator, compress to reduce file size, convert to JPEG or WebP. A 300KB processed image is fine for most use cases; a 8MB original is not.

The barcode scanner use case: expo-camera has a built-in barcode scanner. Set onBarcodeScanned prop and the camera fires a callback with the barcode data when it detects one. This enables QR code scanning, product barcode scanning, and any scan-to-action flow — with no external library.`,

  pre_flight: `Install expo-camera: npx expo install expo-camera. Install expo-image-picker: npx expo install expo-image-picker. Install expo-image-manipulator: npx expo install expo-image-manipulator. Install expo-media-library: npx expo install expo-media-library. Add the required permissions to app.json: camera permission description (iOS) and media library permission. Read the expo-camera and expo-image-picker API reference. Test on a real device — cameras do not work on simulators (you get a static image or no preview).`,

  mastery_questions: [
    `What is the difference between expo-camera and expo-image-picker, and when do you use each? expo-image-picker opens the OS native picker — either the camera app (launchCameraAsync) or the photo library (launchImageLibraryAsync). The OS handles the UI entirely. The result is a URI to the selected/captured image. Use it when you want the standard platform camera experience: simple, reliable, no custom UI. expo-camera renders a CameraView component inside your own UI. You control the frame, overlays, buttons, and capture logic. Use it when you need a custom camera experience: a barcode scanner with an overlay, a photo booth with a timer, a document scanner with edge detection.`,
    `A user taps "Change Avatar". How do you give them the option to take a new photo or choose from the library? Show an ActionSheet (from @expo/react-native-action-sheet or a custom modal) with three options: "Take Photo", "Choose from Library", "Cancel". For "Take Photo": call ImagePicker.launchCameraAsync with the desired options. For "Choose from Library": call ImagePicker.launchImageLibraryAsync. Both return a result with { canceled: boolean, assets: [{ uri, width, height }] }. If not canceled, the asset.uri is a local file path you can display and process.`,
    `The user takes a photo. The file is 7MB (full resolution JPEG). You need to upload it to Cloudflare R2 as their avatar, displayed at 200x200 on screen. What processing do you do before upload? Resize and compress using expo-image-manipulator: ImageManipulator.manipulateAsync(uri, [{ resize: { width: 800 } }], { compress: 0.7, format: SaveFormat.JPEG }). Resize to 800px wide (larger than the display size, smaller than full resolution — preserves quality for Retina displays). Compress to 70% JPEG quality (hard to notice, halves file size). The result is typically 100-300KB. Upload that. The original 7MB file stays in the user's camera roll if saved.`,
    `You are building a barcode scanner. The camera fires onBarcodeScanned many times per second as it detects the barcode. How do you prevent multiple callbacks for the same scan? Add a scanned state flag: const [scanned, setScanned] = useState(false). In the onBarcodeScanned callback: if (scanned) return; setScanned(true); processBarcode(data). After processing (showing a result, navigating), reset: setScanned(false) to allow the next scan. This debounce prevents 20 identical callbacks from processing the same barcode.`,
  ],

  common_mistakes: [
    `Not checking the canceled field in the ImagePicker result. If the user taps Cancel in the picker, the result has canceled: true and no assets. Accessing result.assets[0].uri without checking canceled throws a runtime error.`,
    `Uploading full-resolution images. Full-resolution camera images are 5-15MB. Resize and compress before upload. Users on cellular connections pay for every byte.`,
    `Requesting camera permissions at app launch without context. Request permissions at the moment the user attempts to use the camera, with a clear explanation of why. If you request on launch, users often deny before they understand the feature.`,
    `Displaying the full-resolution image in a small Image component. Even if the image displays at 100x100, React Native loads the full 7MB into memory. Use a resized URI for display (use expo-image-manipulator to generate a thumbnail) or use the FastImage library with resize mode.`,
    `Not handling the case where camera permission is permanently denied. On iOS, once denied, you cannot request again. Show a message explaining that camera access is required, with a button that calls Linking.openSettings() to open the app settings where the user can grant permission manually.`,
  ],

  debug_help: `Camera shows a black preview: this is almost always a permissions issue. The permission was granted but the CameraView is not receiving it. Check that you are awaiting the permission request and only rendering CameraView after permission is granted. On iOS Simulator, the camera shows a static image (not a live feed). "Invalid image" error when processing: the URI from ImagePicker is a file:// URI that expo-image-manipulator can read. On Android, the URI may be a content:// URI — expo-image-manipulator handles both, but some libraries do not. If you are processing with a different library, convert the content:// URI to a file:// URI first using expo-file-system. Image picker shows no images on Android: check that the READ_EXTERNAL_STORAGE permission is granted (managed by expo-image-picker automatically in the new permissions model, but older Android versions may need it explicitly).`,

  ai_assist: [
    `"Write an avatar upload flow in React Native using expo-image-picker. Show an ActionSheet with 'Take Photo', 'Choose from Library', 'Cancel'. After selection, use expo-image-manipulator to resize to 800px wide and compress to 70% JPEG. Display the processed image in a circular preview. Include permission handling with expo-camera."`,
    `"Write a QR code scanner screen using expo-camera. Show a camera preview with a square overlay indicating the scan area. When a QR code is detected, vibrate using expo-haptics, display the result, and pause scanning for 3 seconds before resuming. Handle the case where camera permission is denied."`,
    `"Write the permission request flow for expo-camera in React Native. Request permission when the user navigates to the camera screen (not on app launch). If granted, show the camera. If denied, show an explanation with a button that opens app Settings via Linking.openSettings()."`,
  ],

  stretch: [
    `Add document scanning to Hydra's data import. The user can photograph a page of habits written on paper, and expo-camera captures it. Then call a vision API (Google Cloud Vision or Claude's vision) to extract the text and parse it as habit names. This combines camera capture with AI processing.`,
    `Implement a photo-a-day feature for habits. Each habit can have an optional photo attachment. The user takes a photo when checking off the habit. Photos are stored as file URIs in SQLite alongside the completion record. The history screen shows thumbnails.`,
    `Add face detection to a check-in flow using expo-face-detector (powered by ML Kit on Android, Vision framework on iOS). When the user opens the check-in screen, the camera confirms a human is present before unlocking the check-off. A fun use of the camera API.`,
  ],
});

rewriteWeek("mobile-engineering", 10, {
  context: `Location is the feature that makes mobile apps contextually aware. A restaurant app knows you are near a restaurant. A fitness app tracks your run. A delivery app shows you where the driver is. Location on mobile has two modes: foreground (the app is open and active) and background (the app is in the background or not running). They have different capabilities, different battery impacts, and different permission requirements.

expo-location provides the location API. Foreground location: requestForegroundPermissionsAsync() and getCurrentPositionAsync() or watchPositionAsync(). Background location: requestBackgroundPermissionsAsync() (a separate, stricter permission) and startLocationUpdatesAsync() (requires a background task). Always start with foreground — background location requires explicit user approval and App Store justification.

Accuracy levels matter for battery. Accuracy.Balanced uses cell towers and Wi-Fi — fast, low battery drain, accuracy of ~100 metres. Accuracy.High uses GPS — slower to acquire, significant battery drain, accuracy of ~5 metres. Accuracy.BestForNavigation uses GPS with additional sensors — maximum accuracy, maximum battery drain. Use Balanced for most cases. Only use High or BestForNavigation when navigation or precise tracking is required.

Maps: react-native-maps is the standard. On iOS it renders Apple Maps. On Android it renders Google Maps (requires a Google Maps API key). You place MapView as a full-screen component, add Marker components for points of interest, and Polyline for routes.

Geofencing: trigger code when the user enters or exits a geographic region (a circle defined by latitude, longitude, and radius). expo-location has startGeofencingAsync — it monitors regions in the background and fires a background task. Use case: notify the user when they are near a Bean Forge coffee shop, check in automatically when a runner passes a checkpoint.

Geocoding: convert addresses to coordinates (forward geocoding) and coordinates to addresses (reverse geocoding). expo-location has reverseGeocodeAsync(coords) which returns a structured address object. For forward geocoding (address to coordinates), use the Google Geocoding API or expo-location's geocodeAsync.`,

  pre_flight: `Install expo-location: npx expo install expo-location. Install react-native-maps: npx expo install react-native-maps. For Android Google Maps, get an API key from Google Cloud Console (Maps SDK for Android). Add it to app.json under android.config.googleMaps.apiKey. Add the location permission descriptions to app.json (iOS requires NSLocationWhenInUseUsageDescription). Read the expo-location and react-native-maps documentation. Note: react-native-maps requires a development build on iOS to test Google Maps; Apple Maps works in Expo Go.`,

  mastery_questions: [
    `A fitness app wants to track a user's run continuously in the foreground. The user starts a run, locks their phone, and keeps running. After 5 minutes, the app stops receiving location updates. What is happening and how do you fix it? When the user locks the phone, your app moves to the background. Foreground location (watchPositionAsync) stops when the app is backgrounded. To track location during a locked screen, you need background location: requestBackgroundPermissionsAsync() and startLocationUpdatesAsync() with a TaskManager background task. On iOS, you must also add UIBackgroundModes: location to your app.json. This requires App Store Review justification — you must clearly describe why background location is needed.`,
    `You have a map that shows nearby restaurants. When the user moves around the city, the markers should update. What is the most battery-efficient way to get location updates? Use watchPositionAsync with Accuracy.Balanced and a distanceInterval: 50. The distanceInterval means a location update only fires when the user has moved at least 50 metres — not on every GPS fix. This dramatically reduces updates (and battery drain) when the user is stationary. On the map, re-centre when the user moves significantly using the region prop of MapView.`,
    `How do you reverse geocode coordinates to get a human-readable address? const address = await Location.reverseGeocodeAsync({ latitude, longitude }). The result is an array of address objects (there may be multiple interpretations). The first result typically has { street, streetNumber, city, region, country, postalCode }. Format the result: \`\${address[0].streetNumber} \${address[0].street}, \${address[0].city}\`. Note that reverse geocoding accuracy depends on the data provider — in rural areas, you may get only a city name.`,
    `You are building a geofence that notifies the user when they arrive home. The geofence circle has a radius of 100 metres. The user lives in a dense city where GPS accuracy is 20-30 metres. How do you tune this? The geofence trigger fires when the user's location (within the accuracy margin) enters the circle. If accuracy is 30 metres and the circle radius is 100 metres, you have a 70-metre practical buffer — this should work reliably. If you set the radius too small (20 metres) and accuracy is 30 metres, the geofence fires erratically (the user is inside and outside within the margin of error). Rule of thumb: geofence radius should be at least 3x the expected GPS accuracy.`,
  ],

  common_mistakes: [
    `Requesting background location permission on the first app launch without foreground permission first. iOS requires you to request foreground permission before background permission. The background permission dialog says "Allow [app] to also use your location when you are not using the app?" — it cannot appear without foreground permission already granted.`,
    `Using Accuracy.BestForNavigation for a use case that only needs city-level location. Best accuracy drains the battery significantly. Match accuracy to the requirement: city-level content localisation needs Accuracy.Balanced; turn-by-turn navigation needs Accuracy.BestForNavigation.`,
    `Not handling permission denial gracefully. If location permission is denied, your map screen should still render — show a default location or prompt the user to enable location in Settings, rather than crashing or showing nothing.`,
    `Re-requesting location on every render. getCurrentPositionAsync is a full GPS acquisition — it can take seconds and drains battery. Call it once in a useEffect, cache the result, and only update it when the user explicitly requests a refresh or after a meaningful time interval.`,
    `Using watchPositionAsync without unsubscribing on component unmount. The subscription keeps running after the component is gone, draining battery and calling into an unmounted component (causing state update errors). Return the unsubscribe function from useEffect: return () => subscription.remove().`,
  ],

  debug_help: `Location permission dialog does not appear: check that the usage description strings are set in app.json (iOS requires them in infoPlist). Also check that you are calling requestForegroundPermissionsAsync() before getCurrentPositionAsync(). Map is blank on Android: check that your Google Maps API key is set in app.json and that the Maps SDK for Android is enabled in Google Cloud Console. Also check that billing is enabled on the Google Cloud project (Maps API requires it). watchPositionAsync stops updates after backgrounding: you are using foreground location. For background updates, use the background location API with a TaskManager task. Location accuracy is low (1km+): the device is using cell towers (Accuracy.Low). Set accuracy: Location.Accuracy.Balanced or higher. In an indoor environment with poor GPS signal, accuracy will remain low regardless of the setting.`,

  ai_assist: [
    `"Write a React Native screen that shows the user's current location on a react-native-maps MapView. Request foreground location permission on mount. Show a Marker at the user's location. As the user moves (using watchPositionAsync with Accuracy.Balanced and distanceInterval: 20), update the marker. Clean up the subscription on unmount."`,
    `"Write a geofencing setup using expo-location. Register a circular geofence of radius 200m around a set of coordinates. In the TaskManager background task, when the user enters the region, schedule a local notification: 'You are near [location name]'. Include the background permission request flow."`,
    `"Write a reverse geocoding function that takes latitude and longitude, calls expo-location reverseGeocodeAsync, and returns a formatted address string. Handle the case where the result is empty or the network is unavailable."`,
  ],

  stretch: [
    `Add a route recorder to Hydra as a stretch habit type. The user can log a walk/run as a habit completion. When they start, record location points every 10 seconds using watchPositionAsync. When they stop, calculate total distance (sum of great-circle distances between consecutive points using the Haversine formula). Display the route on a map in the completion history.`,
    `Implement "smart reminders" for Hydra: instead of a fixed time reminder, remind the user when they arrive home (detected via a geofence around their home location). The user sets their home address (reverse geocoded from a location they mark on a map). Use startGeofencingAsync to trigger the notification.`,
    `Add a "nearby habits" mode: habits tagged with a location. When the user is within 500m of the tagged location (checked every 5 minutes with Accuracy.Balanced), show a notification. This combines geofencing with habit-specific context.`,
  ],
});
