import { rewriteWeek } from "../rewrite-week";

// mobile-engineering W21-W24

rewriteWeek("mobile-engineering", 21, {
  context: `Expo Application Services (EAS) is Expo's cloud build and submission service. It replaces the complex native build setup with a managed cloud service that builds your app on Apple's macOS infrastructure (for iOS) and Linux (for Android). The result is a signed .ipa (iOS) or .aab (Android) file ready for store submission.

EAS Build: you define build profiles in eas.json (development, preview, production). A development build is installed on your device and connected to the Metro bundler for hot reload. A preview build is a standalone app (no Metro connection) for testing. A production build is what you submit to the stores. Run eas build --platform all --profile production to build for both stores simultaneously.

Code signing is the biggest complexity in mobile deployment. iOS requires: a bundle ID registered in Apple Developer portal, a provisioning profile (which devices are allowed to install the app), and a distribution certificate. EAS manages all of this with eas credentials — it generates and stores the certificates for you. Android requires: a keystore (a cryptographic key that signs your APK). EAS generates and securely stores your keystore. Never lose your keystore — you cannot update your Android app without the same keystore used to sign the original.

EAS Submit: after a successful build, eas submit --platform ios submits the .ipa to App Store Connect, and eas submit --platform android submits the .aab to Google Play. This replaces manually downloading the build and uploading it through the web dashboards. Requires API keys for both stores.

Over-the-Air (OTA) updates: for JavaScript-only changes (no native code changes), you do not need to submit a new build to the stores. EAS Update deploys a new JavaScript bundle to your app's update channel. Users download the update silently the next time they open the app. This allows fixing bugs and shipping small features without waiting for App Store Review (which takes 1-3 days). Native code changes (adding a new native library, changing app permissions) always require a new store submission.`,

  pre_flight: `Install EAS CLI: npm i -g eas-cli. Create an Expo account at expo.dev. Create an Apple Developer account ($99/year) at developer.apple.com. Create a Google Play Developer account ($25 one-time) at play.google.com/console. Run eas login. Run eas build:configure to set up eas.json. Run eas credentials to let EAS manage your certificates. Read the EAS Build documentation end-to-end.`,

  mastery_questions: [
    `You make a change to Hydra that adds a new native library (react-native-vision-camera). Can you ship this with an OTA update? No. OTA updates (EAS Update) can only update the JavaScript bundle. Adding a new native library requires recompiling the native code and producing a new .ipa/.aab file. You must submit a new build to the stores. OTA updates are only for JavaScript changes: fixing a bug in your React components, updating API endpoints, changing translations, adding a new screen (if it uses no new native libraries).`,
    `Your Android keystore is lost. The app is live in the Play Store with 10,000 users. What happens? You cannot update the app. Google Play requires you to sign every update with the same keystore used to sign the original app. Without the keystore, you cannot publish updates. Your options: if you enrolled in Google Play App Signing before submitting, Google has a copy of your upload key and can re-sign with their key — you can generate a new upload key and submit. If you did not enrol in Google Play App Signing, the only option is to publish a new app with a new package name — existing users will not receive it as an update. This is why EAS stores your keystore securely and why you must back it up.`,
    `You find a crash affecting 5% of users. It is a JavaScript bug — no native code change needed. You want to ship a fix in the next hour without going through App Store Review. How? Use EAS Update. Fix the bug in your JavaScript code. Run eas update --branch production --message "fix: crash on habit delete". EAS pushes the new JavaScript bundle to your update channel. When users open the app, it downloads the update in the background. On next launch, they run the fixed code. The update can reach users within minutes. No App Store Review required.`,
    `What is the difference between a development build, a preview build, and a production build in EAS? Development build: compiled with debug flags, connected to Metro bundler for hot reload, not distributed through stores, used for daily development on your device. Preview build: standalone app (not connected to Metro), can be distributed via TestFlight or Google Play internal testing, used to test the release build experience (no hot reload, real performance). Production build: compiled with release flags, app size optimised (Hermes bytecode, minification), signed for store distribution, what users download from the stores.`,
  ],

  common_mistakes: [
    `Not backing up your Android keystore and iOS certificates. EAS stores them securely, but you should also download and store them offline. One way to get locked out of your own app: lose your signing credentials.`,
    `Using OTA updates for native code changes. If you add a native library and push an OTA update, users with the old binary download JavaScript that expects a native module that does not exist — the app crashes. OTA updates are safe only for pure JavaScript changes.`,
    `Not testing the production build before submitting. The production build behaves differently from the development build (Hermes is enabled, debugging is off, some debug-only libraries are excluded). Always install and test a preview build before submitting the production build.`,
    `Not setting up two-factor authentication on your Apple Developer and Google Play accounts. These accounts control apps that millions of users have installed. A compromised account can push malicious updates. Enable 2FA and store recovery codes securely.`,
    `Forgetting to increment the version and build number before building. The App Store and Google Play reject builds with duplicate version/build numbers. Increment app.json version (user-visible: 1.0.0, 1.0.1) and buildNumber/versionCode (internal: 1, 2, 3) for every build submitted.`,
  ],

  debug_help: `EAS build fails with "No matching provisioning profile": run eas credentials and let EAS manage your provisioning profiles. If you have manually created profiles that conflict, delete them from developer.apple.com and let EAS regenerate. Android build fails with "Keystore not found": run eas credentials --platform android and follow the prompts to generate or upload a keystore. EAS Update not reaching users: check the update channel name in your eas.json matches the channel you specified in the update command. Also check that expo-updates is properly configured in app.json with the EAS project ID. App Store submission rejected: common reasons: missing privacy policy URL (required for apps that collect any data), missing permissions usage descriptions in app.json, screenshots in the wrong size. Read the rejection reason carefully — Apple provides specific feedback.`,

  ai_assist: [
    `"Write the eas.json for a React Native app with three build profiles: development (development client, debug mode), preview (standalone, internal distribution via TestFlight), and production (store submission, release mode, OTA updates enabled). Include the channel configuration for EAS Update."`,
    `"Walk me through the complete Hydra App Store submission checklist: app metadata (name, description, keywords, categories), screenshots required (all sizes), privacy policy URL, age rating, pricing, TestFlight internal testing, review notes. What is most likely to cause a rejection?"`,
    `"Write a GitHub Actions workflow that builds and submits Hydra for both iOS and Android when a tag matching v*.*.* is pushed. Use eas build and eas submit with the production profile. Include the steps to set up EAS credentials as GitHub secrets."`,
  ],

  stretch: [
    `Set up Fastlane alongside EAS for advanced automation: automatic screenshot generation in multiple languages using Fastlane Snapshot, automatic App Store metadata updates using Deliver. Fastlane and EAS complement each other — EAS handles builds, Fastlane handles metadata and screenshots.`,
    `Implement a forced update check. On app start, your server returns the minimum required app version. If the installed version is below the minimum, show a non-dismissable update modal that links to the App Store/Play Store. This lets you force users off broken versions. Use expo-updates to get the current app version.`,
    `Set up separate development, staging, and production environments with separate app IDs (com.yourapp.dev, com.yourapp, etc.) so you can install all three simultaneously on your device. Configure EAS build profiles to build each environment with the correct configuration.`,
  ],
});

rewriteWeek("mobile-engineering", 22, {
  context: `App versioning and update strategy are the operational concerns that determine how smoothly you can ship changes to users. Unlike web (where you deploy once and all users are immediately on the new version), mobile apps have version fragmentation — users on version 1.0 coexist with users on 1.2 and 1.5. Your backend must handle requests from all live versions.

Semantic versioning for mobile: version (user-visible: 1.2.3, shown in the store) and buildNumber/versionCode (internal counter, incremented with every submitted build). The store rejects builds with a duplicate versionCode. Conventions: major version for breaking changes, minor for new features, patch for bug fixes. Build numbers go 1, 2, 3... or use YYYYMMDDNN format (2026052601).

API versioning: your mobile app talks to your API. When you change the API (remove a field, change a response format), old app versions break. Solutions: version your API (/api/v1/habits). Keep v1 running while deploying v2. Old app versions hit v1, new versions hit v2. Deprecate v1 gradually. The alternative is to design APIs that are additive only — never remove fields, only add new ones (but give old fields a deprecatedAt marker and log their usage).

Forced updates: sometimes you must force users to update (a critical security vulnerability, an API deprecation). Implement a minimum app version check: your server returns the minimum required version (1.1.0) and the current user's app version (from expo-constants). If below minimum, show a non-dismissable update screen with a link to the store.

Update channels with EAS: EAS Update uses channels (main, production, staging) and branches (like git branches). You publish an update to a channel and all app builds pointing to that channel receive it. You can roll back to a previous update by republishing an older update to the channel. This is your escape hatch when an OTA update has a bug.

Changelog and release notes: App Store and Google Play ask for "What's New" with every update. Write it for users, not developers. "Fixed a bug where streaks were calculated incorrectly" is good. "Fix off-by-one error in streakCalculator.ts" is developer-speak.`,

  pre_flight: `Read the EAS Update documentation on channels and branches. Know the difference between a build and an update in EAS: a build is a native binary (compiled); an update is a JavaScript bundle. Understand how expo-updates works in the app: it checks for updates on app start, downloads them, and applies them on the next app launch. Read expo-updates API docs for the useUpdates hook.`,

  mastery_questions: [
    `You push an OTA update that has a bug — the habits list crashes on load. 30% of your users have already received the update. How do you roll back? In EAS Update, publish a rollback: eas update --branch production --republish to republish the last known-good update to the production channel. Users who received the buggy update will download the rollback on their next app open. For the 30% currently on the buggy version: if the crash prevents the app from opening (and thus downloading the rollback), you cannot reach them with OTA. This is why you test OTA updates on a preview channel first before publishing to production.`,
    `Your backend has an endpoint GET /api/habits that returns { habits: [], total: number }. In version 2, you want to rename total to count. How do you do this without breaking users on version 1? Do not remove total. Add count alongside it: return { habits: [], total: length, count: length }. Both fields have the same value. Old app versions (v1) use total. New app versions (v2) use count. After version 1 is no longer in use (you can check server logs for which versions are making requests), remove total from the API. The key principle: additive changes are safe, removals are breaking.`,
    `How do you implement the minimum version check? Your server has an endpoint GET /api/config that returns { minAppVersion: "1.2.0" }. On app start, call this endpoint. Compare the returned minAppVersion to Constants.expoConfig.version (the current app version). Use a semver library to compare: semver.lt(currentVersion, minVersion). If the current version is below the minimum, render a non-dismissable <UpdateRequired> screen that links to the store using Linking.openURL(storeUrl). Do not block the API call itself — the user cannot update while offline.`,
    `You have 5000 active users on version 1.0, 3000 on 1.1, and 2000 on 1.2. Your backend logs every API request with the app version from the X-App-Version header. A bug is only reproducible on version 1.0. How do you handle this? Deploy a bug fix as an OTA update to the production channel (targeting all versions). If the bug is in native code, you cannot OTA fix it — submit a new build. For version 1.0 users who cannot update for some reason (corporate MDM), you can add a server-side workaround: detect the old version from the X-App-Version header and apply different logic for requests from version 1.0. This is version detection, an anti-pattern to use only as a last resort.`,
  ],

  common_mistakes: [
    `Never testing on older app versions. You add a new API field in version 1.2 and use it in the UI. Users on 1.1 (who have not updated) send requests and receive the field, but their app code does not know about it (they have the old JavaScript). Wait — OTA updates ensure all users run the latest JavaScript. But if the user has network issues and their OTA update has not downloaded, they may still be running old JS with a new API. Defensive coding: always handle undefined fields gracefully.`,
    `Deploying OTA updates without a staged rollout. An OTA bug that reaches all users simultaneously is worse than a store update bug (which takes days to roll out). Use EAS Update's rollout percentage: deploy to 10% of users first, monitor Sentry, then expand to 100%.`,
    `Forgetting to update the version in app.json before building. If you forget to increment the version, the new build has the same version as the last one. The App Store rejects duplicate build numbers. Add version incrementing to your release checklist.`,
    `Not writing "What's New" for App Store releases. Users read release notes. Apple reviewers read release notes. "Bug fixes and performance improvements" for every update is a missed opportunity to re-engage users and inform reviewers what you changed.`,
    `Storing configuration in the app bundle that should be remote. Feature flags, API endpoints, minimum version requirements, app strings — these change more often than the app version allows. Fetch them from a remote config endpoint and cache them locally.`,
  ],

  debug_help: `OTA update is not downloading: check that the EAS project ID in app.json matches your EAS project. Check that the update channel in your EAS Update publish matches the channel configured in the build. Use expo-updates's useUpdates hook to check the update status programmatically. Users on old versions after OTA: some users have the app backgrounded for days. OTA updates download on next foreground but apply on the launch after that. Add an in-app update check: if an update is available, offer a "Restart to apply update" button. App Store build rejected for version code: versionCode in app.json (android.versionCode) must be higher than the last submitted build. Increment it before building.`,

  ai_assist: [
    `"Write a React Native component that checks for a minimum app version on mount. It calls an API endpoint for the minimum version, compares it to Constants.expoConfig.version using semver, and if the current version is too old, renders a full-screen non-dismissable modal with the app name, a message, and a button that opens the App Store/Play Store link."`,
    `"Write a useOTAUpdate hook using expo-updates. On mount, check for available updates. If an update is available, show a toast with a 'Restart now' button. On button press, reload the app to apply the update. Handle the case where the check fails (network error)."`,
    `"Write the X-App-Version header middleware for an Express API. It reads the version from the header, logs it as a structured field for analytics, and rejects requests from versions below a configurable minimum with a 426 Upgrade Required response and a JSON body containing the minimum version and the store URLs."`,
  ],

  stretch: [
    `Implement a staged OTA rollout. Use EAS Update's rolloutPercent option to deploy to 10% of users first. Monitor Sentry for crashes for 24 hours. If error rate is acceptable, expand to 50%, then 100%. Write the rollout command sequence and the monitoring checklist.`,
    `Build a version analytics dashboard. Log app versions from API request headers into a database table. Write a query that shows the distribution of app versions (what % of active users are on each version) and graphs it over time. This tells you when it is safe to deprecate old API versions.`,
    `Set up TestFlight external testing with 50 beta users. Write the TestFlight onboarding email explaining how to install the build and what to test. Collect feedback via a TypeForm linked in the TestFlight description. Run a beta cycle for 2 weeks before the production App Store release.`,
  ],
});

rewriteWeek("mobile-engineering", 23, {
  context: `App Store Optimisation (ASO) is to the App Store what SEO is to Google — the practice of making your app more discoverable and compelling to potential users. Most app installs come from App Store search. The factors that determine whether your app appears and whether users download it are within your control.

The App Store search algorithm: keyword relevance, conversion rate (how many people who see your app install it), ratings and reviews (both count and recency), and engagement (how often users open the app after installing). Your job: optimise the first three. Engagement comes from building a good app.

Keyword research: find the words and phrases your target users search for. Tools: AppFollow, Sensor Tower, MobileAction, or the free AppFollow free tier. Search for your app's use case and look at what apps rank. Your app's title, subtitle, and keywords field contribute to search ranking. The title is weighted highest. The keywords field accepts up to 100 characters (comma-separated, no spaces around commas). Do not repeat words from the title in the keywords — they are already indexed.

Screenshots are the most important conversion factor. On the search results page, users see your first 1-3 screenshots (depending on the device) before tapping. These screenshots decide whether they tap to learn more. Best practice: the first screenshot conveys the core value proposition with a short caption. Subsequent screenshots show the key features. Use a device frame with marketing text (tools: Rottenwood, AppLaunchpad, or Figma templates). Test different screenshot sets with App Store A/B testing (Apple's Product Page Optimization).

Ratings and reviews: users who love your app rarely leave reviews unless prompted. Use expo-store-review (which calls SKStoreReviewAPI on iOS and its Android equivalent) to show the native rating prompt at the right moment — after the user has had a positive experience (after a habit streak milestone, after they explicitly say they enjoy the app). The rating prompt can only be shown 3 times per year per user. Choose the moment wisely.

Respond to every review, especially negative ones. A thoughtful response to a 1-star review shows potential users that you care. "We are sorry to hear this — please email support@hydra.app and we will resolve this for you" turns a public complaint into an invitation to fix the problem privately.`,

  pre_flight: `Study the top 5 apps in your category on the App Store. Note their titles, subtitles, first screenshot, and ratings count. Sign up for AppFollow free tier (appfollow.io) for keyword tracking. Read Apple's App Store screenshot specifications (device sizes and pixel requirements). Read the Google Play store listing best practices. Prepare your marketing assets: app icon (1024x1024px, no alpha channel), screenshots in all required sizes.`,

  mastery_questions: [
    `Your app is named "Hydra" and your subtitle is "Habit Tracker & Streak Builder." What keywords should you put in the 100-character keywords field? Do not repeat "habit", "tracker", or "streak" — they are in the title/subtitle and already indexed. Use the 100 characters for additional terms users might search: "daily goals,routine builder,accountability,wellness,productivity,morning routine,self improvement,health". Prioritise: high-search volume terms your app is actually relevant to, terms where your competition is not overwhelming, long-tail phrases (lower volume but higher intent). Research which terms similar apps rank for using AppFollow.`,
    `Your app has a 3.8-star average rating from 200 reviews. A competitor has a 4.6-star average from 5000 reviews. How do ratings affect App Store ranking and what do you do? Ratings affect both App Store search ranking and the conversion rate on your app page. A 3.8 average is below the App Store average (4.4) and will hurt conversion. To improve: fix the issues causing low ratings (read every 1 and 2-star review — there is usually a pattern). Then prompt happy users for a review at the right moment using expo-store-review. One well-timed prompt to an engaged user is worth 100 un-prompted reviews you never get. Do not buy reviews — Apple bans apps caught doing this.`,
    `How do you measure whether your App Store optimisation changes are working? Install velocity (downloads per day), before and after the change. Conversion rate (tap to install percentage) — visible in App Store Connect > Analytics > Conversion Rate. Keyword ranking — track your target keywords in AppFollow weekly. For screenshot changes, use Apple's Product Page Optimization (A/B test two versions of screenshots). For keyword changes, allow 2 weeks of data before evaluating (search ranking changes slowly). Keep a change log with dates so you can correlate changes to metric movements.`,
    `You want to use expo-store-review to prompt users for a rating. When is the right moment and what are the constraints? The right moment: after a positive emotional event — after the user completes a 7-day streak, after they mark all habits complete for the day for the first time, after they explicitly say "I love this app" in a feedback prompt. The wrong moment: on first launch, after an error, when the user is mid-task. Constraints: SKStoreReviewAPI can only be called 3 times per 365 days per user. After 3 prompts, calling it does nothing. Plan your 3 prompts strategically. Also: if the user has already rated the app, the prompt does not appear (on iOS 16+).`,
  ],

  common_mistakes: [
    `Using the same screenshots on the App Store and Google Play. Each store has different screenshot requirements (sizes, dimensions) and different audiences. Create platform-specific screenshots. Google Play also shows the screenshot with the play button for the preview video — design accordingly.`,
    `Putting marketing text in the screenshot image itself using small, unreadable fonts. Screenshot text must be readable at the thumbnail size shown in search results (about 120px wide on a phone). Use large, high-contrast text with a short message (5 words maximum).`,
    `Updating keywords randomly without tracking results. ASO is a data-driven process. Track keyword rankings before and after changes. Wait 2 weeks for data. Evaluate whether the new keywords are ranking and converting before changing again.`,
    `Showing the rating prompt immediately on first launch. The user has not experienced the app yet — they have no basis for a positive review. Show the prompt only after the user has experienced the core value proposition.`,
    `Ignoring the short description (Google Play) and subtitle (App Store). These appear in search results. After the app name, they have the most weight. Write them to explain the core value in 10 words or less, using high-intent keywords.`,
  ],

  debug_help: `expo-store-review prompt is not appearing: check that you have not exhausted the 3 prompts for the year. In development, StoreReview.requestReview() opens the prompt on a physical device but not on a simulator. Verify that the user is not in the "already rated" cohort (on iOS 16+, iOS suppresses the prompt if the user has rated the version). App not appearing in search results for target keywords: it can take 4-8 weeks for new keyword changes to take effect. Check in AppFollow whether the keywords are indexed at all. Some keywords are too competitive to rank for without a large install base — choose keywords where you can realistically rank in the top 10. Screenshots rejected by App Store: the simulator status bar must show 9:41am (the time shown in Apple marketing materials) or be hidden. Screenshots must be device-specific sizes. No third-party app icons or brand logos.`,

  ai_assist: [
    `"I am launching a habit tracking app called Hydra. Write the App Store listing: title (30 chars max), subtitle (30 chars max), description (4000 chars), keywords field (100 chars, comma-separated, no repeated words from title/subtitle). Target users: people who want to build better daily habits. Optimise for discoverability and conversion."`,
    `"Write the rating prompt trigger logic for Hydra. Show the expo-store-review prompt after: the user's first 7-day streak (check in the streak calculation), the first time the user completes all habits in a day (check in the completion handler). Track in MMKV how many times the prompt has been shown (max 3 per year). Include the check for available time since last prompt (at least 30 days between prompts)."`,
    `"Generate screenshot caption text for Hydra's App Store screenshots. The first screenshot shows the habit list. Write a hero caption (max 5 words, high contrast) that communicates the core value. The second shows the streak screen. The third shows the calendar history. Each needs a short, punchy caption."`,
  ],

  stretch: [
    `Run an A/B test on your App Store screenshots using Apple's Product Page Optimization. Create two versions of your first screenshot with different designs and captions. Run the test for 90 days. Analyse which version has a higher conversion rate. Apply the winner and note the improvement.`,
    `Build a review response workflow. Set up AppFollow or AppBot to notify a Slack channel when a new review is posted. Respond within 24 hours to every 1-3 star review (acknowledge the issue, invite them to email support). Track whether your average rating improves over 90 days.`,
    `Analyse your top competitors' keyword rankings using AppFollow's competitor analysis. Find keywords where they rank highly but you do not, and where your app is equally relevant. Add these to your keywords field and track whether your ranking improves over the next 4 weeks.`,
  ],
});

rewriteWeek("mobile-engineering", 24, {
  context: `This is the week you ship Hydra to both the App Store and Google Play and get your first real users. The capstone is not about adding features — it is about going through the full release cycle: review preparation, submission, approval, and distribution. And then doing the harder thing: getting real people to install and use the app.

App Store review takes 1-3 days on average. The review team checks: does the app crash? Does it do what the description says? Are all features accessible (not behind broken paywall logic)? Does it comply with the App Store guidelines (no unapproved content, no privacy violations, no misleading interface)? Google Play review takes a few hours to a few days.

Pre-submission checklist: the app does not crash on first launch or during normal use. All screens are accessible via VoiceOver/TalkBack. The app has a privacy policy URL (required if you collect any data). Permission usage descriptions are in app.json (NSCameraUsageDescription, NSLocationWhenInUseUsageDescription, etc.) and match the actual permissions used. The app icon has no alpha channel (App Store requirement). Screenshots are in the correct sizes for all device types.

Review notes: when submitting, you can add notes to the reviewer. If your app has any unusual features or requires specific steps to test, explain them. If your app requires a login, provide a test account. If a feature requires a specific hardware (like Face ID), describe what the reviewer will see on a device without it.

After launch: the real work begins. Track your crash rate (Sentry), rating (AppFollow), and installs (App Store Connect, Google Play Console). The first week of data tells you a lot about onboarding — where users drop off is where you iterate first. Respond to every review. Fix every crash.

Getting your first users: post in relevant communities (r/habits, r/getdisciplined, r/productivityapps on Reddit, IndieHackers, Product Hunt). Share your launch story — how you built it, what you learned, why you built it. The authentic builder story is more compelling than a generic launch post. Write a blog post about building Hydra in 24 weeks.`,

  pre_flight: `Create accounts in App Store Connect (appstoreconnect.apple.com) and Google Play Console (play.google.com/console). Set up your bank account and tax information in both (required before you can charge for anything). Create the app listing in both stores (bundle ID must match your eas.json). Prepare all metadata: app description, keywords, screenshots (all device sizes), app icon, privacy policy URL (host it on a simple web page). Run the pre-submission checklist above.`,

  mastery_questions: [
    `App Store Review rejects Hydra with "4.3 - Apps that are primarily designed to upsell or advertise." You have a paywall for Pro features. How do you respond? Apple's guideline 4.3 (and the broader "Spam" guidelines) are about apps that exist purely to advertise. A freemium app with legitimate free features and paid premium is allowed. Your response: write a detailed appeal explaining the free features (habit tracking, streaks, history) and the paid features (unlimited habits, advanced analytics). If the free tier is too limited (one habit only, which is functionally useless), Apple may reject. Ensure the free tier is genuinely usable. Submit the appeal through the Resolution Center in App Store Connect.`,
    `You submit version 1.0. It gets approved and goes live. The next day, you find a critical crash affecting all users on iOS 17. You fix the JavaScript bug. How fast can you get the fix to users? OTA update via EAS Update: publish the fix to the production channel within an hour. Users who open the app will download and apply the fix without going through App Store Review. This is the most important operational reason to configure OTA updates — critical fixes reach users in minutes, not days.`,
    `Your app has 500 installs after 2 weeks. Day 1 retention is 45% (45% of users who installed come back the next day). Day 7 retention is 12%. What do these numbers mean and what do you do? 45% D1 retention is solid (industry average ~25-30% for utility apps). 12% D7 is below expectations — users are dropping off between day 1 and day 7. This means the first impression is good but the ongoing value is not compelling users to return. Focus: what happens on day 2-7? Are users setting up their habits but not returning to check them? Are notifications working? Look at the analytics funnel: do users who enable the daily reminder have higher D7 retention? If yes, optimise the onboarding to increase reminder opt-in rate.`,
    `A user emails you: "Your app crashes every time I try to add a habit on my Samsung Galaxy S21." You cannot reproduce it on your devices. How do you investigate? Check Sentry for crashes associated with the "Add Habit" flow and filter by Android device model. If there is a crash, the stack trace shows where. If Sentry shows nothing, add more breadcrumb logging around the habit creation flow. Ask the user for their Android version (Settings > About Phone). Samsung Galaxy S21 runs OneUI — Samsung sometimes customises Android in ways that affect React Native apps. Check whether the crash is related to a Samsung-specific API behaviour or a font/layout issue specific to the device.`,
  ],

  common_mistakes: [
    `Not testing on a wide range of devices before submission. Most developers test on 1-2 devices. Real users have hundreds of different device configurations. At minimum, test on one iPhone, one Android flagship, and one Android mid-range device (where most Android users are). Use a service like BrowserStack for device testing.`,
    `Launching without a support channel. Users who have problems will email you, leave bad reviews, or both. Set up support@yourapp.com before launch. Reply within 24 hours. Every user who leaves a good support interaction is a potential 5-star review.`,
    `Launching without telling anyone. An app that is not promoted is invisible. Post in every relevant community. Reach out to YouTube creators who review apps. Submit to app review newsletters. Write a launch post on IndieHackers. The app will not market itself.`,
    `Not setting up financial reporting. App Store Connect and Google Play Console both show earnings. If you have paid subscriptions, set up a spreadsheet or use RevenueCat's dashboard to track MRR (monthly recurring revenue), churn rate, and LTV (lifetime value). Know your numbers.`,
    `Stopping development after launch. The apps that retain users are the ones that keep improving. Plan your next 3 features before you launch so you have momentum. Communicate the roadmap to users — people who know features they want are coming back will not delete the app.`,
  ],

  debug_help: `App Store submission fails at upload: check that the build was created with eas build --platform ios --profile production (not development). The archive must be signed with a distribution certificate, not a development certificate. Google Play upload fails with "You need to use a different version code": increment android.versionCode in app.json and rebuild. App Review notes: if the reviewer cannot find a feature, they may reject with "we could not review your app." Be explicit in the review notes about which features are available in the free tier and how to access them. If the reviewer needs a test account, provide one. Post-launch crash spike: check Sentry immediately. Filter to the current app version and the most recent timeframe. Look for patterns: which screen, which device, which OS version. For JavaScript crashes, push an OTA fix. For native crashes, build and submit a patch immediately.`,

  ai_assist: [
    `"Write the App Store submission review notes for Hydra. Include: a brief description of the app's core features, which features are available in the free tier, which require Pro subscription, the test account credentials (use placeholder), and any notes about device-specific behaviour (Face ID appears on compatible devices, falls back to passcode otherwise)."`,
    `"Write the launch blog post for Hydra: 'I built a habit tracker in 24 weeks — here is what I learned.' Structure: what the app does, the tech stack (React Native + Expo + SQLite), the hardest week, the most impactful feature for retention, three things I would do differently, and a call to download the app."`,
    `"Write a 30-day post-launch analytics review framework for a mobile app. Metrics to track: daily installs, Day 1/D7/D30 retention, crash-free session rate, average session length, feature adoption rates, subscription conversion rate, and MRR. For each metric, include the target benchmark and the action to take if below target."`,
  ],

  stretch: [
    `Write a detailed retrospective: which of the 24 weeks was hardest and why, which week taught you the most, what you would build differently if starting over, and what you are building next. Publish it on your blog or IndieHackers. The discipline of writing retrospectives is what separates developers who keep improving from those who repeat the same mistakes.`,
    `Submit Hydra to three curated app review sites: AppAdvice, 148Apps, and a relevant niche site (a productivity blog, a self-improvement newsletter). Write a personalised pitch for each that explains why their audience would love the app. Track installs from each source using UTM links on a landing page before the App Store redirect.`,
    `Build a public roadmap page for Hydra. List the top 5 features users have requested (from reviews and support emails), which ones you are planning to build, and the rough timeline. Link to it from the app's Settings screen. A public roadmap builds trust, reduces "when is feature X coming?" support emails, and gives users a reason to stay subscribed.`,
  ],
});
