import { rewriteWeek } from "../rewrite-week";

// mobile-engineering W16-W20

rewriteWeek("mobile-engineering", 16, {
  context: `Mobile analytics and crash reporting are not optional for a production app. Without them, you find out about crashes from App Store reviews, and you find out about user behaviour patterns when you guess. With them, you have evidence.

Crash reporting: Sentry is the standard. It captures unhandled JavaScript errors, native crashes (in development builds), the stack trace, the device model and OS version, the user's session, and groups duplicate crashes. One crash affecting 500 users appears as one Sentry issue with a count of 500. Without Sentry, it looks like no reported bugs. Install @sentry/react-native and initialise it before your root component renders.

Analytics: you need to know how users move through your app. Which screens do they visit? Where do they drop off in the onboarding flow? What features do the retained users use? Mixpanel, Amplitude, or PostHog are the standard mobile analytics tools. You instrument events manually: track('habit_checked', { habitId, habitName, completionStreak }). The events you do not instrument are invisible. Instrument the most important user actions on day one, not later.

Event taxonomy: design your events deliberately before you start tracking. Events have a verb-noun format: habit_completed, habit_created, habit_deleted, onboarding_completed, reminder_set, notification_opened. Include properties that allow segmentation: which habit, what time of day, what device, what app version. An event with no properties tells you something happened but not why or in what context.

Performance monitoring: track app startup time, screen render time, and API response times. Sentry's performance monitoring and Expo's built-in performance tools measure these. App startup time directly affects Day 1 retention — apps that take more than 3 seconds to show content lose a measurable percentage of new users.

Privacy and consent: analytics tracking requires user consent in the EU (GDPR) and increasingly in other jurisdictions. On iOS 14.5+, ATT (App Tracking Transparency) requires explicit user permission for cross-app tracking. For first-party analytics (tracking your own users in your own app), ATT does not apply. But if you use advertising networks or cross-device tracking, ATT consent is required.`,

  pre_flight: `Create a Sentry account and a React Native project. Install @sentry/react-native: npx expo install @sentry/react-native. Run the Sentry wizard: npx @sentry/wizard@latest -i reactNative. Create a PostHog account (posthog.com, generous free tier). Install posthog-react-native: npm i posthog-react-native. Read the Sentry React Native quickstart. Decide on your event taxonomy before writing any tracking code.`,

  mastery_questions: [
    `Sentry shows an unhandled promise rejection from an API call. The error is "Network request failed" and it has happened 1,847 times in the last week, affecting 234 unique users. How do you investigate this? Check the Sentry issue for the breadcrumbs (the sequence of events before the crash) — which screen was the user on? Which API endpoint was failing? Look at the OS distribution — is this only on Android, or both platforms? Check the network timeline — was this during a period when your backend had an incident? Filter by app version — did this start after a specific release? With this information: if it is a specific API endpoint, look at your server logs for that period. If it is all networks equally, check whether the API URL is correct in that version. If it is only Android, check for Android-specific network configuration.`,
    `You want to measure how many users complete the Hydra onboarding flow (3 screens: Welcome, Set first habit, Enable reminders). How do you track the funnel? Track events at each step: onboarding_started, habit_created, reminders_configured, onboarding_completed. In your analytics tool, create a funnel analysis: how many users who fired onboarding_started also fired onboarding_completed? At which step do most drop off? If 100 users start, 80 create a habit, 60 configure reminders, and 55 complete — the big drop is at reminders (80 to 60). This tells you to investigate: is the reminders screen confusing? Is it getting an error? Should reminders be optional?`,
    `App startup time is 4.2 seconds on the median device. Users report the app "feels slow." How do you diagnose and fix this? Profile startup using the React Native Performance Monitor (flipper, or react-native-performance). The startup phases: native app launch (iOS/Android loading the binary), JavaScript engine initialisation, JavaScript bundle evaluation, first render, data loading. If the JS bundle is large, evaluate it faster with Hermes (already enabled in modern Expo). If the first render takes long, check whether you are doing synchronous work (reading MMKV, computing state) before the first render. If data loading is slow, use cached data for the initial render and refresh in the background. Each second of startup time corresponds to ~5% drop in Day 1 retention.`,
    `You track a user_property user_type with values 'free' and 'pro'. A user upgrades from free to pro. How do you update this in your analytics tool? In most analytics tools, user properties are associated with the distinct_id (user ID). Call identifyUser with the updated properties: analytics.identify(userId, { user_type: 'pro', upgraded_at: new Date().toISOString() }). The tool updates the property on the user profile. Future events from this user carry the new property value. Historical events are not retroactively updated (they were logged with user_type: 'free'). This is why retroactive analysis must segment by event properties, not just user properties.`,
  ],

  common_mistakes: [
    `Initialising Sentry after root component renders. Crashes that happen during early initialisation (before the root component) are not captured. Initialise Sentry.init() as the very first line of your entry file (App.tsx before the App function declaration).`,
    `Not wrapping root in Sentry.wrap. Without the error boundary: Sentry.wrap(App), unhandled React rendering errors are not captured. The wrapper provides the React error boundary that catches and reports render crashes.`,
    `Tracking too many events with no analysis plan. If you track 200 different events but never look at them, you have a data swamp, not analytics. Track fewer events more deliberately. The events that matter: conversion events (habit_created, subscription_started), retention events (daily_open, habit_completed), and failure events (onboarding_abandoned, payment_failed).`,
    `Logging user PII in analytics events. Never include email addresses, full names, phone numbers, or health data in analytics event properties. Use internal IDs (userId) and derived attributes (user_type, streak_length). PII in analytics tools creates legal exposure.`,
    `Not testing crash reporting before shipping. Throw a deliberate error in a development build and verify it appears in Sentry. If you only test crash reporting in production, you might find out it was misconfigured after a real incident.`,
  ],

  debug_help: `Sentry is not capturing crashes: verify the DSN is correct and that Sentry.init() is called before any other code. Check the Sentry dashboard for the project — are there any issues at all? Try Sentry.captureException(new Error('test')) in a button handler to verify the SDK is sending. Analytics events not appearing: check the PostHog live stream in the dashboard (posthog.com > Activity). Events may be batched and sent with a delay — check after 60 seconds. Verify the PostHog API key is correct. App startup time measurement: use the @expo/react-native-action-sheet perf markers or install react-native-performance to measure the time from JS engine start to first render. Compare debug and release builds — release builds with Hermes are significantly faster.`,

  ai_assist: [
    `"Set up Sentry in a React Native Expo app. Initialise Sentry at the top of App.tsx before anything else. Wrap the root component with Sentry.wrap. Add a user context (userId, email) after login. Show how to manually capture an exception with extra context: Sentry.captureException(error, { extra: { habitId, screen } })."`,
    `"Design an analytics event taxonomy for a habit tracking app. List 10 events that cover the user lifecycle: acquisition (first open), activation (first habit created), retention (daily usage), revenue (subscription), and churn (app uninstalled or subscription cancelled). For each event, list 3-5 properties to include."`,
    `"Write a performance monitoring wrapper for React Native screen loads. On each screen mount, record the start time. When data has loaded and the component is rendered, record the end time. Track the total load duration as an analytics event: screen_loaded with properties screenName and durationMs."`,
  ],

  stretch: [
    `Implement a developer debug screen accessible from the Settings screen in debug builds. Show: the Sentry DSN (to verify configuration), the last 10 analytics events, the current user's analytics properties, and a button to send a test crash. This makes it fast to verify instrumentation without checking the dashboard.`,
    `Build a retention cohort analysis. From your analytics data, extract weekly cohorts (users who first opened the app in week N) and calculate their D1, D7, and D30 retention rates (what % returned on day 1, 7, 30 after first open). Use PostHog's retention analysis or export the event data to a Python notebook.`,
    `Set up remote configuration using Firebase Remote Config or PostHog Feature Flags. Control the onboarding flow A/B test: half of new users see the 3-step onboarding, half see a 1-step onboarding. Measure which variant has higher habit_created rates. Ship the winner.`,
  ],
});

rewriteWeek("mobile-engineering", 17, {
  context: `60 frames per second is the contract between your app and your users. At 60fps, animations feel smooth and interactions feel instant. At 30fps, everything feels slightly sluggish. Below 30fps, the app feels broken. Performance problems on mobile have different causes than on web, and fixing them requires understanding how React Native renders.

The render pipeline: React renders to a virtual DOM diff, passes the diff to the React Native bridge (or JSI), which calls native layout and drawing APIs. The result is displayed on screen. This pipeline runs on every state update. The JavaScript thread handles your React renders, event handlers, and business logic. The UI thread handles native rendering. They run concurrently — JavaScript being slow does not directly cause dropped frames, but passing too much work across the bridge can.

The most common performance problems: re-rendering components that did not change, computing expensive values on every render, rendering large lists inefficiently, and passing large data across the bridge too frequently.

React DevTools profiler: shows which components re-rendered and how long each render took. Accessible via the Expo Dev Tools. Use it to identify the "hot" components — the ones that re-render most often and take the longest.

Memoisation: React.memo wraps a component and only re-renders when its props change (shallow equality check). useMemo caches the result of a computation and only recomputes when dependencies change. useCallback caches a function reference and only creates a new function when dependencies change. Overusing these adds complexity — use them only when the React Profiler shows that a component is re-rendering unnecessarily and the re-render is expensive.

FlatList optimisations: getItemLayout tells FlatList the exact height of each item, so it does not need to measure them. initialNumToRender controls how many items render on the first pass. windowSize controls how many screens of content are rendered above and below the visible area. removeClippedSubviews offloads off-screen items from memory (experimental, may cause issues — test carefully).

Hermes is the JavaScript engine used in modern React Native. It is optimised for mobile: it compiles JavaScript to bytecode at build time (instead of JIT at runtime), which significantly reduces startup time. It is enabled by default in Expo SDK 47+.`,

  pre_flight: `Enable Flipper (if on older Expo) or use the React Native DevTools for profiling. Know how to use the React DevTools Profiler (install react-devtools: npm i -g react-devtools, then run react-devtools in a terminal and open Expo Dev Tools). Understand what causes a React component to re-render: props change, state change, context change, parent re-renders. Read the React documentation on performance optimisation.`,

  mastery_questions: [
    `You have a HabitList component that re-renders every second because a parent component has a timer that updates every second. The timer is needed in the parent for a countdown display. The HabitList does not use the timer at all. How do you stop HabitList from re-rendering? Wrap HabitList in React.memo. React.memo does a shallow equality check on props. If the HabitList's props (habits, onToggle) did not change, it skips re-rendering even when the parent re-renders. Ensure the onToggle function is wrapped in useCallback so it has a stable reference — if it is a new function on every render, React.memo sees changed props and re-renders anyway.`,
    `Your HabitList has 1000 items. Scrolling is choppy at 30fps. How do you diagnose and fix this? First, check if each row is doing expensive computation in render (sorting, filtering, string manipulation). Move computation out of render: use useMemo for derived data. Second, check if FlatList items are re-rendering when they should not. Wrap each row in React.memo. Third, add getItemLayout if all rows have the same height — this removes the measurement pass on each row. Fourth, enable removeClippedSubviews={true} cautiously (can cause visual glitches). Fifth, check what is in each row — avoid heavy components (complex nested views, large images) in list items.`,
    `What is the JavaScript thread and why do you not want to block it? The JavaScript thread runs your React renders, event handlers, and business logic. It is a single thread — only one thing runs at a time. If you run a 200ms synchronous computation (sorting 10,000 items, parsing a large JSON blob), the JavaScript thread is blocked for 200ms. During this time, the app cannot respond to touch events — it appears frozen. The UI thread still runs (animations continue), but no new touch events can be processed. Solutions: move heavy computation to a background thread using Web Workers (supported via react-native-threads) or break the computation into smaller chunks with requestAnimationFrame or Promise.resolve().then().`,
    `You are rendering a FlatList of user avatars (circular images). Each avatar is fetched from a URL. Scrolling is slow and images take long to appear. What do you do? Replace the React Native Image component with react-native-fast-image. FastImage uses NSURLCache (iOS) and OkHttp cache (Android) for image caching — images load from cache on scroll, not re-fetched. Also: add a disk cache size limit and use resizeMode='cover' with fixed dimensions. Avoid overly large images — if the avatar displays at 50x50dp, request a 100x100 image (2x for Retina), not the full-resolution 2000x2000 original.`,
  ],

  common_mistakes: [
    `Adding React.memo, useMemo, and useCallback to everything without measuring. Premature optimisation: these tools add code complexity and their overhead (the comparison) can outweigh the benefit for cheap renders. Profile first, then optimise the components that are proven to be slow.`,
    `Calling setState inside a render function or in a loop. This triggers infinite re-renders (setting state causes a re-render which calls render which sets state...). Derive computed values from existing state instead of storing them as separate state.`,
    `Using anonymous functions and object literals in JSX props that are passed to memoised components. <MemoComponent onPress={() => doSomething(id)} config={{ key: value }} /> creates new function and object references on every render, defeating React.memo. Use useCallback for functions and useMemo for objects.`,
    `Heavy synchronous work in the component render function. Sorting, filtering, and complex string operations run every render. Extract to useMemo with the correct dependency array so they only recompute when inputs change.`,
    `Not using a production build for performance testing. Debug builds with the Chrome debugger are 5-10x slower than production builds. Always test performance on a production build (npx expo build or eas build --profile production).`,
  ],

  debug_help: `App is slow but the React Profiler shows no expensive renders: the bottleneck is outside React — network requests, storage operations, or native bridge calls. Use Sentry's performance monitoring or the Flipper Network plugin to identify slow network calls. FlatList is slow even with React.memo on items: check whether keyExtractor is returning a stable key. If it returns the array index, React recreates all items on every data change. Use a unique, stable identifier (habit.id). React.memo is not working (component still re-renders): the props are not shallowly equal. Arrays and objects are compared by reference, not value. If the parent creates a new array on every render (const items = habits.filter(...)), the prop is technically different every time. Memoize the filtered array with useMemo.`,

  ai_assist: [
    `"Profile this React Native FlatList component and identify why it is slow: [paste component]. Point out: components that should be wrapped in React.memo, functions that should be wrapped in useCallback, computed values that should be in useMemo, and FlatList props that should be added for performance (getItemLayout, removeClippedSubviews, initialNumToRender)."`,
    `"Write a React Native FlatList of habit rows that is optimised for 1000+ items. Include: React.memo on the row component, useCallback for the onToggle and onDelete handlers, getItemLayout (all rows are 64dp tall), initialNumToRender: 15, and a custom skeleton list for the initial load state."`,
    `"Explain how to move a heavy computation (sorting and filtering a list of 5000 items with multiple criteria) off the JavaScript main thread in React Native, using a separate thread or chunked processing."`,
  ],

  stretch: [
    `Set up the React Native Flashlist library as a replacement for FlatList. Flashlist is 2-10x faster than FlatList because it recycles native components instead of JavaScript virtual DOM nodes. Migrate the Hydra habit list from FlatList to FlashList and measure the scroll frame rate before and after.`,
    `Write a performance benchmark screen in Hydra's developer settings. Render 1000 habits in a FlatList, measure the time to first render and scroll frame rate. Then enable each optimisation (React.memo, getItemLayout, FlashList) one by one and re-measure. Document the results.`,
    `Profile the Hermes bytecode compilation improvement. Build the app twice: once with hermes: false and once with hermes: true. Measure the app startup time for each (time from native launch to first JS render). The difference is the Hermes benefit.`,
  ],
});

rewriteWeek("mobile-engineering", 18, {
  context: `Mobile accessibility is about building apps that work for the 15-20% of users who have visual, motor, or cognitive disabilities. Screen readers, large text, reduced motion, and switch access are not edge cases — they are features that millions of users depend on daily. App stores increasingly require accessibility compliance, and enterprise app buyers evaluate it in their procurement criteria.

VoiceOver (iOS) and TalkBack (Android) are the built-in screen readers. They read aloud the content and purpose of every UI element as the user navigates with swipe gestures (or on Android, touch exploration). A properly accessible app works completely eyes-free. Test your app with VoiceOver enabled (iOS: Settings > Accessibility > VoiceOver > On, or triple-click the side button). Navigate using swipe right/left to move between elements, double-tap to activate.

The accessibility API in React Native: accessible={true} marks an element as a single accessible unit. accessibilityLabel="Check off morning run" provides the text VoiceOver reads. accessibilityHint="Double tap to check or uncheck" provides additional context. accessibilityRole="button" tells the screen reader what type of element it is ('button', 'checkbox', 'header', 'image', 'text', 'link'). accessibilityState={{ checked: isCompleted }} communicates state.

Accessible names: if an element has only an icon (no text label), it is invisible to screen readers without an accessibilityLabel. A button with a trash icon and no label is announced as "image" or nothing. Add accessibilityLabel="Delete habit" to icon-only buttons.

Text scaling: users set a preferred text size in OS settings. On iOS, this affects all apps that use Dynamic Type. React Native Text components scale with system font size by default. Test at the largest text size (Settings > Accessibility > Display & Text Size > Larger Text > max). Layout must not break — buttons must stay tappable, text must not be clipped.

Reduced motion: some users experience vestibular disorders and get motion sickness from animations. iOS and Android have a "Reduce Motion" setting. Read it with AccessibilityInfo.isReduceMotionEnabled() and disable or simplify animations for these users.`,

  pre_flight: `Enable VoiceOver on your iPhone (Settings > Accessibility > VoiceOver) and navigate through Hydra without looking at the screen. Note every element that is confusing or silent. Enable the largest text size and check every screen for layout breaks. Install the Accessibility Inspector on macOS (comes with Xcode, in Xcode > Open Developer Tool > Accessibility Inspector) — it shows the accessibility tree of a simulator.`,

  mastery_questions: [
    `You have a habit row component. VoiceOver reads "Morning run, image, button, button" — the user hears four separate things when they swipe through the row. What should it say and how do you fix it? It should say "Morning run, completed, double tap to toggle" (one thing). Wrap the entire row in a View with accessible={true}. The accessible prop makes the view a single accessibility element — VoiceOver treats it as one unit. Add accessibilityLabel="Morning run" and accessibilityState={{ checked: isCompleted }}. Add accessibilityHint="Double tap to toggle completion". With this setup, VoiceOver reads the whole row as one element with complete information.`,
    `Your app has a 30-second animation on the onboarding screen. The user has "Reduce Motion" enabled. What should happen? Read the reduce motion preference: const reduceMotion = await AccessibilityInfo.isReduceMotionEnabled(). If true, skip the animation entirely (or show a static version). You can subscribe to changes: AccessibilityInfo.addEventListener('reduceMotionChanged', handler). Use this to conditionally apply animation: the animation should not be the only way to convey information — users with reduce motion enabled should get the same information through text or static content.`,
    `A user navigates to the HabitDetail screen. VoiceOver announces "HabitDetail" (the screen name). The user does not know what is on the screen. How do you fix this? Add a screen title announcement on screen mount: AccessibilityInfo.announceForAccessibility("Morning Run detail. 7-day streak. 14 completions this month."). This fires a VoiceOver announcement when the screen loads, giving the user context without them having to swipe through every element. Also ensure the first focusable element on the screen has a meaningful label.`,
    `Your app has a custom checkbox component. The user taps it to toggle. VoiceOver says "button" when focused but does not announce the checked/unchecked state. How do you fix it? Add accessibilityRole="checkbox" and accessibilityState={{ checked: isCompleted }}. VoiceOver announces "Checked, checkbox" or "Unchecked, checkbox" based on the state. When the user double-taps to toggle, VoiceOver announces the new state. Without accessibilityState, the user cannot tell the current state without reading the visual indicator — which they cannot see.`,
  ],

  common_mistakes: [
    `Using View instead of Text for text content. Screen readers skip non-text Views by default. Wrap all text content in Text components. Use accessibilityLabel on Views that must be announced.`,
    `Icon-only buttons with no accessibilityLabel. A delete button with only a trash icon is announced as "image" by VoiceOver. Add accessibilityLabel="Delete habit" to every icon-only interactive element.`,
    `Marking decorative images as accessible. Images that add no information (decorative dividers, background patterns) should have accessible={false} so screen readers skip them.`,
    `Not testing with actual screen reader users or at least with the screen reader yourself. Accessibility code that was never tested with VoiceOver is accessibility code that probably does not work. Test it yourself — navigate through every screen with VoiceOver before shipping.`,
    `Forgetting to group related elements. A form with a label above an input is two separate accessible elements — the screen reader reads "Name" then "text field" without connecting them. Use accessibilityLabel on the TextInput to include the label: accessibilityLabel="Name, text field".`,
  ],

  debug_help: `VoiceOver reads element names you cannot find in the code: the system may be reading the children's text content automatically. Use the Accessibility Inspector to see exactly what VoiceOver reads for each element and trace it to the component. "accessibilityLabel is not read": if the element has children with text, React Native may ignore accessibilityLabel and read the children instead. For grouping with a custom label, use accessible={true} to collapse children into one element. Large text breaks layout: find which container has a fixed height that clips text. Replace fixed heights with minHeight and ensure paddingVertical instead of fixed height. Reduce motion changes not detected: AccessibilityInfo.addEventListener('reduceMotionChanged') may not fire on some Android versions. Check the current value on every mount: AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion).`,

  ai_assist: [
    `"Audit this React Native habit row component for accessibility: [paste component]. Identify: missing accessibilityLabel on icon buttons, missing accessibilityRole, missing accessibilityState for the checkbox, and any elements that should be grouped. Provide the corrected component."`,
    `"Write a custom accessible checkbox component for React Native. It should: announce 'checked' or 'unchecked' state to VoiceOver, support double-tap to toggle, have a visible focus ring when navigated to with a keyboard/switch, and respect reduced motion (no animation if reduce motion is enabled)."`,
    `"Write a reduce motion hook for React Native that reads AccessibilityInfo.isReduceMotionEnabled() on mount and subscribes to changes. Return { reduceMotion: boolean }. Show how to use it in a component that conditionally applies animation."`,
  ],

  stretch: [
    `Conduct a full VoiceOver audit of Hydra. Enable VoiceOver, navigate through every screen using only swipe gestures, and document every accessibility issue found. Fix each issue. Repeat until every screen can be navigated completely without seeing the screen. This is the test that matters.`,
    `Add switch access support. Switch access allows users who cannot use a touchscreen to navigate with a single or dual switch (a button that cycles through elements). In React Native, this works through the accessibility focus system. Test that your app's focus order is logical (left-to-right, top-to-bottom) and that no elements are unreachable.`,
    `Submit a TestFlight beta to a blind user (contact accessibility testing communities like AppleVis) for a 15-minute usability test. The feedback from a daily screen reader user is invaluable and will reveal issues that sighted developers testing VoiceOver cannot anticipate.`,
  ],
});

rewriteWeek("mobile-engineering", 19, {
  context: `Internationalisation (i18n) is preparing your app to support multiple languages, regions, and locales. Localisation (l10n) is adapting the app for a specific locale. Most apps need both if they are targeting international markets. Even for English-only apps, you should understand date, number, and currency formatting differences.

i18n-js and i18next are the standard libraries. They manage translation strings, handle pluralisation rules (English: 1 item, 2 items; Arabic: has 6 plural forms), interpolate variables into translated strings, and fall back to a default language when a translation is missing.

Translation files: you maintain one JSON file per locale, with the same key structure. en.json: { "habit_count": "{{count}} habits" }, ar.json: { "habit_count": "{{count}} عادة" }. Your code references keys, never hardcoded strings: t('habit_count', { count: habits.length }).

Locale detection: on mobile, the device locale (the language/region the user has set in their OS settings) is available from expo-localization. Expo.getLocales() returns an ordered list of the user's preferred locales. Use the first one as your app's locale if it is supported, otherwise fall back to your default.

Number and currency formatting: 1,234.56 in the US is 1.234,56 in Germany and 1 234,56 in France. Use Intl.NumberFormat (built into the JavaScript engine) with the locale: new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(1234.56). Never hardcode number separators.

Date and time formatting: July 4 is 4 Juli in German, 4 luglio in Italian. Use Intl.DateTimeFormat for localised date strings. Also consider: some locales use right-to-left (RTL) text direction — Arabic, Hebrew, Persian. React Native has RTL support (I18nManager.forceRTL) but it requires testing and thoughtful layout decisions (margins and paddings swap, icon positions swap, text alignment changes).`,

  pre_flight: `Install expo-localization: npx expo install expo-localization. Install i18next and react-i18next: npm i i18next react-i18next. Create locale JSON files for at least 2 languages. Read the i18next quickstart. Understand what ICU message format is (a standard for expressing plurals and variables in translation strings). Know how to change the language in iOS Simulator: Settings > General > Language & Region.`,

  mastery_questions: [
    `You have the string "You have completed 1 habit today." When there are 2 habits, it should say "2 habits." When 0, "0 habits." How do you handle this with i18next? Use i18next's pluralisation. In your translation file: { "habits_completed": "You have completed {{count}} habit today", "habits_completed_plural": "You have completed {{count}} habits today", "habits_completed_zero": "You have not completed any habits today" }. In your code: t('habits_completed', { count: completedCount }). i18next selects the correct key based on the count and the locale's pluralisation rules. In English, _zero overrides count=0, _plural applies to count>=2. In a language with 6 plural forms (Arabic), you would provide 6 keys.`,
    `A user's device is set to Arabic. Your app switches to RTL layout. What specific layout changes are needed? The flex direction of row layouts reverses: flexDirection: 'row' goes right-to-left. Icons that indicate direction (back arrow, forward arrow) should be mirrored. Text alignment changes from left to right by default. Margins and paddings that provide left/right spacing should use marginStart and marginEnd (RTL-aware) instead of marginLeft and marginRight. React Native's I18nManager.isRTL is true when RTL is active — use it to conditionally reverse directional icons.`,
    `How do you format a currency amount that works correctly for any locale? Use Intl.NumberFormat with the currency option: const formatter = new Intl.NumberFormat(locale, { style: 'currency', currency: 'USD' }); formatter.format(amount). The result is locale-appropriate: "$1,234.56" in en-US, "1.234,56 $" in de-DE. Never format currencies manually with string concatenation — the symbol position, decimal separator, and grouping separator all vary by locale.`,
    `You want to show "2 days ago" in the user's language. How do you localise relative time? Use Intl.RelativeTimeFormat: new Intl.RelativeTimeFormat(locale, { numeric: 'auto' }).format(-2, 'day'). Returns "2 days ago" in en-US, "vor 2 Tagen" in de-DE, "hace 2 días" in es-ES. Calculate the relative amount (the difference in days, hours, etc.) in your business logic, then format it with the locale. For "2 days ago" vs "yesterday" vs "just now", choose the appropriate unit (second, minute, hour, day) based on the magnitude of the difference.`,
  ],

  common_mistakes: [
    `Hardcoding strings directly in component code. Every string must come from the translation file. Run a linter rule or code review checklist to catch hardcoded strings. Even error messages, placeholder text, and button labels must be translated.`,
    `Not extracting all strings before shipping the first translated version. Going back to extract strings from existing code is painful. Extract strings as you build features — it takes only slightly more time and avoids a large extraction effort later.`,
    `Assuming all locales use left-to-right text and the same calendar. Some locales use RTL (Arabic, Hebrew). Some locales use non-Gregorian calendars (Persian solar calendar, Hebrew calendar). If your app shows dates, use Intl.DateTimeFormat with the locale and calendar option rather than manual formatting.`,
    `Not testing with pseudolocalisation. Before you have real translators, use a pseudolocalisation tool that transforms your strings to a fake locale (e.g., "Hello" becomes "[Ĥëłłö]" with random character expansion). This reveals strings you forgot to translate (they appear in English) and layout issues (pseudolocalised strings are 30% longer, testing text overflow).`,
    `Not providing translation context to translators. A key like "view" could be the noun (a view) or the verb (to view). Translators need context. Add comments to your translation files explaining where each string is used.`,
  ],

  debug_help: `i18next returns the key instead of the translation: the translation file is not loaded or the key does not exist. Check that the namespace and language are configured correctly. Add i18next's debug: true option to log missing keys to the console. RTL layout not working: call I18nManager.forceRTL(true) and restart the app (not just reload JS). RTL changes require a full app restart. Check that you are using flexDirection: 'row-reverse' or marginStart/marginEnd instead of marginLeft/marginRight for RTL-affected layouts. Intl not available: older React Native versions with JSC (not Hermes) had limited Intl support. Hermes includes full Intl support. If you are on an older setup, install intl and @formatjs/intl-pluralrules as polyfills.`,

  ai_assist: [
    `"Set up i18next in a React Native Expo app with two locales: en and fr. Use expo-localization to detect the device locale and set the initial language. Create translation files for: habit list title, habit completion count (with pluralisation), and empty state message. Show how to use the t() function in components."`,
    `"Write a useLocale hook for React Native that: reads the device locale from expo-localization, returns { locale, language, isRTL }, updates when the app comes to the foreground (language might have changed), and provides a currency formatter and date formatter using Intl that respect the locale."`,
    `"Show how to handle RTL layout in a React Native habit row. The row has: an icon on the left, the habit name, and a checkbox on the right. In RTL mode, the icon should be on the right and the checkbox on the left. Use I18nManager.isRTL and flexDirection to handle both layouts."`,
  ],

  stretch: [
    `Add three languages to Hydra: English, French, and Arabic (RTL). Use a real translator (DeepL API or a native speaker from your network) for the French translation, not machine translation alone. Test the Arabic layout thoroughly — every screen must look correct in RTL.`,
    `Implement in-app language switching. Add a language picker in Settings that lets the user override the device language. Store the preference in MMKV. Reload the app (or the relevant screens) when the language changes. This is complex because React Native's RTL setting requires a full app restart to take effect.`,
    `Extract all Hydra strings and submit them to Crowdin (a translation management platform with a free tier) for community translation. Share the Crowdin project link publicly. See how many volunteer translators contribute. This is how many popular open source apps get translated into 40+ languages.`,
  ],
});

rewriteWeek("mobile-engineering", 20, {
  context: `Testing mobile apps is harder than testing web apps. You have two platforms (iOS and Android), two test environments (simulator and device), hardware variations, OS version fragmentation, and device-specific behaviours. A test strategy that ignores this complexity will miss platform-specific bugs. A test strategy that tries to cover everything will be too slow to run.

Unit testing in React Native uses Jest (bundled with Expo). Pure functions (streak calculation, date formatting, validation logic) are easy to test with Jest — they have no dependencies on React Native or the device. Test these aggressively. For React components, use @testing-library/react-native — it renders components in a virtual environment and allows querying by accessible labels, text, and roles.

Component tests with @testing-library/react-native: use getByRole, getByLabelText, and getByText to find elements (the same queries used by screen readers — which also confirms accessibility). Use fireEvent to simulate user interactions. Use waitFor to handle async operations. These tests run in Node without a device and are fast.

Mocking native modules: most React Native native modules cannot run in Jest's Node environment (they call native code). Mock them: jest.mock('expo-secure-store', () => ({ getItemAsync: jest.fn(), setItemAsync: jest.fn() })). Expo provides a jest-preset that mocks many Expo modules automatically. Use jest-expo preset in your Jest config.

End-to-end testing with Detox: Detox runs a real app on a simulator/device and drives it like a user (tap, type, swipe). It uses a grey box approach — it knows when your app is idle (no JS work pending, no animations running) and only proceeds when the app is ready. This makes Detox tests significantly more stable than naive timeout-based E2E tests. Detox is complex to set up but essential for testing critical user flows (sign up, first habit creation, subscription).

Test coverage strategy: unit tests for all business logic, component tests for interactive components (forms, lists), integration tests for screens that involve navigation and API calls (mocked), and Detox E2E for 3-5 critical user journeys. Do not aim for line coverage — aim for critical path coverage.`,

  pre_flight: `Install jest-expo: npm i -D jest-expo. Install @testing-library/react-native: npm i -D @testing-library/react-native. Configure Jest: add "preset": "jest-expo" to package.json. Install Detox: npm i -D detox @types/detox. Read the Detox getting started guide (the setup is lengthy). Run npx jest to verify the Jest setup works. Write a trivial test to confirm.`,

  mastery_questions: [
    `You want to test that when the user checks off a habit, the streak count increments. How do you write this as a component test? Render the HabitList component with jest-expo mocks. Use waitFor and fireEvent.press to simulate tapping the habit row. Assert that the streak counter text updates to the expected value. You must mock: the SQLite database (return test data from mock queries), the MMKV store (return mock settings), and expo-notifications (mock schedule functions). The test verifies the UI behaviour — not the database writes (those are tested separately in a service layer unit test).`,
    `You have a Detox E2E test that checks the onboarding flow. It fails intermittently — sometimes it passes, sometimes it times out waiting for an element. What are the most common causes? Race conditions: the test taps before the screen has finished animating or loading. Detox's waitFor handles most of this, but complex animations or async operations can cause issues. Fix: add more explicit waitFor calls. If a navigation transition is animated, wait for the destination screen to be visible before asserting. Also: simulator performance varies. CI runners are slower than developer machines — add a buffer. Flaky tests: investigate each failure individually. A flaky test is a bug in your test — fix it.`,
    `You have a hook that fetches habits from SQLite on mount. How do you test this hook in isolation? Use @testing-library/react-hooks (or renderHook from @testing-library/react-native). Mock expo-sqlite: jest.mock('expo-sqlite', () => ({ openDatabaseAsync: jest.fn().mockResolvedValue({ getAllAsync: jest.fn().mockResolvedValue([{ id: 1, name: 'Test habit' }]) }) })). Render the hook with renderHook(() => useHabits()). Wait for the state to update: await waitFor(() => expect(result.current.habits).toHaveLength(1)). Assert the habits array contains the expected data.`,
    `What is the difference between shallow rendering and deep rendering in component tests, and which should you prefer? Shallow rendering renders a component but replaces child components with stubs (it does not recurse into children). Deep rendering renders the full component tree. @testing-library/react-native uses deep rendering by default and discourages shallow rendering. The reason: shallow rendering tests implementation details (what components you chose to use as children) rather than behaviour (what the user sees and can do). Deep rendering is closer to what the user experiences. The counterargument for shallow rendering (speed) is largely moot with modern hardware.`,
  ],

  common_mistakes: [
    `Testing implementation details instead of behaviour. Asserting that a specific function was called (spying on internals) makes tests brittle — they break when you refactor the implementation without changing the behaviour. Test what the user sees and can do.`,
    `Not mocking native modules in Jest. If a module calls native code and is not mocked, Jest throws "module not found" or a native call fails. Use jest-expo preset which mocks many Expo modules, and manually mock any additional native modules your code uses.`,
    `Writing E2E tests for every user journey. E2E tests are slow and brittle. Write them only for the 3-5 most critical flows (signup, first habit, subscription). Use component tests and unit tests for everything else.`,
    `Not running tests in CI. Tests that only run locally are optional suggestions. All unit and component tests must run on every PR. E2E tests can run on a nightly schedule or on merges to main.`,
    `Snapshot testing over-use. React Native's toMatchSnapshot() is useful for catching unexpected UI regressions on simple components. On complex components, it creates large brittle snapshots that fail on any visual change (even intentional ones). Use snapshot tests sparingly.`,
  ],

  debug_help: `Jest fails with "Cannot find module 'react-native'": ensure jest-expo preset is configured in package.json. The preset resolves React Native modules correctly. "NativeModule X is null" in tests: the native module is not mocked. Add a manual mock: create __mocks__/expo-sqlite.js with a jest.fn() implementation. Detox cannot connect to the app: the app is not built for Detox. Run detox build --configuration ios.sim.debug before running tests. Detox test times out waiting for element: the element is not visible (it may be off-screen). Use element(by.id('habit-1')).scrollTo('bottom') to scroll to it, or check whether the element's accessibility label matches what Detox is looking for. @testing-library/react-native finds no elements: use getByRole with the correct role, or getByText with the exact text. Use screen.debug() to print the rendered output and see what is there.`,

  ai_assist: [
    `"Write Jest unit tests for the Hydra streak calculation function. The function takes an array of completion date strings and returns the current streak count. Test: empty array returns 0, streak of 1 (only today completed), streak of 5 (5 consecutive days), streak broken (gap in days), streak considering yesterday (habit not yet done today), and streak not counting today's incomplete habits."`,
    `"Write a @testing-library/react-native component test for the HabitRow component. The test should: render the component with a habit object, verify the habit name is displayed, simulate tapping the checkbox, verify the onToggle function is called with the habit id, verify the checked state is reflected in the accessibility state."`,
    `"Write a Detox E2E test for the Hydra first-run flow: launch the app, dismiss the welcome screen, tap 'Add your first habit', type a habit name, tap 'Save', verify the habit appears in the list, and tap it to check it off."`,
  ],

  stretch: [
    `Set up Detox in your CI pipeline (GitHub Actions). Use the macOS large runner for iOS Detox tests (the regular ubuntu runner cannot run iOS simulators). Configure the workflow to: build the Detox release configuration, start the iOS simulator, run the Detox test suite, and report results.`,
    `Write property-based tests using fast-check for the streak calculation. Property: for any valid array of completion dates, the streak is always between 0 and the number of days in the array. Property: adding a new consecutive completion date always increases the streak by 1. Property: removing a day from the middle always breaks the streak. This catches edge cases your manually-written tests miss.`,
    `Add visual regression testing with Detox. After running a Detox test, capture a screenshot: await device.takeScreenshot('habits-checked'). Compare to a baseline screenshot and fail if they differ by more than a threshold. This catches CSS-like regressions where the layout changes unexpectedly.`,
  ],
});
