/**
 * v2 rewrite batch 4: data-science Weeks 18-22
 *  W18: Reddit Sentiment v0.4 — Live dashboard
 *  W19: Reddit Sentiment v0.5 — REST API + Docker
 *  W20: Reddit Sentiment v1.0 — Ship + retro
 *  W21: Project 3 — Energy Forecast v0.1 (exploratory analysis)
 *  W22: Energy Forecast v0.2 — ARIMA model
 */

import { rewriteWeek } from "../rewrite-week";

// ─── W18 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 18, {
  context: `Last week you balanced your dataset three different ways and wrote a reflection on when synthetic data helps and when it quietly makes things worse. All of that work was still offline -- static files, local notebooks, results that only you could see in your own terminal.

This week the model goes live. One button press pulls the 50 most recent posts from your chosen subreddit, runs them through the fine-tuned DistilBERT you trained in week 15, and shows you a real-time sentiment breakdown -- how the community actually feels right now, not from last month's training data.

The platform is Streamlit, which you have touched before for static charts. This week it earns its keep. You will use st.session_state to remember results between button clicks without re-running the whole app from scratch. You will use st.columns to put the sentiment distribution chart next to the most strongly opinionated posts. And you will use st.cache_data to avoid hitting the Reddit API on every refresh. That caching step matters more than it sounds -- Reddit's API throttles aggressive clients, and an app that ignores rate limits returns errors that look like your model is broken when the issue is actually your fetch logic.

There is one piece of infrastructure that makes this week non-trivial: loading a fine-tuned PyTorch model inside a running Streamlit app. Your DistilBERT checkpoint is roughly 250MB on disk. If you load it inside a button callback, the app spends 20 to 30 seconds frozen on every click. The fix is to load it once at startup, outside any callback, and cache it with st.cache_resource. This is inference in production -- the same pattern that Hugging Face's Inference API, AWS SageMaker endpoints, and every ML deployment you will encounter at a company runs under the hood.

The time-series snapshot is the part most people skip and should not. Every time you pull from Reddit, you append a row to a CSV: timestamp, subreddit, positive count, negative count, neutral count. By next Sunday you will have seven days of those rows and be able to plot whether sentiment around your subreddit is trending up or down. That question -- "compared to when?" -- is what every stakeholder asks and most dashboards cannot answer. By Sunday the app is live at a public URL, the CSV is growing in your repo, and you can demo the whole thing in two minutes to someone who has never opened a Jupyter notebook.`,

  pre_flight: `Before you write any Streamlit code, sketch the layout on paper. Two columns or one? Where does the fetch button live? What does the page show when no fetch has happened yet -- blank, a spinner, cached results from last run? Writing this down takes 5 minutes and saves an hour of rearranging st.columns calls. Also: pull 5 posts manually from your subreddit's public JSON endpoint (reddit.com/r/MachineLearning/new.json -- it is just a URL) and look at the raw response. The field names are not intuitive, and knowing the shape before coding prevents the first hour of KeyErrors.`,

  mastery_questions: [
    `Load your fine-tuned DistilBERT with AutoModelForSequenceClassification.from_pretrained('./distilbert-reddit-sentiment'). Wrap the call in an @st.cache_resource function and paste both the decorator and the function body. Time the cold load with time.time() before and after -- it should be 10 to 30 seconds depending on disk speed. Skip the decorator and Streamlit reloads the full model on every user interaction. Hugging Face's Inference API and every production ML service keep models resident in memory for exactly this reason. Now call model.eval() after loading and write one sentence explaining why eval mode matters at inference time -- specifically what it turns off that should not be active when you are making predictions.`,
    `Click your "Fetch latest posts" button twice in a row without session_state. Streamlit reruns the full script top-to-bottom on each click, wiping the previous results while new ones load. Add st.session_state['results'] to persist the last fetch, and check 'results' in st.session_state before overwriting. Paste the relevant lines. Then write one sentence about whether your dashboard is stateful (shows the previous results while fetching) or stateless (replaces results on every click) -- and why you made that choice. Both are valid designs; the reasoning is what matters.`,
    `Wrap your Reddit fetch function in @st.cache_data(ttl=300). Paste the decorated function signature and the first line of the body. Now: what actually happens without this? Reddit's API limits unauthenticated requests to roughly 10 per minute. A Streamlit app with 3 users each hitting refresh would exhaust that quota in 2 minutes and start returning empty results -- which breaks your chart in ways that look like model failures. Also confirm you are handling the case where the API returns an error or an empty list: a silent failure here will make your dashboard show a frozen-zero distribution that looks like legitimate data.`,
    `After each successful fetch, append a row to snapshots.csv with these columns: timestamp, subreddit, n_positive, n_negative, n_neutral, total_posts. Use pd.DataFrame(...).to_csv(..., mode='a', header=False, index=False). Paste three sample rows. Now add an st.line_chart showing the proportion of positive posts across your stored snapshots. Even two days of data shows variation. Bloomberg terminals, brand sentiment platforms, and social monitoring tools all solve the "compared to when?" question the same way: keep the row-level snapshots and compute the trend from them.`,
    `Run your live dashboard for at least one real session and find a moment where the sentiment distribution surprises you -- a spike of negative on a normally calm subreddit, or a batch of posts scored neutral that you can see from reading them are not. Describe or paste the distribution numbers at that moment. Then pick the 3 posts your model scored most confidently that you think it got wrong. For each, write one sentence about what the model missed -- a specific word, a specific context, a specific gap in the training data. Twitter's trust-and-safety teams run this exact exercise after every major moderation event. The model's confident mistakes are the most useful thing it can show you.`,
  ],

  common_mistakes: [
    `Putting model.from_pretrained inside a button callback instead of at the top level with @st.cache_resource. The first click takes 30 seconds, users assume the app is broken, and you spend an hour debugging what is actually just a slow cold load.`,
    `Not calling model.eval() before inference. During training, dropout randomly zeroes activations -- same input, different output each forward pass. Without eval(), your model returns slightly different sentiment scores every time you click Fetch, which looks like model instability but is expected training behaviour left on by accident.`,
    `Forgetting to handle Reddit's rate-limit response (HTTP 429). The praw library raises prawcore.exceptions.RequestException; raw requests return a 429 with a Retry-After header. If you do not catch it, the app crashes silently and shows an empty chart.`,
    `Appending to the CSV without checking if it exists first. On first run, you want the header row. On subsequent runs, use mode='a', header=False. Use os.path.exists() or pd.DataFrame.to_csv with conditional header logic -- otherwise you end up with a CSV that has the header row embedded 40 rows in.`,
    `Using st.rerun() inside a cached function. st.cache_data and st.cache_resource functions are meant to be pure (no side effects). Calling st.rerun() inside one causes an infinite rerun loop that crashes the app with no useful error message.`,
  ],

  debug_help: `Two errors you will almost certainly see. First: "OSError: Can't load tokenizer for './distilbert-reddit-sentiment'." The tokenizer files (vocab.txt, tokenizer_config.json) were not saved alongside the model weights. Fix: in your week-15 notebook, also run tokenizer.save_pretrained('./distilbert-reddit-sentiment') and commit those files to the repo. Second: "StreamlitAPIException: st.cache_resource function returned None." Your cached function hit an exception during model load and returned None silently. Wrap the load in a try/except and log the error explicitly -- Streamlit swallows exceptions inside cached functions unless you surface them yourself. For the Reddit fetch, the quiet failure is praw returning an empty generator when the subreddit has no recent posts matching your filter -- check len(posts) > 0 before scoring.`,

  ai_assist: `Use Claude to generate the Streamlit layout boilerplate (two-column structure, fetch button, session_state skeleton) -- it is plumbing you should write once and move past. The part not to outsource: the logic that decides what counts as a "confident prediction" for display purposes. Should you filter out low-confidence scores from the sentiment distribution? At what threshold? That decision changes what your dashboard is measuring, and only you can make it based on your week-16 SHAP analysis of where the model is and is not reliable.`,

  stretch: [
    `Add a "compare two subreddits" mode: two fetch buttons side-by-side, two sentiment distributions shown simultaneously. The diff between r/MachineLearning and r/learnmachinelearning is more informative than either alone.`,
    `Write a one-page product spec for Reddit Sentiment v0.4 as if you were pitching it internally at a social analytics company. What is the use case? Who is the user? What is missing before it could be a paid feature? Writing the spec surfaces gaps the code does not.`,
    `Set up a GitHub Action that runs the fetch-and-snapshot logic on a cron schedule (every 6 hours) without the Streamlit UI. The CSV grows automatically even when nobody visits the dashboard.`,
  ],
});

// ─── W19 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 19, {
  context: `Last week your Streamlit app loaded a 250MB model at startup and scored posts inside the same Python process that was rendering the UI. That works fine for a side project with one user. It breaks when you try to add a second frontend -- a mobile app, a scheduled job, another team's tool -- because they all need to import your model too, or worse, copy it.

The answer is to separate concerns. One service holds the model and does the scoring (the API). One or more clients talk to it over HTTP (the Streamlit frontend, the mobile app, whatever comes next). This week you make that split. A FastAPI backend with a POST /predict endpoint. Pydantic to validate incoming payloads before they touch the model. Your Streamlit frontend updated to send HTTP requests instead of running inference directly. Then you package the backend in a Docker container and deploy it to Hugging Face Spaces, which gives you a free persistent inference endpoint.

FastAPI is worth understanding properly. It is the most-used Python API framework at serious ML companies right now -- Weights & Biases and Hugging Face both use it internally, and most ML serving layers are built on top of it or similar ASGI frameworks. The Pydantic validation layer is not an optional nicety; it is the mechanism that catches a client sending a string where a list of strings was expected, before that bad input reaches your model and produces a confusing error 10 layers deep.

Docker is the other non-optional piece. Your model runs on your laptop with a specific Python version, specific torch version, specific transformers version. Without Docker, "works on my machine" is a guarantee you cannot keep. The Dockerfile for this week is about 15 lines. Understanding what each line does -- base image, dependency installation, the CMD that starts the server -- is what separates someone who can use Docker from someone who can deploy with it reliably.

By Sunday: a live FastAPI endpoint on Hugging Face Spaces that accepts a list of Reddit post strings and returns sentiment labels and confidence scores. A Streamlit frontend that calls it via HTTP. A Dockerfile committed to the repo. And a clear mental model of why this split matters for every ML project you will build after this one.`,

  pre_flight: `Before you write any FastAPI code, write the POST /predict endpoint contract in plain English. What does it accept -- a list of strings? A JSON object with a "posts" key? A maximum item count? What does it return -- a list of labels? Label plus confidence score per post? Agreeing on this contract before writing code is what API design actually is. The 10 minutes you spend on it now prevents the silent mismatch between what your Streamlit sends and what FastAPI expects.`,

  mastery_questions: [
    `Write your FastAPI app with a POST /predict endpoint. The request body should be a Pydantic model: class PredictRequest(BaseModel): posts: list[str]. Paste the full endpoint definition, including the Pydantic model and the return type annotation. Now test it with curl or the auto-generated docs page at http://localhost:8000/docs. What happens if you send a payload missing the "posts" key entirely? Paste the error response. That structured validation error -- returned before your code runs -- is exactly why production APIs use Pydantic.`,
    `Load your DistilBERT model inside a FastAPI lifespan function (the current recommended approach, replacing the deprecated @app.on_event("startup")). Paste the lifespan code. Why does model loading go in lifespan rather than at the top level of the module? (Hint: top-level code runs at import time, which matters when gunicorn spawns multiple workers -- each worker loads the model separately on startup.) For a 250MB model, that detail is the difference between a deployment that starts in 30 seconds and one that takes 3 minutes.`,
    `Write the Dockerfile for your FastAPI backend. Paste every line. Each should make sense: FROM python:3.11-slim (not full python -- smaller image), COPY requirements.txt and RUN pip install (separate layer so dependencies cache between builds), COPY the app code (last layer -- changes most often), CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]. Port 7860 is what Hugging Face Spaces expects. Run docker build locally first and confirm docker run -p 7860:7860 starts without errors before pushing.`,
    `Deploy the Docker container to Hugging Face Spaces. Paste the Space URL and an example curl call to your live endpoint. Now update your Streamlit app to call the API via requests.post() instead of running inference locally. Paste the updated fetch function. Time the round-trip: how many milliseconds does an HTTP call to your HF Space take compared to local inference? The latency is usually 200-600ms from most locations -- acceptable for a dashboard, too slow for a real-time chat application. Knowing your specific number is the point.`,
    `Send your live API three edge-case inputs: one post containing only an emoji, one with non-ASCII characters, and one that is 2000 characters long (longer than DistilBERT's 512-token limit). Paste what happened in each case. The 512-token truncation is silent by default -- the tokenizer truncates without warning, which means the model scored the first 512 tokens and ignored the rest. For Reddit posts this is usually fine; for legal documents or financial filings it is not. Add a check that flags truncated inputs to the caller instead of silently truncating.`,
  ],

  common_mistakes: [
    `Using 127.0.0.1 as the uvicorn host inside the Dockerfile. The API starts but Docker routes traffic to localhost inside the container, which nothing outside the container can reach. Always use 0.0.0.0 as the host in the CMD.`,
    `Putting the model load inside the predict endpoint function rather than in lifespan. Cold-start time on every request -- 20 to 30 seconds. The endpoint appears to work in local testing (you wait) but fails in production (callers time out at 5 or 10 seconds by default).`,
    `Not pinning dependency versions in requirements.txt. transformers==4.40.0, not transformers. A Spaces deploy 6 months from now will pull a newer version that may break your model load silently, with no obvious connection to what changed.`,
    `Forgetting to include the model checkpoint files in the repo before deploying. The Dockerfile copies your code; if the model weights are in .gitignore (common because they are large), the deployed container has no model to load and fails at startup with a confusing FileNotFoundError.`,
    `Calling requests.get() instead of requests.post() from the Streamlit frontend. GET requests have no body -- your payload silently disappears and FastAPI returns a 422 validation error that looks like a server bug.`,
  ],

  debug_help: `Three specific errors. First: "422 Unprocessable Entity" from FastAPI means the request body failed Pydantic validation -- usually a missing field or wrong type. The /docs page lets you test the endpoint interactively and shows the exact validation error, which is faster than reading raw curl output. Second: "ConnectionRefusedError" from Streamlit calling the API means either FastAPI is not running, or you used 127.0.0.1 as the host in Docker (see common mistakes). Third: "RuntimeError: CUDA error: no kernel image" on Hugging Face Spaces. The free tier uses CPU only -- call model.to('cpu') and move tokenizer inputs to CPU before inference. A model trained on GPU but served on CPU needs explicit device handling.`,

  ai_assist: `Use Claude to generate the Pydantic models for your request and response types -- it is mechanical and Claude does it correctly. Also use it to explain what each line of your Dockerfile does, especially the difference between RUN pip install and COPY and why their order matters for Docker's layer cache. The thing not to outsource: the lifespan function. The startup and shutdown lifecycle is the part most developers get wrong in production, and working through it yourself is worth the 20 minutes.`,

  stretch: [
    `Add a GET /health endpoint that returns {"status": "ok", "model_loaded": true}. Hugging Face Spaces and every load balancer in production pings this to confirm the service is alive before routing traffic to it.`,
    `Add request logging to your FastAPI app: middleware that logs the method, path, and response time in milliseconds for every request. After 24 hours of real traffic, look at the distribution. Slow outliers are usually your long posts hitting the 512-token truncation boundary.`,
    `Rate-limit your /predict endpoint using slowapi (one of several options). Without it, one user can send 1000 requests per second and crash your free Space. One decorator, professional-grade protection.`,
  ],
});

// ─── W20 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 20, {
  context: `You have been building Reddit Sentiment since week 12. Hand-labelled training data in week 13. Statistical rigour in week 14. Fine-tuned DistilBERT in week 15. SHAP interpretability in week 16. Synthetic data in week 17. A live dashboard in week 18. A production API in week 19. Eight weeks of work. This week you ship it -- by which I mean you do the thing most engineers skip: you write about it.

The blog post is the deliverable. Not because writing "looks good" somewhere, but because it forces you to confront the gaps in your understanding that working code hides. You cannot write a clear sentence about why you chose TF-IDF + LogReg before DistilBERT without actually knowing the reason. You cannot explain the A/B test without re-understanding statistical power. The writing is also where you discover that you changed direction three times, which is worth documenting because interviewers ask "walk me through your process" and the honest answer -- with the pivots named -- is more interesting than a polished retrospective narrative.

The demo video is three to five minutes. Screen recording, voice-over, no editing required. You open the live dashboard, click "Fetch latest posts," watch the sentiment scores populate, pull up a SHAP explanation for one post, and walk through what the model is doing. The purpose is to prove the thing works -- not to an interviewer in theory, but to a stranger on video who can pause and rewind.

Stranger-verified means exactly what it sounds like: you share the dashboard URL with someone who has not seen this project and watch them use it without you explaining anything. What confuses them is what needs a label or a tooltip. What they click first tells you what your layout implies. This is the feedback loop that product teams run -- the name for it is user testing, but when it is one person and a Zoom screen share it is also just watching a friend be confused in instructive ways.

By Sunday: a published blog post, a 3-5 minute demo video linked from the README, and a RETRO.md in your repo that names three things you would do differently if you started over. The retro is not for show -- it is for you, and it is the fastest way to consolidate what eight weeks of work actually taught you.`,

  pre_flight: `Before you write the blog post, write one honest paragraph first -- not for publication. Three sentences: what went better than expected, what took much longer than estimated, what you would skip if you started today. This private draft is what makes the published post accurate. Most polished project write-ups omit the things that went wrong, which makes them useless as learning artefacts for the next person who attempts the same project.`,

  mastery_questions: [
    `Write RETRO.md. Three sections: What worked (specific techniques that performed better than expected, specific decisions that saved time), What did not (specific things you would replace or avoid -- be concrete: "hand-labelling 200 posts took 4 hours, 3x longer than estimated"), What next (what would v2.0 do that v1.0 cannot). Paste the file. Vague retros ("it was a good learning experience") are useless. Specific ones ("TF-IDF + LogReg matched DistilBERT on 200 labels, which means we could have deferred fine-tuning until we had more data") are the institutional knowledge teams document in Notion and reference six months later.`,
    `Write the blog post. Minimum 600 words, no maximum. Structure it around a single question: "How do you measure how the internet feels about something?" Answer it by walking through the project -- not in chronological build order but in the order that makes the answer clear. The technical details (TF-IDF, DistilBERT, SHAP) are supporting evidence, not the main event. Paste the post or its published URL. A post that a non-technical person can follow to the end is harder to write than a technical tutorial, and considerably more useful.`,
    `Record the demo video. Three to five minutes. Open Loom, QuickTime, or OBS. Hit record and narrate what you are doing as you do it -- open the dashboard, fetch posts, describe the sentiment distribution, pull up a SHAP explanation for one specific post, close with what you would build next. Paste the URL. Then watch it back once. Write one sentence about the single thing you would change if you recorded it again. Watching yourself is uncomfortable and instructive in roughly equal measure.`,
    `Share the dashboard URL with one person who has not seen this project. Watch them use it (screen share or in person). Write down: what did they click first, what confused them without explanation, and what they misunderstood about what the chart was measuring. Paste your three observations. This is the only feedback that is immune to politeness -- people's behaviour when confused tells you more than what they say when asked "is this clear?"`,
    `Re-read your week-14 experiment-01.md and your BIASES.md from week 16. Given everything you built since, are those documents still accurate? Did fine-tuning address any of the biases you documented in week 16? Paste one specific update you would make to BIASES.md with eight weeks of additional context behind it. Keeping documentation honest as a project evolves is the discipline that separates a finished project from something you can actually hand to someone else.`,
  ],

  common_mistakes: [
    `Writing the blog post in chronological build order. "First I did X, then I did Y" is a notebook log, not a post. Start with what you built and why it matters, then use the technical steps as evidence.`,
    `Not publishing the blog post because it is not polished enough. A dev.to post with three screenshots and 600 honest words is more useful than a draft you have been almost ready to publish for two months. Drafts in Notion that never go public do not exist for the purposes of showing your work.`,
    `Recording a 15-minute demo video. Three to five minutes. Anyone who cares can ask follow-up questions. Anyone who does not care will not watch past minute 2.`,
    `Skipping the stranger-verification step because you know it works. You know it works because you built it. The stranger finds the unlabelled chart axis, the confusing column header, the modal that does not close. That gap is real and embarrassing to discover during an interview demo.`,
    `Writing a retro that only mentions what went well. The useful information is in what went wrong -- and the useful version names the specific thing, not "the ML parts were harder than expected."`,
  ],

  debug_help: `The most common blocker this week is not technical -- it is the paralysis of "the post is not good enough to publish." It is good enough. The bar for a public project write-up is "could another person attempting this project learn something useful from it." Not "is this publication-quality." Paste the draft in whatever state it is in on Thursday. You can polish on Friday. You cannot polish a draft that does not exist. The same applies to the demo video -- one imperfect recorded take is infinitely more useful than a video you never made because the dashboard was not quite ready.`,

  ai_assist: `Use Claude to edit your blog post for clarity -- specifically ask it to flag any sentence where you used a technical term without explaining it. "Identify sentences that assume knowledge the reader might not have." Then decide for each flag whether to explain it or trust the reader. Do NOT ask Claude to write the post. The post is proof that you understand what you built -- a Claude-written summary of your project is evidence of Claude's understanding, not yours.`,

  stretch: [
    `Submit the blog post to r/MachineLearning or r/datascience. Read the comments, including the critical ones. The comments are a free expert review, and the critical ones are the most useful.`,
    `Write a "known limitations" paragraph for the README that honestly names two things the dashboard cannot do and why. Honest documentation of what a tool cannot do is a mark of a senior engineer, and it pre-empts the question in every demo.`,
    `Clean up the repo before calling it done. Delete experimental scripts, notebooks you never cleaned up, the first version of the Streamlit app before you split the backend. Ship a clean repo, not an archaeological dig.`,
  ],
});

// ─── W21 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 21, {
  context: `Reddit Sentiment ran for eight weeks and gave you something specific: intuition for NLP pipelines, classification metrics, and serving ML models. Project 3 is a different animal. Energy Forecast is a time series problem, and time series breaks almost every intuition you built on tabular and text data.

You are working with AEP (American Electric Power) hourly electricity demand -- a real utility company's actual grid load, hour by hour, from 2004 to 2018. Roughly 121,000 rows. The unit is megawatts. AEP serves about 5.4 million customers across 11 US states, so the numbers are not abstract: a 10-gigawatt peak on a summer afternoon is a real air-conditioning load from real people, and missing that peak by 5% in a production forecast means either rolling blackouts or $50 million of standby capacity idling unnecessarily.

The core challenge this week is that the data has structure your previous models simply did not have. Every electricity measurement is connected to the one before it and the one after it. Running a standard train/test split that shuffles the data randomly would contaminate your test set with future information -- the model would see next Tuesday's demand during training and "predict" it perfectly, which tells you nothing useful about real forecasting. You will learn to split time series by holding out the last N months as the test set, untouched, and training on everything before it.

The deliverable this week is exploratory analysis only -- no model yet. You will decompose the series into trend, seasonality, and residual using STL decomposition. You will build a heatmap of average demand by hour-of-day and day-of-week that shows, very clearly, that weekday mornings look nothing like weekend mornings. You will compute autocorrelation -- the correlation of the series with a lagged copy of itself -- which tells you how far back in time useful signal actually reaches. And you will implement one baseline: the persistence forecast (next hour = this hour), which is the dumbest model that knows about time. Any real model you build next week must beat it. If it does not, the model is not useful.

By Sunday: a notebook with three visualisations (seasonal decomposition, hour-day heatmap, autocorrelation plot), a written paragraph interpreting each, the persistence baseline calculated on your held-out test set, and one specific hypothesis about what will make ARIMA work on this data next week.`,

  pre_flight: `Download AEP_hourly.csv from the Kaggle "hourly energy consumption" dataset (search that exact phrase, the file is about 4MB). Before loading it into Python, open it in Excel or a text editor and look at the first 20 rows. Note the column names. Note whether timestamps appear to be UTC or local time. Note any obvious jumps or gaps. This 5-minute manual inspection before coding is the same habit analysts at PG&E and National Grid use before touching any new grid dataset -- utilities are full of logging errors, meter outages, and daylight-saving-time bugs that bite hard if you do not know to look.`,

  mastery_questions: [
    `Load the AEP CSV with pd.read_csv, setting the Datetime column as the index (parse_dates=True, index_col=0). Run df.resample('h').mean() to confirm you have a complete hourly series with no gaps. Paste df.shape and df.isna().sum(). If there are NaN values after resampling, the original data had missing hours -- paste how many there are and what you decide to do about them (forward-fill, interpolate, or drop). Missing hours in energy data are usually meter outages or daylight-saving transitions, and your choice here affects every model downstream.`,
    `Plot a 30-day slice of the series (pick any month outside pandemic years). The pattern should be obvious: peaks on weekday mornings and evenings, lower on weekends, lower at night. Write two sentences interpreting what you see -- not "there is a pattern" but what the pattern means in terms of actual human behaviour driving the load. Now zoom to a full year. Is there a seasonal arc across months? Paste both plots and the two-sentence interpretation.`,
    `Run STL decomposition on the daily resampled series (df.resample('D').mean(), then statsmodels.tsa.seasonal.STL with period=7). Plot all three components: trend, seasonal, and residual. Paste the plot. The residual is what your model needs to explain after trend and seasonality are accounted for. If the residual looks like white noise (no obvious pattern), trend plus seasonality does most of the work. If it has structure, there is more to capture. Write one sentence about what you observe in the residual.`,
    `Build an hour-of-day by day-of-week heatmap. Group by (df.index.hour, df.index.dayofweek), compute mean demand, pivot, and plot as a seaborn heatmap. Paste the plot. Now identify the single highest-demand cell and the single lowest-demand cell. Write one sentence explaining each in terms of real human behaviour. This visualisation is the standard first step in every utility company's load analysis -- Southern California Edison and Duke Energy both publish versions of it in their public grid transparency reports.`,
    `Implement the persistence baseline: next-hour prediction = current hour's actual value. Compute MAE and RMSE on your held-out test set using this baseline. Paste both numbers. Then write your specific hypothesis for week 22: will ARIMA beat this baseline, and by what percentage reduction in MAE? A specific guess -- even a wrong one -- is what calibrates your intuition. The analyst who says "I expected 15% improvement and got 8%, here is why I was off" is doing better thinking than the one who just reports the number without a prior.`,
  ],

  common_mistakes: [
    `Shuffling before splitting. This is the cardinal sin of time series. Your test set must be the LAST portion of the data chronologically, never a random sample. A random sample leaks future information into training and produces metrics that are fiction.`,
    `Not resampling to a regular frequency before decomposition. STL requires equally-spaced observations. If your data has missing hours, resample and fill gaps first or STL will error or, worse, return nonsense silently.`,
    `Plotting the full 14-year series at hourly resolution. 121,000 points in a matplotlib line chart produces an unreadable black band. Resample to daily for full-period plots; zoom to 30 days to see the hourly pattern.`,
    `Reporting only MAE for the persistence baseline. Always report both MAE and RMSE. RMSE penalises large errors more -- in energy forecasting, large errors (blackout risk or wasted standby capacity) are disproportionately expensive, so RMSE is often the metric grid operators care about.`,
    `Treating the persistence baseline as trivially easy to beat. Many expensive ML models in production do not beat it on short-horizon forecasts. Knowing your baseline number precisely is what lets you say "ARIMA beats persistence by 22%" with confidence -- and what makes you immediately suspicious if the improvement is 80%.`,
  ],

  debug_help: `Two common surprises. First: STL decomposition on hourly data takes a long time and sometimes raises "period must be a positive integer." Resample to daily before decomposing (df.resample('D').mean()), then use STL with period=7 for weekly seasonality. Second: the hour-day heatmap pivot produces NaN cells if some hour-day combinations are missing from your data. This usually means missing hours for specific days. Check your groupby result with .agg(['mean','count']) before pivoting, and look for cells where count is very low -- those are thin data, not true zero-demand readings.`,

  ai_assist: `Use Claude to explain what autocorrelation means in plain English, and ask it for a real-world example from energy forecasting specifically. Once you understand it, compute it yourself: df['AEP_MW'].autocorr(lag=24) (24-hour lag) and df['AEP_MW'].autocorr(lag=168) (one-week lag). Those values tell you how much yesterday's same-hour demand predicts today's -- that number is the single most important input to ARIMA order selection next week. Do NOT use Claude to choose your train/test split boundary. That decision depends on your dataset size and how much seasonal signal you want to capture in training, and making it yourself is the point.`,

  stretch: [
    `Download a second utility's data from the same dataset (PJME or DAYTON) and compare the seasonality profiles side-by-side. Different grid operators in different geographies show meaningfully different daily and seasonal patterns. The comparison takes about 10 minutes and is a useful calibration.`,
    `Compute the Fourier periodogram of the series. It shows which frequencies carry the most power -- 24-hour and 168-hour periods should dominate. This is the mathematical reason why ARIMA seasonal periods of 24 and 7 are the right starting point.`,
    `Look up how ISO New England publishes its public load forecasts (isonenglane.com). Compare their reported error metrics to your persistence baseline MAE. The gap between your baseline and their production system is roughly what a professional forecasting system achieves -- useful context for what ARIMA will and will not buy you.`,
  ],
});

// ─── W22 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 22, {
  context: `Last week you established that the AEP series has three layers: a long-term trend (slowly rising from 2004 to 2008, then slowly declining as efficiency improved), strong daily and weekly seasonal patterns, and a residual that is not pure noise. Your persistence baseline gave you a concrete MAE number to beat. This week you build the first real model and beat it.

ARIMA (AutoRegressive Integrated Moving Average) was formalised by Box and Jenkins in 1970, and it is still in production at central banks, energy utilities, and logistics companies because it does one thing well: it extracts signal from a well-behaved univariate time series without requiring a single external feature. The GDP desk at the US Federal Reserve uses ARIMA variants. So does every power utility's day-ahead forecasting system, at minimum as a benchmark against which fancier models justify their complexity.

The "integrated" part is the one that trips people up. I in ARIMA means differencing -- subtracting each observation from the one before it. A series with a trend is non-stationary (its mean changes over time), and ARIMA requires stationarity. Differencing removes the trend. The ADF (Augmented Dickey-Fuller) test tells you whether you have achieved stationarity, and you will run it before and after differencing so the decision is evidence-based rather than a guess.

pmdarima's auto_arima function will search for the best (p, d, q) parameters automatically. Let it -- but understand what it searched. p is the number of autoregressive lags (how many past values the model looks back at), d is the differencing order (usually 1 for energy data with a trend), and q is the number of moving-average terms (how many past errors the model corrects for). If you do not understand what each parameter does, you cannot explain the model when asked, which is the interview question you will definitely face.

By Sunday: a fitted ARIMA model, a forecast plot with 95% confidence intervals, RMSE on the held-out test set that beats the persistence baseline, and a short written comparison noting by how much you beat it and where the model still fails. ARIMA will handle the slow trend and the weekly pattern, but it will miss sudden spikes -- a heat wave, a factory shutdown -- because it knows nothing about weather. That limitation is the setup for everything you build in the next two weeks.`,

  pre_flight: `Before running auto_arima, check stationarity manually. Plot the rolling mean and rolling standard deviation with window=168 (one week). If the rolling mean drifts visibly across the full period, the series is non-stationary. Write down what you see. Then run the ADF test (from statsmodels.tsa.stattools import adfuller) on the raw daily series. Paste the ADF statistic and p-value. If p > 0.05, the series is not stationary and you need at least one round of differencing before fitting ARIMA.`,

  mastery_questions: [
    `Run the ADF test on the raw daily series. Paste the ADF statistic, the p-value, and what the null hypothesis actually is (the null is that the series HAS a unit root, i.e., is non-stationary). If p > 0.05, apply first differencing (df.diff().dropna()) and run ADF again. Paste both sets of results side by side. Now you know d -- the I in ARIMA. Understanding this test is what makes ARIMA stop being a magic parameter search and start being a disciplined response to a specific property of your data.`,
    `Fit auto_arima on your training set using daily resampled data (df.resample('D').mean()). Set seasonal=True, m=7, stepwise=True. Paste the selected order (p,d,q)(P,D,Q,m) and how long the search took. Now fit the model again manually with those exact parameters using ARIMA() directly, so you own the fitted object and can call it later. Paste the model summary. The AIC values from both fits should match -- if they do not, check that your parameters match exactly.`,
    `Generate a 90-day forecast on your held-out test set. Plot the forecast against the actual values on the same chart, with the 95% confidence interval shaded. Paste the plot. Where do the confidence intervals widen? (Usually: further into the forecast horizon, uncertainty grows.) Name one specific week where the miss is large and write your hypothesis about what caused it -- sudden weather event? holiday? Both are plausible and neither is in the model.`,
    `Compute MAE and RMSE on the test set (model forecast vs. actuals). Paste both numbers. Compare to your persistence baseline from week 21. What is the percentage improvement in MAE? Was your week-21 hypothesis correct? If you predicted 15% improvement and got 8%, write two sentences about what ARIMA captured and what it missed. That specific analysis -- model beat baseline by X% because Y, but missed Z because the model has no feature for it -- is exactly how you present model results to a non-technical stakeholder.`,
    `Plot the residuals from your fitted model (model.resid()). They should look like white noise -- roughly centred on zero, no obvious pattern. Run the Ljung-Box test (from statsmodels.stats.diagnostic import acorr_ljungbox) on the residuals at lag 14. Paste the p-value. If p < 0.05, the residuals are autocorrelated and your model is leaving signal on the table -- usually a sign you need higher p or seasonal terms. Senior practitioners always check residuals before reporting results. A model with autocorrelated residuals is a model that is not done yet.`,
  ],

  common_mistakes: [
    `Running auto_arima on hourly data with seasonal=True. The seasonal period would be 8760 (one year of hours), which is computationally infeasible. Always resample to daily before fitting ARIMA; model the hourly pattern separately if needed.`,
    `Including any test data when fitting auto_arima. Feed it only the training set. The test set must remain untouched until the final evaluation -- this is the same rule as week 21, and it applies to every model selection step, not just the final fit.`,
    `Reporting only point forecasts without confidence intervals. The interval is often more useful than the point estimate -- a utility operator needs to know the 95th percentile demand to plan standby capacity, not just the expected value.`,
    `Treating auto_arima's first result as final without checking residuals. If the Ljung-Box test fails (p < 0.05), the model order needs adjustment. Accepting a mis-specified model because the search returned a result is the most common ARIMA mistake in production.`,
    `Over-differencing by accepting d=2 from auto_arima on a trend-weak series. The symptom is a forecast that is a nearly flat line. Drop d to 1 manually and refit. Auto_arima occasionally over-differences when the trend is subtle, and the flat-line forecast is the tell.`,
  ],

  debug_help: `Three specific issues. First: "ValueError: maxlag must be less than nobs" from the Ljung-Box test. Your test set is smaller than the lag you specified. Use lag=min(14, len(resid)//2). Second: auto_arima hangs for more than 10 minutes. Add max_p=3, max_q=3, max_P=1, max_Q=1 to limit the search space -- hourly data with a wide parameter range takes exponentially longer. Third: the forecast is a nearly flat line after fitting. This is the over-differencing sign -- d=2 was likely chosen and the doubly-differenced series has almost no signal. Set d=1 explicitly in the ARIMA() call and refit. You will see a meaningful forecast appear almost immediately.`,

  ai_assist: `Use Claude to explain the ADF test output in plain English before you decide on the differencing order -- "given this ADF statistic and p-value, is my series stationary and how confident should I be?" is a good prompt. Once you have the ARIMA order selected, use Claude to explain what each (p, d, q) term contributes to the model -- that explanation is what you need to answer "walk me through your forecasting model" in an interview. Do NOT use Claude to pick the ARIMA order for you. The auto_arima process, with you understanding each step, is how you build the intuition needed for the more complex models in weeks 23 to 28.`,

  stretch: [
    `Fit a seasonal naive baseline (forecast = same hour exactly 7 days ago) and compare its RMSE to ARIMA. Seasonal naive beats ARIMA on many energy datasets because the weekly cycle is so dominant. Knowing whether that is true for yours before adding model complexity is the honest first step.`,
    `Plot the ARIMA in-sample fit against the training data alongside the out-of-sample forecast. The in-sample fit should be very close (the model was fitted on this data). The degradation from in-sample to out-of-sample is your model's actual generalisation gap -- visible in one chart.`,
    `Read Sections 8.1 through 8.5 of "Forecasting: Principles and Practice" by Hyndman and Athanasopoulos (free at otexts.com/fpp3). It is the clearest explanation of ARIMA in the literature, and Hyndman wrote much of the forecasting software the energy industry uses today.`,
  ],
});
