/**
 * v2 rewrite batch 7: data-science Weeks 33-37
 *  W33: RAG Systems — retrieval-augmented generation in production
 *  W34: Computer Vision — CNN, transfer learning, Vision Transformers
 *  W35: Causal Inference — going beyond correlation
 *  W36: ML Fairness and Bias — the audit you actually run
 *  W37: Capstone v0.2 — Build (extended)
 */

import { rewriteWeek } from "../rewrite-week";

// ─── W33 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 33, {
  context: `Every major enterprise that touched LLMs in 2023 and 2024 built the same thing first: a question-answering system over their own documents. Legal teams querying contracts. Finance teams querying earnings reports. Support teams querying product manuals. The pattern is called RAG -- Retrieval-Augmented Generation -- and it is now the most commonly deployed LLM application architecture in production.

The idea is straightforward. You cannot fit 10,000 company documents into an LLM's context window. And you do not want to, because the model would hallucinate specific facts that are not in the documents. Instead: when a user asks a question, retrieve the 3-5 most relevant document chunks, add them to the prompt alongside the question, and let the model generate an answer grounded in retrieved text. The retrieval layer handles the "where is the answer?" question. The model handles the "how do I phrase the answer?" question. Separating those two concerns is what makes RAG work.

The retrieval layer is where most of the engineering lives. Documents are split into chunks (a decision that matters more than most people expect -- too small and the chunk loses context, too large and retrieval is imprecise). Chunks are embedded into a vector space using an embedding model. At query time, the question is embedded too, and the chunks closest in vector space to the question are retrieved. The assumption is that semantic similarity in embedding space corresponds to topical relevance -- which is true often enough to be useful and wrong often enough to require evaluation.

This week you build and deploy a RAG app over a corpus you actually care about. The corpus choices that produce the best learning are narrow and specific: the documentation for a Python library you use constantly, a set of research papers in a domain you want to understand, or the transcripts from a podcast you follow. Wide corpora ("all of Wikipedia") produce mediocre recall and are harder to evaluate. Narrow corpora let you actually check whether the retrieved chunks are relevant.

By Sunday: a deployed Streamlit RAG app that accepts a question, retrieves relevant chunks from your corpus, and generates a grounded answer with citations showing which chunks were used. An evaluation on 20 hand-written question-answer pairs showing retrieval accuracy and answer faithfulness. And honest documentation of where it fails.`,

  pre_flight: `Choose your corpus and collect it before writing any code. If it is PDFs, download them. If it is web pages, scrape them now. If it is documentation, export the HTML. Count the total number of documents and estimate the total word count. A corpus under 100,000 words fits in FAISS with no performance concerns. Over 1 million words, you will want to think about chunk size and retrieval latency before you start embedding. Write those numbers down -- they shape every decision this week.`,

  mastery_questions: [
    `Split your corpus into chunks using a recursive character text splitter (LangChain's RecursiveCharacterTextSplitter or equivalent). Try chunk_size=500 with chunk_overlap=50. Paste df.shape of your chunk DataFrame and 2 sample chunks. Now try chunk_size=200. Compare the two: smaller chunks are more precise but lose sentence context. Larger chunks preserve context but retrieve noisier results. Write one sentence about which you chose for this corpus and why -- the right answer depends on whether your documents are dense technical text or narrative prose.`,
    `Embed all chunks using sentence-transformers (all-MiniLM-L6-v2 is fast and good enough for most tasks). Paste the embedding shape (n_chunks, embedding_dim). Build a FAISS index (faiss.IndexFlatL2) and add the embeddings. Paste the index.ntotal. Now run a test query: embed one question, search the index for the top 5 chunks, paste the retrieved chunk texts. Do they look relevant? If the top result is clearly off-topic, your chunk size or embedding model may need adjustment.`,
    `Wire the retrieval into a generation call. Construct the prompt: system message explaining the task, retrieved chunks labelled as context, user question. Call an LLM (OpenAI, Anthropic, or a local model via Ollama). Paste the prompt template and one complete example: question, retrieved chunks, generated answer. Does the answer cite the chunks? Does it make claims beyond what the chunks say? The second question is how you detect hallucination.`,
    `Evaluate on 20 hand-written QA pairs. For each pair, run the RAG pipeline and score: (1) retrieval hit rate -- did at least one of the retrieved chunks contain the answer? (2) answer faithfulness -- does the generated answer stay within what the chunks say, or does it add information not present? Paste your hit rate and faithfulness score. If hit rate is below 70%, chunk size is probably the issue. If faithfulness is low, your prompt is not grounding the model tightly enough.`,
    `Deploy the app to Streamlit Community Cloud or Hugging Face Spaces. The UI: a text input for the question, a "submit" button, the generated answer, and below it an expandable "sources" section showing the retrieved chunks with their document names. Paste the URL. Open it and ask a question you know the answer to. Does the app get it right? Paste one example of a question it gets wrong and one sentence about why -- usually either the relevant chunk was not retrieved, or the model ignored the retrieved chunk in favour of its prior knowledge.`,
  ],

  common_mistakes: [
    `Not adding chunk overlap. Without overlap, a sentence that spans two chunks is split in half and may not be fully retrievable from either. chunk_overlap=50 costs almost nothing and prevents this common retrieval failure.`,
    `Embedding the query with a different model than the chunks. The query embedding and the chunk embeddings must come from the same model to be comparable in vector space. A mismatch produces retrieval results that look random.`,
    `Using too many retrieved chunks. Retrieving 10 chunks and stuffing them all into the context makes the LLM's job harder, not easier -- relevant signal is diluted by noise. Start with top-3 or top-5. More is not always better.`,
    `Evaluating only whether the answer sounds right, not whether it is grounded in the retrieved chunks. An answer can be factually correct and still be a hallucination if the model generated it from training data rather than the provided context. Faithfulness evaluation requires checking the answer against the chunks, not against your own knowledge.`,
    `Building over a corpus you cannot evaluate. If you cannot write 20 ground-truth QA pairs, you cannot measure whether your RAG app works. Choose a corpus you know well enough to write test questions for.`,
  ],

  debug_help: `Two specific failure modes. First: retrieval returns irrelevant chunks even for simple questions. Check that the embedding model was correctly applied to both chunks and queries -- a common bug is embedding the raw text versus the pre-processed text. Also try cosine similarity (faiss.IndexFlatIP with normalised vectors) instead of L2 distance: for semantic similarity, cosine often outperforms Euclidean. Second: the LLM ignores the retrieved context and answers from its training data. Make your prompt more directive: "Answer ONLY using the provided context. If the context does not contain the answer, say so." Adding "if the context does not contain the answer" changes the model's behaviour significantly on out-of-corpus questions.`,

  ai_assist: `Use Claude to generate 20 diverse test questions for your corpus -- give it 3 sample documents and ask for questions that range from factual lookups to reasoning questions. Verify each generated question has a retrievable answer in your corpus before using it as evaluation data. Do NOT use Claude to evaluate whether your RAG answers are correct -- evaluation requires checking answers against your ground-truth corpus, and a model evaluating another model's output on the same knowledge domain is not independent evaluation.`,

  stretch: [
    `Add a BM25 retrieval layer (rank_bm25 library) alongside the vector retrieval and combine the results (hybrid search). On most corpora, hybrid search beats pure vector search by 5-15% on retrieval accuracy. The combination is what production RAG systems at Elastic and Cohere actually use.`,
    `Add a cross-encoder re-ranker: after retrieving the top 10 chunks by vector similarity, re-score all 10 using a cross-encoder (sentence-transformers/ms-marco-MiniLM-L-6-v2) and keep only the top 3. Re-ranking consistently improves precision with minimal latency cost.`,
    `Read "RAGAS: Automated Evaluation of Retrieval Augmented Generation" (Es et al., 2023). The RAGAS framework defines four metrics -- faithfulness, answer relevancy, context precision, context recall -- that together give a complete picture of RAG system quality. Running RAGAS on your system gives you numbers you can put in the project README.`,
  ],
});

// ─── W34 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 34, {
  context: `Most data science work is tabular or text. Computer vision is the third domain, and it comes up more often than people expect -- not just at camera companies and autonomous vehicle startups, but at retail (shelf inventory), healthcare (medical imaging), agriculture (crop disease detection), and manufacturing (defect detection). This week you build and deploy an image classifier. The skill transfers widely.

The practical reality of CV in 2025 is that you almost never train from scratch. A ResNet50 or EfficientNet trained on ImageNet has already learned to detect edges, textures, shapes, and object parts from 14 million labelled images. Your job is to take those learned features and adapt them to your specific task with your specific data. Fine-tuning the last few layers takes minutes. Fine-tuning the whole network takes hours but often produces a few percentage points more accuracy when your domain is different from natural images (medical scans, satellite imagery, microscopy).

Vision Transformers (ViT) changed how the field thinks about image processing. Instead of convolutions that slide a filter across local regions, ViT splits the image into patches and runs a transformer over them -- the same attention mechanism from BERT, applied to image patches. On large datasets, ViT outperforms CNNs. On small datasets (fewer than 10,000 images), CNNs still tend to win because convolutions have the right inductive bias for images baked in, and transformers need more data to learn that bias from scratch.

Choose a specific, verifiable task. Bird species classification, dog breed identification, food type recognition, or plant disease detection -- all of these have public datasets, clear ground truth, and real difficulty. Avoid "cats vs. dogs" (too easy, already solved, demonstrates nothing) and avoid medical imaging without domain expertise (the stakes are high and the evaluation requires clinical knowledge you probably do not have).

By Sunday: a fine-tuned model deployed as a FastAPI endpoint, evaluated on a proper held-out test set, with per-class accuracy numbers and a honest failure analysis showing which classes the model confuses most.`,

  pre_flight: `Find the dataset before picking the model. Search Kaggle or Hugging Face Datasets for your chosen task. Download a sample (50 images) and look at them manually. Are the images consistently sized? Are they clearly labelled? Are there classes with very few examples? A dataset with 10 images for one class and 1000 for another is an imbalanced classification problem on top of a CV problem -- know this before you start, not after your confusion matrix looks wrong.`,

  mastery_questions: [
    `Load your dataset and apply standard preprocessing: resize to 224x224 (the ImageNet standard), normalise with ImageNet mean and std (mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]). Add at least two augmentations to the training set (random horizontal flip, random rotation, colour jitter). Paste the transforms. Now confirm with one sanity check: display one augmented image and confirm it still looks like the correct class. Augmentation that changes the semantic meaning of the image (vertical flip on cars, for example) hurts training.`,
    `Load a pretrained ResNet50 (torchvision.models.resnet50(weights='IMAGENET1K_V1')). Freeze all layers except the final classification head: for param in model.parameters(): param.requires_grad = False, then replace model.fc with a new Linear layer matching your number of classes. Paste the number of trainable parameters (should be in the thousands, not millions). Fine-tune for 5-10 epochs. Paste train accuracy and validation accuracy at final epoch. If val accuracy is more than 10 points below train accuracy, you are overfitting -- add dropout or reduce learning rate.`,
    `Unfreeze the last two residual blocks and continue training at a lower learning rate (1e-4 instead of 1e-3). Paste val accuracy before and after unfreezing. This "gradual unfreezing" is the standard transfer learning recipe -- freezing first forces the new head to learn sensible weights before the backbone is disturbed. The accuracy gain from unfreezing varies by how different your domain is from ImageNet.`,
    `Evaluate on your held-out test set. Paste overall accuracy and the per-class accuracy. Find the two classes your model confuses most (look at the confusion matrix). Paste those two classes and one sentence about why they might look similar to the model -- similar colours, similar shapes, similar backgrounds. This confusion analysis is what a CV engineer presents in a model review before deployment.`,
    `Wrap the model in a FastAPI endpoint: POST /predict accepts a base64-encoded image, returns the top-3 class predictions with confidence scores. Paste the endpoint code and one test curl call with output. Deploy to Hugging Face Spaces or a free host. Paste the URL. Test it with an image not from your training set -- a photo you took yourself or found online. Does it predict correctly? If not, write one sentence about whether the failure is a data distribution issue or a model capacity issue.`,
  ],

  common_mistakes: [
    `Normalising test images with statistics computed from the training set. You should use the fixed ImageNet mean and std (or compute from your training set once and hard-code them). Recomputing statistics from the test set leaks information and produces slightly overoptimistic metrics.`,
    `Not shuffling the training data between epochs. If your DataLoader is deterministic and batches always contain the same class mix, the model sees the same gradient pattern repeatedly. Set shuffle=True in the training DataLoader.`,
    `Evaluating on validation data (used for early stopping and hyperparameter tuning) instead of a separate test set. Validation loss drove your decisions -- evaluating on it is like grading your own homework. Keep a true held-out test set untouched until final evaluation.`,
    `Using the same learning rate for the frozen head and the unfrozen backbone. When you unfreeze, the backbone needs a much smaller learning rate (10x-100x smaller) than the head -- the backbone has already learned useful features and large updates will destroy them.`,
    `Not checking for class imbalance before training. If 80% of your images are one class, a model that always predicts that class gets 80% accuracy. Check class counts with torchvision or pandas value_counts before training, and use weighted sampling or class weights if imbalance is severe.`,
  ],

  debug_help: `Three specific issues. First: "RuntimeError: Expected all tensors to be on the same device." Your model is on GPU but inputs are on CPU (or vice versa). Add .to(device) to both model and input tensors, where device = torch.device('cuda' if torch.cuda.is_available() else 'cpu'). Second: validation accuracy plateaus immediately and does not improve past epoch 1. Usually means the learning rate is too high for the unfrozen backbone -- reduce by 10x. Third: all predictions collapse to one class (your model always predicts "Labrador"). This is the class imbalance problem -- the model learned to predict the majority class. Use class_weight='balanced' or oversample the minority classes.`,

  ai_assist: `Use Claude to explain what a ResNet skip connection actually does, in plain English. The skip connection is the innovation that made deep networks trainable -- understanding it is what lets you explain your model architecture in an interview. Do NOT use Claude to choose the architecture or the hyperparameters. Those decisions depend on your dataset size, your class count, and your available compute, and making them yourself (with a reasoning sentence) is the skill.`,

  stretch: [
    `Try a ViT (vit_b_16 from torchvision) on the same dataset with the same train/test split. Compare test accuracy to ResNet50. If ViT wins, your dataset is large enough for attention to outperform convolutions. If ResNet wins, you have confirmed the small-dataset advantage of CNNs.`,
    `Add Grad-CAM visualisation: for 5 test images, overlay the Grad-CAM heatmap showing which pixels most influenced the prediction. The visualisation reveals whether the model is looking at the object (correct) or the background (a common failure mode when backgrounds are correlated with classes in training data).`,
    `Try object detection on one of your images using a pretrained YOLO or DETR model (no fine-tuning). Note what it detects, where it places the bounding boxes, and where it fails. Understanding the difference between classification (what is this whole image?) and detection (where are the objects?) is a conceptual step that many DS practitioners skip.`,
  ],
});

// ─── W35 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 35, {
  context: `You have spent 34 weeks building models that predict things. This week you step back and ask a harder question: do your predictions mean anything about causes?

Correlation is easy to find. AEP electricity demand correlates with temperature. Reddit sentiment correlates with post length. Taxi tips correlate with trip distance. None of those correlations, by itself, tells you that temperature causes demand, or that length causes sentiment. There might be a common cause (weekday vs. weekend drives both longer posts and more positive sentiment). There might be reverse causation. There might be a confounder you have not measured.

This distinction matters more than it might seem. A company that acts on a correlation as if it were causal causation and invests $10 million in the wrong lever is making a decision that a data scientist could have prevented. The person in the room who asks "wait, is this causal or just correlated?" is doing more value than the person who built the model that found the correlation. That question -- and the tools to answer it -- is what this week is about.

DAGs (Directed Acyclic Graphs) are the notation for drawing causal assumptions. Before running any statistical test, you draw the graph: nodes are variables, arrows are causal relationships, and the absence of an arrow is a claim that there is no direct effect. A DAG makes your assumptions visible and checkable. Confounders, mediators, and colliders are patterns in the graph that determine which variables to control for in your analysis -- and which variables to explicitly NOT control for (controlling for a collider introduces bias, which is counterintuitive and trips up even experienced analysts).

You will apply one real causal inference method to a question from your own project data. It does not have to be a clean result. A clean negative result -- "we cannot determine whether X causes Y with this data because we cannot isolate the necessary variation" -- is a rigorous, honest, and useful conclusion.

By Sunday: a DAG for your causal question, one applied method (propensity score matching or difference-in-differences, most likely), and a one-page causal memo that states the question, the method, the result, and the limitations with honesty.`,

  pre_flight: `Write down one causal question you genuinely want to answer about your project data. Not "does X correlate with Y" -- "does X cause Y to change, and by how much?" For Energy Forecast: "did the 2009 recession cause AEP demand to permanently fall, or was demand already declining?" For Reddit Sentiment: "does post length cause more negative sentiment, or do negative posts happen to be longer for other reasons?" Write the question in one sentence and identify what the "treatment" variable is.`,

  mastery_questions: [
    `Draw the DAG for your causal question using dagitty.net (free, browser-based) or the dagitty R/Python package. Include at least 4 nodes: the treatment, the outcome, and at least 2 potential confounders or mediators. Paste the DAG as an image or the dagitty model string. Now use dagitty's "adjustment sets" feature to identify which variables you need to control for to estimate the causal effect. Paste the output. If dagitty says "no adjustment set exists," write one sentence about what that means -- it means the effect is not identifiable from observational data with this graph structure.`,
    `Identify whether your causal question is better answered by propensity score matching, difference-in-differences, or an instrumental variable approach. Write one paragraph justifying the choice. The right method depends on the data structure: DiD requires pre-treatment and post-treatment observations for both a treated and control group. PSM requires overlapping covariate distributions between treated and untreated units. IV requires a valid instrument. If none of the three apply cleanly, write that honestly.`,
    `Apply your chosen method using dowhy or econml. For propensity score matching: fit a logistic regression on the treatment indicator using the adjustment set variables, compute propensity scores, match treated to control units, and estimate the ATT (Average Treatment Effect on the Treated). Paste the estimate and its confidence interval. For DiD: fit the two-way fixed effects model and paste the treatment coefficient. The number is not the result -- the interpretation is.`,
    `Check the assumptions of your chosen method. For PSM: plot the propensity score distributions for treated and control groups -- if they do not overlap, matching fails. For DiD: plot the pre-treatment trends for treated and control groups -- if they are not parallel, the parallel trends assumption is violated and DiD is invalid. Paste the diagnostic plot and write one sentence about whether the assumption holds in your data.`,
    `Write the causal memo. One page. Sections: Question (one sentence), Method (why you chose it), Result (the estimate, the confidence interval, plain English interpretation), Assumptions (what has to be true for this result to be valid), Limitations (what you cannot rule out with this data). Paste the memo. A clean negative result ("the data does not support a causal interpretation because the parallel trends assumption is violated") is a rigorous conclusion. An overconfident positive result on shaky assumptions is a retraction waiting to happen.`,
  ],

  common_mistakes: [
    `Controlling for mediator variables when you want the total causal effect. A mediator is a variable on the causal path from treatment to outcome -- controlling for it blocks the very mechanism you are trying to measure. Draw the DAG before deciding what to control for.`,
    `Controlling for colliders. A collider is a variable caused by both the treatment and the outcome. Conditioning on a collider (including it as a covariate) introduces spurious associations between treatment and outcome that were not there. This is the most counterintuitive mistake in causal inference and the most common.`,
    `Conflating statistical significance with practical significance. A propensity score matched estimate of 0.3 with p=0.04 might be statistically significant and practically irrelevant. Report effect size, not just p-value.`,
    `Assuming the DAG is correct without testing it. A DAG encodes assumptions. Some of those assumptions can be tested (d-separation tests, covariate balance checks). Test the ones you can, and explicitly list the ones you cannot.`,
    `Using causal language in the write-up when the method only supports associational claims. "X caused Y to increase by 3%" requires a valid causal identification strategy. "Our DiD estimate suggests X was associated with a 3% increase in Y, assuming parallel trends" is honest.`,
  ],

  debug_help: `The most common stuck point is choosing the identification strategy. If you are unsure, use this decision tree: do you have data from before and after a treatment, for both a treated and a control group? DiD. Do you have a variable that affects treatment assignment but not the outcome directly? IV. Otherwise: PSM if covariate overlap is sufficient, or "causal effect is not identifiable from this data" if it is not. "Not identifiable" is a valid and important scientific conclusion -- it tells the organisation that they need a different study design to answer this question.`,

  ai_assist: `Use Claude to explain the difference between a confounder and a mediator with a specific example from your domain. "In the context of predicting electricity demand, is temperature a confounder or a mediator of the effect of time-of-day on demand?" -- the answer requires understanding both the causal structure and the domain. Once you understand the distinction, you can apply it to your own DAG without prompting. Do NOT use Claude to draw the DAG -- the DAG encodes your causal assumptions about the domain, and those assumptions must come from your domain knowledge, not from a model's priors.`,

  stretch: [
    `Read "The Book of Why" by Judea Pearl, Chapters 1 and 6. Pearl invented the do-calculus and the modern framework for causal inference. Chapter 1 explains why correlation is not causation at a level that is both rigorous and readable. Chapter 6 covers the counterfactual framework. Both are worth 2 hours of your time.`,
    `Run a sensitivity analysis on your causal estimate: how large would an unmeasured confounder have to be to explain away your result? The sensitivity package in R (or sensemakr in Python) computes this. A result that requires a very strong unmeasured confounder is more robust than one that falls apart with even a weak unmeasured confounder.`,
    `Find one published study in your domain that claims a causal relationship. Draw the DAG implied by their methods. Does their identification strategy actually identify the causal effect? Or are they making an associational claim dressed in causal language? This exercise -- reading published work with a causal inference lens -- is one of the most valuable skills you can build.`,
  ],
});

// ─── W36 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 36, {
  context: `Every model you have shipped this year made decisions. The Reddit Sentiment classifier labelled posts. The Energy Forecast model allocated attention to certain hours. The image classifier assigned categories. If any of those models were deployed in a real product, they would be making decisions about real people at scale -- and some of those decisions would be systematically wrong for specific groups.

ML fairness is not an ethics lecture. It is an engineering problem with specific, measurable failure modes and a set of tools for detecting and mitigating them. The reason it belongs in a data science curriculum is practical: bias in a shipped model is a legal liability, a PR crisis, and an operational failure. Amazon scrapped an internal recruiting ML model in 2018 because it downrated CVs with the word "women's." Apple's credit card algorithm offered lower limits to women than men with equivalent financial profiles in 2019. Both failures were detectable before deployment with the tools you will learn this week.

The core tension is that there are multiple mathematically incompatible definitions of fairness. Demographic parity (equal positive prediction rates across groups) and equal opportunity (equal true positive rates across groups) cannot both hold simultaneously unless the base rates are equal across groups. This is not a software bug -- it is a theorem. Knowing which definition of fairness is the right one for your application is a decision that involves the domain, the stakes, and the legal context, and it cannot be made by optimising a metric.

You will audit one of your own earlier models this week. The most instructive choices are the Reddit Sentiment classifier (does it treat posts about different demographic groups differently?) or the Capstone model (does it perform equally well across meaningful subgroups in your data?). The audit produces a BIAS.md document -- specific, honest, and actionable. The specific is the hard part.

By Sunday: a fairness audit of one model using at least two fairness metrics, a BIAS.md added to the relevant project repo, and a written recommendation about what you would do before shipping this model to real users.`,

  pre_flight: `Before running any fairness code, identify the protected attributes in your dataset -- the characteristics that fairness law and good practice say should not determine model outcomes (gender, race, age, religion, nationality). Write down which of those attributes are present in your data, which are proxy-encoded (a zip code often encodes race, a name often encodes gender), and which are absent entirely. If your dataset has no demographic attributes, you cannot measure demographic fairness -- write that down too, because "we cannot measure this" is important information.`,

  mastery_questions: [
    `Define the subgroups you will audit. If your model involves people, the subgroups should be demographic (gender, age bracket, geography). If it involves content, the subgroups might be topic categories or subreddits. Compute the base rate of your target variable for each subgroup -- what percentage of each group gets the positive prediction? Paste the base rates. If base rates differ across groups, demographic parity cannot hold simultaneously with equal opportunity -- write one sentence about which fairness definition is more appropriate for your use case and why.`,
    `Compute at least two fairness metrics across your subgroups: (1) demographic parity difference (positive prediction rate difference between the most and least advantaged group), (2) equal opportunity difference (true positive rate difference). Use Fairlearn's MetricFrame: MetricFrame(metrics=..., y_true=..., y_pred=..., sensitive_features=...). Paste the MetricFrame summary. A demographic parity difference above 0.1 or an equal opportunity difference above 0.05 is typically considered significant in practice.`,
    `Identify the worst-performing subgroup on each metric. For that group, pull 10 examples where the model predicted incorrectly. Paste 3 of them (or describe them if they contain personal data). Write one sentence about the pattern -- is there something systematically different about these examples that the model is not capturing? This manual inspection is the step that most automated audit tools cannot replace.`,
    `Write BIAS.md for the audited project. Required sections: Summary (what model was audited and what was found), Metrics (the specific numbers from the MetricFrame), Root Cause Hypothesis (one or two sentences about why the bias exists -- training data bias? label bias? feature correlation?), Mitigation Options (three specific options: data-level, model-level, post-processing -- with one sentence on the trade-off of each), Recommendation (what you would actually do before shipping). Paste the file. Vague is not useful. "The model may disadvantage some groups" is not an audit finding. The specific metric numbers and the specific subgroup are.`,
    `Apply one mitigation and measure its effect. Options: re-weight training samples by group (data-level), use Fairlearn's GridSearch to add a fairness constraint during training (model-level), or apply a threshold adjustment per group to equalise a specific metric (post-processing). Paste the before-and-after fairness metric comparison. Usually mitigation improves fairness at a cost to overall accuracy -- document that trade-off explicitly. A model that is 2% less accurate but 40% more fair is a different decision than one that is 10% less accurate and 5% more fair.`,
  ],

  common_mistakes: [
    `Auditing only overall accuracy without breaking it down by subgroup. A model with 85% overall accuracy might have 92% accuracy on the majority group and 68% on a minority group. The aggregate metric hides this completely.`,
    `Choosing the wrong fairness definition for the domain. For a hiring model, equal opportunity (equal true positive rates) is usually more appropriate than demographic parity, because the goal is to identify qualified candidates equally across groups, not to select equal proportions. The wrong metric gives you the right number for the wrong thing.`,
    `Treating fairness as a post-hoc fix. The deepest source of bias is usually in training data collection and labelling, not in the model. Post-processing can reduce measurable disparity but cannot fix a model trained on systematically biased data.`,
    `Not reporting the accuracy-fairness trade-off. Any mitigation that improves fairness at the cost of accuracy is a trade-off that stakeholders need to know about and decide on. Reporting only the fairness improvement without the accuracy cost is an incomplete result.`,
    `Confusing individual fairness and group fairness. Group fairness requires similar outcomes for groups. Individual fairness requires that similar individuals receive similar predictions. Both are real fairness concerns and they are not the same thing.`,
  ],

  debug_help: `Fairlearn's MetricFrame raises a "Sensitive features must be a 1D array" error when you pass a DataFrame column instead of a Series. Use df['protected_col'].values or df['protected_col'].to_numpy(). It also raises errors when subgroup sizes are very small -- if one subgroup has fewer than 10 examples, the metric estimates are unstable. Report "insufficient data for reliable estimate" for those subgroups rather than reporting the noisy number.`,

  ai_assist: `Use Claude to explain the mathematical incompatibility between demographic parity and equal opportunity in plain English -- specifically, why you cannot achieve both simultaneously when base rates differ. Understanding this theorem is what lets you explain to a stakeholder why you chose one fairness definition over another, rather than being asked "why didn't you just make it fair in all the ways?" Do NOT ask Claude to write BIAS.md. The audit findings and the mitigation recommendations require domain knowledge and judgment that must be yours.`,

  stretch: [
    `Run the audit using AI Fairness 360 (IBM's library) instead of Fairlearn. Compare the metric outputs. The two libraries sometimes disagree on edge cases, and understanding why is instructive about the subtleties of fairness measurement.`,
    `Read the FairML chapter from "Weapons of Math Destruction" by Cathy O'Neil. The recidivism prediction case study (COMPAS) is the canonical example of a fairness failure in a high-stakes system. Understanding that case in detail is the foundation for every fairness conversation you will ever have in a professional setting.`,
    `Calculate the "disparate impact ratio" (the ratio of positive prediction rates between the least and most advantaged group). The US legal standard under disparate impact doctrine is that this ratio should be above 0.8 (the "four-fifths rule"). Is your model above or below that threshold?`,
  ],
});

// ─── W37 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 37, {
  context: `You chose your capstone topic in week 28 and built the first version in week 29. This week you return to it with more tools. The goal is not to add complexity -- it is to add rigour. The difference between a student project and a senior portfolio piece is not the model architecture. It is the quality of the evaluation, the reproducibility of the pipeline, and the honesty of the documentation.

Cross-validation done correctly is the first thing to fix. Most early-career practitioners run one train/test split and report that number. The problem is that one split has variance -- a different random seed gives a different test set and a different accuracy. Cross-validation gives you a distribution of performance estimates rather than a point estimate, and the standard deviation of that distribution is at least as informative as the mean. If your model scores 82% on one fold and 71% on another, you have learned something important about how much your model's performance depends on which data it saw.

The reproducible pipeline is the second thing to add. Right now your notebook probably runs top-to-bottom when you execute every cell in order, and breaks if you run cells out of order or on a different machine. A reproducible pipeline has a single entry point (a Python script or a Makefile target) that runs the full workflow from raw data to final metrics, produces the same output every time (given the same random seed), and works on a machine that has never seen the repo before. This sounds like overhead. It is the difference between a project you can hand to a collaborator and a project that only works on your laptop.

Multi-metric evaluation is the third addition. You have been reporting accuracy or MAE. Those numbers are real, but they are incomplete. A classification model needs precision, recall, F1, and the confusion matrix. A regression model needs MAE, RMSE, and the residual distribution. For some tasks, a business metric matters more than any statistical metric -- if your model is recommending interventions, the cost of a false negative might be 10x the cost of a false positive, and that asymmetry should drive the evaluation.

By Sunday: a reproduced pipeline with a single entry point, cross-validated performance estimates with standard deviations, a multi-metric evaluation table, and updated documentation reflecting the new rigour.`,

  pre_flight: `Before touching code, run your existing capstone notebook top-to-bottom on a fresh kernel. Does it work? Does it produce the same metrics as before? If either answer is no, that is the first bug to fix this week. A notebook that only works the way you originally ran it is not a project -- it is a record of a project you once ran.`,

  mastery_questions: [
    `Implement k-fold cross-validation (k=5) on your capstone model. Use sklearn's cross_validate with scoring for at least two metrics. Paste the per-fold scores and the mean plus standard deviation for each metric. If the standard deviation is more than 5% of the mean, write one sentence about what might be causing high variance -- small dataset, high-variance model, or leakage in preprocessing that was not caught.`,
    `Write a reproducible pipeline script (pipeline.py or a Makefile). The script must: load raw data from a fixed path, run preprocessing, split (using a fixed random_state), train, evaluate, and write results to a results.json file. Paste the script entry point and the contents of results.json after one run. Run it twice and confirm the results.json is identical both times. If it is not, you have a non-deterministic step -- find and seed it.`,
    `Add business-metric evaluation. For a classification task: compute the expected cost using asymmetric costs (e.g., false negatives cost $10, false positives cost $1). Try two different decision thresholds (0.5 and a threshold you choose based on the cost asymmetry) and paste the expected cost for each. For a regression task: compute the percentage of predictions within 10% of the actual value (a business accuracy metric), not just RMSE. Paste the result. The question "what does it cost when the model is wrong?" should be answerable from your evaluation.`,
    `Add unit tests for at least two functions in your pipeline: one data preprocessing function and one feature engineering function. Use pytest. Each test should: call the function with known input, assert a specific output or property of the output. Paste the test file. The tests do not need to be comprehensive -- two working tests are worth infinitely more than zero tests for showing that you understand testable code.`,
    `Update the project README to reflect the new rigour. Add a "Results" section with the cross-validated metrics (mean ± std), the business metric, and one sentence each about what the metric means and whether it is good enough for the use case. A README that says "accuracy: 0.84" is less informative than one that says "5-fold CV accuracy: 0.84 ± 0.03 (range 0.81-0.87). False negative rate on minority class: 0.22, which represents a known limitation for deployment." Paste the updated Results section.`,
  ],

  common_mistakes: [
    `Fitting the scaler or encoder inside the cross-validation fold on the full training set before splitting. The correct way is to fit preprocessing on the training fold only, then transform both training and validation folds. Sklearn Pipelines handle this correctly; manual preprocessing often does not.`,
    `Using shuffled k-fold for time series data. K-fold shuffles the data before splitting, which leaks future information into training. For time series, use TimeSeriesSplit from sklearn, which respects the temporal order.`,
    `Reporting the best fold's metric instead of the mean. The best fold is the luckiest fold. Report mean ± std so readers can see the variance.`,
    `Writing tests that test the framework, not your code. If your test calls pd.read_csv and asserts that the result is a DataFrame, you are testing pandas, not your preprocessing. Test your specific transformations with specific expected outputs.`,
    `Not setting random_state in every stochastic step of the pipeline. One unfixed seed means the results change on every run. Audit every call that accepts random_state or seed and set them all explicitly.`,
  ],

  debug_help: `The most common reproducibility failure is a step that reads from an external source (an API, a file path that is relative rather than absolute, or a database that has changed). Make all external dependencies explicit and document them. If the data comes from an API, save the raw response to a file with a timestamp and read from that file in subsequent runs. The pipeline should be able to run offline, on raw saved data, and produce identical results to the original run.`,

  ai_assist: `Use Claude to review your test file. Ask it: "Are these tests actually testing my code, or are they testing the libraries I use? What edge cases are missing?" The edge cases it names (empty input, nulls in a column, a zero-length time window) are the ones that will cause runtime failures in production. Do NOT ask Claude to write the tests -- writing tests requires understanding what your function is supposed to do and what counts as failure, which is knowledge you built this week.`,

  stretch: [
    `Set up pytest with coverage (pytest --cov) and report the coverage percentage for your pipeline module. Getting coverage above 70% on a data science project is harder than it sounds because data loading functions are hard to test without real data. The attempt to cover them teaches you which parts of your code are fragile.`,
    `Add a data validation step to the pipeline using Great Expectations or pandera: assert that the input data has the expected columns, the expected dtypes, and that key columns are within expected ranges. If the validation fails, the pipeline exits with a clear error rather than producing wrong results silently.`,
    `Try Weights & Biases (wandb) as an alternative to MLflow for experiment tracking. Log the cross-validation run as a sweep. The comparison between the two tools -- ease of setup, UI quality, collaboration features -- is worth 30 minutes of hands-on experience.`,
  ],
});
