/**
 * v2 rewrite batch 8: data-science Weeks 38-43
 *  W38: Capstone v0.3 — Polish + deploy
 *  W39: Capstone v1.0 — Ship + interview-ready story
 *  W40: Reinforcement Learning — the practical intro
 *  W41: Recommender Systems — the algorithms behind every feed
 *  W42: Distributed ML — when your data does not fit on one laptop
 *  W43: Privacy and Differential Privacy — the senior-DS topic nobody teaches
 */

import { rewriteWeek } from "../rewrite-week";

// ─── W38 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 38, {
  context: `Last week you added rigour to the capstone: cross-validation, a reproducible pipeline, multi-metric evaluation, unit tests. This week you make it presentable. Not beautiful -- presentable. There is a meaningful difference. Beautiful takes weeks. Presentable takes one.

Dead code is the first thing to remove. Every project accumulates it: the cell you ran to debug something at 2am, the function you wrote before you changed direction, the commented-out import from a library you tried and abandoned. A hiring manager or collaborator who opens the repo and encounters dead code draws an inference about how you work. That inference is not flattering. Run through every file and delete anything that is not part of the current pipeline.

Docker is the packaging layer. You built a Dockerfile for the FastAPI API in week 19 and understand the basics. This week you write a Dockerfile for the capstone pipeline itself: an image that contains the Python environment, the raw data (or a download script), and the pipeline entry point. Someone who has never seen your project should be able to run docker run and get the results.json file produced in week 37. No setup instructions, no "you also need to install X," no "it only works on Mac." The image is the environment.

The portfolio README is the last piece. It is not the project's README -- it is the document that explains the capstone to a stranger who found it through your GitHub profile. It answers four questions: what problem does this solve, what data did you use, what did you find, and how do I see it working. The "how do I see it working" answer should be one command. A demo that requires five minutes of setup will not be demoed.

By Sunday: a clean repo with no dead code, a working Dockerfile, a deployed public endpoint, and a portfolio README that answers all four questions in under 400 words.`,

  pre_flight: `Open every file in the repo and flag any code that is not part of the pipeline described in the README. Write the list. Everything on the list gets deleted or moved to an archive/ folder before you write any new code this week. Cleaning before adding is harder than adding before cleaning.`,

  mastery_questions: [
    `Delete all dead code from the repo. Run git diff --stat to confirm the removals. Paste the line count before and after (git ls-files | xargs wc -l). It is normal and good for the line count to drop this week. Now run the pipeline top-to-bottom one more time to confirm nothing you deleted was actually used. If something breaks, you found a hidden dependency -- fix it before moving on.`,
    `Write the Dockerfile for the capstone pipeline. It must: use a pinned base image (python:3.11.9-slim, not python:latest), install dependencies from requirements.txt, copy the pipeline source, and have a CMD that runs pipeline.py. Paste the Dockerfile. Run docker build and docker run locally. Paste the final line of docker run output -- it should be the metrics from results.json. If docker run fails with a file not found error, the raw data is not in the image. Either COPY it in or add a download step to pipeline.py.`,
    `Deploy the capstone output to a public host. If it is a model: deploy the inference endpoint to Hugging Face Spaces. If it is a dashboard: deploy to Streamlit Community Cloud. If it is a notebook with outputs: publish it on Kaggle or GitHub. Paste the public URL. Confirm it loads in an incognito tab in under 10 seconds. An app that takes 30 seconds to cold-start will not be demoed by a recruiter.`,
    `Write the portfolio README. Maximum 400 words. Four sections: Problem (one sentence), Data (source, size, time range), Findings (the two or three most interesting results from the multi-metric evaluation in week 37), How to run (one command to see the model working). Paste the README. Read it aloud and time it -- if it takes more than 90 seconds, cut it. The stranger reading your GitHub profile is giving you 30 seconds, not 90.`,
    `Add docstrings to every function in the pipeline that does not have one. The docstring format does not matter -- what matters is that it says what the function does, what the inputs are, and what it returns. Run pydoc pipeline to confirm all public functions are documented. Paste the pydoc output for your most complex function. Code that is hard to document is usually code that does too many things at once -- if writing the docstring reveals this, refactor the function.`,
  ],

  common_mistakes: [
    `Using python:latest as the base image in the Dockerfile. "Latest" is a moving target -- six months from now it will be a different Python version and your build might break. Always pin: python:3.11.9-slim.`,
    `Not testing the Docker image on a clean machine or a fresh environment. The image builds on your machine where some environment variable or system library might be present that is not in the Dockerfile. The test for a working Docker image is "does it run from a fresh docker pull with no other setup?"`,
    `Writing a portfolio README that describes the process ("first I loaded the data, then I cleaned it...") instead of the findings ("the model achieved X on Y dataset, outperforming the baseline by Z%"). Process is in the notebook. Findings are in the README.`,
    `Deploying an application that requires API keys or environment variables without documenting how to set them. If your app needs an OPENAI_API_KEY to run, the README must say so explicitly and explain how to get one. Undocumented dependencies are broken applications.`,
    `Skipping the "one command to run" requirement and writing five setup steps instead. Every additional setup step loses roughly half the people who would otherwise have tried the demo. The friction is real.`,
  ],

  debug_help: `The most common Docker issue is "ModuleNotFoundError" inside the container for a package that is installed on your local machine. This means the package is not in requirements.txt. Run pip freeze > requirements.txt before building -- but also review the output, because pip freeze includes everything in your virtual environment, some of which may be system-specific and break the Docker build. Use pip-tools or manually curate requirements.txt to only include the packages your pipeline actually imports.`,

  ai_assist: `Use Claude to generate docstrings for your pipeline functions. Paste the function body and ask for a NumPy-style or Google-style docstring. Review each generated docstring for accuracy -- if the docstring is wrong about what the function does, the function is probably doing something different from what you intended. A wrong docstring is useful information.`,

  stretch: [
    `Set up GitHub Actions CI that runs the pipeline on every push and posts the results.json metrics as a comment on the commit. A project with automated testing and automated metric reporting is a project that a team could actually maintain.`,
    `Write a CONTRIBUTING.md that explains how to set up the development environment, run the tests, and add a new model to the comparison table. Writing this document reveals exactly which parts of your project have undocumented assumptions.`,
    `Profile the pipeline and identify the slowest step (cProfile or line_profiler). Report the runtime of each major step in the README. Knowing where the bottleneck is matters when someone asks "how long does this take to retrain?"`,
  ],
});

// ─── W39 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 39, {
  context: `The capstone is deployed. The code is clean. The Docker image runs. This week the work is entirely about how you talk about what you built -- because the thing that converts a good project into a job offer is not the project itself, it is the story you tell about it.

Three different versions of the story exist, and you need all three. The 90-second elevator pitch: what you built, what you found, why it matters. Used in networking conversations, the end of a first-round call, LinkedIn messages. The five-minute walkthrough: the pitch plus the methodology, the key decision points, the results. Used in technical phone screens. The 30-minute deep-dive: the walkthrough plus a discussion of what you tried that did not work, the trade-offs you made, the things you would do differently. Used in the technical interview's project discussion round.

The most common mistake in all three versions is starting with the methodology. "I used a random forest with 200 trees and..." is not an opening sentence. The opening sentence names the problem and why it matters. "Power utilities need accurate 24-hour demand forecasts to avoid both blackouts and wasted standby capacity. I built a model that..." -- that is an opening sentence. Methodology is the evidence for a claim. The claim comes first.

Senior interviewers test one specific thing in the project discussion: whether you know where your model fails. The candidate who says "it performed well on the test set" and moves on gets a lower signal than the candidate who says "it performed well on stable periods but consistently underestimated demand during heat waves, because temperature is not a feature in the model." Knowing your model's failure modes, being able to name them specifically, and having a hypothesis about why they exist -- that is the senior-DS signal.

By Sunday: three written versions of the capstone story (90s, 5min, 30min), recorded practice answers to five common interview questions, and the RETRO.md for this project written and committed.`,

  pre_flight: `Read the job description for three roles you actually want to apply for. Write down the two or three technical skills each one emphasises. Then map your capstone to each: which aspect of the capstone is most relevant to each role? A recommender system project maps differently to a consumer tech role than to an analytics role. The mapping exercise prepares you to customise the story without inventing new facts.`,

  mastery_questions: [
    `Write the 90-second elevator pitch for the capstone. One sentence on the problem. One sentence on the data. One sentence on the method (high-level). One sentence on the key finding. One sentence on what you would do next. That is five sentences. Time yourself reading it aloud -- it should be 75-95 seconds. Paste the text. If it is a paragraph of more than 100 words, it is not an elevator pitch -- it is a summary, and summaries do not survive interruption.`,
    `Write the 5-minute walkthrough. The pitch (above), expanded. Add: why you chose this dataset over alternatives, what the baseline was and why it matters, what you tried that did not work (one specific thing), the final model choice and the metric it achieved, and one sentence on limitations. Practise it aloud until it takes 4-5 minutes and not 8. Recording yourself and listening back is not optional -- you will catch two problems you cannot catch by reading.`,
    `Write detailed answers to three senior-DS interview questions about the capstone: (1) "What would you do if the model's performance degraded in production?" (2) "How did you decide which metric to optimise?" (3) "Walk me through a decision you made that you would make differently now." Each answer should be 60-90 seconds when spoken aloud. Paste all three. The answers should be specific to your project, not generic -- "I would monitor for data drift using Evidently and retrain monthly using the MLflow pipeline from week 25" is specific. "I would monitor the model" is not.`,
    `Write RETRO.md for the capstone. Required: what the biggest technical challenge was (and how you solved it), what you underestimated (time, difficulty, or complexity of a specific step), what the most interesting finding was, and what you would add with two more weeks. Paste the file. This retro closes the project. A project without a retro is a project you cannot learn from systematically.`,
    `Submit two job applications this week for roles where the capstone is directly relevant. Paste the company names and role titles. In the cover letter or application notes, reference the capstone specifically: "I recently built a [one-sentence description] -- the project and write-up are at [URL]." A referenced project that is live and linkable is the single most effective thing you can add to a data science application.`,
  ],

  common_mistakes: [
    `Opening the project story with methodology. "I used XGBoost with a learning rate of 0.01..." is not a hook. Start with the problem and why it matters. The methodology is the middle of the story, not the beginning.`,
    `Claiming your model "performs well" without specifying the metric and the baseline. "Performs well" means nothing. "Achieves 82% F1 on the held-out test set, compared to a 71% F1 majority-class baseline" means something. Be specific every time.`,
    `Saying "I would improve the model by adding more data" when asked about limitations. This is the vague answer every interviewer hears 20 times per week. The specific answer is "the model underestimates demand during periods of unusual weather because temperature is not a feature -- adding NOAA hourly temperature data as an external regressor would likely close that gap."`,
    `Practising interview answers by reading them silently. You interview by speaking. The answer that reads perfectly takes 6 minutes to speak and trails off at the end. Practise out loud, time yourself, and stop when time is up even if you are not finished.`,
    `Not applying because the job posting requires 3 years of experience and you have less. Job postings describe the ideal candidate, not the minimum viable one. If you can do 70% of the listed work and have the projects to demonstrate it, apply. The worst outcome is silence -- which is the same as not applying.`,
  ],

  debug_help: `If the interview story feels flat when you say it aloud, the problem is almost always that it is a description instead of a story. A description tells what happened. A story has a problem, a complication, and a resolution. The problem is the business need. The complication is the thing that made it hard (the data was messy, the first model did not beat the baseline, the evaluation metric kept changing). The resolution is what you shipped and what it showed. If your pitch does not have a complication, add one -- every real project had one.`,

  ai_assist: `Use Claude to play interviewer. Paste your 5-minute walkthrough and ask it to ask you three follow-up questions a senior DS interviewer would ask. Answer those questions in writing, then practise them out loud. The follow-up questions reveal the gaps in your story that you had not anticipated. Do NOT ask Claude to write the interview answers. The answers are yours -- they describe what you built, what you decided, and what you learned. Claude can generate plausible-sounding answers, but a plausible-sounding answer about a project you barely understand will collapse under a single follow-up.`,

  stretch: [
    `Do one real mock technical interview through Pramp or Interviewing.io. Ask the interviewer specifically to push back on your project answers -- "tell me something that went wrong." One session of real-time pressure is worth more preparation than 10 hours of solo practice.`,
    `Write a 200-word LinkedIn post about the capstone with one chart from the project. Post it. The act of posting public technical writing, however small, is the habit that compounds into a professional reputation over 3 years.`,
    `Read "Cracking the PM Interview" (Gayle Laakmann McDowell, the chapter on analytical interviews). The analytical interview format used at Google, Meta, and Amazon maps almost exactly to how senior DS candidates are evaluated on case studies. Knowing the format before you see it is a significant advantage.`,
  ],
});

// ─── W40 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 40, {
  context: `Supervised learning requires labelled data: you feed the model input-output pairs and it learns to predict the output. Reinforcement learning is a different contract: you give the model an environment, a set of possible actions, and a reward signal, and it learns a policy by trying things and observing the consequences.

The canonical RL example is a game-playing agent -- AlphaGo, OpenAI Five. Those are real and impressive. They are also not what most data scientists encounter in practice. The RL application that actually appears in industry is the contextual bandit: a simpler setting where there is no state that carries over between decisions, just a context (who is this user, what is this situation), a set of actions (which article to show, which price to offer, which treatment to recommend), and a reward (did they click, did they buy, did they recover). Netflix's thumbnail selection, Spotify's playlist ordering, Booking.com's offer ranking -- all contextual bandits at their core.

Q-learning is the foundational algorithm for full RL. It learns an action-value function Q(s, a) -- the expected future reward of taking action a in state s. Once the Q-function is learned, the optimal policy is just "take the action with the highest Q-value in the current state." You will implement Q-learning on a simple grid environment (OpenAI Gym's FrozenLake or Taxi) not because you will use it in production, but because implementing it once makes RL click in a way that reading about it never does.

The contextual bandit you build this week is the production-relevant piece. You have a context (a feature vector), you take an action, you observe a reward. The epsilon-greedy strategy -- explore randomly with probability epsilon, exploit the current best action otherwise -- is the simplest approach that works. By Sunday you will have implemented both the foundational algorithm and the practical one, and you will understand why the practical one is used in production.`,

  pre_flight: `Install gymnasium (the maintained fork of OpenAI Gym): pip install gymnasium. Open a Python shell and run import gymnasium as gym; env = gym.make('FrozenLake-v1'); print(env.observation_space, env.action_space). Paste the output. Write down what the state space and action space represent physically (the grid, the four directions). You will write code that navigates this environment before writing anything more abstract.`,

  mastery_questions: [
    `Implement Q-learning on FrozenLake-v1. Initialise a Q-table of shape (state_space, action_space) to zeros. For 10,000 episodes: reset the environment, select an action using epsilon-greedy (random with probability epsilon, argmax(Q[state]) otherwise), step the environment, update Q[state, action] += alpha * (reward + gamma * max(Q[next_state]) - Q[state, action]). Paste the Q-table update formula and the average reward over the last 100 episodes. Train until average reward is above 0.5. How many episodes did it take?`,
    `Visualise the learned policy: for each cell of the 4x4 FrozenLake grid, print the greedy action (the argmax of the Q-values). Paste the grid. Does the policy make spatial sense -- does it route around the holes? Where does it fail? Write one sentence about the failure case -- Q-learning on FrozenLake with a fully random start can converge to a suboptimal policy if it never discovers certain paths in early exploration.`,
    `Implement a contextual bandit. Context: a feature vector of 5 random features representing a "user." Actions: 3 options (e.g., article A, B, C). Reward: a function of context and action that you define (e.g., action A rewards well for users with feature_1 > 0.5, action B for the rest). Implement epsilon-greedy: with probability epsilon, choose a random action; otherwise, use a linear model per action to predict reward and choose the highest. After 1000 steps, paste the cumulative reward curve. Does it increase over time? A flat curve means the bandit is not learning.`,
    `Compare three exploration strategies on the same contextual bandit: epsilon-greedy (epsilon=0.1), epsilon-greedy (epsilon=0.3), and pure exploitation (epsilon=0). Plot cumulative reward over 1000 steps for all three. Paste the plot. Write one sentence about the exploration-exploitation trade-off you observe: high epsilon explores more early, low epsilon exploits faster but might get stuck in a suboptimal policy.`,
    `Write a one-paragraph explanation of when you would use RL versus supervised learning for a business problem. Use a specific example from a domain you know. The distinguishing question is: is there a delayed reward that depends on a sequence of decisions, or is each prediction independent? Netflix thumbnail selection is a bandit (each impression is independent). Drug dosing over a hospital stay is full RL (each dose affects future state). Write the paragraph and paste it.`,
  ],

  common_mistakes: [
    `Setting epsilon to 0 too early and converging to a suboptimal policy. Exploration needs to persist long enough to discover all relevant states. Use epsilon decay: start at 1.0 and multiply by 0.999 each episode.`,
    `Forgetting to discretise continuous state spaces before using a Q-table. Q-tables work on discrete states. FrozenLake is discrete by design, but custom environments often have continuous states -- those require function approximation (a neural network as the Q-function), not a table.`,
    `Mixing up the contextual bandit setting with full RL. In a bandit, there is no state that carries over -- each decision is independent given the context. Applying full RL machinery (Q-learning with temporal credit assignment) to a bandit problem adds complexity without benefit.`,
    `Using cumulative reward as the only metric. Cumulative reward grows over time by definition (as long as rewards are positive). What you care about is average reward per step over time, specifically whether it improves as the agent learns.`,
    `Not resetting the environment before each episode. env.reset() must be called at the start of each episode, not just once before the training loop.`,
  ],

  debug_help: `The most common Q-learning bug is the update formula. The correct formula is: Q[s,a] = Q[s,a] + alpha * (reward + gamma * max(Q[s_next]) - Q[s,a]). Two common errors: (1) using reward - Q[s,a] without the gamma * max(Q[s_next]) term -- this is a single-step update that ignores future rewards. (2) using Q[s_next, a_next] instead of max(Q[s_next]) -- this is SARSA (on-policy), which converges to a different policy than Q-learning (off-policy). Know which you are implementing.`,

  ai_assist: `Use Claude to explain the Bellman equation in plain English: "What does the Bellman optimality equation for Q-learning say in words, and why does it allow the agent to learn from delayed rewards?" Understanding the Bellman equation is what makes RL stop being magic and start being a specific algorithm with specific convergence guarantees. Do NOT use Claude to debug your Q-learning implementation by pasting the whole code -- diagnose it yourself first by printing Q[s,a] values after each episode and checking whether they change. If they do not change, the update step is not executing.`,

  stretch: [
    `Try Deep Q-Networks (DQN) on CartPole-v1 using PyTorch. Replace the Q-table with a small neural network. The architecture change is minor; the conceptual leap (a neural network approximating the Q-function) is major and foundational to all modern deep RL.`,
    `Read "Reinforcement Learning: An Introduction" by Sutton and Barto, Chapters 1 and 2 (free online). Chapter 2 covers the multi-armed bandit -- the simplest case of exploration vs. exploitation -- with rigour. It is short, clear, and foundational.`,
    `Find one real-world case study of a contextual bandit in production (Netflix, LinkedIn, and Yahoo all have published papers). Note what the context features were, what the actions were, and how they measured success. Seeing the production version makes the classroom version make more sense.`,
  ],
});

// ─── W41 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 41, {
  context: `Recommender systems are the most-interviewed DS topic at consumer technology companies. Amazon's product recommendations, Netflix's watch queue, Spotify's Discover Weekly, TikTok's For You page -- all of these are recommender systems in production at massive scale. The technical interview at any of those companies, at any DS level, will include some version of "how would you build a recommender system for X?"

The three approaches you will compare this week represent three generations of the field. Collaborative filtering is the oldest: find users similar to you, recommend what they liked. The intuition is clear. The cold start problem -- what do you recommend to a new user with no history? -- is the central limitation. Matrix factorisation (SVD or ALS) is the second generation: decompose the user-item interaction matrix into lower-dimensional user and item embeddings, then predict missing ratings as the dot product of the two embeddings. This is what Netflix's winning algorithm from their 2009 $1 million prize competition used. The two-tower deep learning architecture is the current production standard: a neural network that separately encodes user features and item features, trains them jointly to maximise the dot product for observed interactions, and at inference time retrieves candidates by approximate nearest neighbour search over the item embedding space.

The MovieLens 100K dataset is the standard benchmark. One hundred thousand ratings from 943 users on 1682 movies. Every technique you implement will be evaluated on the same test split using the same metrics: Precision@10 (of the 10 movies you recommended, how many did the user actually rate positively?) and NDCG@10 (the ranking-aware version, which rewards putting the best items at the top of the list).

By Sunday: all three approaches implemented, evaluated on the same test split, and an honest comparison table with recommendations for when you would use each in a production context.`,

  pre_flight: `Download MovieLens 100K from grouplens.org (it is 5MB). Open the u.data file in a text editor and look at the format: user_id, item_id, rating, timestamp. Four columns. Write down: what is the sparsity of the user-item matrix? (100K ratings over 943 users x 1682 movies = 100K / (943 * 1682) = about 6.3% density -- 94% of the matrix is missing.) High sparsity is the fundamental challenge of recommender systems, and knowing your specific number makes the algorithm choices concrete.`,

  mastery_questions: [
    `Build the user-based collaborative filtering baseline. For each test user, find the K=20 most similar users (cosine similarity on the rating vectors), aggregate their ratings with similarity weights, and predict ratings for items the test user has not seen. Paste Precision@10 on the test set. Write one sentence about why collaborative filtering fails for new users with fewer than 5 ratings -- hint: sparse rating vectors produce unreliable similarity scores.`,
    `Apply SVD matrix factorisation using the Surprise library (from surprise import SVD). Train on your training split with n_factors=50. Evaluate on the test split. Paste RMSE and Precision@10. Compare to the collaborative filtering baseline. Now inspect the item embedding matrix: find two movies that are close in embedding space. Do they seem similar to a human? Write one sentence about what the SVD has implicitly learned.`,
    `Implement a two-tower architecture using PyTorch. User tower: embed user_id into 32 dimensions. Item tower: embed item_id into 32 dimensions. Training objective: maximise the dot product of (user_emb, item_emb) for observed positive interactions (rating >= 4), minimise it for sampled negatives. Paste the model definition and the training loss after 10 epochs. At inference time, retrieve the top 10 items for a test user by computing dot products with all item embeddings. Paste Precision@10.`,
    `Build the comparison table: collaborative filtering, SVD, two-tower -- Precision@10 and NDCG@10 for each, on the same test split. Paste the table. Now answer: which model would you recommend for (a) a startup with 10,000 users and 6 months of history, (b) a company with 50 million users and 10 years of history, (c) a new product with zero user history? The right answer differs for each scenario and requires reasoning about cold start, data scale, and training cost.`,
    `Address the cold start problem for new items. When a new movie is added with zero ratings, collaborative filtering and matrix factorisation cannot recommend it. Write and implement one cold start strategy: content-based fallback (use movie genre and year as features to find similar rated items), popularity-based (recommend new items based on early aggregate ratings), or bandit-based (explore new items with a small random traffic allocation). Paste the code. Write one sentence about the trade-off your chosen strategy makes.`,
  ],

  common_mistakes: [
    `Evaluating on the full rating matrix instead of a proper train/test split. Recommender systems must be evaluated on ratings the model did not see during training. Use leave-one-out (hold out the last rating per user) or a temporal split (train on ratings before a date, test on ratings after).`,
    `Using RMSE as the only metric. RMSE measures prediction accuracy for explicit ratings -- how close is your predicted 3.8 to the actual 4? But most modern recommender systems use implicit feedback (clicks, watches, purchases) and rank-based metrics (Precision@K, NDCG@K) that measure whether the right items appear at the top of the list. Report both.`,
    `Not sampling negatives for the two-tower model. The model should see roughly equal numbers of positive and negative examples during training. If you only train on observed interactions (all positives), the model has never seen a negative and will assign high scores to everything.`,
    `Ignoring the cold start problem in the write-up. Every recommender system has a cold start problem. A project that does not mention it implies you did not notice it.`,
    `Comparing models trained on different data. All three approaches must use the same training split and be evaluated on the same test split for the comparison table to be valid.`,
  ],

  debug_help: `The two-tower model's most common failure is that training loss decreases but Precision@10 does not improve. Usually this means the negative sampling is wrong -- you are sampling negatives uniformly at random from all items, but many of those "negatives" are items the user simply has not rated yet (not necessarily disliked). Try harder negatives: sample negatives from items the user's similar users rated highly (items the model should rank lower, but which look plausible). Harder negatives produce faster, more meaningful convergence.`,

  ai_assist: `Use Claude to explain the intuition behind why the ALS (Alternating Least Squares) optimisation for matrix factorisation works -- specifically, why alternating between fixing user embeddings and fixing item embeddings converges to a solution. The intuition (each sub-problem is a convex least squares when the other is fixed) is what makes the algorithm stop being mysterious. Do NOT use Claude to write the two-tower PyTorch code. Writing a training loop with negative sampling from scratch is the skill -- the understanding that comes from implementing it is not transferable from reading someone else's implementation.`,

  stretch: [
    `Add side features to the two-tower model: concatenate movie genre one-hot vectors to the item embedding, and user age and gender to the user embedding. Measure the change in Precision@10. Side features often help most for cold start -- a new movie with genre features can be embedded even with zero ratings.`,
    `Implement approximate nearest neighbour retrieval using FAISS for the two-tower at inference time. For 1682 items the brute-force dot product is fine. For 10 million items it is not. Understanding the retrieval step is what makes the two-tower production-viable at scale.`,
    `Read "Deep Neural Networks for YouTube Recommendations" (Covington et al., 2016). It is the paper that established the two-tower architecture at production scale. Section 3 covers the candidate generation network -- the same architecture you just built, with the engineering decisions that made it work at YouTube scale.`,
  ],
});

// ─── W42 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 42, {
  context: `This week is about knowing when you need distributed computing -- and when you do not. The second lesson is at least as important as the first.

Most "big data" problems that data scientists encounter in practice are not actually big data problems. A dataset with 50 million rows and 20 columns is about 8GB in memory. A machine with 32GB of RAM -- which costs less than $200 per month on AWS -- fits it comfortably. PySpark on a cluster costs more, takes longer to set up, and runs the same query 3x slower than pandas on a single large machine, because network overhead and serialisation costs eat the parallelism gains for anything under a few hundred gigabytes. The decision to scale out (more machines) versus scale up (a larger machine) is one of the most frequently misjudged calls in data engineering.

Dask is the honest middle ground. It extends the pandas API to datasets larger than RAM on a single machine by processing chunks lazily. For datasets between 10GB and 500GB that are not already in a distributed system, Dask is often the right tool. It integrates with sklearn (dask-ml), runs locally with no cluster setup, and produces results in the same format as pandas. The trade-off is that it is slower than pandas for datasets that fit in RAM, and slower than Spark for datasets that truly require cluster distribution.

PySpark is the industry standard for true distributed workloads: hundreds of gigabytes to petabytes, cluster execution, fault tolerance for long-running jobs. The key conceptual shift from pandas is that Spark is lazy -- transformations are not executed until an action (collect, write, count) triggers execution. This laziness is what allows Spark to optimise the query plan before running. Understanding lazy evaluation is what separates a Spark user from a Spark debugger.

By Sunday: the same analytical task implemented in pandas, Dask, and PySpark, with an honest runtime comparison and a one-page memo on when you would choose each.`,

  pre_flight: `Identify a dataset from your earlier projects that is as large as possible. If none is above 500MB, generate a synthetic dataset: import pandas as pd; import numpy as np; df = pd.DataFrame(np.random.randn(10_000_000, 10), columns=[f'col_{i}' for i in range(10)]); df.to_parquet('big_data.parquet'). Ten million rows at ten columns is about 800MB on disk. Write the file and confirm its size with ls -lh. This is your benchmark dataset for the week.`,

  mastery_questions: [
    `Run a groupby-aggregation on the dataset using pandas. Time it with %%timeit. Paste the operation, the result shape, and the wall time. Also check memory usage during the operation (memory_profiler or psutil). Does the operation fit in RAM? Pandas loads the entire dataset into memory before operating -- for datasets larger than available RAM, this fails with a MemoryError. That failure mode is what motivates everything else this week.`,
    `Run the same groupby-aggregation using Dask. Create a Dask DataFrame (dask.dataframe.read_parquet), run the same groupby, call .compute() to trigger execution. Paste the result (it must match the pandas result exactly) and the wall time. Is Dask faster or slower than pandas on this dataset? Write one sentence explaining why -- Dask parallelises the computation across cores but has overhead for partitioning and combining results, so for datasets that fit in RAM, pandas is often faster.`,
    `Start a local PySpark session (SparkSession.builder.master("local[*]").getOrCreate()). Read the parquet file into a Spark DataFrame. Run the same groupby-aggregation. Paste the result and the wall time. Now run df.explain() and paste the query plan. The query plan shows you what Spark will execute before it executes it -- the "Exchange" operations (shuffles) are the expensive steps. Understanding the plan is what separates someone who uses Spark from someone who can optimise Spark.`,
    `Build the runtime comparison table: operation, pandas time, Dask time, PySpark time. Paste the table. Now write the one-page memo: when would you choose pandas (dataset < RAM, interactive exploration, ad-hoc analysis), Dask (dataset > RAM on a single machine, existing pandas code to scale, no cluster available), and PySpark (dataset is hundreds of GB or TB, cluster is already provisioned, fault tolerance is required). The memo is the deliverable -- the table is evidence for it.`,
    `Implement a sklearn model training step using dask-ml: a distributed train/test split and a distributed LogisticRegression fit. Paste the dask-ml code. Compare training time to sklearn on the same data sample. Note: dask-ml does not support all sklearn models -- some require explicit conversion. Write one sentence about which use cases benefit most from distributed ML training versus simply using a larger single machine.`,
  ],

  common_mistakes: [
    `Using Spark for a 1GB dataset because "it is best practice." Spark has significant startup overhead (several seconds just to initialise the session) and is slower than pandas for small data. Choose the tool to the problem size, not to what sounds impressive.`,
    `Calling .collect() on a large Spark DataFrame to view results. collect() pulls the entire distributed dataset back to the driver -- for a 1TB table, this crashes the driver. Use .show(20) or .limit(100).toPandas() to inspect results without materialising everything.`,
    `Not partitioning data correctly before joining. Spark joins trigger shuffles -- moving data across the network between executors -- unless the data is pre-partitioned on the join key. A join without proper partitioning on a large table is the most common source of PySpark performance disasters.`,
    `Ignoring the lazy evaluation model in Dask. Dask computations do not execute until .compute() is called. Chaining multiple operations without calling .compute() is fine and often more efficient. Calling .compute() after every operation kills the performance benefits.`,
    `Comparing pandas, Dask, and PySpark on the same machine without noting that PySpark and Dask are designed to scale out to clusters. The local comparison is useful for understanding overhead, but the production case (1TB dataset, 20-node cluster) is where PySpark's architecture produces real gains.`,
  ],

  debug_help: `Two common PySpark issues. First: "Java heap space" error. Increase driver memory in SparkConf: spark.driver.memory = "4g". Second: Spark job runs but produces wrong results on grouped aggregations. Usually a data skew issue -- one partition has 90% of the data for a specific key value, which causes one executor to do all the work and possibly run out of memory. Fix with repartition on the join/group key before the expensive operation. For Dask: "MemoryError during compute" -- your partitions are too large. Re-read the file with npartitions=20 or blocksize="128MB" to create smaller, more manageable chunks.`,

  ai_assist: `Use Claude to explain the difference between Spark RDDs and DataFrames in plain English, and why you should almost always use DataFrames. The answer involves the Catalyst optimizer -- a query planner that can only optimise DataFrame operations, not arbitrary RDD transformations. Understanding this is what lets you answer "why DataFrames over RDDs?" in a Spark interview. Do NOT ask Claude to write the PySpark groupby -- write it yourself, make it fail, read the error, and fix it. The error messages in PySpark are verbose but informative, and learning to read them is the skill.`,

  stretch: [
    `Profile a PySpark job using the Spark UI (http://localhost:4040 while the job runs). Find the slowest stage and identify whether it is compute-bound or shuffle-bound. A shuffle-heavy job benefits from repartitioning; a compute-heavy job benefits from caching intermediate results.`,
    `Try Polars as a fourth comparison. Polars is a Rust-based DataFrame library that outperforms pandas by 5-20x on most operations for datasets that fit in RAM. Its lazy API (polars.scan_parquet instead of polars.read_parquet) also handles datasets larger than RAM. The benchmark comparison against pandas, Dask, and PySpark on the same operation is a genuinely informative experiment.`,
    `Read "The Databricks Lakehouse Platform" white paper (free). Databricks is the company built on top of Apache Spark and is where most enterprise PySpark usage lives. Understanding the Lakehouse architecture (Delta Lake + Spark + MLflow) is understanding where large-scale data science actually happens.`,
  ],
});

// ─── W43 ───────────────────────────────────────────────────────────────────────
rewriteWeek("data-science", 43, {
  context: `The data science roadmap ends where the hard problems actually begin: privacy.

Every dataset you have worked with this year contained real information about real things -- taxi trips, electricity demand, Reddit posts. Real datasets are often about real people. And real people have a reasonable expectation that their individual data will not be exposed by models trained on it, even if the model was trained for a legitimate purpose.

The naive answer to privacy is anonymisation: remove names, phone numbers, addresses, and the data is anonymous. This is wrong. Latanya Sweeney demonstrated in 2000 that 87% of Americans could be uniquely identified by just three variables: zip code, date of birth, and gender. The Netflix Prize dataset was "anonymised" -- user IDs replaced with random numbers -- and was de-anonymised by cross-referencing with public IMDb reviews within weeks of release. Anonymisation that removes obvious identifiers is not a privacy guarantee. It is a speed bump.

Differential privacy (DP) is a formal privacy guarantee. A mechanism is epsilon-differentially private if adding or removing one person's data from the dataset changes the output distribution by at most a factor of e^epsilon. Smaller epsilon means stronger privacy. The Laplace mechanism adds noise calibrated to the sensitivity of the query and the privacy budget. Apple uses differential privacy in iOS to aggregate typing statistics. Google uses it in Chrome to aggregate browser statistics. The US Census Bureau used it to publish the 2020 Census results.

The privacy budget (epsilon) is the trade-off. Lower epsilon means more noise, which means less accurate results. A query on a dataset with epsilon=1 is strongly private and somewhat noisy. With epsilon=10, the result is nearly exact but the privacy guarantee is weak. Knowing this trade-off is what lets you answer "how private is this?" rather than "is it private?" -- a fundamentally more honest framing.

By Sunday: a hands-on DP notebook showing Laplace noise addition, a privacy budget analysis, and PRIVACY.md added to one of your existing projects documenting the privacy considerations of that model.`,

  pre_flight: `Before writing any code, write down two pieces of information about your project dataset that a malicious actor could exploit if the model's training data were exposed. For the NYC taxi dataset: a high-value individual's home address could be inferred from their frequent pickup location. For energy demand: an individual household's schedule (when they sleep, when they leave for work) could be inferred from fine-grained smart meter data. Knowing what you are protecting before applying privacy tools is the difference between principled privacy engineering and security theatre.`,

  mastery_questions: [
    `Implement the Laplace mechanism from scratch. For a counting query q on your dataset, compute the true answer, add Laplace noise with scale = sensitivity / epsilon, and compare to the true answer. Sensitivity for a count query is 1 (one person's presence changes the count by at most 1). Try epsilon = 0.1, 1.0, and 10.0. Paste the true answer and the noisy answer for each epsilon. Write one sentence interpreting the trade-off -- at epsilon=0.1, is the result usable? At epsilon=10.0, how much privacy protection does it actually provide?`,
    `Use the Opacus library (PyTorch differential privacy) to add DP-SGD to a simple training run. DP-SGD clips per-sample gradients and adds Gaussian noise before the parameter update, guaranteeing (epsilon, delta)-DP for the training process. Paste the Opacus PrivacyEngine setup code. Train for 5 epochs and paste the epsilon spent by epoch 5 (privacy_engine.get_epsilon(delta=1e-5)). Compare accuracy to the non-DP baseline. The accuracy drop is the cost of privacy -- document it honestly.`,
    `Run a re-identification attack on a sample dataset to demonstrate why anonymisation fails. Take 200 rows from your project data, remove the obvious identifying columns, then try to re-identify 5 rows using just 3 non-identifying columns (zip code, age bracket, profession, or their equivalents in your dataset). Paste how many of the 5 rows you successfully re-identified. If you matched even 2 out of 5, write one sentence about what this implies for the "anonymised" dataset.`,
    `Write PRIVACY.md for one of your existing projects. Required sections: Data collected (what personal or quasi-personal information the dataset contains), Re-identification risk (your assessment of whether individuals could be identified from the training data), Privacy controls applied (what was done -- anonymisation? DP? nothing?), Residual risk (what risks remain after the controls), Compliance notes (is this data subject to GDPR, HIPAA, CCPA, or other regulations?). Paste the file. "We are not storing personal data" is not a privacy analysis. A specific risk assessment is.`,
    `Compute the privacy cost of a machine learning training run using the Rényi differential privacy accountant in Opacus. The accountant tracks the cumulative privacy budget spent across all training steps. Paste the (epsilon, delta) guarantee for your training run. Write one sentence about how you would present this to a non-technical stakeholder -- the phrase "epsilon=2.5 with delta=1e-5" means nothing to a product manager; "adding or removing any individual's data from the training set changes the model's outputs by at most a factor of 12" is an approximation they can reason about.`,
  ],

  common_mistakes: [
    `Confusing epsilon=0 with perfect privacy. Epsilon=0 means no information is released -- the mechanism always outputs the same value regardless of the data. It is maximally private and maximally useless. Real applications use epsilon between 0.1 (strong, noisy) and 10 (weak, nearly exact).`,
    `Applying DP to the model outputs without applying it during training. Post-processing a non-DP model's outputs with noise does not provide the formal DP guarantee -- the guarantee must apply to the training process itself. Opacus's DP-SGD applies noise at training time.`,
    `Treating GDPR compliance as equivalent to differential privacy. GDPR is a legal framework about consent, data rights, and data minimisation. DP is a mathematical guarantee about information leakage. Both matter; neither implies the other.`,
    `Using the same privacy budget for exploratory analysis and for the final model. Exploratory queries spend epsilon. If you run 50 exploratory queries before training the model, your privacy budget is mostly consumed before the production use case. Budget the epsilon allocation before starting.`,
    `Not reporting the accuracy-privacy trade-off. DP always costs accuracy. A paper or project that reports DP guarantees without the accuracy cost is incomplete -- the cost is the whole point of the trade-off.`,
  ],

  debug_help: `Opacus raises "GradSampleModule" errors when the model architecture contains layers that are not supported for per-sample gradient computation (batch normalisation is the most common). Replace BatchNorm with GroupNorm before wrapping with Opacus -- GroupNorm computes statistics per sample rather than per batch, which is compatible with per-sample gradient clipping. Opacus's ModuleValidator.validate(model) will tell you exactly which layers are incompatible before you try to train.`,

  ai_assist: `Use Claude to explain the difference between (epsilon, 0)-DP (pure DP) and (epsilon, delta)-DP (approximate DP) in plain English. The delta parameter is often misunderstood -- it is not "probability of failure," it is a relaxation that allows the mechanism to have a small probability of leaking arbitrarily much. Understanding this distinction is what lets you answer "how private is delta=1e-5 really?" in a technical interview. Do NOT ask Claude to set your epsilon value. The epsilon choice is a domain-specific risk decision that depends on the sensitivity of the data, the population size, and the acceptable risk tolerance -- it cannot be made without that context.`,

  stretch: [
    `Implement federated learning simulation using PySyft or Flower (flwr). Train a model on 5 "clients" (data partitions) without any raw data leaving each partition -- only model updates are aggregated. The output is a model trained on distributed private data without centralising it. This is the architecture Apple uses for on-device learning and is increasingly required for healthcare and financial applications.`,
    `Read Apple's paper "Learning with Privacy at Scale" (2017). It describes the local differential privacy mechanism used to collect emoji usage statistics from iOS devices. The engineering decisions -- local versus central DP, the randomised response mechanism, the calibration of epsilon -- are the real-world application of everything you built this week.`,
    `Add a "Privacy Budget Tracker" to your RAG or capstone project: a running log of every query made against the dataset, with the epsilon spent per query and the cumulative budget consumed. This is the infrastructure that a production DP system requires -- knowing when you have spent your budget is as important as knowing how to spend it.`,
  ],
});
