/**
 * v2 rewrite: data-science Week 2 — "Math you actually need (lin alg + prob + stats)"
 * Run: npx tsx scripts/v2/ds-w02.ts
 */

import { rewriteWeek } from "../rewrite-week";

rewriteWeek("data-science", 2, {
  context: `Last week you loaded 3.5 million taxi trips and asked them questions. This week you go one floor deeper and learn what was actually happening underneath your code.

Every time you called df['fare_amount'].mean() last week, your laptop did a dot product — it multiplied a vector of numbers by a vector of ones and divided by the length. Every histogram you plotted was a probability distribution. Every "remove the impossible rows" decision you made was, implicitly, a Bayesian update. You did the math already. This week you find out it was math.

I am going to be honest with you about something. A lot of people skip this week. They tell themselves they will come back to the math later, after they have built more projects. They almost never do, and you can spot them in interviews from a mile away — they can call a model but they cannot tell you why it makes the prediction it makes. They are stuck doing junior work forever because they outsourced the part of the job that is hardest to outsource.

Five days of math. That is the entire ask. No abstract textbook proofs — every concept you learn this week, you will compute on your actual TaxiPulse data from last week. Vectors will be columns from your dataframe. Probability distributions will be your fare data. Bayes theorem will be a real question about taxi rides ("given that a trip ended at JFK, what is the probability the rider tipped over 20%?"). Linear regression you will solve by hand using the normal equation, and your coefficients will match the actual NYC metered taxi rate to two decimal places. That last part is the moment the math stops being academic and becomes a tool you trust.

By Sunday you will have a math notebook in your taxipulse repo where every concept is applied to real data. More importantly, you will have stopped being afraid of equations. The next time you read a paper that says "let X be a matrix in R^{n×d}", you will know exactly what they mean because you spent a week treating your own data that way.`,

  pre_flight: `Before you watch the videos: open last week's TaxiPulse notebook. Find the cell where you computed df['fare_amount'].mean(). Stare at it for a second. By Friday, you should be able to explain in two sentences what your computer literally did when it ran that line — at the level of "it took the 3.5 million numbers, treated them as a vector, took the dot product with a vector of ones, and divided by the length." If you cannot say that yet, that is fine. That is what the week is for. But check yourself on Friday and be honest about whether you can or not.`,

  mastery_questions: [
    `Take any numeric column from your taxi data (fare_amount, trip_distance, tip_amount — pick one). Use NumPy to compute the mean two ways: once with .mean() and once by hand using a dot product (np.dot(col, np.ones(len(col))) / len(col)). Paste both numbers — they should be identical to many decimal places. Now you have proven to yourself that the mean is a dot product. Why does this matter? Because everything sklearn does is matrix multiplication wearing different clothes. Once that clicks, you stop being intimidated by ML papers.`,
    `Plot a histogram of fare_amount with 50 bins. Look at the shape. Is it symmetric, or is the right tail much longer than the left? This is called right-skew (positive skew) and it is the single most common distribution shape you will see in real business data — incomes, prices, response times, anything that has a hard floor at zero but no ceiling. Compute the mean and median of the same column. The mean should be larger than the median. Explain in one sentence WHY that gap exists for skewed data. (Hint: a few $400 airport rides pull the mean up but cannot move the median past the middle person.) This is the most important sentence you will write about distributions all year.`,
    `Bayes by hand. Look at your data: among all trips that ended at JFK (RatecodeID 2 in NYC TLC data), what fraction had a tip over 20%? Now: among trips that did NOT end at JFK, what fraction had a tip over 20%? Paste both percentages. The gap between them tells you something real about behaviour — what is your hypothesis for WHY airport rides have a different tipping pattern? You just did a conditional probability calculation on a question that actually matters. P(tip > 20% | trip = JFK) — that notation will never feel scary again, because you just did it.`,
    `Linear regression by hand. Pick two columns: trip_distance (X) and fare_amount (y). Compute the slope and intercept using the closed-form normal equation: beta = (X^T X)^-1 X^T y. Paste your slope. NYC taxis charge roughly $3 per mile (the actual rate is $3.00/mile plus a $3 base fare as of 2023). Does your slope match? If yes, you just rediscovered a real-world pricing formula from raw data, which is what regression is for. If your slope is way off, your data probably needs cleaning — find the outliers, drop them, recompute. (This is exactly the iteration loop real data scientists run, by the way. The model lies until the data is honest.)`,
    `Watch StatQuest's Gradient Descent video. Then explain it back, in your own words, in 3 sentences. Use an analogy. (Common ones: rolling a ball down a hill, walking down a foggy mountain feeling for the slope with your foot, etc.) Now answer one question: what happens if your learning rate is too big? What happens if it is too small? Paste both answers. Knowing this saves you from the most common "why is my model not converging" mistake for the rest of your career.`,
  ],

  common_mistakes: [
    `Confusing population statistics with sample statistics. When you do .mean() on your 3.5M rows, that is a SAMPLE — October 2023. The population is "all NYC taxi trips ever." Tiny distinction now, huge distinction once you start doing hypothesis tests.`,
    `Forgetting that NumPy operations on a column return a NumPy array, not a Series. Sometimes this matters (e.g., .iloc stops working). When something breaks weirdly after a NumPy call, the first check is type(your_variable).`,
    `Reading the Bayes formula and feeling stupid because the notation is unfamiliar. The notation is just shorthand — P(A|B) means "the percentage of times A happens when we restrict our view to only the times B happens." If you write that sentence next to the formula, the formula stops being scary.`,
    `Solving the normal equation and getting wildly wrong coefficients because trip_distance has zeros in it (matrix is not invertible). Drop the zero-distance rows first. This is the same lesson as last week: the cleaning IS the analysis.`,
    `Watching the 3Blue1Brown videos at 2x speed to "save time." Those videos are designed at 1x. Two-pass approach: watch once at normal speed without taking notes, then watch again pausing to actually compute the examples. The second watch is where the math sticks.`,
  ],

  debug_help: `Two kinds of breakage this week. First kind: NumPy shape mismatches. When you see ValueError: shapes (3500000,) and (3500000,1) not aligned, NumPy is telling you your vectors have slightly different shapes — one is a 1D array, one is a 2D column. Use .reshape(-1, 1) to convert a 1D array to a column, or .flatten() to go the other way. This is the single most common NumPy error and it happens to everyone forever. Second kind: the math result feels wrong (your slope is negative when it should be positive, or your probability is 1.4). That is almost always an algebra slip — you forgot to transpose somewhere, or you divided by the wrong thing. Walk through the formula on paper, line by line, with tiny numbers (3 rows of fake data) before suspecting your data is wrong. The math on tiny data should match the math on big data exactly.`,

  ai_assist: `This is the week AI can short-circuit your learning if you let it. Do NOT ask Claude to "solve linear regression for me." Ask it instead: "I am trying to derive the normal equation from scratch — can you walk me through the steps WITHOUT giving me the final formula?" Use AI as a slower teacher, not a faster calculator. The math only becomes intuitive if you do it yourself the first time. Second, when you watch the 3Blue1Brown videos and a moment confuses you, pause the video and ask Claude to re-explain that specific minute in different words. That targeted use is gold. Third — and this is the test of whether the math stuck — try explaining gradient descent BACK to Claude as if Claude were a beginner. If you can teach it, you understand it. If you cannot, you do not yet.`,

  stretch: [
    `Compute the covariance matrix of three columns (fare_amount, trip_distance, tip_amount) by hand using NumPy. Now do the same calculation with np.cov() and verify they match. This is the building block of PCA, which you will meet in a few weeks.`,
    `Take your linear regression coefficients from question 4 and use them to predict the fare for a hypothetical 5-mile trip. Compare your prediction to the actual mean fare of 5-mile trips in your data. How close did you get? The gap between them is called RESIDUAL — and the next month of ML is basically about shrinking it.`,
    `Read the Wikipedia page for "Central Limit Theorem" and write a 3-sentence summary in your notebook. Then verify it on your data: take 100 random samples of 30 trips each, compute the mean of each sample, plot the distribution of those 100 means. The shape should be approximately normal even though the underlying fare distribution is heavily skewed. That is the central limit theorem in action — and it is why most of statistics actually works.`,
  ],
});
