import { rewriteWeek } from "../rewrite-week";

// devops-cloud W16-W20

rewriteWeek("devops-cloud", 16, {
  context: `Secrets management is one of the most consequential security decisions in infrastructure. A secret is any value that provides access: API keys, database passwords, TLS private keys, OAuth client secrets, SSH private keys. How you store, distribute, rotate, and audit secrets determines whether a breach exposes just one system or your entire infrastructure.

The worst approach: hardcoded secrets in source code. They end up in git history forever, visible to everyone with repository access, and copied into every developer's machine. The second-worst: environment variables on servers set manually. They are visible in /proc/environ, are not rotated, and are not audited. Better: Kubernetes Secrets (base64-encoded, stored in etcd, accessible only to pods with the right RBAC). But Kubernetes Secrets are not encrypted at rest by default and are only as secure as your cluster's etcd access control.

HashiCorp Vault is the industry standard secret management solution. It provides: dynamic secrets (generate database credentials on-demand that expire after an hour — no static passwords), static secret storage (API keys you cannot make dynamic), secret leasing and renewal, fine-grained access control (AppRole, Kubernetes auth), and full audit trail (every secret access is logged). Vault's dynamic secrets for databases are transformative: instead of storing a password for your database, your application asks Vault for credentials at startup, Vault creates a short-lived PostgreSQL user, and your app uses it. When the credentials expire, Vault revokes the database user. No password to steal.

Cloud provider secret managers: AWS Secrets Manager, GCP Secret Manager, Azure Key Vault. These are managed equivalents of Vault — less feature-rich (no dynamic secrets for most sources) but operationally simpler and natively integrated with their cloud services. AWS Secrets Manager automatically rotates RDS passwords and integrates with ECS, Lambda, and EC2 via IAM. Use the cloud provider's secret manager for most use cases; consider Vault for complex multi-cloud or on-premises scenarios.

Secrets in Kubernetes: the External Secrets Operator (ESO) syncs secrets from Vault, AWS Secrets Manager, or other backends into Kubernetes Secrets. Pods use the Kubernetes Secrets as normal; ESO handles fetching and rotation from the external store. This gives you the cloud secret manager's operational benefits while keeping the Kubernetes Secret as the delivery mechanism for pods.`,

  pre_flight: `Create a free Vault cluster on HashiCorp Cloud Platform (HCP Vault) — no installation required. Or install Vault locally: brew install vault && vault server -dev. Read the Vault getting started guide. Install the External Secrets Operator in your Kubernetes cluster: helm install external-secrets external-secrets/external-secrets. Know that Kubernetes Secrets are base64-encoded (not encrypted) by default. Read how to enable encryption at rest in Kubernetes (EncryptionConfiguration).`,

  mastery_questions: [
    `You have a Node.js application deployed to Kubernetes. It needs a PostgreSQL password. Walk through the External Secrets Operator flow to get this secret into the pod. Create the password in AWS Secrets Manager: aws secretsmanager create-secret --name prod/db/password --secret-string "hunter2". In Kubernetes, create an ExternalSecret resource that references the AWS secret, specifying the key and target Kubernetes Secret name. ESO (which has an IAM role via IRSA to read from Secrets Manager) periodically fetches the secret and creates/updates a Kubernetes Secret. Your pod spec references the Kubernetes Secret as an environment variable or volume. The pod sees the password without ever talking to AWS directly.`,
    `Your application uses a static API key for a third-party service. How do you rotate it with zero downtime? Secret rotation with zero downtime requires two active keys simultaneously during the rotation window. Process: (1) generate a new API key at the third-party service (keep the old one active). (2) Update the secret in your secret manager with the new key. (3) Your application picks up the new key (either via a restart, or via ESO's refreshInterval which re-syncs periodically). (4) Verify the application is using the new key successfully. (5) Revoke the old key at the third-party service. If you skip step 4 before step 5, you revoke the key before the app has switched — outage.`,
    `What is the difference between a Vault AppRole and Kubernetes auth method? Both are authentication methods for applications to authenticate to Vault and receive a token. AppRole: the application receives a role_id (not secret) and a secret_id (short-lived, can be generated fresh per deployment). Used when you need to authenticate outside Kubernetes (CI systems, on-premises services). Kubernetes auth: Vault reads the pod's Kubernetes Service Account JWT token. The pod mounts the JWT at a known path. Vault validates it against the Kubernetes API server (is this a real token for the right service account?). This is more secure for Kubernetes workloads — no static credentials needed, the JWT is automatically rotated.`,
    `How does Vault's dynamic database secrets work for PostgreSQL? You configure a database secrets engine in Vault and give it a privileged PostgreSQL connection (the Vault database account). You define a role in Vault: a SQL template for creating temporary users and the TTL (e.g., 1 hour). When your application requests credentials from Vault (/database/creds/myrole), Vault connects to PostgreSQL, creates a new user with a random password (matching the SQL template), sets an expiry, and returns the credentials to your app. Your app uses these credentials. When the TTL expires, Vault revokes the credentials — PostgreSQL drops the user. The credentials were never stored, never static, and expired automatically. If they are leaked, they stop working in at most 1 hour.`,
  ],

  common_mistakes: [
    `Rotating secrets one-at-a-time (atomic cutover). Rotating a secret while the application is running requires the old and new secrets to be simultaneously valid during the rotation window. If you revoke the old secret before the app has adopted the new one, you get an outage.`,
    `Logging secrets in application code. Logging request bodies or debugging unexpected values can accidentally include secrets. Audit your logging code. Use a redaction middleware that strips known secret patterns from logs.`,
    `Storing Vault root tokens or unseal keys in Kubernetes secrets or application configuration. These are the keys to your entire secrets system. Store them in a separate secure location (HSM, PGP-encrypted, split key among multiple people). Never in the same system they protect.`,
    `Using the same secret for multiple environments. A dev database password leaking should not compromise production. Use separate secrets per environment. With AWS Secrets Manager, the convention is /prod/db/password vs /dev/db/password.`,
    `Not auditing secret access. Vault provides a full audit trail: who accessed what secret, when. Enable audit logging: vault audit enable file file_path=/var/log/vault/audit.log. Set up alerts for unusual access patterns (bulk reads, access at 3am from an unfamiliar IP).`,
  ],

  debug_help: `ESO ExternalSecret is stuck in "SecretSyncedError": check the ESO controller logs (kubectl logs -n external-secrets deployment/external-secrets). Common causes: IAM permissions missing for the SecretStore's authentication, the secret does not exist at the specified path, or the key name does not match. Vault returns 403 Forbidden: the token does not have a policy that allows reading the specific path. Check the token's policies with vault token lookup. Ensure the policy includes capability: read for the path. Kubernetes Secret not updating after ESO sync: check the ExternalSecret's refreshInterval — it only syncs on that schedule. Force an immediate sync by adding an annotation or using kubectl annotate externalsecret [name] force-sync=$(date +%s). Application receives empty secret: the pod was started before the Secret existed. Add an initContainer that waits for the Secret to exist, or restart the pod after the Secret is populated.`,

  ai_assist: [
    `"Write a complete External Secrets Operator setup for AWS Secrets Manager. Include: the SecretStore (with IRSA authentication), an ExternalSecret that syncs a database password and an API key from specific Secrets Manager paths, and the resulting Kubernetes Secret structure. Show how the pod references the resulting Secret as environment variables."`,
    `"Write a Vault policy (HCL) that grants an application read-only access to the path secret/data/prod/myapp/* and the dynamic database credentials at database/creds/myapp-readonly. Show how to create the policy, create an AppRole with the policy, and authenticate using the AppRole from a Node.js application."`,
    `"Implement secret rotation without downtime for an application using AWS Secrets Manager. Write the Lambda function that Secrets Manager calls during rotation: it generates a new password, updates the secret with AWSPENDING stage, tests the new password, and marks it as AWSCURRENT. Explain the four-step rotation process."`,
  ],

  stretch: [
    `Set up Vault dynamic secrets for your local PostgreSQL instance. Install Vault locally, configure the database secrets engine with your PostgreSQL connection, create a role that generates read-only credentials with a 1-hour TTL. Write a Node.js application that fetches credentials from Vault at startup and renews them before expiry. Observe in PostgreSQL (SELECT * FROM pg_roles) as Vault creates and drops users.`,
    `Implement the Vault agent sidecar pattern in Kubernetes. The Vault agent runs as a sidecar container in the pod, authenticates to Vault using Kubernetes auth, fetches secrets, and writes them to a shared volume as a .env file. The main application container reads the file. This keeps the main application unaware of Vault entirely.`,
    `Audit your entire infrastructure for secrets: grep your git history for common secret patterns (API key formats, passwords, private keys). Use truffleHog3 or git-secrets. Rotate any found secrets. Implement a pre-commit hook that prevents future secret commits.`,
  ],
});

rewriteWeek("devops-cloud", 17, {
  context: `Continuous Integration and Continuous Delivery in the DevOps/Cloud context is different from the application developer's CI/CD. As an infrastructure engineer, you are building the CI/CD systems that other teams use, managing deployments across multiple services and environments, and ensuring the pipeline itself is reliable, secure, and fast.

A mature CI/CD pipeline is not just "run tests and deploy." It is: source code → lint and type check → unit tests → integration tests → build Docker image → scan image for vulnerabilities → push to registry → deploy to staging → run smoke tests → deploy to production → monitor for anomalies → roll back if needed.

The deployment strategies that matter in production. Rolling update: replace pods one at a time — always some old, some new, then all new. Kubernetes Deployments use this by default. Zero downtime but requires both old and new code to serve requests simultaneously (backward-compatible API changes). Blue-green: two identical environments (blue is live, green gets the new version). After green is tested, the load balancer switches all traffic from blue to green. Instant cutover, easy rollback (switch back to blue), but 2x the resource cost. Canary: route a small percentage of traffic to the new version. If error rates are acceptable, gradually increase. Requires sophisticated traffic splitting (Istio, Argo Rollouts).

Argo CD is the GitOps continuous delivery tool for Kubernetes. You commit desired cluster state to a git repository. Argo CD watches the repository and continuously reconciles the cluster to match git. This separates CI (building and testing code) from CD (deploying to Kubernetes). CI produces an image and commits the new image tag to the gitops repository. Argo CD detects the commit and deploys.

GitHub Actions secrets and OIDC: instead of storing cloud credentials (AWS access keys) as GitHub Secrets, use OIDC. GitHub Actions gets a short-lived token from GitHub's OIDC provider. AWS, GCP, and Azure can be configured to trust this token and exchange it for cloud credentials. No long-lived credentials to manage or rotate.`,

  pre_flight: `Install Argo CD on your Kubernetes cluster: kubectl create namespace argocd && kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml. Access the Argo CD UI: kubectl port-forward svc/argocd-server -n argocd 8080:443. Read the Argo CD getting started guide. Understand the GitOps model: the git repository is the single source of truth for cluster state. Understand GitHub Actions OIDC: github.blog/2021-11-23-secure-deployments-openid-connect-github-actions-generally-available.`,

  mastery_questions: [
    `You merge a PR to main. The new code has a Docker image change. Describe the full CI/CD pipeline from merge to production. GitHub Actions triggers on push to main. The CI workflow: checkout code, run npm test, build Docker image (docker build -t ghcr.io/org/app:SHA .), scan with Trivy (fail if CRITICAL CVEs), push to GitHub Container Registry (authenticated via OIDC). The CD step: commit the new image tag to the gitops repository (update image: ghcr.io/org/app:NEWSHA in the Kubernetes deployment manifest). Argo CD detects the commit to the gitops repo (it polls every 3 minutes, or you configure a webhook for instant sync). Argo CD compares the desired state (new image tag) to actual cluster state (old image tag) and applies the change — rolling update in Kubernetes. Argo CD monitors the rollout status and reports success or failure.`,
    `What is the difference between a CI/CD pipeline that deploys by running kubectl apply in the pipeline vs GitOps with Argo CD? Pipeline-based deploy (push model): the CI system has cluster credentials, runs kubectl apply directly. Advantages: simple, well-understood. Disadvantages: CI system needs cluster credentials (security risk), no continuous reconciliation (drift between git and cluster goes undetected), hard to see what is deployed where. GitOps (pull model): CI pushes to git, Argo CD pulls from git and applies. Advantages: cluster credentials never leave the cluster (Argo CD runs inside), continuous reconciliation (Argo CD detects and fixes drift), clear audit trail in git, multi-cluster management from one Argo CD instance. Disadvantage: additional complexity (two repositories to manage).`,
    `Your deployment to production failed halfway through a rolling update. Half the pods are running the old image, half the new image. What does Argo CD show and what do you do? Argo CD shows the Application as "Degraded" (pods are not in the expected state). The deployment has a rollout failure. Option 1: rollback. kubectl rollout undo deployment/myapp restores all pods to the previous image version. In GitOps, revert the git commit (git revert) and let Argo CD sync the revert. Option 2: forward fix. If the issue is correctable, fix it and push a new commit. Argo CD syncs the fix.`,
    `How do you implement a canary deployment using Argo Rollouts? Install Argo Rollouts. Replace your Deployment with a Rollout resource (same spec, additional strategy field). Configure the canary strategy: steps: - setWeight: 5 (route 5% of traffic to new version) - pause: {duration: 5m} (wait 5 minutes) - setWeight: 50 - pause: {} (manual approval) - setWeight: 100. Argo Rollouts creates a stable ReplicaSet (old version) and a canary ReplicaSet (new version). An Argo Rollouts-managed Service and VirtualService handle the traffic split (using Istio or Nginx). You promote the rollout manually (or automate based on Prometheus metrics) to proceed through the steps.`,
  ],

  common_mistakes: [
    `Storing cloud credentials as long-lived secrets in CI. AWS access keys, GCP service account keys — if these are compromised, an attacker has persistent cloud access. Use OIDC for GitHub Actions to AWS/GCP/Azure. The tokens are short-lived (15 minutes) and scoped to the specific workflow run.`,
    `Deploying to production without a staging gate. Every production deployment should first deploy to staging, run smoke tests, and pass before production is updated. An automated check that catches issues in staging is worth 10 post-incident retrospectives.`,
    `Not separating the application code repository from the gitops configuration repository. If both are in the same repo, every code change triggers a deployment (even for changes that should not deploy). The gitops repo holds only deployment configuration (image tags, replicas, environment-specific values). The application repo holds application code and CI that updates the gitops repo.`,
    `Using kubectl apply --force in CI. Force apply bypasses merge conflicts and can silently overwrite manual changes or other pipeline's changes. Use standard apply. If there are conflicts, they should be investigated, not forced through.`,
    `Not monitoring the deployment itself. A deployment may succeed (all pods running) but the application may be serving errors. Add post-deployment smoke tests and monitor error rates in Sentry or your observability platform for 10 minutes after every production deploy.`,
  ],

  debug_help: `Argo CD shows "OutOfSync" but syncing has no effect: the resources in the cluster have annotations or labels added manually (kubectl annotate, kubectl label) that are not in git. Argo CD sees a difference but sync does not remove the annotation (by default). Use kubectl apply --prune=false or configure Argo CD to ignore specific annotations. GitHub Actions OIDC failing with "Error assuming role": verify the GitHub OIDC token conditions in the AWS IAM trust policy match the workflow's context (repo, branch, environment). The condition must match the specific github.repository and github.ref. Deployment is stuck in Progressing: kubectl describe deployment [name] for events. A common cause: the new pods are failing their readiness probe — Kubernetes waits for them to be ready before removing old pods, but they never become ready.`,

  ai_assist: [
    `"Write a complete GitHub Actions workflow for a Node.js application using OIDC for AWS authentication. The workflow: triggers on push to main, runs tests, builds and scans a Docker image, pushes to ECR (using OIDC, no stored credentials), and updates the image tag in a separate gitops repository."`,
    `"Write an Argo CD Application manifest that deploys a Helm chart from a gitops repository. It should: watch the gitops repo's main branch, use the production-values.yaml file, enable automated sync with self-healing (re-apply if someone kubectl-edits a resource), and notify a Slack channel on sync success or failure."`,
    `"Write an Argo Rollouts Rollout manifest for a canary deployment that: deploys 5% to canary for 10 minutes, pauses for manual approval, deploys 50% for 5 minutes, then 100%. Use Nginx for traffic splitting. Include the analysis template that uses Prometheus to check error rate (abort rollout if error rate > 1%)."`,
  ],

  stretch: [
    `Implement a full deployment pipeline with automated canary analysis using Argo Rollouts and Prometheus. Set up a Prometheus metric for HTTP error rate. Configure an AnalysisTemplate that queries Prometheus during the canary step and automatically aborts the rollout if error rate exceeds 1%. Test by deploying a version that returns 500 errors for 5% of requests.`,
    `Set up Dagger as a portable CI/CD engine. Dagger runs your CI pipeline as containers — the same pipeline runs locally (dagger run .) and in GitHub Actions (with the Dagger GitHub Action). This eliminates the "works in CI but not locally" debugging problem. Migrate your application's CI workflow to Dagger.`,
    `Implement GitOps for your Terraform infrastructure using Atlantis. Atlantis listens for PR events, runs terraform plan on every PR, posts the plan as a PR comment, and runs terraform apply when the PR is merged. Add a policy check (Open Policy Agent) that rejects Terraform plans that remove certain resource types without a specific label.`,
  ],
});

rewriteWeek("devops-cloud", 18, {
  context: `GitOps is the operational model where the desired state of your infrastructure and applications is stored in git, and automation continuously reconciles actual state to match the desired state. The git repository becomes the single source of truth: if it is in git, it is deployed; if it is not in git, it should not exist. The phrase "GitOps" was coined by Weaveworks in 2017; the pattern is now widely adopted.

The two principles of GitOps: declarative (the desired state is expressed declaratively — what you want, not how to get there) and continuous reconciliation (an operator continuously watches git and applies any diff to the live system — not just on deploy commands). Argo CD and Flux are the two dominant GitOps operators for Kubernetes.

Flux CD is the CNCF-graduated alternative to Argo CD. Flux is more GitOps-pure (all configuration is Kubernetes Custom Resources) and more modular. Its components: source-controller (watches git, Helm, and OCI registries), kustomize-controller (applies kustomizations), helm-controller (reconciles HelmReleases), notification-controller (sends alerts), image-automation-controller (updates image tags automatically when a new image is pushed to a registry). Together, these form a fully automated deployment pipeline with no manual steps.

Image automation with Flux: when your CI pushes a new Docker image (myapp:SHA) to a registry, Flux's image-automation-controller detects the new tag (based on your tag policy — latest, semver, or regex), commits a change to your gitops repository updating the image tag, and then the reconciliation loop deploys the new image. This closes the loop: push code → CI builds image → Flux detects new image → Flux updates git → Flux deploys. No human involvement after the PR merge.

Multi-tenancy in Argo CD / Flux: multiple teams sharing a cluster, each managing their own namespace. Argo CD has Projects that define which git repos and namespaces a team can deploy to. Flux has Tenants and NS-level Kustomizations. The infrastructure team manages the cluster itself (cluster controllers, monitoring, networking); application teams manage their applications in their assigned namespaces.`,

  pre_flight: `Install Flux CLI: fluxcd.io/docs/installation. Bootstrap Flux in your cluster pointing to a GitHub repository: flux bootstrap github --owner=OWNER --repository=REPO --branch=main --path=clusters/my-cluster. Read the Flux getting started guide. Understand the difference between Flux source-controller (fetches from git) and kustomize-controller (applies manifests). Have a container image in a public registry (ghcr.io) to experiment with image automation.`,

  mastery_questions: [
    `Your application team commits a Kubernetes Deployment manifest with a wrong image tag to the gitops repository. Flux reconciles and the deployment rolls out the wrong image. How does GitOps help you recover vs a traditional deploy? In GitOps: git revert [commit] creates a revert commit. Flux detects the revert, reconciles, and rolls back the deployment — the cluster returns to the previous state automatically. The rollback is auditable (the git history shows the wrong commit, the revert, and the reason). In a traditional pipeline: you would need to find the previous image tag, manually construct and run a kubectl rollout undo or re-run the old CI build. The GitOps advantage: rollback is just git revert — a familiar operation with a clear audit trail.`,
    `You want Flux to automatically deploy a new Docker image within 5 minutes of it being pushed to ghcr.io (without any human intervention). Walk through the Flux image automation setup. Create an ImageRepository that tells Flux to watch ghcr.io/myorg/myapp. Create an ImagePolicy with a filter (e.g., semver: range: ">=1.0.0") to select which tags are considered. Add a marker comment in your Deployment manifest: image: ghcr.io/myorg/myapp:v1.0.0 # {"$imagepolicy": "flux-system:myapp"}. Create an ImageUpdateAutomation that commits the new image tag to git when the policy selects a new tag. Flux source-controller detects the git change, kustomize-controller reconciles the Deployment — the new image is deployed without any human action.`,
    `What is the difference between Argo CD and Flux? When would you choose each? Argo CD: has a rich web UI, is well-suited for teams that want a visual interface for managing deployments, supports multi-cluster management with a single control plane, and has more mature features for Helm and Kustomize. Flux: has no built-in UI (use Weave GitOps or Grafana), is more modular (you install only the components you need), has built-in image automation, and is considered more "GitOps pure" — everything is a Kubernetes CRD with no separate server to manage. Choose Argo CD if UI-driven workflows matter to your team. Choose Flux if you prefer a purely declarative, no-GUI approach.`,
    `A developer accidentally deletes a Deployment from the cluster with kubectl delete deployment myapp. With Argo CD's sync policy set to automated self-healing, what happens? Argo CD's controller continuously reconciles actual state with git. When it detects that myapp Deployment is missing (actual state differs from git state), it re-creates the Deployment within the sync interval (every 3 minutes by default, instantly with a webhook). The developer sees the Deployment disappear and reappear. If they want to remove the Deployment permanently, they must remove it from git — not from the cluster directly. This is the GitOps invariant: git is truth.`,
  ],

  common_mistakes: [
    `Direct kubectl changes to resources managed by Argo CD or Flux. They will be overwritten on the next sync. All changes must go through git. If you need to make an emergency change, make it in git, not directly in the cluster.`,
    `Storing all environments in the same gitops repository with no branch protection on production. A developer with write access can modify production directly. Use separate repositories for production, or branch protection with required reviews for production paths.`,
    `Not setting up notifications for sync failures. If Argo CD or Flux fails to sync (a Helm chart upgrade fails, a manifest has a syntax error), you need to know immediately. Configure notifications to Slack or PagerDuty for any sync failure.`,
    `Too-frequent reconciliation loops. Polling every 30 seconds for 100 repositories creates significant API load on your git server. Use webhooks to trigger reconciliation on push, and set the polling interval to 5-10 minutes as a fallback.`,
    `Image automation updating production directly without a staging validation step. Automatic image promotion to production means a broken image (which passed image scanning but fails at runtime) goes directly to users. Add a staging step: auto-promote to staging, run tests, require manual approval (or a Prometheus query passing) for production promotion.`,
  ],

  debug_help: `Flux is not reconciling (stuck in "Reconciling"): check the source-controller logs (kubectl logs -n flux-system deployment/source-controller). Common causes: git authentication failing (check the GitRepository's Secret for the SSH key or token), network policy blocking access to GitHub, or a Flux controller OOMKill. Argo CD shows "Health: Missing" for a resource: the resource exists in git but is not in the cluster. Force a sync: argocd app sync myapp --force. Check whether RBAC is preventing Argo CD from creating the resource in the target namespace. Image automation not updating: check that the marker comment (# {"$imagepolicy": ...}) is in the exact right format. Run flux get images all to see whether the ImagePolicy has selected a new tag. Check the ImageUpdateAutomation status with kubectl describe imageupdateautomation.`,

  ai_assist: [
    `"Write a complete Flux CD setup for a multi-tenant cluster with two teams: team-a and team-b. Each team has their own namespace and gitops repository path. The infrastructure team manages cluster-wide resources (monitoring, ingress). Show the Kustomization hierarchy: infrastructure → team-a apps, infrastructure → team-b apps. Include RBAC that prevents team-a from managing resources in team-b's namespace."`,
    `"Write the Flux image automation configuration for a production application. Include: ImageRepository pointing to ghcr.io, ImagePolicy selecting tags matching semver >=1.0.0, the deployment manifest with the imagepolicy marker comment, and ImageUpdateAutomation with a commit message template and push credentials."`,
    `"Compare Argo CD ApplicationSets with Flux's Kustomizations for managing the same application deployed to 5 clusters. Which approach requires less YAML? Which is more flexible? Show the configuration for both approaches."`,
  ],

  stretch: [
    `Implement progressive delivery with Flagger (the Flux companion). Flagger automates canary releases by continuously monitoring Prometheus metrics during a rollout. Configure a Canary resource for your application: 5% initial traffic, advance 10% every 30 seconds if error rate < 1% and latency p99 < 500ms. Watch Flagger automatically roll out the new version or roll back on metric failure.`,
    `Build a self-service deployment platform. Developers open a PR to the gitops repository to deploy their application. A GitHub Actions workflow validates the manifests (kubeval, conftest policy checks), posts the validation result as a PR comment, and requires approval from the infrastructure team. On merge, Argo CD or Flux deploys automatically. This is platform engineering for your team.`,
    `Set up multi-cluster Argo CD. Deploy Argo CD in a management cluster. Register two additional clusters (staging and production). Create Argo CD Applications in the management cluster that deploy to staging and production. Implement ApplicationSets that template the same application configuration across both clusters with environment-specific values.`,
  ],
});

rewriteWeek("devops-cloud", 19, {
  context: `Observability is the ability to understand the internal state of your system from its external outputs. The three pillars: metrics (numeric measurements over time), logs (timestamped event records), and traces (end-to-end request journeys across services). In a containerised, microservices environment, these three together tell the complete story of what your system is doing and why.

Prometheus is the standard metrics system for Kubernetes. It pulls metrics from targets (your applications and Kubernetes components expose metrics at /metrics in the OpenMetrics format). Prometheus stores time-series data: each metric is a time-series of (timestamp, value) pairs with labels. You query metrics with PromQL — a functional query language. Alertmanager receives alerts from Prometheus and routes them to Slack, PagerDuty, or email based on configurable rules.

Grafana is the visualisation layer. It connects to Prometheus (and many other data sources) and renders dashboards. The kube-prometheus-stack Helm chart installs Prometheus, Grafana, Alertmanager, and a set of pre-built dashboards for Kubernetes monitoring in one command. This is the standard starting point for Kubernetes observability.

OpenTelemetry (OTel) is the standard instrumentation framework. It replaces vendor-specific SDKs (DataDog agent, New Relic agent) with one set of APIs that can export to any backend (Jaeger, Zipkin, Tempo, Honeycomb, Datadog). You instrument your application once with the OTel SDK; you can switch observability backends without changing application code. OTel collectors (agents or sidecars) receive telemetry from applications and route it to backends.

Distributed tracing: a single user request in a microservices system may touch 10 services. A trace records the entire journey: each service creates a span (a unit of work with a start time, duration, and metadata). Spans are linked by a trace ID. Viewing the trace shows a waterfall of all spans — which service was slow, where the error occurred, how long each operation took. Jaeger (open source) or Tempo (part of the Grafana stack) store and visualise traces.

PromQL is the query language you must learn to use Prometheus effectively. Key concepts: instant vector (current value), range vector (values over a time range), rate(http_requests_total[5m]) (per-second rate of increase), sum by (status_code) (aggregate by label), histogram_quantile(0.95, http_request_duration_seconds_bucket) (95th percentile latency).`,

  pre_flight: `Install the kube-prometheus-stack: helm install monitoring prometheus-community/kube-prometheus-stack. Access Grafana: kubectl port-forward svc/monitoring-grafana 3000:80 (default user: admin, pass: prom-operator). Access Prometheus: kubectl port-forward svc/monitoring-kube-prometheus-prometheus 9090:9090. Install Jaeger for tracing: kubectl create -f https://github.com/jaegertracing/jaeger-operator/releases/download/v1.49.0/jaeger-operator.yaml. Read the PromQL tutorial on the Prometheus documentation site.`,

  mastery_questions: [
    `Write the PromQL query that gives the 95th percentile of HTTP request latency over the last 5 minutes, grouped by endpoint. histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint)). Breaking it down: http_request_duration_seconds_bucket is a histogram metric where each bucket tracks the count of requests below a certain duration. rate([5m]) gives the per-second rate of increase over 5 minutes. sum by (le, endpoint) aggregates buckets by the "less than or equal" boundary and endpoint label. histogram_quantile(0.95, ...) calculates the 95th percentile from the bucket distribution. Result: for each endpoint, the duration that 95% of requests complete within.`,
    `Your application's Prometheus metrics are exposed at /metrics. A ServiceMonitor is configured but Prometheus is not scraping the metrics. What do you check? In Prometheus UI (Status > Targets), look for the expected target. If it is missing: check that the ServiceMonitor is in the correct namespace and that the selector matches the Service labels. Prometheus Operator watches ServiceMonitors in specific namespaces (configured by the Operator). Check if the ServiceMonitor's namespaceSelector includes your application's namespace. Check that the Service's port name matches the ServiceMonitor's endpoints.port. If the target appears but shows "Connection refused": the application is not listening on the metrics port. If it shows "403 Forbidden": add authentication to the scrape config.`,
    `How does distributed tracing work with OpenTelemetry? Your application receives an HTTP request. The OTel instrumentation creates a root span for the incoming request (name: HTTP GET /users). Inside the handler, your code calls another microservice — the OTel HTTP client middleware creates a child span for the outgoing call and injects the trace context into the request headers (traceparent: version-traceId-spanId-flags). The receiving service extracts the trace context from the header, creates its own root span as a child of the incoming span. When both complete, they report to the OTel collector. The collector exports to Jaeger. Viewing the trace in Jaeger shows both spans linked — the waterfall shows the total time spent in each service.`,
    `What is the USE method for diagnosing performance problems? The USE method (Brendan Gregg) stands for Utilisation, Saturation, and Errors. For every resource (CPU, memory, disk, network, database connections): Utilisation: how much is the resource being used (CPU is 80% busy)? Saturation: is work queued because the resource cannot keep up (CPU run queue length > 1, disk I/O wait high)? Errors: are there errors in using the resource (disk errors, network packet drops)? Apply the USE method to each resource systematically before diving into application-level profiling. Most performance problems are in infrastructure resources, not application code.`,
  ],

  common_mistakes: [
    `Using too many metric labels with high cardinality. A label like user_id on every HTTP request creates one time series per user. With 1 million users, that is 1 million time series — Prometheus cannot handle this efficiently. Use low-cardinality labels (status_code, endpoint, method) not unique identifiers.`,
    `Not setting up alerting. Metrics without alerts are dashboards without action. Set up alerts for the four golden signals: error rate > 1%, p99 latency > 1s, throughput drops > 50%, saturation > 80%. Alerts should page when action is needed, not just when a threshold is crossed.`,
    `Sampling traces at 100%. Every request generating a trace creates significant overhead (the OTel SDK + network to collector + storage). In production, sample 1-10% of requests (head-based sampling) or sample 100% of error traces (tail-based sampling with OpenTelemetry Collector's tail sampling processor).`,
    `Dashboard sprawl — too many dashboards, none maintained. Create and maintain 3-5 core dashboards (Kubernetes cluster health, application latency/errors, database performance, business metrics). Archive or delete dashboards that are not actively used. Dashboards that are not current are misleading.`,
    `Not correlating logs with traces. Log lines with no trace ID cannot be associated with a specific request. Add the trace ID and span ID to every log line from a request's context. Many log aggregation systems (Loki, DataDog) can then link from a log line directly to the trace.`,
  ],

  debug_help: `Prometheus is not scraping your application: check Status > Targets in the Prometheus UI. If the target is not there, the ServiceMonitor is not being picked up. Run kubectl get servicemonitors -A to verify it exists and kubectl describe servicemonitor [name] to check the selector. Grafana dashboard shows "No data": verify the data source in Grafana (Configuration > Data Sources) is pointing to the correct Prometheus URL. Check the time range in the dashboard — if the metric just started being collected, select "Last 5 minutes." Jaeger shows no traces: check that the OTel collector is receiving spans (collector logs: kubectl logs deployment/otel-collector). Check that the application is configured to export to the collector's endpoint. Verify the sampling rate is not 0%.`,

  ai_assist: [
    `"Write the OpenTelemetry SDK setup for a Node.js Express application. Configure: trace exporter to an OTel collector at otel-collector:4317, metrics exporter to Prometheus, automatic HTTP instrumentation (capture incoming and outgoing request traces), and manual span creation for a database query. Include the OTel collector configuration that routes traces to Jaeger and metrics to Prometheus."`,
    `"Write 5 Prometheus alerting rules for a production Node.js application: high error rate (>1% of requests returning 5xx), high latency (p99 > 1 second), low traffic (>50% drop from the 1-hour average — may indicate a service failure), memory near limit (>90% of the container memory limit), and pod restarts (>3 restarts in 1 hour)."`,
    `"Write a Grafana dashboard JSON definition (or describe the panels) for a Node.js microservice. Include: request rate (req/s), error rate (%), p50/p95/p99 latency (ms), active database connections, memory usage, and CPU throttling. Show which PromQL queries to use for each panel."`,
  ],

  stretch: [
    `Set up the full Grafana observability stack: Loki for log aggregation, Tempo for distributed traces, Mimir (or Prometheus with remote write) for long-term metrics storage. Configure Grafana to correlate across all three: from a slow request's log line, jump to the trace; from the trace, pivot to the metrics during that time window. This is the Grafana LGTM stack (Loki, Grafana, Tempo, Mimir).`,
    `Write a custom Prometheus exporter for a metric your application generates (number of active subscriptions, queue depth, cache hit rate). The exporter exposes a /metrics endpoint with Gauge and Counter metrics. Register a ServiceMonitor and create a Grafana dashboard for the custom metric.`,
    `Implement SLO tracking with Sloth or Pyrra. Define an SLO for your application (99.9% availability, p99 latency < 500ms). These tools generate multi-window, multi-burn-rate Prometheus alerting rules for SLO violation detection. Add the SLO burn rate dashboards to Grafana.`,
  ],
});

rewriteWeek("devops-cloud", 20, {
  context: `Site Reliability Engineering is the discipline of applying software engineering to infrastructure and operations problems. It originated at Google when they hired software engineers to run production systems and gave them the mandate to automate themselves out of operational toil. The result: Google runs millions of servers with a small SRE team. The SRE book (available free at sre.google) codifies these practices.

SLOs (Service Level Objectives): a target reliability level agreed upon between the SRE team and the product team. An SLO is not a promise to customers (that is an SLA — Service Level Agreement); it is an internal target used to make engineering decisions. Example: "The user-facing API will have 99.9% availability and p99 latency below 500ms, measured over a rolling 28-day window." SLOs are expressed in terms users experience, not infrastructure metrics.

Error budgets: the flip side of the SLO. If your SLO is 99.9% availability, your error budget is 0.1% — 43.8 minutes per month. Every minute of downtime spends error budget. When the error budget is exhausted, the SRE team can freeze new deployments (risk of more downtime) until the budget replenishes. This creates a shared incentive: developers want to ship fast, SREs want to maintain reliability. The error budget is the negotiation currency — if the budget is healthy, ship faster; if it is depleted, slow down and fix reliability.

Toil is work that is manual, repetitive, automatable, tactical, and has no enduring value. Responding to the same alert every week and fixing it the same way is toil. Automating the alert response is engineering. Google's SRE teams have a rule: no more than 50% of time spent on toil. The other 50% is engineering work that reduces future toil. This ratio is what makes SRE scalable.

On-call best practices. Alerts must be actionable — if an alert fires and you cannot do anything about it, it should not be an alert. Alerts must have runbooks — documented steps for the on-call engineer. Incidents must be reviewed — post-incident reviews (PIRs, also called post-mortems) are blameless analyses of what happened, why, and what systemic changes prevent recurrence. Blameless means the root cause is a system design issue, not individual failure.

Chaos engineering (from W10's stretch) is the SRE practice of deliberately introducing failures to discover system weaknesses before they cause outages. Failure injection in production (with careful controls) builds confidence that your reliability mechanisms actually work.`,

  pre_flight: `Read the Google SRE book introduction and the chapters on "Embracing Risk" and "Service Level Objectives" (free at sre.google/books). Know the four golden signals from W19. Install Sloth (the SLO generator) or use the Pyrra Prometheus operator. Understand the difference between availability (percentage of time the service is functional) and reliability (probability that a given request succeeds). Calculate: if your SLO is 99.9% availability per month, how many minutes of downtime are allowed?`,

  mastery_questions: [
    `Your service has a 99.9% SLO. In the first week of the month, a bad deployment caused 20 minutes of downtime. What is your error budget status, and how does this affect the rest of the month? Monthly error budget: 30 days × 24 hours × 60 minutes × 0.001 = 43.2 minutes. After 20 minutes of downtime: 23.2 minutes of error budget remaining for the next 23 days. That is 53% of the budget consumed in 23% of the time — you are on track to exhaust the budget early. The appropriate response: no new deployments that add risk until the budget recovers, prioritise reliability work this sprint, investigate the root cause and implement changes that prevent recurrence.`,
    `You have a critical alert that fires 3 times per week. Each time, the on-call engineer investigates for 20 minutes and manually restarts a service. This has been happening for 3 months. What is the SRE perspective on this situation? This is toil. The alert is consuming on-call time that could be used for engineering work. The correct SRE response: first, create a runbook (if one does not exist). Second, investigate the root cause — why does the service need restarting? Is it a memory leak? A bug? An external dependency failure? Third, fix the root cause (permanent solution) or automate the response (runbook as code — a script that runs when the alert fires and automatically restarts the service, with circuit breakers). The goal is zero manual toil for this issue.`,
    `You have a post-incident review after a 45-minute outage caused by a bad database migration. The root cause is clear: the developer who wrote the migration did not test it on production-size data. How do you make the PIR blameless, and what systemic changes prevent recurrence? Blameless means the PIR does not name or blame the developer who wrote the migration. It focuses on system failures that made the incident possible. Root causes (systemic): no process for testing migrations on production-size data. No staging environment with representative data volume. The deployment pipeline allowed a migration to run in production without a review step. No automated rollback plan for failed migrations. Action items: add a staging database with a production-sized snapshot. Add a migration review checklist. Add automated migration tests (run on staging data before production). Add a rollback step to the migration runbook.`,
    `What is the difference between MTTR and MTBF, and which is more important for a high-availability system? MTBF (Mean Time Between Failures): the average time between incidents. Improving MTBF means making the system fail less often. MTTR (Mean Time to Recover): the average time to restore service after a failure. Improving MTTR means recovering faster when failures happen. For high-availability systems, MTTR is often more important. Some failures are inevitable (hardware failures, network partitions, cosmic bit flips). If you can recover in 2 minutes vs 30 minutes, a monthly hardware failure is a minor event vs a major outage. Investments in automation (automated failover, chaos engineering that validates recovery), observability (detect failures faster), and runbooks (resolve faster) improve MTTR.`,
  ],

  common_mistakes: [
    `Setting SLOs at 100% or "five nines" (99.999%). 100% is not achievable and creates perverse incentives. 99.999% requires 5.26 minutes of downtime per year — no scheduled maintenance is possible. Set SLOs that match user expectations and are achievable with your current infrastructure. Start with 99.9%, improve from there.`,
    `Blameful post-incident reviews. Naming and blaming individuals for incidents creates an environment where engineers hide failures rather than learning from them. The systemic problem (no test environment, no review process, no alerting) is always the real root cause. Focus on systems, not people.`,
    `Alert fatigue from alerting on symptoms rather than user impact. Alerting on CPU > 80% is not useful if the service still responds correctly. Alert on user-visible signals: error rate, latency, availability. Infrastructure alerts (CPU, disk, memory) should be informational — visible in dashboards, paging only when they are causing user impact.`,
    `Not having runbooks. An on-call engineer facing an unfamiliar alert at 3am without a runbook will make the outage longer and more stressful. Every alert must have a runbook. Every runbook must be tested. Outdated runbooks are worse than no runbooks.`,
    `Measuring SLOs only after incidents instead of continuously. SLOs should be tracked continuously with burn rate alerts. A fast burn rate alert (error budget depleting 14x faster than normal) pages the team to take action before the budget is exhausted — not after.`,
  ],

  debug_help: `SLO burn rate alerts are too noisy: the alert thresholds may be too sensitive. Tune the burn rate windows and thresholds: use 1-hour window for fast burn (14x rate), 6-hour window for medium burn (6x rate), and 72-hour window for slow burn (3x rate). This multi-window approach is the Google SRE recommended method. Sloth SLO rules not appearing in Prometheus: check that Sloth generated the PrometheusRule and that Prometheus is watching the correct namespace. Run kubectl get prometheusrule -A. Alertmanager not sending notifications: check the Alertmanager config (kubectl get secret alertmanager-monitoring-kube-prometheus-alertmanager -o yaml) for the correct Slack webhook URL or PagerDuty key. Check Alertmanager UI for inhibited or silenced alerts.`,

  ai_assist: [
    `"Write an SLO definition document for a REST API. Include: SLO target (availability 99.9%, p99 latency 500ms), error budget calculation (per 28-day window), measurement methodology (which requests count toward availability, what counts as a failure), burn rate alert thresholds, and what actions to take at each burn rate level."`,
    `"Write a blameless post-incident review template. Include: incident timeline, user impact (duration, affected services, number of affected users), root cause analysis (5 Whys), contributing factors, what went well, what went poorly, and action items with owners and due dates."`,
    `"Write Prometheus alerting rules implementing multi-window multi-burn-rate SLO alerts for a 99.9% availability SLO. Include: fast burn (1h window, 14x burn rate), medium burn (6h window, 6x burn rate), and slow burn (72h window, 3x burn rate). Use the error_budget_burn_rate recording rule pattern."`,
  ],

  stretch: [
    `Implement a game day (controlled failure exercise). Plan a scenario: your primary database becomes unreachable. Document the expected system behaviour (failover to replica, or graceful degradation). Run the scenario on staging. Measure: how long until the alert fires? How long until the team identifies the issue? How long until failover completes? Document the gaps between expected and actual behaviour.`,
    `Build an internal SLO dashboard that shows: current error budget remaining for each service (as a percentage and as time remaining), burn rate over the last 1h/6h/24h, and the incident timeline for the current period. This gives leadership visibility into reliability without requiring them to understand PromQL.`,
    `Instrument your application with SLI tracking at the application layer, not just the infrastructure layer. Track: the percentage of payments that complete successfully (not just HTTP 200), the percentage of search queries that return results within 500ms, the percentage of user sign-ups that complete. These are user-centric SLIs that infrastructure metrics miss.`,
  ],
});
