import { rewriteWeek } from "../rewrite-week";

// devops-cloud W11-W15

rewriteWeek("devops-cloud", 11, {
  context: `Raw Kubernetes YAML is verbose, repetitive, and hard to manage across environments. A Deployment manifest for your staging environment is almost identical to production — but with different image tags, replica counts, resource limits, and environment variables. Helm is the package manager for Kubernetes that solves this problem.

A Helm chart is a collection of templates and default values. Templates are Kubernetes YAML files with Go template syntax for parameterisation: {{ .Values.replicaCount }} is replaced with the value from values.yaml. You install a chart with helm install myrelease ./mychart --set image.tag=1.2.3. Helm renders the templates with the provided values and sends the resulting YAML to Kubernetes.

Charts have a standard directory structure: Chart.yaml (metadata: name, version, description), values.yaml (default values), templates/ (YAML templates), charts/ (chart dependencies). The values.yaml contains sensible defaults; users override them with --set or custom values files (helm install -f prod-values.yaml).

The Helm chart repository ecosystem: Artifact Hub (artifacthub.io) hosts thousands of community charts. Adding a repository: helm repo add bitnami https://charts.bitnami.com/bitnami. Installing a chart: helm install my-postgres bitnami/postgresql --set auth.password=secret. This is how you deploy PostgreSQL, Redis, nginx, Prometheus, and many other services without writing any YAML yourself.

Helm vs Kustomize: Helm uses Go templates for parameterisation (powerful but complex — logic, loops, conditionals). Kustomize uses overlays (patch files that override specific fields). Kustomize is simpler for small differences between environments; Helm is more powerful for complex parameterisation. Many teams use Kustomize for their own applications and Helm for third-party software (databases, monitoring stacks).

Helm release management: helm list shows installed releases. helm history myrelease shows the history of changes. helm rollback myrelease 2 rolls back to revision 2. helm uninstall myrelease removes all resources the release created.`,

  pre_flight: `Install Helm: helm.sh/docs/intro/install. Verify: helm version. Add the Bitnami chart repository: helm repo add bitnami https://charts.bitnami.com/bitnami && helm repo update. Know the helm install, helm upgrade, helm list, helm rollback, and helm uninstall commands. Read the Helm getting started guide. Have your local Kubernetes cluster running (minikube start).`,

  mastery_questions: [
    `You are deploying a PostgreSQL database using the Bitnami Helm chart. The default values use a random password. You want to set a specific password for your environment and persist it across upgrades. How do you do this? Create a values override file prod-values.yaml with: auth: { postgresPassword: "your-secure-password" }. Install with: helm install my-postgres bitnami/postgresql -f prod-values.yaml. For upgrades (helm upgrade), pass the same -f prod-values.yaml. Alternatively: create a Kubernetes Secret manually before installing, and configure the chart to use the existing secret: auth: { existingSecret: "my-postgres-secret" }. This is the better production approach — the password is in a Secret managed by your secret management system, not in a values file.`,
    `You have written a Helm chart for your application. The chart has a template for a Service. In the template, you want to make the service type (ClusterIP, LoadBalancer, NodePort) configurable. Show the template syntax. In templates/service.yaml: apiVersion: v1, kind: Service, spec: { type: {{ .Values.service.type }} }. In values.yaml: service: { type: ClusterIP }. To override at install time: helm install myapp ./myapp --set service.type=LoadBalancer. The template renders the value from .Values. If the value is not provided (via --set or -f), Helm uses the default from values.yaml.`,
    `You install a Helm chart at version 3.5.0. A new chart version 3.6.0 is available with a critical security fix. How do you upgrade? helm repo update (refresh the chart repository index). helm upgrade my-postgres bitnami/postgresql --version 3.6.0 -f prod-values.yaml. Helm upgrades the running resources to match the new chart version. If the upgrade fails (misconfiguration, incompatible changes), helm rollback my-postgres to return to the previous revision. Always review the chart's CHANGELOG or release notes before upgrading.`,
    `What is the difference between helm install and helm upgrade --install? helm install creates a new release — it fails if a release with that name already exists. helm upgrade upgrades an existing release — it fails if the release does not exist. helm upgrade --install is idempotent: if the release does not exist, it installs; if it does, it upgrades. This is the correct command for CI/CD pipelines where you do not know whether the release was previously installed.`,
  ],

  common_mistakes: [
    `Not specifying --version when installing charts in production. Without --version, Helm installs the latest version. The next time someone installs from scratch, they may get a different version. Pin the chart version: helm install myapp bitnami/myapp --version 12.3.4.`,
    `Storing helm values files with secrets in git. Values files with passwords, API keys, or tokens committed to git are security incidents waiting to happen. Use Helm Secrets (with SOPS) or pass secrets via --set from a CI secret, never in a committed values file.`,
    `Not using --atomic in CI deployments. helm upgrade without --atomic can leave resources in a partially upgraded state if an error occurs. --atomic rolls back automatically if the upgrade fails (within the timeout). Use: helm upgrade --atomic --timeout 5m.`,
    `Overusing Helm for everything. Helm shines for distributing complex third-party software (databases, monitoring). For your own simple application YAML (3 resources), Kustomize or plain kubectl apply is often simpler and less magic.`,
    `Not reviewing rendered templates before applying. helm template myapp ./myapp --set image.tag=1.2 renders the templates to stdout without installing. Review the output to catch template errors, missing values, or unexpected configurations before applying to the cluster.`,
  ],

  debug_help: `helm install fails with "Error: cannot re-use a release name": a release with that name already exists. Use helm upgrade --install or delete the old release with helm uninstall myapp. Template rendering error ("undefined variable"): run helm template to see the rendered output and the specific template error. Check that the value path in the template matches the key structure in values.yaml (case-sensitive). Chart values not being applied: verify the values file path is correct and the YAML syntax is valid. Use helm get values myapp to see what values are actually applied to a running release. Resources not being deleted on helm uninstall: by default, PersistentVolumeClaims are not deleted (to prevent accidental data loss). Add --cascade=orphan to see what resources would be orphaned, or delete PVCs manually after uninstall.`,

  ai_assist: [
    `"Write a complete Helm chart for a Node.js application. Include: Chart.yaml (name, version, appVersion), values.yaml (image repository, tag, replica count, service type, resource requests/limits, environment variables, ingress enabled), deployment template, service template, and configmap template. Use standard Helm template helpers (_helpers.tpl)."`,
    `"Show how to deploy the Bitnami PostgreSQL Helm chart in production with: a specific chart version, external secret for the password (existingSecret), persistence enabled (10Gi), replica count of 1, and custom resource limits. Include the helm upgrade --install command and a production values file."`,
    `"Explain Helm's hook system. What is a pre-install hook and a post-upgrade hook? Show a Helm hook that runs a database migration job before the application Deployment is upgraded."`,
  ],

  stretch: [
    `Publish your own Helm chart to GitHub Pages. Create a GitHub repository with your chart, use chart-releaser-action to package and publish it on every tag. Add the GitHub Pages URL as a Helm repo: helm repo add myrepo https://yourusername.github.io/myrepo. This is how open source Helm charts are distributed.`,
    `Use Helm Secrets with SOPS to encrypt sensitive values in your values files. SOPS encrypts specific keys in YAML using an AWS KMS key, GCP KMS key, or age key. The encrypted file is safe to commit to git. CI decrypts it at deploy time using the KMS key (accessed via IAM role). This is the production-grade solution for Helm values with secrets.`,
    `Migrate your Edge Portfolio application from raw kubectl YAML to a Helm chart. Parameterise: image tag, replica count, ingress hostname, and resource limits. Create a values-staging.yaml and values-production.yaml. Update your CI pipeline to use helm upgrade --install with the appropriate values file for each environment.`,
  ],
});

rewriteWeek("devops-cloud", 12, {
  context: `Kubernetes networking handles communication between pods and between the cluster and the outside world. But as applications grow more complex — microservices communicating with each other, diverse clients with different requirements, security policies between services — the basic Service and Ingress are not enough. Service meshes and modern networking tools fill this gap.

The service mesh problem: you have 50 microservices talking to each other. You want: mutual TLS (mTLS) between services (so a compromised service cannot spy on other services' traffic), traffic metrics (how many requests per second between service A and service B, what is the error rate), circuit breaking (stop sending traffic to a service that is failing), and gradual traffic shifting (send 5% of traffic to the new version before committing). Implementing all of this in each service's application code is duplicative and error-prone. A service mesh adds this as infrastructure, transparent to the application.

Istio: the most feature-rich service mesh. It injects a sidecar proxy (Envoy) into every pod. The sidecar intercepts all traffic in and out of the pod. Istio's control plane (istiod) configures the sidecars. From the application's perspective, nothing changes — it still makes HTTP requests to the Service. The sidecars handle mTLS, telemetry, and traffic policies transparently. The tradeoff: Istio is complex, resource-intensive (each sidecar adds ~50MB memory), and has a learning curve.

Linkerd: a lighter-weight service mesh focused on simplicity. Uses its own proxy (written in Rust, much lighter than Envoy). Provides mTLS, traffic metrics, and retries out of the box. Less feature-rich than Istio but significantly simpler to operate. The right choice if you want the core service mesh benefits without Istio's complexity.

eBPF (extended Berkeley Packet Filter): a technology that allows you to run programs in the Linux kernel without modifying the kernel source or loading kernel modules. Cilium uses eBPF for Kubernetes networking: it replaces kube-proxy, provides high-performance networking, and can implement network policies and observability at the kernel level — without sidecar proxies. Cilium + Hubble (Cilium's observability component) provides service mesh-like capabilities without the sidecar overhead.

Kubernetes Ingress vs Gateway API: an Ingress routes external HTTP/HTTPS traffic to services. The Gateway API is the newer, more expressive successor — it separates concerns between the infrastructure admin (Gateway), the cluster operator (Routes), and the developer (HTTPRoute). The Gateway API is the future of Kubernetes external traffic management.`,

  pre_flight: `Install Istio on your minikube cluster: istioctl install --set profile=demo. Label the default namespace for sidecar injection: kubectl label namespace default istio-injection=enabled. Deploy the sample application from the Istio documentation. Install Linkerd separately on a separate cluster or namespace to compare. Read the Istio concepts documentation (traffic management, security, observability).`,

  mastery_questions: [
    `Explain how Istio's mutual TLS (mTLS) works between two services without changing the application code. When service A wants to talk to service B, A's application code makes an HTTP request to B's Service DNS name. The Envoy sidecar in A's pod intercepts the outgoing request. It looks up the certificate for service B from istiod (Citadel, the Istio CA). It upgrades the connection to TLS, presents A's certificate to B's sidecar, and verifies B's certificate. B's sidecar verifies A's certificate and forwards the decrypted request to the service B application. The application never sees TLS — it makes plain HTTP internally. From outside the pod, all traffic is encrypted and authenticated.`,
    `You want to gradually shift traffic from version 1 to version 2 of your service — 10% to v2, 90% to v1. After verifying v2 is healthy, shift to 50/50, then 100% to v2. How do you implement this with Istio? Create two Deployments: myservice-v1 with label version: v1 and myservice-v2 with label version: v2. Create a single Service that matches both (selector: app: myservice). Create a VirtualService that routes based on weight: destination: host: myservice, subset: v1, weight: 90 and subset: v2, weight: 10. The DestinationRule defines the subsets using pod labels. To update the weights, edit the VirtualService: kubectl apply changes take effect immediately — Istio's control plane pushes the new routing rules to all Envoy sidecars.`,
    `What is the difference between a Kubernetes NetworkPolicy and Istio's AuthorizationPolicy? NetworkPolicy operates at the network layer (L3/L4 — IP addresses and ports). It controls which pods can communicate with which other pods at the IP level. It is enforced by the CNI plugin (Cilium, Calico). AuthorizationPolicy operates at the application layer (L7 — HTTP methods, paths, headers, service identity). It controls which services can call which endpoints. It is enforced by the Envoy sidecar. Example: a NetworkPolicy can say "only pods in namespace monitoring can reach port 9090." An AuthorizationPolicy can say "only the payments service (with its Istio identity certificate) can call POST /charge."`,
    `You are running Cilium as the CNI plugin and considering it as a replacement for Istio. What can Cilium with Hubble provide and what would you lose? Cilium + Hubble provides: network-level observability (which services are talking to which, traffic volume, error rates), network policies (L3/L4), and with Cilium Service Mesh: L7 observability and policies without sidecars. What you lose compared to Istio: Istio's rich traffic management features (VirtualService, DestinationRule, fault injection, retries, circuit breaking), Istio's mature mTLS with per-service certificate rotation, and the large Istio community and documentation. The tradeoff: Cilium is lower overhead (no sidecars), Istio is more feature-rich.`,
  ],

  common_mistakes: [
    `Installing Istio in production without understanding the resource requirements. Each sidecar adds 50-100MB RAM per pod. A cluster with 200 pods needs 10-20GB more RAM just for sidecars. Evaluate whether you need a service mesh before installing one. Many teams run successfully without a service mesh for years.`,
    `Enabling global mTLS in STRICT mode before verifying all services have sidecars. In STRICT mode, Istio rejects plain HTTP traffic. If any service does not have a sidecar (a pod that was created before enabling injection, or a job in a namespace without injection enabled), it cannot communicate. Start with PERMISSIVE mode, then switch to STRICT after verifying all traffic uses mTLS.`,
    `Not monitoring Istio's control plane resource usage. istiod, the Envoy proxies, and the Prometheus instance Istio installs consume significant resources. Set resource limits and monitor them. An OOM-killed istiod causes all sidecar proxies to fall back to cached config — which may be stale.`,
    `Using NetworkPolicy without Cilium or Calico. NetworkPolicy objects are only enforced if your CNI plugin supports them. The default kubenet and kindnet do not support NetworkPolicy. Without a supported CNI, NetworkPolicy objects are accepted by the API server but have no effect.`,
    `Forgetting to configure the ingress gateway. Istio replaces the standard nginx Ingress with an Istio Ingress Gateway. You must configure Gateway and VirtualService resources to route external traffic. Many teams set up Istio but forget to route external traffic through the Istio gateway.`,
  ],

  debug_help: `Sidecar not injected despite namespace label: check that the pod was created after the label was applied (existing pods do not get sidecars retroactively). Delete and recreate the pod. Service returns 503 after Istio installation: the sidecar is blocking traffic that was previously allowed. Check Istio's access logs (istioctl proxy-config log [pod] --level debug). mTLS failure: check the Istio authorization policy — if you have a DENY policy that inadvertently blocks legitimate traffic. Use kiali (Istio's UI) to visualise traffic and identify mTLS failures. Cilium pods in CrashLoopBackOff: Cilium requires specific kernel features. Check the minimum kernel version (4.9+ for basic, 5.3+ for full features). Use cilium status to see component health.`,

  ai_assist: [
    `"Write Istio VirtualService and DestinationRule manifests for a canary deployment of a service called 'payments'. Route 5% of traffic to the canary version (v2) and 95% to stable (v1). Include the two Deployments with version labels, the single Service selector, and the Istio traffic splitting configuration."`,
    `"Write a Kubernetes NetworkPolicy that: allows all pods in the 'app' namespace to receive traffic only from pods with the label role: frontend, allows all pods to receive traffic from the 'monitoring' namespace on port 9090, and denies all other ingress traffic."`,
    `"Explain the Gateway API's resource model: GatewayClass, Gateway, HTTPRoute. Compare it to the old Ingress resource. Show an HTTPRoute that routes traffic to different services based on the path prefix (/api to the API service, / to the frontend service) and adds a response header."`,
  ],

  stretch: [
    `Deploy Kiali (Istio's service mesh observability UI) and explore the traffic graph for your sample application. Watch real-time traffic flow between services, see error rates and response times on each edge. Inject a fault (using Istio's fault injection) and watch how it propagates through the graph.`,
    `Implement zero-trust networking in your cluster: enable Istio mTLS in STRICT mode across all namespaces. Write AuthorizationPolicies for each service that specify exactly which other services can call it. Deny all by default, allow specific paths. This is the zero-trust networking model — no implicit trust, even inside the cluster.`,
    `Explore eBPF with Cilium: replace kube-proxy with Cilium's eBPF-based implementation (helm upgrade cilium cilium/cilium --set kubeProxyReplacement=strict). Use Hubble to observe the real-time network flows. Compare the latency of kube-proxy iptables rules vs Cilium eBPF using a simple benchmark (hey or wrk).`,
  ],
});

rewriteWeek("devops-cloud", 13, {
  context: `Infrastructure as Code (IaC) means your infrastructure is defined in version-controlled files, just like your application code. Before IaC: you click through a cloud console to create a VPC, subnets, security groups, EC2 instances, RDS databases, load balancers. The configuration exists only in the cloud provider's database. There is no record of why you made each decision. Recreating it in another region takes hours and is error-prone. After IaC with Terraform: your entire infrastructure is in .tf files. Recreating it is terraform apply. Auditing is git blame.

Terraform is the dominant IaC tool. It uses HCL (HashiCorp Configuration Language), a declarative syntax that describes desired infrastructure state. Providers connect Terraform to cloud APIs: AWS, GCP, Azure, Cloudflare, GitHub, Datadog, and hundreds more. Terraform talks to the provider APIs to create, update, and delete resources.

The Terraform workflow. terraform init: downloads providers and modules. terraform plan: shows what changes will be made (resources to create, update, or destroy) without making them. Always review the plan. terraform apply: makes the changes. terraform destroy: tears down all resources. The plan/apply separation is Terraform's safety net — you see what will happen before it happens.

State: Terraform maintains a state file (terraform.tfstate) that maps your configuration to real cloud resources. The state is how Terraform knows what exists and what needs to change. Problem: the state file contains sensitive values (database passwords, API keys) and must be stored securely and shared across team members. Solution: remote state in S3 (with DynamoDB for state locking) or Terraform Cloud. Never commit terraform.tfstate to git.

Modules: reusable Terraform configurations. A module encapsulates a set of resources and exposes input variables and output values. The Terraform Registry (registry.terraform.io) has community modules for common patterns: VPCs, EKS clusters, RDS instances. Instead of writing 200 lines of AWS VPC configuration, use the terraform-aws-vpc module with a few variables.`,

  pre_flight: `Install Terraform: developer.hashicorp.com/terraform/install. Verify: terraform version. Create an AWS account or use an existing one. Create an IAM user with programmatic access and the permissions you need. Configure AWS credentials: aws configure (or use environment variables). Create an S3 bucket and DynamoDB table for remote state (terraform backend). Read the Terraform "Get Started - AWS" guide on HashiCorp's developer portal.`,

  mastery_questions: [
    `You change the instance_type of an existing EC2 instance in your Terraform configuration from t3.micro to t3.small. You run terraform plan. What does the plan show, and what happens to the running instance? Terraform shows: "aws_instance.web will be updated in-place" with instance_type changing from t3.micro to t3.small. For most EC2 changes, Terraform stops the instance, modifies it, and restarts it — brief downtime. However, for some changes (like changing the AMI), Terraform must destroy and recreate the instance: "aws_instance.web must be replaced" — it creates the new instance and destroys the old one. Read the plan carefully for "must be replaced" vs "updated in-place" to understand the impact.`,
    `Your team has two engineers working with the same Terraform state. Engineer A runs terraform apply while Engineer B is also running terraform apply. What happens without state locking, and how does state locking solve this? Without locking: both plans are based on the same state snapshot. Both applies run concurrently. The second apply may corrupt the state (race condition on the state file write) or create duplicate resources. With state locking: when Engineer A runs terraform apply, Terraform acquires a lock on the remote state (using DynamoDB for S3 backend). Engineer B's apply finds the lock, waits, and retries. After Engineer A's apply completes and releases the lock, Engineer B's apply proceeds — using the updated state as its baseline.`,
    `You accidentally delete a resource from your Terraform configuration and run terraform apply. Terraform deletes the corresponding cloud resource. The database is gone. How do you recover? If you have backups (AWS RDS automated backups, S3 versioning), restore from backup. For the Terraform state: you can import the restored resource back into state: terraform import aws_db_instance.main [restored-instance-id]. This tells Terraform that the restored resource corresponds to the aws_db_instance.main configuration block. Then restore the configuration block. Prevent recurrence: set lifecycle { prevent_destroy = true } on critical resources — Terraform will refuse to destroy them even when you remove them from configuration (you get an error instead of accidental deletion).`,
    `What is the difference between Terraform plan output of "~" (tilde) and "-/+" (dash plus)? Tilde (~) means the resource will be updated in-place — the existing resource is modified without recreation. Example: changing an EC2 instance's tags. Dash plus (-/+) means the resource will be destroyed and recreated — the change cannot be applied in-place. Example: changing an EC2 instance's AMI. The old resource is marked for destruction (-) and a new one is marked for creation (+). Always understand which resources are recreated in a plan — it determines the blast radius of a Terraform change.`,
  ],

  common_mistakes: [
    `Running terraform apply without reviewing the plan. terraform apply shows the plan before applying but many developers skip reading it. Run terraform plan first, save it to a file (terraform plan -out=tfplan), review it, then apply only the saved plan (terraform apply tfplan).`,
    `Storing terraform.tfstate in git. State files contain sensitive values (passwords, private keys, access tokens) in plaintext. Use remote state (S3 + DynamoDB, Terraform Cloud). If you accidentally commit state, rotate all credentials immediately.`,
    `Not using provider version constraints. Without version constraints, terraform init downloads the latest provider version. A provider update can introduce breaking changes. Pin provider versions: required_providers { aws = { source = "hashicorp/aws", version = "~> 5.0" } }.`,
    `Writing monolithic Terraform configurations. One giant main.tf with 2000 lines is hard to review and has large blast radius (a mistake can affect everything). Separate by concern: networking.tf, compute.tf, database.tf. Or use modules for reusable components.`,
    `Not using terraform fmt and terraform validate. fmt formats your HCL consistently (like gofmt). validate checks for syntax errors and obvious mistakes. Run both before committing. Add them to your CI pipeline.`,
  ],

  debug_help: `"Error: state file is locked": another terraform apply is in progress (or a previous apply was interrupted). Check DynamoDB for the lock record: aws dynamodb scan --table-name terraform-locks. If the lock is stale, delete it (terraform force-unlock [lock-id]). "Error: Reference to undeclared resource": you reference a resource that does not exist in your configuration (typo in resource name, or you removed it). Check the resource type and name match. "Provider configuration not present": you removed a provider block but there are still resources from that provider. Remove the resources first, apply, then remove the provider. Terraform plan shows unexpected changes: you manually changed a cloud resource outside of Terraform. The plan will show Terraform "fixing" the drift by reverting your manual change. Use terraform import to bring manual changes into state, or accept the revert.`,

  ai_assist: [
    `"Write a Terraform configuration to create: a VPC with public and private subnets in two availability zones, an Internet Gateway, route tables, security groups (web servers allow HTTP/HTTPS, database allows MySQL only from web servers), an EC2 instance in the public subnet, and an RDS PostgreSQL instance in the private subnet. Use the eu-west-1 region."`,
    `"Write a Terraform module for a Kubernetes namespace with associated RBAC. The module creates a Namespace, a ServiceAccount, a Role with read-only access to pods and deployments, and a RoleBinding. The module takes namespace_name and team_name as input variables."`,
    `"Set up a Terraform remote backend using AWS S3 and DynamoDB state locking. Show the backend configuration block, the S3 bucket policy (deny non-HTTPS access, enable versioning, enable server-side encryption), and the DynamoDB table for locking. Include the terraform init command to migrate local state to remote."`,
  ],

  stretch: [
    `Implement Terraform CI/CD with Atlantis (the open-source tool for Terraform pull request automation). Atlantis runs on a server and comments on PRs with terraform plan output. Merging the PR automatically runs terraform apply. This gives your team a peer-reviewed, audited infrastructure change process.`,
    `Write a Terratest (go test-based infrastructure testing) for your Terraform module. The test applies the module, verifies the created resources are accessible (HTTP check on the EC2 instance, connection check on the database), and destroys the resources. This is infrastructure TDD.`,
    `Migrate your Edge Portfolio infrastructure (server, DNS, SSL) to Terraform. Write resources for: DigitalOcean Droplet, Cloudflare DNS records, and a null_resource that configures nginx and SSL via SSH. Verify that terraform destroy and terraform apply recreate the identical infrastructure from scratch.`,
  ],
});

rewriteWeek("devops-cloud", 14, {
  context: `Managed Kubernetes services (EKS on AWS, GKE on Google Cloud, AKS on Azure) eliminate the burden of managing the Kubernetes control plane. In a self-managed cluster, you are responsible for: etcd backups, API server certificate rotation, control plane version upgrades, master node high availability, and more. With a managed service, the cloud provider handles all of that. You pay for the worker nodes; the control plane is managed.

EKS (Amazon Elastic Kubernetes Service): AWS manages the control plane. You provision worker nodes (EC2 instances) in node groups, or use Fargate (serverless — no EC2 to manage, pods run directly). EKS integrates with AWS services: IAM for authentication (IRSA — IAM Roles for Service Accounts, letting pods assume IAM roles without long-lived credentials), ALB (Application Load Balancer) for Ingress, EBS/EFS for PersistentVolumes.

GKE (Google Kubernetes Engine): Google's managed Kubernetes. Often regarded as the most polished managed Kubernetes experience — GKE invented the technology after all. Features: Autopilot mode (GKE manages both control plane and nodes — fully managed), binary authorisation (only signed container images can run), and seamless integration with Cloud Run for serverless workloads.

AKS (Azure Kubernetes Service): Microsoft's offering. Strong integration with Azure Active Directory for authentication and Azure Monitor for observability. Popular in enterprise environments where Microsoft products dominate.

eksctl is the official CLI for EKS: eksctl create cluster --name myapp --region us-east-1 creates a complete EKS cluster. For production, use Terraform (terraform-aws-eks module) to manage the cluster as IaC. The eksctl approach is good for learning; Terraform is right for production.

IRSA (IAM Roles for Service Accounts): the secure way to give Kubernetes pods access to AWS services. Instead of mounting long-lived AWS credentials into pods (security risk), IRSA lets pods assume an IAM role via a Kubernetes Service Account. The mechanism: an OIDC identity provider in your EKS cluster, an IAM role with a trust policy that allows the service account, and an annotation on the Kubernetes Service Account. Pods in that service account automatically receive temporary credentials for the IAM role.`,

  pre_flight: `Create an AWS account with billing set up. Install eksctl: eksctl.io/installation. Install the AWS CLI: aws.amazon.com/cli. Configure credentials: aws configure with your IAM access key. Read the EKS getting started guide. Know that an EKS cluster costs money — a minimal cluster (control plane + 2 t3.micro nodes) costs about $0.10/hour for the control plane plus EC2 costs. Destroy the cluster when not in use.`,

  mastery_questions: [
    `You deploy an application to EKS that needs to read from an S3 bucket. How do you grant access securely without hardcoding AWS credentials? Use IRSA. Create an IAM role with a policy that allows s3:GetObject on the bucket. The trust policy allows the EKS cluster's OIDC provider to assume the role, restricted to a specific namespace and service account. Create a Kubernetes ServiceAccount in the namespace with the annotation: eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/my-role. Use this ServiceAccount in your pod spec. The pod's containers receive temporary AWS credentials from the EKS pod identity webhook. No AWS_ACCESS_KEY_ID needed.`,
    `What is the difference between an EKS managed node group and Fargate? Managed node group: EC2 instances you provision and manage (choose instance type, AMI, size). Kubernetes schedules pods onto these nodes. You pay for the EC2 instances. You manage node upgrades (roll the AMI). Good for: predictable workloads, stateful applications, GPU workloads, cost optimisation (spot instances). Fargate: AWS runs each pod on dedicated compute — no EC2 nodes to manage. Each pod gets its own isolated micro-VM. You pay per pod per second. Good for: batch workloads, infrequent jobs, if you want truly managed infrastructure. Limitation: Fargate does not support DaemonSets, stateful sets with persistent volumes (certain storage drivers), or privileged containers.`,
    `How does EKS authentication work? Who can access your cluster and how? EKS uses IAM for authentication and Kubernetes RBAC for authorisation. The kube-apiserver does not natively speak IAM — it uses the AWS IAM Authenticator. When you run kubectl, the kubeconfig executes aws eks get-token which calls the STS AssumeRole API and returns a short-lived token. The API server passes the token to the IAM Authenticator which validates it with AWS. The IAM Authenticator maps the IAM principal (user or role) to a Kubernetes username and groups, defined in the aws-auth ConfigMap (or now, EKS Access Entries). Kubernetes RBAC then determines what the username/groups can do.`,
    `An EKS cluster is running in us-east-1. You want pods to communicate with an RDS database in the same VPC. How do you configure networking? The EKS worker nodes run in your VPC (you specified the subnets when creating the node group). The RDS database is also in the VPC (in private subnets). The pods inherit the worker node's VPC connectivity — they can reach the RDS endpoint by its DNS name within the VPC (no internet required). The security group on the RDS database must allow inbound traffic on port 5432 from the worker node security group (or the pod IP range if using custom networking). Connection string: use the RDS endpoint hostname, which resolves to a private VPC IP.`,
  ],

  common_mistakes: [
    `Forgetting to delete the cluster when not using it. EKS costs money even when idle (control plane: $0.10/hour, worker nodes: EC2 instance costs). Set a calendar reminder or use AWS Cost Alerts. Use eksctl delete cluster or terraform destroy when done learning.`,
    `Placing all worker nodes in public subnets. Production workloads should run in private subnets. Public subnets have direct internet routes — not necessary for worker nodes (they egress via a NAT gateway). Use private subnets for nodes, public subnets for load balancers only.`,
    `Using the cluster admin kubeconfig in production applications. The kubeconfig that eksctl creates has admin privileges. Use IRSA for pod-to-AWS communication. Use Kubernetes Service Accounts with scoped RBAC for pod-to-Kubernetes communication. Never mount admin kubeconfig into pods.`,
    `Not configuring the cluster autoscaler. Without the Cluster Autoscaler, your EKS cluster has a fixed number of nodes. When pods are unschedulable (not enough node capacity), they remain pending. The Cluster Autoscaler watches for pending pods and adds nodes (and removes empty nodes). This is separate from HPA (which scales pods) — CA scales nodes.`,
    `Ignoring EKS version end-of-life. EKS supports Kubernetes for approximately 14 months per minor version. After end-of-life, no security patches are applied. Plan for version upgrades: test in a staging cluster, upgrade the control plane first (managed by AWS), then the node groups.`,
  ],

  debug_help: `kubectl cannot connect to the cluster: run aws eks update-kubeconfig --name CLUSTER --region REGION to update your kubeconfig. Check that your IAM user/role is in the aws-auth ConfigMap. eks:DescribeCluster permission is required. Pod cannot reach RDS: check the RDS security group — does it allow the worker node security group as a source? Run kubectl exec into a pod and nc -zv RDS_ENDPOINT 5432 to test connectivity. ALB Ingress controller not working: ensure the AWS Load Balancer Controller is installed (check helm list -n kube-system). Check the ALB controller logs. The controller needs IRSA permissions to create ALBs. Nodes in NotReady state: kubectl describe node [node-name] for the reason. Common causes: EC2 instance health check failure (replace the node), kubelet failing to connect to the API server (check security groups and VPC routing), or disk pressure (node has insufficient disk space).`,

  ai_assist: [
    `"Write the Terraform configuration to create a production EKS cluster with: a VPC with public and private subnets, an EKS cluster in the private subnets, a managed node group with t3.medium instances (min 2, max 10, desired 3), the Cluster Autoscaler IAM role (IRSA), and the AWS Load Balancer Controller IAM role (IRSA). Use the terraform-aws-eks community module."`,
    `"Write the Kubernetes manifest and IAM role configuration for an IRSA setup. The application needs to write to S3 and publish to SQS. Create: the IAM policy, the IAM role with OIDC trust policy, the Kubernetes ServiceAccount with the role annotation, and the Deployment that uses the ServiceAccount."`,
    `"Write an eksctl config file that creates an EKS cluster in eu-west-1 with: Kubernetes 1.29, a public endpoint, managed nodegroup of 3 t3.medium nodes in private subnets, and Fargate profile for the monitoring namespace."`,
  ],

  stretch: [
    `Set up GitOps for your EKS cluster using Flux CD (covered further in W18). Flux watches a git repository and automatically applies changes to the cluster. When you push a new Kubernetes manifest or change an image tag, Flux reconciles the cluster state. This closes the loop between code changes and cluster state.`,
    `Implement cost optimisation on your EKS cluster using Karpenter (the newer, more efficient replacement for the Cluster Autoscaler). Karpenter provisions nodes directly (bypassing auto-scaling groups) and can select the optimal instance type for each pod's requirements. Configure Spot instances for interruptible workloads.`,
    `Deploy a multi-region active-passive setup: EKS in us-east-1 (primary) and eu-west-1 (secondary). Use Route 53 health checks to fail over DNS from the primary to the secondary if the primary's health check fails. Use RDS cross-region read replicas that can be promoted to primary during a failover.`,
  ],
});

rewriteWeek("devops-cloud", 15, {
  context: `Every cloud provider has different APIs, different pricing models, different service names, and different strengths. AWS has the broadest service catalogue. GCP has the best Kubernetes and data engineering services. Azure is dominant in enterprise environments with Microsoft licenses. Choosing a cloud provider (or using multiple) is a significant architectural decision.

Vendor lock-in is the state where you depend on a specific vendor's proprietary services to the point where switching is prohibitively expensive. The opposite of lock-in is portability — running the same workload on any cloud or on-premises. The tension: proprietary managed services (AWS Lambda, GCP BigQuery, Azure Cosmos DB) offer significantly better developer experience and operational leverage than self-managed open source equivalents, but they tie you to a vendor.

The lock-in spectrum. High lock-in: using AWS Lambda (serverless, AWS-specific), DynamoDB (NoSQL, AWS-specific), SageMaker (ML platform). Low lock-in: running containerised applications on Kubernetes (portable across managed Kubernetes services and on-premises), PostgreSQL (runs everywhere), S3-compatible object storage (Cloudflare R2, Backblaze B2). The pragmatic approach: use proprietary services where the operational leverage is worth the lock-in. Avoid proprietary services for core data storage where migration cost is highest.

Multi-cloud: running workloads across multiple cloud providers simultaneously. The reasons: regulatory requirements (data must stay in a specific region where only one provider has a data centre), avoiding single-vendor risk, negotiating leverage. The reality: multi-cloud adds significant operational complexity. Most startup and mid-size companies do not need multi-cloud. If you are using Kubernetes, you are already 80% of the way to cloud-portable — the remaining 20% is storage, networking, and cloud-specific services.

Cloud-native vs cloud-agnostic: cloud-native means using the managed services of a specific cloud to their fullest extent (Lambda + DynamoDB + SQS + SNS + RDS + ...). Cloud-agnostic means running only portable workloads (containers on Kubernetes, PostgreSQL, Redis) that could run on any cloud. The pragmatic answer for most teams: be cloud-native for your chosen cloud (pick one and use it well) and accept the lock-in as a reasonable operational tradeoff.`,

  pre_flight: `Create accounts on AWS Free Tier, GCP Free Tier, and Azure Free Tier to compare console UX and pricing. Use the AWS, GCP, and Azure pricing calculators to estimate the cost of equivalent services. Read the FinOps Foundation's Cloud Native cost management guide. Know the fundamental services each cloud offers: compute (EC2/Compute Engine/VMs), storage (S3/Cloud Storage/Blob Storage), managed Kubernetes (EKS/GKE/AKS), managed database (RDS/Cloud SQL/Azure Database).`,

  mastery_questions: [
    `You are building a new SaaS application. You need: compute (web servers), a managed relational database, object storage, and a CDN. You are deciding between AWS and Cloudflare + DigitalOcean + Neon. Compare the two approaches. AWS approach: EC2 or ECS for compute, RDS PostgreSQL for database, S3 for storage, CloudFront for CDN. Everything in one console, one bill, integrated IAM. Operational advantage: everything talks to each other with VPC private networking. Cost: higher for small-scale, better economies of scale at large scale. Alternative approach: DigitalOcean App Platform for compute (simpler than EC2), Neon for serverless PostgreSQL, Cloudflare R2 for storage (free egress), Cloudflare CDN (free tier). More vendors, but potentially cheaper at small scale with less lock-in. The right answer depends on team size, scale, and operational capacity.`,
    `What services should you generally avoid abstracting away (high lock-in risk) and which proprietary services are worth the lock-in? Avoid lock-in: data storage (use portable formats: PostgreSQL, Redis, S3-compatible object storage). Data is hard to migrate. Services worth the lock-in: managed Kubernetes (EKS/GKE/AKS — you can migrate your Kubernetes workloads to another managed service), managed databases (RDS — PostgreSQL is portable, even if the RDS management plane is not), serverless functions (AWS Lambda is fast to build with but hard to migrate — acceptable for non-core logic). Do not abstract: if you are going to use Lambda, use it fully — wrapping it in a Docker container "to avoid lock-in" loses the operational benefits while keeping the complexity.`,
    `Your application stores data in a proprietary cloud database (DynamoDB). The vendor announces a 50% price increase. What are your migration options and how do you assess them? DynamoDB-to-PostgreSQL migration is complex: the data models are fundamentally different (key-value/document vs relational). You would need to redesign the schema, write a migration script, run both databases in parallel during migration, and cut over. The cost of migration (engineering time) may exceed years of the price increase. Prevention: design your data layer with a repository pattern that abstracts the database — theoretically portable, though in practice the query patterns are often too database-specific. The lesson: evaluate the exit cost before committing to a proprietary data store.`,
    `A startup has been running on AWS and gets acquired by a company that runs entirely on Azure. What is the migration path? The migration path depends on which services are used. Containerised applications running on EKS: migrate to AKS (the Kubernetes manifests are mostly compatible). Databases: RDS PostgreSQL → Azure Database for PostgreSQL (same PostgreSQL, export/import). S3 buckets: use the AWS S3 to Azure Blob Storage Migration Service. Lambda functions: rewrite for Azure Functions (similar concept, different runtime model). The proprietary services (DynamoDB, SQS, SNS) need the most work — replace with Azure Cosmos DB and Azure Service Bus equivalents, or with cloud-agnostic alternatives (PostgreSQL, RabbitMQ/Redis Streams).`,
  ],

  common_mistakes: [
    `Choosing multi-cloud before you need it. Multi-cloud requires double the operational expertise, double the IAM configurations, cross-cloud networking complexity, and often higher cost. Start single-cloud. Move to multi-cloud only when you have a specific regulatory or business requirement.`,
    `Over-indexing on avoiding vendor lock-in to the point of ignoring managed services. Managed services (RDS vs self-managed PostgreSQL) can save dozens of hours per month on operations. The exit cost is real but rarely triggered. Do not sacrifice operational efficiency for theoretical portability.`,
    `Choosing a cloud based on marketing rather than workload requirements. If your team has deep AWS expertise, choosing GCP to avoid "lock-in" means retraining and slower delivery. Cloud expertise is a competitive advantage — choose the cloud your team knows best, or the one that dominates in your industry.`,
    `Not analysing egress costs. AWS charges for data transfer out of the cloud (egress). At scale, egress costs can be a significant portion of the bill. Cloudflare R2 and Backblaze B2 have no egress fees. Factor egress into your cost model from the start.`,
    `Not using reserved instances or committed use discounts for predictable workloads. On-demand pricing is 3-4x more expensive than 1-year reserved instances for EC2. If you know you will run a certain instance size for at least a year, buy reserved capacity. The savings are significant.`,
  ],

  debug_help: `Unexpected cloud bill: enable AWS Cost Explorer and set up a billing alert for your monthly budget. Group costs by service and by resource tag. The most common surprises: NAT Gateway data processing (charge for all traffic through NAT), EBS snapshots accumulating, data transfer between regions. Cross-cloud latency is high: inter-cloud communication (AWS → GCP) goes over the public internet. For latency-sensitive traffic, keep services in the same cloud and region. Use cloud interconnect (AWS Direct Connect + GCP Partner Interconnect) for private cross-cloud connections at scale. Terraform state confusion across clouds: use separate Terraform workspaces or separate state files for each cloud. One terraform state file for your entire multi-cloud infrastructure is an anti-pattern.`,

  ai_assist: [
    `"Compare the total cost of running a small SaaS application on three architectures for 1 year: (1) AWS EC2 t3.small + RDS db.t3.micro + S3 + CloudFront, (2) DigitalOcean Droplet 2GB + DigitalOcean Managed PostgreSQL + DigitalOcean Spaces + Cloudflare, (3) Hetzner VPS + self-managed PostgreSQL (Docker) + Cloudflare R2. Include compute, storage, database, bandwidth, and estimated operational overhead."`,
    `"I'm building a real-time analytics pipeline. Compare: AWS Kinesis Data Streams + AWS Glue + Amazon Athena vs GCP Pub/Sub + Dataflow + BigQuery. Which is better for a team with no existing cloud commitment? Consider: cost, ease of use, lock-in risk, and the quality of managed services."`,
    `"Write a cloud provider decision matrix for a fintech startup. Rows: key requirements (latency, compliance, data sovereignty, team expertise, cost, vendor support). Columns: AWS, GCP, Azure. Score each cell 1-5. Include a summary recommendation and rationale."`,
  ],

  stretch: [
    `Price out the same infrastructure (EKS equivalent cluster + RDS equivalent + S3 equivalent + CloudFront equivalent) on AWS, GCP, and Azure using their respective pricing calculators for three traffic levels: 1000 monthly active users, 100,000 MAU, and 1,000,000 MAU. Chart the cost curves and identify where each provider becomes more or less cost-effective.`,
    `Implement a cloud-agnostic storage abstraction in your application code. Write a StorageService interface with upload(key, data) and download(key). Implement it for AWS S3 and for S3-compatible Cloudflare R2 using the AWS SDK with a different endpoint. Write a test that verifies both implementations behave identically. This is what portable storage looks like in practice.`,
    `Read the Google SRE book chapters on "Managing Risk" and the Netflix engineering blog post on how they chose and use AWS. Write a one-page summary of the decision-making frameworks each company uses for infrastructure choices.`,
  ],
});
