import { rewriteWeek } from "../rewrite-week";

// full-stack-web W11-W15

rewriteWeek("full-stack-web", 11, {
  context: `REST is not a technology — it is a set of constraints on how you use HTTP. The word "RESTful" is widely abused. What it actually means in practice: your API uses nouns (resources) not verbs in URLs, HTTP methods carry the semantic meaning of the operation, and responses use standard HTTP status codes so clients do not have to parse error messages to know what happened.

URL design: use plural nouns for collections (/users, /orders, /products). Use the pattern /resource/:id for individual items. Nest sub-resources when the relationship is ownership: /users/:id/orders means the orders that belong to a specific user. Do not nest more than two levels deep — it becomes unwieldy. Avoid verbs in URLs: /users/:id/delete is wrong; DELETE /users/:id is correct. The method IS the verb.

HTTP methods and their contracts. GET is safe (reading does not change state) and idempotent (calling it twice has the same effect as calling it once). PUT replaces an entire resource — sending PUT /users/1 with a partial body should fail or overwrite missing fields with null. PATCH updates specific fields only. POST creates a new resource or triggers an action; it is neither safe nor idempotent. DELETE is idempotent — deleting a resource that does not exist should return 404 or 204, but a second DELETE should not crash.

Status codes. 200 OK, 201 Created (after a successful POST), 204 No Content (success with no response body, common for DELETE). 400 Bad Request (malformed request body), 401 Unauthorized (not authenticated), 403 Forbidden (authenticated but not allowed), 404 Not Found, 409 Conflict (duplicate email on registration), 422 Unprocessable Entity (valid JSON but failed validation). 500 Internal Server Error (something broke on the server). Never return 200 with an error message in the body — that makes your API a lie.

This week you design and build the full REST API for Bean Forge: CRUD endpoints for menu items, orders, and customers. You write an OpenAPI spec for it. You use zod for request validation so bad input never reaches your database.`,

  pre_flight: `You have the Node.js/Express URL shortener from W9 and the PostgreSQL/Prisma setup from W10. Install zod (npm i zod) for validation. Install swagger-ui-express and @types/swagger-ui-express for the OpenAPI explorer. Read the HTTP spec overview at MDN: HTTP methods, HTTP status codes. Understand what idempotent means: f(f(x)) = f(x). Understand what safe means in HTTP: the operation has no side effects.`,

  mastery_questions: [
    `You are designing an API for a blog. A user can like a post. What is the correct REST endpoint for this operation and why? The resource is the "like" relationship between a user and a post. The endpoint is POST /posts/:id/likes with the authenticated user's ID inferred from the JWT. To unlike, it is DELETE /posts/:id/likes/:userId. The wrong approach is POST /posts/:id/like-post — that uses a verb in the URL and is not idempotent. The right design models the like as a resource that can be created and destroyed.`,
    `Your API endpoint POST /orders returns 200 OK with {"success": true} on success and {"success": false, "error": "Item out of stock"} on failure. What is wrong with this? The problem is that the HTTP status code always says 200, meaning "everything is fine." Clients (and monitoring tools, load balancers, and API gateways) use the HTTP status code to determine whether a request succeeded. A 200 with an error payload is invisible to infrastructure. A stock error should return 409 Conflict or 422 Unprocessable Entity with a structured error body. The status code is the contract — honour it.`,
    `You have a PUT /users/:id endpoint. A client sends a request with only {"email": "new@example.com"} — no name, no other fields. What should happen? PUT semantics say the entire resource is replaced by the request body. If name is not in the body, the correct behaviour is to set name to null (or the column default). If you want partial updates, the correct method is PATCH. Many APIs get this wrong and treat PUT as PATCH. The distinction matters because it changes client behaviour — PUT assumes the client has the full resource, PATCH assumes it only has the delta.`,
    `You add zod validation to your POST /orders endpoint. The schema requires quantity to be a positive integer. A client sends quantity: "5" (a string). How does this behave? Zod's .number() will reject the string "5" — it does not coerce by default. Use z.coerce.number().int().positive() if you want to accept "5" from a form submission (where all values are strings). Use z.number().int().positive() if you are a JSON API where strings are always wrong. Know which you need: JSON APIs should reject "5" because the client is sending the wrong type. Form handlers often need coercion because HTML forms cannot send typed values.`,
  ],

  common_mistakes: [
    `Returning 200 for errors. If something fails, return the appropriate 4xx or 5xx status. Clients check the status code first — they should not have to parse the body to know if the request succeeded.`,
    `Nesting routes too deeply. /users/:userId/orders/:orderId/items/:itemId is hard to work with. Flatten when the sub-resource makes sense on its own: /order-items/:id is fine if you can access items directly. Nest only when the parent ID is required for the operation.`,
    `Missing validation on all inputs. Validation only on the happy path is not validation. Validate that :id params are valid UUIDs or integers. Validate query parameters (page, limit). Validate request bodies. Reject early — do not let garbage reach your database layer.`,
    `Exposing database errors to clients. If Prisma throws a unique constraint violation, do not return the raw Prisma error message — it exposes your database schema. Map database errors to appropriate HTTP responses: unique constraint = 409 Conflict, foreign key violation = 400 Bad Request.`,
    `Using GET requests for operations that change state. GET /users/1/delete is wrong on two levels: verbs in URLs and a safe method used for a mutation. Browsers and caches may prefetch or cache GET requests. Mutations must use POST, PUT, PATCH, or DELETE.`,
  ],

  debug_help: `Request fails with 404 but the route exists: check the route registration order in Express — more specific routes must come before wildcard routes. Also check whether you are mounting a router with a prefix that changes the full path. Response says "Cannot POST /api/orders" (not your 404): the route is not registered at all, or the HTTP method is wrong. Use app._router.stack to list registered routes during debugging. Zod validation error returns a 500 instead of 400: you are not catching the ZodError. Wrap your validation in a try/catch and return 400 with z.ZodError.errors when validation fails. Prisma throws "Unique constraint failed" but you are catching it as a generic Error: check the error code. Prisma throws PrismaClientKnownRequestError with code P2002 for unique constraint violations. Check error.code before deciding on the HTTP status.`,

  ai_assist: [
    `"I have this Express route handler: [paste code]. Write a zod schema that validates the request body and returns structured validation errors with field-level messages on failure."`,
    `"Generate an OpenAPI 3.0 spec in YAML for these endpoints: [paste your route list]. Include request/response schemas, status codes, and examples."`,
    `"I'm getting a PrismaClientKnownRequestError when a user tries to register with a duplicate email. Show me how to catch it, identify it as a P2002 error, and return a 409 response with a clear error message."`,
  ],

  stretch: [
    `Add cursor-based pagination to your GET /menu-items endpoint. Return a cursor field in the response that the client can pass as a query param to get the next page. Offset-based pagination breaks when items are inserted during pagination — cursor-based does not.`,
    `Generate a Postman collection from your OpenAPI spec using the openapi-to-postman library and import it into Postman. Run the full collection and verify every endpoint returns the expected status codes.`,
    `Implement API versioning via URL prefix (/api/v1/...). Add a v2 endpoint that returns a different response shape for one resource. Think about how you would handle deprecation — add a Deprecation response header to v1 endpoints.`,
  ],
});

rewriteWeek("full-stack-web", 12, {
  context: `Authentication is about identity: who are you? Authorisation is about permission: what are you allowed to do? These are different systems and conflating them causes security holes. This week you build both correctly for Bean Forge, and you understand the tradeoffs between the two main approaches: sessions and JWTs.

Sessions: when a user logs in, you create a server-side session record (stored in a database or Redis) and set a session ID in an HttpOnly cookie. On every subsequent request, the browser sends the cookie, you look up the session, and you know who the user is. Sessions are easy to invalidate: delete the record. The cookie is HttpOnly so JavaScript cannot read it, preventing XSS token theft. The downside: every request hits the database. For most apps, this is fine.

JWTs (JSON Web Tokens): you sign a payload (user ID, roles, expiry) with a secret key and send the token to the client. The client stores it and sends it with every request. You verify the signature without hitting the database — stateless. The downside: you cannot invalidate a JWT until it expires. If a user's permissions change or their account is compromised, the old token keeps working until expiry. Workarounds exist (blocklist, short expiry + refresh tokens) but they add complexity. Use sessions unless you have a specific reason for JWTs (microservices, third-party clients).

Password storage: hash with bcrypt or argon2. Never store plain text. Never use MD5 or SHA-1 for passwords — these are fast hashing algorithms and can be brute-forced. Bcrypt is deliberately slow. The cost factor (work factor) controls how slow — a cost factor of 12 means 2^12 iterations. Always hash on the server — never trust a hash sent from the client.

OAuth 2.0: the protocol that powers "Sign in with Google." The user is redirected to Google, they grant permission, Google redirects back with an authorization code, your server exchanges the code for tokens using a back-channel request. The key security feature: the client secret never leaves your server. PKCE (Proof Key for Code Exchange) prevents code interception attacks when the redirect target is a public client (like a mobile app or SPA) that cannot keep a client secret.

This week: add email/password auth to Bean Forge with sessions. Add "Sign in with Google" using NextAuth or a manual OAuth implementation. Protect routes with middleware that checks for a valid session.`,

  pre_flight: `Install bcryptjs (npm i bcryptjs @types/bcryptjs). Install express-session and connect-pg-simple (to store sessions in PostgreSQL) or iron-session for a cookie-only session. Know the Prisma schema for a User model with email (unique), passwordHash, role, and createdAt. Read the NextAuth documentation if you are in the Next.js path. Understand what an HttpOnly cookie is and why JavaScript cannot read it.`,

  mastery_questions: [
    `A user logs in and you create a session. Two hours later, the user's account is suspended by an admin. The user still has their session cookie. What happens on their next request, and how do you handle it? The session lookup finds the session record in the database. But before trusting it, you must re-fetch the user from the database to check their current status. If you only store the user object in the session at login time, you will not see the suspension until the session expires. The correct approach: store only the userId in the session, fetch the user on every request (or cache with short TTL), and check the active/suspended status.`,
    `You want to implement "remember me" functionality — the session should last 30 days if the user checks the box, and 1 hour if they do not. How do you implement this? Set the session maxAge differently based on the checkbox. If remember me is checked: maxAge: 30 * 24 * 60 * 60 * 1000 (30 days in ms). If not: maxAge: 60 * 60 * 1000 (1 hour). The session store must also honour the expiry — connect-pg-simple deletes expired sessions. The cookie rolling option (re-setting maxAge on each request) prevents active users from being logged out.`,
    `You are implementing OAuth with Google. A user clicks "Sign in with Google", gets redirected, and Google returns them to your callback URL. How do you prevent a CSRF attack on the callback? The state parameter. Before redirecting to Google, generate a random string, store it in the user's session, and pass it as the state query parameter in the redirect URL. When Google returns to your callback, verify that the state parameter matches what you stored. If they do not match, reject the request. This prevents a malicious site from sending a user to your callback URL with an authorization code it obtained elsewhere.`,
    `Your login endpoint accepts {"email": "...", "password": "..."} and returns a session cookie. How do you prevent timing attacks that allow an attacker to determine whether an email address exists? Bcrypt's compare function takes roughly the same time regardless of whether the hash matches. But if the email does not exist, you skip the compare entirely — returning faster, which leaks that the email is not registered. Fix: always call bcrypt.compare even when the user is not found. Pass a dummy hash when the user is not found. This ensures the response time is consistent whether or not the email exists.`,
  ],

  common_mistakes: [
    `Storing the full user object in the session instead of just the userId. If the user's role changes, the session still holds the old role. Always store the userId and re-fetch the user on each request (or use a short-lived cache).`,
    `Setting cookies without HttpOnly and Secure flags. HttpOnly prevents JavaScript from reading the cookie (blocks XSS token theft). Secure ensures the cookie is only sent over HTTPS. Both flags must be set in production. In development, Secure can be omitted for localhost.`,
    `Not expiring or rotating sessions after password changes. If a user changes their password, all existing sessions should be invalidated. Store a tokenVersion or passwordChangedAt on the user, increment it on password change, and validate it against the session on each request.`,
    `Logging passwords in error messages. If login fails and you log request bodies for debugging, passwords end up in your logs. Never log request bodies that may contain credentials. Redact sensitive fields from any logging middleware.`,
    `Using JWT for sessions without understanding the invalidation problem. If you use JWTs with a 24-hour expiry and a user is compromised, you cannot lock them out for 24 hours. Either use short-lived JWTs (15 minutes) with refresh tokens stored in the database, or just use sessions.`,
  ],

  debug_help: `Session cookie is not being sent on subsequent requests: check sameSite setting. If your frontend and backend are on different domains (localhost:3000 and localhost:4000), sameSite: 'none' and secure: true are required. In development with both on localhost, use sameSite: 'lax'. bcrypt.compare always returns false even with the correct password: you may be hashing the hash. Make sure you are storing the hash (the output of bcrypt.hash) and comparing against the original plain-text password. OAuth callback fails with "state mismatch": the state value was not stored before the redirect or was lost (e.g., session not initialised before the redirect). Ensure session middleware runs before the OAuth route. Google returns an error at the callback URL: check that your redirect URI in Google Cloud Console exactly matches the one you pass in the authorization URL — including trailing slashes and http vs https.`,

  ai_assist: [
    `"Write a bcrypt-based email/password login function in TypeScript. It takes email and password, looks up the user in a Prisma database, compares the password hash, and returns the user or throws a specific error (not a generic one) for email not found vs wrong password. Use constant-time comparison to prevent timing attacks."`,
    `"I'm implementing OAuth with Google using the authorization code flow manually (not NextAuth). Give me the exact sequence: redirect URL construction, callback handler, token exchange, user upsert. Include the state parameter for CSRF protection."`,
    `"Write an Express middleware function that reads the session, fetches the current user from the database, checks that the user is active (not suspended), and attaches the user to req.user. Return 401 if no session, 403 if user is suspended."`,
  ],

  stretch: [
    `Implement refresh token rotation. Issue a short-lived JWT (15 min) and a long-lived refresh token stored in the database. On each use of the refresh token, issue a new pair and invalidate the old refresh token. This is more secure than a single long-lived JWT.`,
    `Add role-based access control. Users have roles: customer, staff, admin. Write middleware that accepts a required role and rejects requests from users with insufficient roles. Use it to protect admin-only endpoints.`,
    `Implement account lockout after 5 failed login attempts. Store failedLoginAttempts and lockedUntil on the User model. Increment on failure. Lock for 15 minutes after 5 failures. Reset on successful login.`,
  ],
});

rewriteWeek("full-stack-web", 13, {
  context: `Stripe is the standard for online payments because it handles the hard parts: PCI compliance, fraud detection, 3D Secure, global payment methods, tax calculation. Your job is to integrate it correctly — and "correctly" means understanding that webhooks, not API responses, are the source of truth.

Stripe primitives. A Customer is a Stripe object that represents a paying user — attach your user's database ID to the Stripe customer for lookups. A Product is what you sell (a SaaS plan, a physical item). A Price is how you sell it — attached to a Product, can be recurring (subscription) or one-time. A PaymentIntent represents an attempt to collect payment — it has a status lifecycle (requires_payment_method, requires_confirmation, processing, succeeded, canceled). A Subscription links a Customer to a Price with a billing cycle.

Checkout vs Elements. Stripe Checkout is a hosted payment page — Stripe renders the UI, handles card number entry, validation, and 3D Secure. Use Checkout for most apps: it is the fastest path to PCI compliance because card numbers never touch your server. Stripe Elements is a set of embeddable UI components — you control the layout, Stripe handles the secure input fields. Use Elements when you need a custom checkout experience (your design team will not accept the Stripe-hosted page).

Webhooks are the source of truth. When a user completes payment, Stripe fires a webhook to your server. You must handle these events and update your database accordingly — do not update the database based on the API response from your server-side checkout creation call, because the user might close the browser before the success page loads. The events you care about: checkout.session.completed, customer.subscription.created, customer.subscription.updated, customer.subscription.deleted, invoice.payment_succeeded, invoice.payment_failed. Verify webhook signatures using Stripe's library — reject any request that does not have a valid signature.

This week you add a subscription to Bean Forge. Users can subscribe to "Bean Forge Pro" for a monthly fee. You create the Stripe checkout session, handle the success/cancel redirects, and process webhooks to grant/revoke Pro status in your database.`,

  pre_flight: `Create a Stripe account at stripe.com. Install the Stripe Node library: npm i stripe. Install the Stripe CLI for local webhook testing: stripe listen --forward-to localhost:4000/webhooks/stripe. Add STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, STRIPE_PRICE_ID (your Pro plan price ID) to your .env. Add a stripeCustomerId and isPro boolean to your User Prisma model. Read the Stripe docs quickstart for Node.js.`,

  mastery_questions: [
    `A user pays successfully, the Stripe Checkout redirect sends them to your /success page, and your success page marks them as Pro. What is the failure mode here? If the user closes the browser immediately after payment but before the redirect fires, your success page never loads, and the user is never marked as Pro. Stripe received the payment; your database does not know. The fix: never update the database based on a redirect. Instead, handle the checkout.session.completed webhook. Webhooks are server-to-server — they do not depend on the user's browser.`,
    `Your webhook endpoint is receiving events. How do you verify that the request actually came from Stripe and is not a forged request from an attacker? Use stripe.webhooks.constructEvent(rawBody, signature, webhookSecret). The signature is in the Stripe-Signature header. Stripe signs the raw request body with your webhook secret. If you parse the body as JSON before calling constructEvent, the signature validation fails because the raw bytes have been altered. In Express, use express.raw({ type: 'application/json' }) for the webhook route, not express.json().`,
    `A user's subscription is cancelled. What events does Stripe fire, and when does access end? When a subscription is cancelled, Stripe fires customer.subscription.updated with status "active" and cancel_at_period_end: true if it is a scheduled cancellation. At the end of the billing period, Stripe fires customer.subscription.deleted. You should revoke Pro access on the deleted event, not the updated event — the user has paid for access through the end of the period. Revoking early is a support ticket.`,
    `You want to offer a 14-day free trial before charging. How do you implement this with Stripe? Set the trial_period_days parameter when creating the subscription, or pass trial_end as a Unix timestamp. Stripe will not charge the customer until the trial ends. The subscription status during the trial is "trialing." You should still collect payment method upfront — otherwise many users will not add one before the trial ends. When the trial ends, Stripe fires customer.subscription.updated with status changing from "trialing" to "active."`,
  ],

  common_mistakes: [
    `Updating the database from the redirect URL instead of from webhooks. The redirect is a user experience signal, not a payment confirmation. Webhooks are the confirmation.`,
    `Parsing the webhook body with express.json() instead of express.raw(). The JSON parser transforms the raw bytes, breaking the HMAC signature verification. The webhook route must receive the raw body. Use express.raw({ type: 'application/json' }) for that specific route.`,
    `Not verifying the webhook signature. If you skip verification, anyone can POST fake events to your webhook endpoint and grant themselves Pro access. Always verify.`,
    `Storing the Stripe secret key in your frontend code or git repository. The secret key can issue charges on your behalf. Store it in environment variables only, never in client-side code or in git history.`,
    `Not handling idempotency in webhook processing. Stripe may deliver the same webhook more than once. Your handler must be idempotent — processing the same event twice should not create two subscriptions. Use the Stripe event ID to track which events you have already processed.`,
  ],

  debug_help: `Webhook signature verification fails: check that you are using express.raw() not express.json() for the webhook route. Also verify the STRIPE_WEBHOOK_SECRET matches the one shown in the Stripe CLI output when you run stripe listen. Checkout session creation fails with "No such price": the price ID in your .env does not match a real price in your Stripe account. Make sure you are using the correct mode — test mode prices start with price_ and are only visible in test mode. The Stripe CLI is not forwarding events: make sure you are running stripe listen --forward-to localhost:PORT/webhooks/stripe in a separate terminal. The webhook fires but the database is not updated: add console.log to your webhook handler to verify the event type matches what you are handling — the event object has a type field.`,

  ai_assist: [
    `"Write a Node.js/Express webhook handler for Stripe that handles checkout.session.completed, customer.subscription.updated, and customer.subscription.deleted. It should verify the signature, extract the relevant data, and update a Prisma User record with isPro and stripeSubscriptionId. Include idempotency: skip events that have already been processed."`,
    `"Write a TypeScript function that creates a Stripe Checkout session for a subscription. It takes userId and priceId, looks up or creates the Stripe Customer for that user, and returns the checkout URL. Include success and cancel URLs."`,
    `"Explain the Stripe payment status lifecycle for subscriptions: what events fire in what order for a new subscription, a successful renewal, a failed renewal, and a cancellation."`,
  ],

  stretch: [
    `Add a customer portal link using Stripe Billing Portal. Users can manage their subscription (upgrade, downgrade, cancel) without you building any UI. One API call to create a portal session, redirect the user there.`,
    `Implement metered billing. Track usage in your application (e.g., number of API calls per month) and report it to Stripe using subscription items. Stripe bills based on the reported usage at the end of the billing period.`,
    `Handle failed payments. When invoice.payment_failed fires, send the user an email with a link to update their payment method. Give them 3 days before revoking access. Track payment failure state on the user model.`,
  ],
});

rewriteWeek("full-stack-web", 14, {
  context: `Email is infrastructure. When a user signs up, forgets their password, makes a purchase, or triggers any significant event, your application sends email. Getting email right means understanding the difference between transactional email and marketing email, the infrastructure that determines whether your message reaches the inbox, and the regulations that govern what you can send.

Transactional email is triggered by user action: welcome email, password reset, order confirmation, invoice. The user expects it. Send it from a transactional email provider: Resend, Postmark, or AWS SES. These providers optimise for deliverability on triggered, one-to-one messages.

Marketing email is bulk: newsletters, product announcements, promotional campaigns. Use a marketing email provider: Loops (good for SaaS), Mailchimp, or ConvertKit. The distinction matters because bulk email and transactional email have different sending patterns — ISPs treat them differently. Mixing them harms your transactional deliverability.

Deliverability: the science of getting email into the inbox. The three DNS records you must configure. SPF (Sender Policy Framework): a TXT record that lists the mail servers authorised to send email from your domain. Prevents strangers from sending email that appears to come from you. DKIM (DomainKeys Identified Mail): your email provider generates a key pair. You publish the public key as a DNS TXT record. The provider signs outgoing emails with the private key. Recipients verify the signature. Proves the email was not altered in transit. DMARC (Domain-based Message Authentication, Reporting, and Conformance): a policy that tells receiving servers what to do with email that fails SPF and DKIM checks — reject it, quarantine it, or report it. Start with p=none (report only), move to p=quarantine, then p=reject.

Regulations. CAN-SPAM (US): all commercial email must include a physical mailing address and an unsubscribe link. The unsubscribe must work within 10 business days. GDPR (EU): you need consent to send marketing email to EU residents. Pre-ticked checkboxes do not count. Keep a record of when and how consent was given.

This week you add transactional email to Bean Forge: welcome email on signup, password reset flow (token generation, email dispatch, token verification), and order confirmation.`,

  pre_flight: `Create a Resend account at resend.com (free tier is generous). Get your API key. Install the Resend SDK: npm i resend. Add RESEND_API_KEY to your .env. Add a FROM_EMAIL to your .env (you can use onboarding@resend.dev in development without domain verification). Read the Resend Node.js quickstart. Know how to generate a cryptographically secure random token in Node: crypto.randomBytes(32).toString('hex').`,

  mastery_questions: [
    `You send a password reset email with a token. The email contains a link to /reset-password?token=abc123. How do you implement this securely? Generate the token with crypto.randomBytes(32).toString('hex'). Hash it before storing in the database (use SHA-256 — it does not need to be bcrypt because password reset tokens are long-lived and random, not user-chosen). Store the hash, the userId it belongs to, and an expiry (15 minutes from now). Send the raw token in the email link. When the user clicks the link, hash the token from the URL, look up the hash in the database, verify it has not expired, then allow the password reset and delete the token. The reason you store the hash: if your database is breached, the attacker cannot use the stored tokens to reset passwords.`,
    `A user reports they never received the welcome email. What do you check? First check your email provider dashboard for the send event — did it actually send? If yes, was it delivered? If delivered, ask the user to check spam/junk. If not delivered, check the bounce reason — invalid address, hard bounce (address does not exist) vs soft bounce (mailbox full). Check your sending domain's DNS records (SPF, DKIM, DMARC) using MX Toolbox. Check that the FROM address is from a verified domain. For transactional email, check that you are not sharing sending infrastructure with bulk senders.`,
    `You want to send an order confirmation email with a PDF attachment (the invoice). What does this look like in code with Resend? Resend accepts attachments as base64-encoded content. Generate the PDF using a library like PDFKit or @react-pdf/renderer. Convert the buffer to base64: buffer.toString('base64'). Pass it in the attachments array: [{ filename: 'invoice.pdf', content: base64String }]. The content-type is inferred from the filename or you can specify it explicitly with content_type: 'application/pdf'.`,
    `Your password reset tokens are stored in plain text in the database. A database breach occurs. What is the attacker able to do with these tokens? The attacker can use each valid token to reset the corresponding user's password and take over their account. This is why you hash the token before storing it. The token in the email is the raw random bytes — the database stores only the SHA-256 hash. Even with the hash, the attacker cannot reverse it to get the original token (tokens are 32 random bytes, not a dictionary word) and cannot use the hash as the token because the comparison is hash(incoming token) === stored hash.`,
  ],

  common_mistakes: [
    `Sending transactional email and marketing email from the same sending domain and infrastructure. If your newsletters get marked as spam, it damages the reputation of the domain and harms delivery of password reset emails. Use separate subdomains: mail.yourdomain.com for transactional, newsletter.yourdomain.com for marketing.`,
    `Not rate-limiting the password reset endpoint. Without rate limiting, an attacker can enumerate valid email addresses (by observing response time differences) or flood users with reset emails. Rate limit by IP and by email address.`,
    `Storing password reset tokens in plain text. If your database is breached, these are account takeover keys. Hash them with SHA-256 before storage.`,
    `Using non-expiring tokens. Password reset tokens must expire. 15 minutes for password reset, 24 hours for email verification. After use, delete the token immediately so it cannot be reused.`,
    `Not handling email bounces. If you keep sending to bounced addresses, your sender reputation suffers. Use your provider's webhook for bounce and complaint events to unsubscribe those addresses automatically.`,
  ],

  debug_help: `Resend returns a 403 error: your API key is wrong, or the FROM address is from a domain that is not verified in your Resend account. In development, use onboarding@resend.dev as the from address — it works without domain verification. Email sends but goes to spam: check SPF, DKIM, and DMARC DNS records using MX Toolbox (mxtoolbox.com). Check that your FROM address matches your verified domain. Check the email content — words like "FREE", "Click here", excessive punctuation trigger spam filters. Password reset link in email is wrong: check that your BASE_URL environment variable is set correctly and includes https:// without a trailing slash. The link is constructed as BASE_URL + '/reset-password?token=' + token. Email sends in development but not in production: check that RESEND_API_KEY is set in your production environment variables (not just .env).`,

  ai_assist: [
    `"Write a TypeScript function that generates a password reset token, stores its SHA-256 hash in a Prisma database with a 15-minute expiry, and sends a reset email via Resend. Also write the verification function that takes a token from the URL, hashes it, looks it up in the database, checks expiry, and returns the userId if valid."`,
    `"Write a React Email template for an order confirmation. It should include the order number, list of items with prices, total, and a link to view the order. Use @react-email/components."`,
    `"I need to handle Resend webhooks for bounce and complaint events in Express. Write the handler that verifies the webhook signature and unsubscribes the email address from further sends by setting a suppressedAt field on the User record in Prisma."`,
  ],

  stretch: [
    `Integrate React Email to write your email templates as React components. Run the React Email dev server to preview templates in a browser. This makes email templates maintainable — you can use components, conditionals, and loops instead of raw HTML strings.`,
    `Add an email preferences page where users can opt out of specific email types (marketing, weekly digest, etc.). Store preferences in the database. Check preferences before sending each type of email.`,
    `Set up DMARC reporting and monitor it for a week. Configure a DMARC record with p=none and rua=mailto:dmarc@yourdomain.com. Use a service like DMARC Analyzer to parse the XML reports and see who is sending email claiming to be from your domain.`,
  ],
});

rewriteWeek("full-stack-web", 15, {
  context: `Storing files is not the same as storing data. Database rows are structured and indexed — they are designed for queries. Files are binary blobs that can be gigabytes. Storing them in your database (as BLOBs) works at small scale and is a mess at large scale. The standard architecture: store files in object storage, store the file metadata (URL, size, type, owner) in your database.

Object storage is the category. S3 is Amazon's implementation and the industry standard for the API. Every major cloud has an S3-compatible service: Cloudflare R2 (no egress fees, good choice for most apps), Backblaze B2, DigitalOcean Spaces, Google Cloud Storage. They all implement the same API. The Cloudflare R2 SDK is the AWS SDK with a different endpoint URL — the client code is identical.

Presigned URLs are the right way to handle uploads in a web application. The naive approach: browser uploads file to your server, your server uploads to S3. Problems: your server handles the bandwidth and compute cost, your server is in the critical path, large files can time out. The correct approach: browser asks your server for a presigned URL (a time-limited signed URL that allows a specific upload action), your server generates the presigned URL using the SDK, the browser uploads directly to S3 using that URL — your server is not in the upload path. Your server only handles metadata.

Image optimisation. Next.js has a built-in Image component that handles optimisation — it serves images in WebP or AVIF format (smaller than JPEG/PNG), resizes images to the displayed size (no serving a 2000px image in a 200px container), and lazy loads images below the fold. For user-uploaded images, you typically process them on the server after upload: resize to a maximum dimension, convert to WebP, generate thumbnail variants. Libraries: sharp (fast, native Node module).

Content Delivery Networks cache your static assets at edge locations close to your users. Without a CDN, every user downloads the original file from your single origin server, regardless of geography. With a CDN, the first request to each edge location fetches from origin and caches; subsequent requests are served from the edge — much faster for global audiences. Cloudflare R2 includes CDN functionality. AWS CloudFront sits in front of S3.

This week: add avatar upload to Bean Forge user profiles and menu item image upload to the admin panel using presigned URLs and Cloudflare R2.`,

  pre_flight: `Create a Cloudflare account and create an R2 bucket. Generate R2 API tokens (S3-compatible credentials). Install the AWS SDK S3 client: npm i @aws-sdk/client-s3 @aws-sdk/s3-request-presigner. Install sharp for image processing: npm i sharp. Add R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME, R2_PUBLIC_URL to your .env. Make sure your R2 bucket allows public access (for reading uploaded files).`,

  mastery_questions: [
    `Explain the presigned URL upload flow step by step, including what each party knows and does. Step 1: the browser asks your server for a presigned URL, sending the filename and content type. Step 2: your server validates the request (is the user authenticated? is the file type allowed?), generates a unique S3 key (e.g., users/userId/avatars/randomUUID.webp), calls S3 PutObjectCommand with the key and a 5-minute expiry to generate a presigned URL, and returns the URL and the final public URL of the file to the browser. Step 3: the browser makes a PUT request directly to S3 using the presigned URL, including the file bytes. The presigned URL encodes the allowed bucket, key, content type, and expiry — S3 verifies all of this. Step 4: after the upload succeeds, the browser tells your server the upload is complete, and your server updates the user's avatarUrl in the database to the public URL.`,
    `A user uploads a JPEG avatar. You want to: limit file size to 5MB, resize to 400x400, convert to WebP, and reject non-image files. How do you implement each constraint? File size: in your presigned URL generation, set the ContentLengthRange condition in a policy. Or enforce it client-side before requesting the URL (check file.size < 5 * 1024 * 1024). File type: check file.type on the client and the Content-Type in your server presigned URL request — only allow image/jpeg, image/png, image/webp, image/gif. Processing: after upload (triggered by a webhook from S3 or by a background job), download the file, run it through sharp with .resize(400, 400, { fit: 'cover' }).webp({ quality: 85 }), and replace the original in S3.`,
    `You are displaying 100 product images on a page. Each image is uploaded by an admin and stored at its original size (up to 5MB). What are the performance problems and how do you fix them? Problems: serving full-resolution images in small containers wastes bandwidth, browser must download 100 large files, no lazy loading means they all load at once. Fixes: serve resized variants (generate thumbnails on upload with sharp), use Next.js Image component which handles lazy loading and format optimisation, add Cache-Control headers to your S3 objects so the CDN caches them (max-age=31536000 for images that never change, shorter for images that might). Only the visible images should load initially — Next.js Image does this with loading="lazy".`,
    `An admin deletes a menu item. The menu item had an image in R2. What happens to the image? Nothing, unless you write code to delete it. S3 and R2 have no foreign key constraints — orphaned objects accumulate. Two approaches: delete the R2 object when the database record is deleted (synchronous, simple, can fail partway through and leave the database and storage out of sync); or use a background cleanup job that periodically scans for objects with no corresponding database record and deletes them (asynchronous, more robust). For most apps, the synchronous approach is fine with careful error handling.`,
  ],

  common_mistakes: [
    `Uploading files through your server instead of using presigned URLs. For files larger than a few KB, your server becomes a bottleneck and files can time out on slow connections. Use presigned URLs to let the browser upload directly to storage.`,
    `Not validating file types on the server. A client-side check is a hint, not a security control. Validate the Content-Type in your presigned URL generation and verify the uploaded file's actual content (not just the MIME type header, which can be spoofed) using a library like file-type.`,
    `Storing file paths relative to your local filesystem instead of S3 URLs. If you store ./uploads/avatar.jpg, those files do not exist in production (Vercel, Railway, and similar platforms have ephemeral filesystems). Always store the full S3/R2 URL.`,
    `Setting Cache-Control headers that are too short (or not set at all) for static assets. Images that never change should have max-age=31536000, immutable. Without caching headers, every pageview re-fetches the same images.`,
    `Using the same S3 key for updated files. If a user uploads a new avatar and you store it at users/123/avatar.jpg (overwriting the old one), CDNs and browsers that cached the old URL will continue serving the old image. Use content-based keys (UUID or hash) so each upload has a unique URL.`,
  ],

  debug_help: `Presigned URL request returns "Access Denied": verify the R2 API token has read/write permissions for the bucket. Check that the bucket name in your code matches the actual bucket name. R2 returns a CORS error during upload: R2 buckets require CORS configuration. In your R2 bucket settings, add a CORS rule that allows PUT from your frontend domain with the Content-Type header. sharp fails to install: sharp is a native module that requires compilation. Run npm rebuild sharp after installing. On Windows, you may need the Visual Studio build tools. Alternatively, use sharp's WebAssembly build: npm i @img/sharp-wasm32. Uploaded images are accessible but show as broken: check that your R2 bucket is set to public access and that your R2_PUBLIC_URL environment variable matches the public URL shown in the R2 dashboard.`,

  ai_assist: [
    `"Write a Next.js API route that generates a presigned R2/S3 upload URL. It takes filename and contentType from the request body, validates that contentType is an image type, generates a unique key (users/{userId}/avatars/{uuid}.{ext}), creates a presigned PutObject URL with a 5-minute expiry, and returns both the presigned URL and the final public URL."`,
    `"Write a sharp-based image processing function that takes a Buffer (from S3 download), resizes it to 400x400 with cover cropping, converts it to WebP with 85% quality, and returns the processed Buffer."`,
    `"Write the CORS configuration JSON for Cloudflare R2 that allows PUT requests from localhost:3000 and my-production-domain.com, allows the Content-Type header, and exposes the ETag header."`,
  ],

  stretch: [
    `Add a blurhash placeholder for images. When an image is uploaded, generate a blurhash string using the blurhash library and store it with the image metadata. Display the blurhash as a blurred placeholder while the real image loads — this eliminates layout shift and gives a preview before the image arrives.`,
    `Implement image upload progress in the browser. Instead of using fetch for the presigned URL upload, use XMLHttpRequest — it has an upload.onprogress event that gives you bytes uploaded and total bytes. Show a progress bar to the user.`,
    `Set up S3 lifecycle rules on your bucket to automatically delete incomplete multipart uploads after 7 days. Large file uploads that are started but not completed leave partial data in S3 that costs money. Lifecycle rules clean this up automatically.`,
  ],
});
