import { rewriteWeek } from "../rewrite-week";

// ml-engineering W21-W24

rewriteWeek("ml-engineering", 21, {
  context: `MLOps is the practice of applying software engineering disciplines to machine learning workflows: version control, testing, CI/CD, automated deployment, and monitoring. The reason ML needs its own discipline is that training a model is not a deterministic function — the same code with different data produces different models. The same model with different data distributions produces different predictions. MLOps adds structure to manage this non-determinism while maintaining velocity.

CI/CD for ML differs from web application CI/CD in important ways. The CI for a web app runs unit tests that pass or fail deterministically. The CI for an ML pipeline runs model training that produces a model with a quality metric. "Did the tests pass?" is replaced by "Did the model achieve at least 0.72 ROC AUC on the validation set?" The deployment decision depends on model quality, not just test passage.

Pipeline triggers determine when retraining happens. Code changes: a developer updates the model architecture or the feature engineering code — the pipeline runs automatically. Data changes: a data quality check detects that the new training batch has a different distribution from the reference — the pipeline runs with an alert. Scheduled: the pipeline runs weekly regardless, incorporating new data to maintain model freshness. Manual: a data scientist triggers a training run with specific hyperparameters for an experiment.

Testing ML code is different from testing model quality. Test the code: unit tests for feature engineering functions (does the transform produce the expected columns with the expected types?), data validation (does the training batch meet the expected schema?), and model integration (does the trained model accept the expected input shape and produce output in the expected range?). Test the model: performance above a threshold on the validation set, performance not worse than the previous production model on a comparison set.`,

  pre_flight: `Have a working FlightWise training pipeline from previous weeks. Set up a GitHub Actions workflow file (yaml) that runs on push to main. Know the structure: trigger event, jobs (one or more), steps within each job (checkout code, set up Python, install dependencies, run tests, run pipeline). Understand what dvc repro does: reruns only the pipeline stages whose inputs have changed.`,

  mastery_questions: [
    `You set up a CI/CD pipeline that trains the model on every PR. Training takes 20 minutes. Your team opens 10 PRs per day. CI is running 200 minutes of training per day. Is this sustainable and what are the alternatives? 200 minutes/day is manageable for a small team but expensive in compute cost. Alternatives: (1) Run a smoke test in CI (train for 10 steps on 1000 samples — takes 30 seconds), run full training only on merge to main, (2) Use DVC caching to skip training if the training code and data have not changed (common for PRs that only change documentation or tests), (3) Train on every PR to main only, not feature branches. The right answer depends on the cost of catching regressions late vs. the cost of compute.`,

    `You want to compare the newly trained model against the current production model before deciding whether to deploy. How do you structure this comparison? Maintain a "champion" model in your model registry (the current production version). After training a "challenger" model, evaluate both on the same locked-down comparison dataset (a dataset that does not change between evaluations, separate from the validation set used during training). If the challenger exceeds the champion on the primary metric and does not regress on any guardrail metric, promote the challenger to production. Document the comparison result and store it as a pipeline artifact. This champion-challenger framework is the standard pattern for safe model updates.`,

    `Your MLOps pipeline uses DVC for data versioning and MLflow for experiment tracking. A colleague asks why you need both — "can't DVC track the model artifacts too?" They can partially overlap. DVC tracks file artifacts (data, models as files) with content hashing. MLflow tracks the full experiment context (hyperparameters, metrics, artifacts, model metadata, run lineage). DVC is better for: tracking large data files, pipeline caching, collaborative data access. MLflow is better for: comparing experiment runs, model versioning with metadata, and the model registry with lifecycle stages. In a mature MLOps setup, you use both: DVC for data, MLflow for experiment tracking and model registry.`,

    `You want to automatically retrain when data drift is detected. Your drift monitoring pipeline detects PSI > 0.25 on two features. What happens next in a fully automated MLOps pipeline? The drift detection job publishes an event to a message queue (SQS, Pub/Sub, or a webhook). The retraining pipeline subscribes to that event and triggers automatically. The pipeline: fetches recent training data (including the drifted distribution), runs the DVC pipeline, evaluates the new model against the champion, and either promotes automatically (if above threshold) or opens a pull request for human review (if the quality change is ambiguous). Full automation without human review is appropriate only when the automated evaluation is highly trusted. Most teams keep a human in the loop for promotion decisions.`,

    `You want to test the data loading step of your pipeline in CI without downloading the full 50GB training dataset. What strategies work? (1) Use a small fixture dataset (500 rows) that you commit to git alongside the test code. The test validates that the loading function produces the right schema and types. (2) Use DVC's --no-commit flag to pull a specific small subset from remote storage. (3) Mock the data loading function in unit tests and test the transformation logic independently. The principle: unit tests should run without accessing external storage. Integration tests that require real data should be gated behind a flag and run less frequently (nightly rather than on every PR).`,
  ],

  common_mistakes: [
    `Automating deployment without a human review step for the first few months. Fully automated deployment is appropriate when you have high confidence in your automated evaluation. Before that confidence is established, require a human to approve each promotion from challenger to champion.`,

    `Not storing the pipeline configuration alongside the model artifact. The model file alone is not enough to reproduce a training run. Store with every registered model: the DVC pipeline hash, the MLflow run ID, the data version, and the Python environment hash. Without these, you cannot reproduce the model.`,

    `Using wall-clock time as the data freshness criterion ("retrain every Monday") instead of data-driven triggers. A model may need retraining after 3 days if the data shifts rapidly, or may be fine for 3 months if the distribution is stable. Use drift detection to determine when retraining is needed, not a fixed schedule.`,

    `Running CI pipeline jobs sequentially when they could run in parallel. In GitHub Actions, jobs run sequentially by default. If data validation and unit tests are independent, run them as parallel jobs using the jobs.<job_id>.needs syntax to express only the actual dependencies.`,

    `Not versioning the evaluation dataset. If the comparison dataset changes between evaluations (because it includes new data or was accidentally regenerated), champion-challenger comparisons are invalid. Lock the comparison dataset and version it explicitly.`,
  ],

  debug_help: `The most confusing MLOps pipeline failure is a CI run that passes locally but fails in GitHub Actions. Almost always: a dependency that is installed locally but missing from requirements.txt, an environment variable that exists locally but is not set in the CI environment (set it in GitHub Secrets), a file path that works locally with an absolute path but fails in CI with a relative path, or a test that depends on a GPU that is not available in CI. Run the CI pipeline locally with: \`act\` (a tool that runs GitHub Actions workflows locally) to reproduce the exact CI environment before debugging.`,

  ai_assist: `Use Claude to help you write the GitHub Actions workflow file for your MLOps pipeline. Describe: when to trigger (push to main, PR), what jobs to run (unit tests, data validation, smoke training, evaluation), what environment variables are needed, and what artifacts to store. Ask it to generate the complete workflow YAML. Review every section — workflow YAML has strict indentation requirements and subtle bugs that only appear when the workflow runs.`,

  stretch: [
    `Implement the champion-challenger framework completely: after training a new model, load the current production model artifact, evaluate both on a locked comparison set, and output a comparison report as a GitHub Actions artifact. Add a manual approval gate that requires a reviewer to check the report before promotion.`,
    `Set up alerting for pipeline failures: if the training pipeline fails or the model quality falls below threshold, send a Slack message or email with the failure reason and a link to the failed GitHub Actions run.`,
    `Implement a model leaderboard: a Streamlit app that reads from your MLflow tracking server and displays all registered models with their validation metrics, training date, and deployment status. This replaces ad-hoc checking of the MLflow UI with a purpose-built dashboard.`,
  ],
});

rewriteWeek("ml-engineering", 22, {
  context: `Single-machine training has a ceiling. When your dataset is larger than RAM, or when your model requires more VRAM than one GPU, or when you want to parallelize training across many machines to save time, you need distributed computing. The transition from single-machine to distributed training is one of the most important scaling decisions an ML engineer makes.

The symptoms that indicate you need distributed: training data does not fit in RAM (Pandas cannot load it), a single GPU epoch takes more than a day, model weights require more VRAM than any available single GPU, or you need to reduce a 2-week training run to 2 days to stay competitive. Each symptom has a different solution, and conflating them is a common mistake.

Apache Spark for preprocessing handles the first case. Spark distributes data processing across a cluster of machines, enabling processing of datasets far larger than any single machine's RAM. The DataFrame API is similar to Pandas but operates lazily — computations are not executed until you collect or write results. This enables Spark to optimise the execution plan before running. Spark is excellent for ETL, feature engineering at scale, and batch inference. It is not a training framework.

Distributed Data Parallel (DDP) handles training a single model on multiple GPUs. Each GPU maintains a full copy of the model and processes a different batch of data. Gradients are synchronised across GPUs after each backward pass. This effectively multiplies your batch size by the number of GPUs. DDP achieves near-linear scaling (2 GPUs produces nearly 2x throughput) because gradient synchronisation overhead is small relative to computation.

Model parallelism handles the case where the model itself does not fit on a single GPU. Different layers are placed on different GPUs. A batch passes through GPU 0 (layers 1-10), then GPU 1 (layers 11-20), then GPU 2 (layers 21-30). This is pipeline parallelism. Tensor parallelism splits individual layers across GPUs. Both are more complex to implement and have lower efficiency than DDP due to communication overhead.`,

  pre_flight: `Install pyspark (for Spark preprocessing) and understand that Spark runs as a JVM application — you need Java installed. Know that PyTorch DDP requires multiple GPUs or can be simulated with CPU on a multi-core machine. Have torchrun available (installed with PyTorch). Understand the difference between data parallelism (multiple GPUs, same model) and model parallelism (one model, spread across GPUs).`,

  mastery_questions: [
    `Your Pandas pipeline loads a 120GB CSV into memory, which exceeds your 64GB RAM. You switch to Spark. What does Spark do differently that allows it to handle this data? Spark processes data in partitions. The 120GB CSV is split into hundreds of partitions, each fitting in memory. Spark processes partitions sequentially or in parallel across worker nodes, never loading the full dataset at once. Additionally, Spark is lazy — computations are not executed until an action (collect, write) is called. This allows Spark to optimise the execution plan, push down filters (reducing data read from disk), and fuse operations to minimise passes over the data.`,

    `You want to use DDP with 4 GPUs to train your model. Your current single-GPU training uses batch_size=64 and learning_rate=0.001. What do you change for DDP? Batch size: with DDP, each GPU processes batch_size=64, but the effective batch size is 4 * 64 = 256 (gradients are averaged across 4 GPUs, equivalent to one batch of 256). Learning rate: scale linearly with the effective batch size: new_lr = 0.001 * 4 = 0.004. This linear scaling rule (from the "don't decrease the learning rate" paper) works well up to batch sizes of about 8192. Add a warmup period: ramp the learning rate from 0 to the target over the first few epochs. Without warmup, large learning rates at the start of training cause instability.`,

    `You run DDP training on 4 GPUs. Your single-GPU throughput is 500 samples/second. With 4 GPUs, you achieve 1,800 samples/second instead of the theoretical 2,000. What causes the 10% efficiency loss? Gradient synchronisation overhead: after each backward pass, gradients are all-reduced across all 4 GPUs. This requires inter-GPU communication over NVLink or PCIe, which takes time. On a single machine with NVLink, this overhead is small (5-10% for typical models). Across multiple machines connected by Ethernet, the overhead can be 20-40%. Other sources of inefficiency: data loading cannot keep up with GPU computation (solution: increase DataLoader workers, use prefetch), load imbalance if batches vary in length (sequence models).`,

    `Spark gives you a DataFrame with 500M rows after feature engineering. You want to convert it to PyTorch tensors for training. What is the challenge? Spark runs on the JVM; PyTorch runs in Python. Converting a 500M-row DataFrame to a PyTorch tensor requires: (1) saving the Spark DataFrame to disk (Parquet format is efficient), (2) loading it into PyTorch's DataLoader using a custom Dataset class that reads Parquet files. A 500M-row dataset will not fit in RAM as a PyTorch tensor — you must stream it. Use a PyTorch IterableDataset that reads Parquet files in chunks. This avoids loading the full dataset into RAM at once.`,

    `When does it make sense to scale out (more machines) versus scale up (bigger machine) for ML? Scale up first. A single machine with more RAM or more GPUs is simpler to manage, cheaper to operate, and avoids distributed systems complexity. Scale out when: the data truly cannot fit on any single machine (rare for preprocessing, common for petabyte-scale), or when the compute requirement exceeds what any single machine provides (training very large models). Common mistake: scaling out prematurely because one machine "feels slow." Profile first: is the bottleneck RAM, CPU, GPU, or IO? Each has a single-machine solution before distributed systems are required.`,
  ],

  common_mistakes: [
    `Using Spark for small datasets. Spark has significant overhead for cluster setup and job scheduling. For datasets under 10GB, Pandas (or Dask for 10-100GB) is faster and simpler. Use Spark when the data genuinely requires distributed processing.`,

    `Not accounting for gradient accumulation batch size when implementing DDP. If you use gradient accumulation (accumulate_steps=4) with DDP (4 GPUs), the effective batch size is batch_size * accumulate_steps * num_gpus. Ensure the learning rate is scaled to this effective batch size, not just to the per-GPU batch size.`,

    `Running the full Spark pipeline in development without a local mode shortcut. Add a --dev flag that uses a 10k-row sample from local storage instead of the full distributed dataset. Development iterations on Spark are slow if every run processes the full dataset.`,

    `Not monitoring GPU utilisation during DDP training. If GPU utilisation is below 80%, the GPUs are idle between batches — the bottleneck is elsewhere (data loading, CPU preprocessing, inter-GPU communication). Use nvidia-smi dmon -s u to monitor utilisation in real time.`,

    `Ignoring the cost of multi-machine training. Four machines cost 4x as much as one machine per hour. If DDP achieves 3.5x speedup (due to communication overhead), you are paying 4x for 3.5x speedup — 14% worse cost efficiency. This is still often worth it for time-to-result, but the cost increase must be acknowledged.`,
  ],

  debug_help: `The most confusing DDP bug is non-deterministic training results that vary across runs in a way single-GPU training does not. DDP operations are not perfectly deterministic due to the order of floating-point operations in all-reduce. To get reproducible DDP results: set all random seeds before initialising DDP, use torch.backends.cudnn.deterministic = True, and set CUBLAS_WORKSPACE_CONFIG=:4096:8 (environment variable). Even with these settings, floating-point non-determinism may cause tiny differences. Treat DDP reproducibility as "within statistical noise" rather than bit-for-bit identical.`,

  ai_assist: `Use Claude to help you convert a Pandas feature engineering pipeline to Spark. Paste your existing Pandas code (groupby, merge, window functions) and ask it to write the equivalent Spark DataFrame API code. Spark and Pandas have similar concepts but different APIs. Review the Spark code carefully — Spark's handling of NaN values, date types, and column naming differs from Pandas in ways that cause silent bugs.`,

  stretch: [
    `Profile your DDP training run with PyTorch Profiler to measure the fraction of time spent in: computation (forward + backward), gradient synchronisation, data loading, and optimizer step. Identify the bottleneck and implement one optimisation (e.g., overlap gradient synchronisation with backward pass using gradient bucketing).`,
    `Implement a Spark pipeline that reads from S3, applies feature engineering, and writes output back to S3 as Parquet. Run it on a dataset of 10M rows. Measure total processing time and cost (EMR or Databricks pricing or free tier).`,
    `Benchmark training throughput (samples/second) for 1, 2, and 4 GPUs using DDP. Plot the scaling efficiency curve. Document at what GPU count you see diminishing returns and hypothesise why.`,
  ],
});

rewriteWeek("ml-engineering", 23, {
  context: `Machine learning systems can harm people. Not through dramatic AI takeover scenarios, but through mundane mechanisms: a hiring algorithm that systematically disadvantages one demographic group, a lending model that charges higher rates to historically redlined communities, a medical diagnosis model that performs worse on underrepresented groups. These harms are not hypothetical — they have occurred in deployed systems. Responsible ML is the set of practices that reduce the likelihood and severity of these harms.

Fairness in ML is not a single concept — it is a family of definitions that are mathematically incompatible with each other in most non-trivial cases. Demographic parity requires equal positive prediction rates across groups. Equalised odds requires equal true positive and false positive rates across groups. Calibration requires that predicted probabilities match actual outcome rates for each group. A model cannot satisfy all three simultaneously when base rates differ between groups. This is the fundamental fairness impossibility theorem, and it forces you to make explicit value judgments about which definition fits your use case.

Measuring bias starts with disaggregated metrics: compute accuracy, precision, recall, and false positive rate separately for each protected group in your dataset. If your flight delay model has 78% accuracy for domestic flights but 61% accuracy for international flights, that is a performance disparity that requires investigation regardless of whether the groups are legally protected. Disaggregated evaluation is the baseline practice that every ML project should perform.

Mitigation falls into three categories: pre-processing (reweight or resample training data to reduce representation imbalances), in-processing (add fairness constraints to the training objective), and post-processing (adjust prediction thresholds separately for each group to equalise a chosen metric). Each approach has tradeoffs in complexity, accuracy cost, and which fairness definition it optimises.

Differential privacy adds mathematical guarantees about individual privacy in model training. An epsilon-differentially private model provides a formal bound on how much any individual's data can affect the model's outputs, limiting the information that can be extracted about training set members.`,

  pre_flight: `Install Fairlearn. Know the demographic parity difference: the difference in positive prediction rates between the most and least favored group. Know the equalised odds difference: the maximum difference in true positive rate and false positive rate between groups. Have your FlightWise model and training data ready. Identify a potential sensitive attribute in your dataset: carrier, origin airport, or any attribute that might proxy for a protected characteristic.`,

  mastery_questions: [
    `You compute demographic parity for your loan model across income quintiles. The lowest income quintile is approved at a 15% rate while the highest income quintile is approved at a 62% rate. Is this a fairness problem? The answer requires context. If the base rate of loan repayment (the ground truth) differs across income quintiles in the same proportion, then a model with demographic disparity in approvals may actually be calibrated — it is reflecting the true difference in repayment probability. If the model's approval rate differs more than the base rate difference, it is adding disparity beyond what the underlying data supports. Always compare approval rate disparity to ground truth base rate disparity. Disparity greater than the base rate difference is evidence of algorithmic unfairness.`,

    `You find that your model has a significantly higher false positive rate for Group A than Group B — Group A is more frequently predicted as high-risk when they are actually low-risk. How does this translate to real-world harm? A higher false positive rate means Group A members are more often incorrectly labelled as risky. In lending: Group A members are more often denied loans they would have repaid, costing them the benefits of credit. In hiring: Group A candidates are more often screened out despite being qualified. In criminal justice: Group A defendants are more often predicted to be high recidivism risk when they would not reoffend, leading to longer sentences. The type of harm depends on the consequences of a false positive in the specific application.`,

    `You want to reduce demographic parity difference using post-processing threshold adjustment. How does this work? After training the model, you have a decision threshold (typically 0.5) that converts predicted probabilities to binary decisions. Instead of applying the same threshold to all groups, you apply group-specific thresholds: Group A might be approved above 0.4, Group B above 0.55. The thresholds are chosen to equalise approval rates across groups. The tradeoff: this approach can reduce accuracy (approving some borderline cases that will default, or rejecting some that would have repaid) to achieve demographic parity. Fairlearn's ThresholdOptimizer implements this.`,

    `Differential privacy training with Opacus adds noise to gradients during training. What does the epsilon parameter control and what is the privacy-utility tradeoff? Epsilon is the privacy budget — a formal measure of how much information about any individual training example can be extracted from the model. Lower epsilon = stronger privacy = more noise added = lower model accuracy. Typical epsilon values: epsilon < 1 provides strong formal guarantees but significant accuracy loss; epsilon = 10 provides mild guarantees with small accuracy loss. There is no "free" privacy — every epsilon reduction costs some model quality. The tradeoff must be made explicitly based on the sensitivity of the training data and the use case.`,

    `You write a BIASES.md document for your deployed model. What does it contain? The document covers: (1) Which groups or segments the model performs differently on, with specific numbers (accuracy, false positive rate, false negative rate per group), (2) What data the model was trained on, who is represented, and who may be underrepresented, (3) Which fairness definition the model is optimised for and why that definition was chosen over alternatives, (4) Known limitations and cases where the model should not be used, (5) How to report concerns about model behaviour, and (6) When the model was last audited and when the next audit is planned. This document is the public accountability artifact for the model.`,
  ],

  common_mistakes: [
    `Measuring fairness only on the overall dataset without disaggregation. A model with 80% accuracy overall might have 90% accuracy for the majority group and 65% for a minority group. The overall number hides the disparity. Always compute metrics disaggregated by any group that might be affected differently.`,

    `Removing sensitive attributes from the model's feature set and declaring the model "fair." A model can exhibit discrimination through proxy variables — features that correlate with a protected attribute even though the protected attribute itself is not in the model. Zip code proxies for race. Name proxies for gender and ethnicity. Removing direct sensitive attributes is not sufficient and may not even reduce disparities if proxy variables are present.`,

    `Choosing a fairness definition based on what makes the numbers look best rather than what the stakeholders have agreed is appropriate for the use case. Fairness definitions are value judgments, not technical choices. The selection of a fairness definition should involve the people affected by the model's decisions, not just the ML engineers.`,

    `Not re-auditing for fairness after retraining. If you retrain on new data, the model's demographic performance characteristics may change. Run the fairness audit on every new model version before deploying it.`,

    `Treating fairness as a final checklist item rather than an ongoing consideration. Fairness analysis should happen during data collection, feature selection, model development, and deployment. Post-hoc mitigation after training is harder and less effective than proactive consideration throughout the pipeline.`,
  ],

  debug_help: `The most frustrating fairness debugging scenario is when removing a feature that you believe causes bias makes the fairness metrics worse. This happens when the feature also encodes legitimate predictive signal, and removing it causes the model to rely more heavily on proxy features that have stronger disparate impact. The diagnostic step: compute permutation importance for the fairness metric (how much does fairness change when you remove each feature?). This tells you which features are driving the disparity — and it is often not the feature you expect.`,

  ai_assist: `Use Claude to help you write the BIASES.md document for your FlightWise model. Describe the model: what it predicts, what data it trained on, what groups you have evaluated (airlines, airports, times of day), and any performance disparities you found. Ask it to draft the BIASES.md using a responsible disclosure format. Review carefully — the document makes public commitments, so every claim must be accurate and every limitation honestly represented.`,

  stretch: [
    `Implement Fairlearn's GridSearch constraint: train a model that enforces demographic parity difference below 0.05 on your chosen sensitive attribute. Compare the accuracy of the constrained model against the unconstrained model. Report the accuracy cost of the fairness constraint.`,
    `Apply differential privacy training to your FlightWise model using Opacus with epsilon=10 and epsilon=1. Compare the validation accuracy at each epsilon level to the non-private baseline. Plot the privacy-utility tradeoff curve.`,
    `Conduct a fairness red team: have a colleague (or use yourself) try to adversarially probe your model for unfair behavior — query it with scenarios designed to reveal disparate treatment. Document what you find and what you would change.`,
  ],
});

rewriteWeek("ml-engineering", 24, {
  context: `The capstone is where everything comes together: a full ML system, designed, built, monitored, and shipped. Not just a model. A system — with a data pipeline, a training pipeline, a serving endpoint, monitoring, reproducibility, and documentation. The combination of all these pieces, working together reliably, is what ML engineering produces.

The scoping decision is the hardest part. The instinct is to build something impressive — distributed training, multimodal inputs, real-time monitoring. The right instinct is to build something that works end-to-end with all the engineering quality that implies. A clean, well-monitored, reproducible logistic regression pipeline is a stronger capstone than a messy deep learning system with no monitoring and non-reproducible training.

End-to-end thinking means designing the data pipeline, model, serving, and monitoring as one integrated system before writing any code. Where does the data come from? How does it get preprocessed? Where are the preprocessing artifacts stored so inference uses the same transformations as training? How does the serving endpoint load the model? What metrics does the monitoring collect? What triggers a retraining run? Writing a one-page system design before writing code is the difference between building a system and building a collection of scripts.

The retrospective is as important as the technical work. What decisions turned out to be wrong? What would you architect differently? What took five times longer than expected and why? What would be the first thing to improve in v2? An honest retrospective shows engineering maturity. It demonstrates that you understand the tradeoffs you made, not just the system you built.

Ship something, monitor it, and tell the story. The deliverables: a live endpoint with a public URL, a SYSTEM-DESIGN.md that describes the architecture, an eval report with honest metrics, a monitoring dashboard showing recent predictions, and a retrospective document. The story: a 3-minute demo video and a write-up that explains what problem you solved and why the engineering decisions you made were the right ones.`,

  pre_flight: `Spend two days on system design before writing code. Write a SYSTEM-DESIGN.md covering: data source, preprocessing pipeline, model choice and rationale, serving architecture, monitoring plan, and retraining trigger. Get feedback on the design from someone else before implementing. Choose a dataset you care about — the capstone should solve a problem that interests you.`,

  mastery_questions: [
    `You have designed your capstone system. A reviewer asks: "What happens if the prediction endpoint goes down?" Walk through your failure handling. Your answer should cover: (1) health checks — how does the platform know the endpoint is down?, (2) automatic restart — does your hosting platform restart failed containers?, (3) graceful degradation — if the model endpoint is unavailable, does the application fall back to a simple rule-based prediction or does it return an error?, (4) alerting — how do you know the endpoint went down? Walk through all four. A system without failure handling is not production-ready.`,

    `You have trained your capstone model and the test ROC AUC is 0.77. You present the results. A reviewer asks: "How do you know this model is better than just always predicting the majority class?" Answer with numbers. If 30% of your dataset is positive class, the majority class classifier has 70% accuracy and ROC AUC of 0.50 by definition. Your 0.77 ROC AUC means your model ranks positive examples significantly better than random. Compute the business impact: at the operating threshold, what is the lift over the majority class classifier in precision and recall? Presenting results without a baseline is not acceptable in a professional context.`,

    `Your capstone uses XGBoost. A colleague asks why not a neural network. What is your answer? Neural networks require more data, more compute, and more tuning to outperform XGBoost on tabular data. For datasets under 1M rows with structured features, XGBoost typically matches or beats neural networks with far less engineering effort. The reproducibility and interpretability of XGBoost are also higher. If your dataset were larger, the features were unstructured (text, images), or you needed the representational power for very complex interactions, a neural network would be justified. Model selection should be driven by data characteristics and requirements, not by what is more impressive.`,

    `You deploy your capstone and monitor it for two weeks. You notice the model's predicted probability distribution is shifting toward higher values over time — the model is increasingly predicting higher risk for everything. What do you investigate? Start with input drift: check PSI for all features. If input distributions have not shifted, the model's output shift may be caused by a change in the prediction serving code (a bug that adds a constant to predictions), a model loading issue (loading the wrong version), or a genuine drift in the data that your input features are not capturing. If input drift is detected, the output shift is expected and you should evaluate whether retraining is needed. If no input drift is detected, the output shift is mysterious and suggests a code or infrastructure bug.`,

    `It is the last day before you present your capstone. What do you do? Test the end-to-end flow from a completely fresh environment: clone your repo, follow your README exactly, run the pipeline, send a prediction to the endpoint. Fix any step that does not work as documented. Record a 3-minute demo video showing the system working. Double-check that your monitoring dashboard shows data from the last 24 hours. Review your SYSTEM-DESIGN.md and retrospective for accuracy. Then stop adding features. The capstone is done when the core promise — a working, monitored, reproducible ML system — is fulfilled.`,
  ],

  common_mistakes: [
    `Spending 90% of the time on model training and 10% on everything else. The training is the least differentiated part of the capstone. Anyone can run model.fit(). The system design, the serving infrastructure, the monitoring, the documentation — these are what distinguish an ML engineer from a data scientist. Plan for them explicitly.`,

    `Not having a live endpoint at presentation time. A notebook demo is not a shipped system. A Jupyter notebook running locally is not a deployed model. The capstone must have a URL that works when someone visits it without access to your laptop. Deploy early in the capstone period, not the night before.`,

    `Writing a retrospective that only praises the project. "It went great, I learned a lot" is not a retrospective. A retrospective names specific decisions that turned out to be wrong, specific assumptions that did not hold, and specific things you would do differently. The value is in the honesty.`,

    `Not documenting the model's limitations. Every model has things it cannot do or situations where it performs poorly. Document these explicitly in a LIMITATIONS.md or in the SYSTEM-DESIGN.md. A model deployed without documented limitations will be used in those limitations without appropriate caution.`,

    `Treating "shipped" as the finish line. The capstone is a portfolio artifact. After shipping: write a blog post, record the demo video, add it to your portfolio site, update your LinkedIn. The build is not done until it is visible to the people who might hire you or collaborate with you.`,
  ],

  debug_help: `The most common capstone failure is a system that works in parts but not end-to-end. The preprocessing pipeline works. The training script works. The serving endpoint works. But when you chain them together — train on new data, update the model, reload in the serving endpoint — something breaks. Fix: test the end-to-end flow with a smoke test from day one, not at the end. Build the pipeline as a chain, not as isolated pieces, and run the full chain on every commit. End-to-end integration bugs are much cheaper to catch early than to debug at the end.`,

  ai_assist: `Use Claude throughout the capstone for code review, not code generation. As you build each component, paste the code and ask it to review for: missing error handling, correctness of the preprocessing pipeline, potential data leakage, and any security issues (hardcoded credentials, exposed endpoints). Use it as a second reviewer, not as the author. The capstone demonstrates your engineering judgment — that judgment must be yours.`,

  stretch: [
    `Write a technical blog post about your capstone: the problem, the architecture decisions, the engineering tradeoffs, the eval results, and honest lessons learned. Publish it publicly. This is the artifact that gets you conversations with other engineers and opens interview doors.`,
    `Add an active learning loop: after deployment, identify the predictions your model is least confident about (predicted probability closest to 0.5). Build a simple interface to collect ground truth labels for those cases. Use those high-uncertainty labels to improve the next training run.`,
    `Conduct a "game day" for your capstone: simulate a production incident. Artificially inject data drift, take the model endpoint down for 5 minutes, corrupt an input feature for one hour. Document how quickly your monitoring detected each incident and what the recovery procedure was. The exercise reveals gaps in your monitoring and runbooks.`,
  ],
});
