import { rewriteWeek } from "../rewrite-week";

// mobile-engineering W1-W5

rewriteWeek("mobile-engineering", 1, {
  context: `A mobile app is not a scaled-down website. It runs on a different operating system (iOS or Android), uses different interaction paradigms (touch gestures, not clicks), has access to hardware (camera, GPS, accelerometer, biometrics), and is distributed through app stores instead of web servers. React Native bridges this gap: you write JavaScript and React, and the framework compiles to native components. This is different from a web view (showing a website inside an app shell) — React Native renders real native UI components.

The project for the first 4 weeks is Hydra: a habit tracker. Simple enough to build in a weekend, complex enough to touch every foundational mobile concept — navigation, state, local storage, notifications, forms, TypeScript. By W4, Hydra is a real app that you use personally.

W1 builds Hydra v0.1: a list of habits you can check off each day. This week you understand how React Native differs from React for web. The component library is different: View instead of div, Text instead of p or h1, TouchableOpacity or Pressable instead of button. There is no CSS — styles are applied via StyleSheet objects or inline objects. StyleSheet.create is a performance optimisation that flattens style definitions at creation time. Flexbox is the only layout system (no grid, no floats, no positioning with left/top in the web sense).

Navigation is handled by a library because mobile apps do not have URLs. React Navigation is the standard. It manages a navigation stack (push and pop screens, like browser history), tab bars (bottom navigation), and drawer menus. Each screen is a React component; the navigator renders the currently active screen.

Expo is the toolchain. It provides a managed workflow that eliminates native build configuration for the first several months. The Expo Go app on your phone reads your code and renders it in real time. When you need native APIs not in Expo's managed set, you eject to a bare workflow — but stay in managed for now.`,

  pre_flight: `Install Node.js. Install the Expo CLI: npm install -g expo-cli. Create a new project: npx create-expo-app hydra --template blank-typescript. Install Expo Go on your physical phone (iOS App Store or Google Play). Run npx expo start — scan the QR code with your phone. You should see a blank screen. If you do not have a physical device, install an iOS Simulator (Xcode, macOS only) or Android emulator (Android Studio). Read the React Native core components overview: View, Text, StyleSheet, TouchableOpacity, ScrollView, FlatList.`,

  mastery_questions: [
    `What is the difference between React Native's StyleSheet and CSS? In CSS, styles are strings: "16px". React Native styles are JavaScript objects with camelCased property names and unitless numbers: { fontSize: 16 }. CSS has cascading (child elements inherit parent font size). React Native does not cascade — every component gets default styles. CSS supports floats, grid, and many positioning modes. React Native supports only Flexbox for layout. Flexbox in React Native defaults to column direction (vertical), not row (horizontal) as in browsers. Numbers in React Native are in density-independent pixels (dp on Android, points on iOS) — not actual screen pixels.`,
    `A FlatList is showing 1000 items. What performance advantages does FlatList have over a ScrollView containing all 1000 items? FlatList virtualises the list: it only renders the items currently visible on screen (plus a small buffer). A ScrollView renders all 1000 items at once, consuming memory and computation for items the user cannot see. FlatList renders maybe 20-30 items at a time and recycles the views as the user scrolls. For large lists, a ScrollView with all items will cause noticeable lag and high memory usage. For short lists (under ~20 items), a ScrollView is fine and simpler.`,
    `Your Hydra app has a list of habits. When the user checks off a habit, it should visually update immediately (toggle a checkmark). How do you manage this state? Use useState in the component that owns the habit list. The state is an array of habit objects, each with an id, name, and isCompleted boolean. When the user taps a habit row, call setHabits with a new array where the matching habit has isCompleted toggled. Because React state updates trigger re-renders, the UI updates immediately. The checked state is lost on app restart — W8 covers persisting state to local storage.`,
    `What is the difference between TouchableOpacity and Pressable in React Native? TouchableOpacity reduces the opacity of the element when pressed — a visual feedback effect. Pressable is more flexible: it provides the pressed state (isPressed: boolean) as a render prop, letting you apply any visual change on press — opacity, scale, background colour, border. Pressable also supports onLongPress, onPressIn, onPressOut with configurable delays. For simple buttons with the default opacity effect, TouchableOpacity is fine. For custom press interactions, use Pressable.`,
  ],

  common_mistakes: [
    `Using web-specific CSS properties in React Native. padding: '16px' is wrong (no units). margin: auto does not work in React Native (use flex: 1 or alignSelf: 'center'). There is no border-radius shorthand with individual corners — use borderTopLeftRadius. Read the React Native StyleSheet documentation — it is not CSS.`,
    `Wrapping all content in a ScrollView without needing to. If your content fits on screen without scrolling, a ScrollView adds unnecessary overhead. If the content is a long list, use FlatList. Only use ScrollView for mixed content that is not a uniform list.`,
    `Not providing a keyExtractor to FlatList. FlatList uses the key to track which item is which for re-rendering. Without it, React Native falls back to using the index, which causes incorrect re-renders when items are added, removed, or reordered. Provide keyExtractor={(item) => item.id.toString()}.`,
    `Putting all styles inline instead of using StyleSheet.create. Inline styles create a new object on every render. StyleSheet.create registers styles once and references them by ID. For styles that do not change, use StyleSheet.create. For dynamic styles (computed from props), inline is fine.`,
    `Not testing on a real device early. Simulators are good approximations but miss real-world issues: 60fps feel, real network conditions, notch/dynamic island layout, actual touch response, keyboard behaviour. Test on a real phone as early as possible.`,
  ],

  debug_help: `Expo QR code does not connect: make sure your phone and computer are on the same Wi-Fi network. If they are, try switching Expo to tunnel mode (press 't' in the Expo CLI) — this routes traffic through Expo's servers and works even across networks. "Unable to resolve module" error: the module is not installed. Run npm install or npx expo install (which installs the Expo-compatible version). Red screen with "Text strings must be rendered within a <Text> component": you have a string directly inside a View or other component without a Text wrapper. Find the plain text string in your JSX — even whitespace between tags counts. Styles not applying: check that you are passing the style prop (not className, which does not exist in React Native). Check camelCase: background-color is backgroundColor.`,

  ai_assist: [
    `"Write a React Native habit list screen for the Hydra app. It uses useState with an array of habits (id, name, isCompleted). Each habit is displayed in a row with the habit name and a checkbox that toggles on press. When isCompleted is true, the habit name gets a line-through style. Use FlatList with a keyExtractor."`,
    `"Explain the React Navigation stack navigator. How do I navigate from a HabitList screen to a HabitDetail screen, pass the habit's id as a parameter, and read it in HabitDetail? Show the navigation setup, the navigate call, and the useRoute hook."`,
    `"What is the difference between flex: 1 and alignSelf: 'stretch' in React Native? When would I use each?"`,
  ],

  stretch: [
    `Add a swipe-to-delete gesture to the habit list using react-native-swipeable-row or the react-native-gesture-handler Swipeable component. The habit slides left to reveal a delete button. This introduces you to gesture handling, which is foundational for native-feeling mobile UX.`,
    `Style Hydra with a cohesive visual identity: pick a colour palette (2 primary colours, 1 accent), a font scale (use Expo Google Fonts), and consistent spacing (use multiples of 8px as your spacing unit). The constraint forces you to build reusable style constants.`,
    `Read the React Native architecture documentation — the new architecture (JSI, Fabric, TurboModules) vs the old bridge. Understand at a high level how JavaScript communicates with native code. You will not write native modules this week, but knowing the architecture makes debugging easier later.`,
  ],
});

rewriteWeek("mobile-engineering", 2, {
  context: `Hydra v0.2 adds two features that make it a real daily-use app: a daily reset (habits reset to unchecked at midnight) and reminder notifications (push a local notification at a user-configured time to prompt the daily check-in). These features introduce the local notifications API and scheduled background work — two things that are fundamentally different on mobile vs web.

Local notifications are scheduled by your app and delivered by the operating system. They do not require a server, a push notification service, or network connectivity. They are just a request to the OS: "at 8am every morning, show this notification." The OS delivers it even if the app is not running. expo-notifications is the library that handles this. You request permission first (required on iOS, optional on Android) and then schedule the notification.

Notification permissions are granted by the user. On iOS, the permission dialog appears the first time you request it — if the user denies, you cannot ask again programmatically (they must enable manually in Settings). This means you should explain why you need permission before requesting it. Show a prompt: "Hydra sends you a daily reminder at your chosen time. Tap Allow to enable notifications." If they tap Allow, then you call the permission request.

Date and time handling is harder than it looks on mobile. The user's time zone matters: a reminder at 8am should fire at 8am in the user's local time, not 8am UTC. The daily reset at midnight must use the device's local midnight, not UTC midnight. Use the device's local time for all scheduling. expo-notifications handles this correctly when you use Calendar triggers with local time.

AsyncStorage is the simplest form of local persistence — a key-value store backed by the device's file system. Think of it as localStorage for React Native. You store the reminder time and whether the user has configured it. AsyncStorage is asynchronous (it reads from disk) — always await it and handle the case where the value is null (first launch).`,

  pre_flight: `Install expo-notifications: npx expo install expo-notifications. Install @react-native-async-storage/async-storage: npx expo install @react-native-async-storage/async-storage. Add the notifications configuration to app.json (the expo.plugins array). Read the expo-notifications documentation on scheduling local notifications. Understand Expo's Calendar trigger type: it fires at a recurring time (like a cron). Know that on iOS you must add the notifications permission to your app.json.`,

  mastery_questions: [
    `You schedule a daily reminder notification for 8am using expo-notifications. The user changes their phone's time zone from UTC+0 to UTC+8. Does the notification fire at 8am in the new time zone or at 8am UTC? With a Calendar trigger using local time (the Expo API default), the notification fires at 8am in whatever time zone the device is currently set to. If the device is in UTC+8, it fires at 8am UTC+8. If the device is in UTC+0, it fires at 8am UTC+0. This is correct behaviour — the user wants their reminder at 8am their time. The trigger is interpreted locally by the OS.`,
    `A user opens Hydra at 11:30pm and checks off all their habits. At midnight, the daily reset fires. The user re-opens the app at 11:31pm (one minute after checking off). What should they see? All habits should be unchecked — the midnight reset happened. But there is a subtlety: if your reset logic checks "has today's date changed since the last check-off?", you need to compare dates carefully. Store the last-reset date (not timestamp) in AsyncStorage. On app launch and on AppState change (app comes to foreground), compare today's date to the last-reset date. If different, reset habits.`,
    `You want to cancel a previously scheduled notification and schedule a new one at a different time. How do you do this? expo-notifications returns a notification identifier when you call scheduleNotificationAsync. Store this identifier in AsyncStorage. When the user changes the reminder time, call await Notifications.cancelScheduledNotificationAsync(storedIdentifier) to cancel the old one, then call scheduleNotificationAsync again and store the new identifier. If you do not cancel before scheduling, you accumulate duplicate notifications.`,
    `The user has never opened the app before. When should you request notification permissions? Not immediately on first launch — this is aggressive and users often deny without understanding why. Show an onboarding screen that explains the feature and the benefit ("Get a daily nudge at your chosen time"). Then show a button "Enable Reminders." Only call Notifications.requestPermissionsAsync() when the user taps that button. On iOS, you only get one chance — make it count.`,
  ],

  common_mistakes: [
    `Requesting notification permissions at app launch without context. Users deny because they do not know why the app needs them. Always explain the benefit before requesting.`,
    `Not storing the notification identifier. If you schedule a notification and discard the identifier, you cannot cancel it. The OS will keep firing it. Always store the identifier in AsyncStorage.`,
    `Using setTimeout for daily reset instead of checking on app foreground. setTimeout is unreliable — the OS can kill your app's background process. Check the date on every app foreground event (AppState.addEventListener('change', handler)) and at the top of your component mount.`,
    `Directly awaiting AsyncStorage in render. AsyncStorage is async — calling it during render throws an error or causes stale data. Use useEffect with an async function inside, or use a state initialisation pattern: load from AsyncStorage in useEffect, set state, render based on state.`,
    `Scheduling notifications that fire in the past. If the user sets a reminder for 7am and it is currently 10am, the notification would fire immediately or never (depending on the OS). Check that the scheduled time is in the future before scheduling.`,
  ],

  debug_help: `Notifications are not firing on iOS Simulator: the iOS Simulator does not support local notifications for scheduled triggers. Test on a real iOS device. Android emulator usually supports local notifications. "Permission denied" and you cannot re-request: on iOS, once denied, the app cannot programmatically request again. During development, reset permissions in Settings > Apps > Hydra > Notifications. In production, you can only prompt the user to enable manually and redirect to Settings with Linking.openSettings(). AsyncStorage returns null: this is normal on first launch — the key has never been stored. Always handle the null case: const stored = await AsyncStorage.getItem('key'); if (stored !== null) { ... }. Background task does not fire: expo-task-manager background fetch tasks are unreliable for time-critical operations. Use scheduled local notifications instead of background tasks for the daily reset.`,

  ai_assist: [
    `"Write a React Native function that schedules a daily local notification using expo-notifications. The function takes an hour and minute in local time, cancels any previously scheduled reminder (using a stored identifier in AsyncStorage), schedules the new notification with a Calendar trigger repeating daily, and stores the new identifier. Include error handling."`,
    `"Write the daily reset logic for Hydra. On every app foreground event (using AppState), compare today's date (YYYY-MM-DD) to the last-reset-date stored in AsyncStorage. If different, reset all habits to isCompleted: false and store today's date as the new last-reset-date."`,
    `"Write a notification permission request flow in React Native: first show an explanatory view, then when the user taps 'Enable', call expo-notifications to request permission, handle the granted case (schedule the notification) and the denied case (show a message with a link to Settings)."`,
  ],

  stretch: [
    `Add haptic feedback using expo-haptics when the user checks off a habit. Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light) gives a subtle tap. Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success) gives a success pattern. Small detail, big impact on feel.`,
    `Implement the notification in a notification handler so that if the user receives the reminder while the app is open, you show an in-app banner instead of the OS notification. Use Notifications.setNotificationHandler to intercept notifications while the app is in the foreground.`,
    `Add a time picker for the reminder using @react-native-community/datetimepicker. Show a native OS time picker that returns the selected time. Store the selected hour and minute in AsyncStorage and reschedule the notification.`,
  ],
});

rewriteWeek("mobile-engineering", 3, {
  context: `Hydra v0.3 adds habit history (track which habits were completed on which days) and streaks (consecutive days all habits were completed). These features introduce a real data model: instead of just storing whether today's habits are checked, you store a completion record for every day. This is the point where "simple state" becomes "structured local data" — and where you feel the limits of AsyncStorage.

AsyncStorage is a key-value store. It is good for simple settings (reminder time, user preferences). It becomes awkward for structured data that you want to query. To get all habits completed in the last 30 days, you either store the entire history as one JSON blob (fine until it gets large) or store keys like habit:1:2026-05-01:completed (hard to query).

For structured local data, SQLite is the right tool. expo-sqlite provides a SQLite database on device. You create tables, insert rows, and query with SQL. It is fast, supports transactions, and handles large datasets without loading everything into memory. The tradeoff: SQL schema design and migration management, which is more complex than AsyncStorage.

Streaks require date arithmetic. A streak is the number of consecutive days (ending today or yesterday) on which all habits were completed. You must define "completed day" clearly: does the day end at midnight? What if the user is still using the app at 11:59pm — does checking a habit at 11:58 count for today? For Hydra, define completion at 11:59:59pm device local time.

React Navigation and complex navigation state: Hydra v0.3 has multiple screens — HabitList (today), History (calendar view), and Settings. You add a tab navigator with three tabs. Tab bars are a core mobile navigation pattern — the bottom tab bar is how most mobile apps switch between primary sections of the app.`,

  pre_flight: `Install expo-sqlite: npx expo install expo-sqlite. Install @react-navigation/bottom-tabs: npm i @react-navigation/bottom-tabs. Install react-native-calendars for the history calendar view: npm i react-native-calendars. Read the expo-sqlite getting started guide. Understand SQL basics: CREATE TABLE, INSERT INTO, SELECT WHERE, and basic date functions. Know that SQLite dates are stored as text (ISO 8601: 'YYYY-MM-DD') in SQLite — there is no native date type.`,

  mastery_questions: [
    `Design the SQLite schema for Hydra's habit history. What tables do you need and what are the columns? Two tables. Habits: id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, createdAt TEXT NOT NULL. Completions: id INTEGER PRIMARY KEY AUTOINCREMENT, habitId INTEGER NOT NULL REFERENCES habits(id) ON DELETE CASCADE, completedDate TEXT NOT NULL (ISO 8601 date), UNIQUE(habitId, completedDate). The UNIQUE constraint prevents double-counting. When a user checks off a habit, insert a Completion row. When they uncheck it, delete the row. To query the history, JOIN habits and completions on habitId. To calculate a streak, query completions ordered by completedDate descending and walk the dates.`,
    `How do you calculate a streak in JavaScript given an array of completion dates? A streak ends today (or yesterday — if today is incomplete). Walk backwards from today through consecutive days. For each day, check whether all habits were completed (all habit IDs have a completion row for that date). Increment the streak counter while all habits are completed. Stop when you find a day with missing completions. This requires knowing the total number of habits — if a habit was added recently, do you count days before it was added? Decision: only count days that are on or after the habit's createdAt date for that habit's contribution.`,
    `The user opens Hydra on their phone. The app shows the History screen with a calendar. Dates with full completion are shown in green, partial completion in yellow, no completion in grey. How do you query this data from SQLite efficiently? Query completions for the displayed date range (e.g., last 90 days): SELECT completedDate, COUNT(*) as completedCount FROM completions WHERE completedDate BETWEEN '2026-02-25' AND '2026-05-25' GROUP BY completedDate. Also get the total habit count at each date — this is harder because habits may have been added or deleted over time. A simpler approach: query the total active habits per day by checking which habits existed on each date using their createdAt. This is the hard problem of "slowly changing dimensions" — handle it by also storing a deletedAt on habits and filtering.`,
    `A user has 5 habits. They complete 4 of them today and close the app. The next day, they do not open the app. The day after, they complete all 5. What is their streak? Zero. The streak counts consecutive days with all habits completed. Day 1: 4/5 complete — does not count as a full day. Day 2: 0 complete (did not open app). Day 3: 5/5 complete — starts a new streak of 1. If you want a more lenient streak (allow one missed day per week), that is a product decision — define it explicitly in a business logic function.`,
  ],

  common_mistakes: [
    `Opening a new SQLite connection on every function call. Open the database once at module level or with a hook, and reuse the connection. Each open call has overhead and may create conflicting connections.`,
    `Not using transactions for multi-step database operations. If you insert a completion and then update a streak counter in two separate queries, and the app crashes between them, your data is inconsistent. Wrap multi-step operations in db.transaction().`,
    `Storing dates as timestamps (Unix epoch) in SQLite instead of ISO 8601 strings. SQLite date functions work with ISO 8601 strings. Storing timestamps requires conversion everywhere. Use 'YYYY-MM-DD' for dates and 'YYYY-MM-DDTHH:MM:SSZ' for datetimes.`,
    `Calculating streak in the UI component. Streak calculation is business logic — it belongs in a utility function that you can test independently. The component calls getStreak(completions, habits) and displays the result.`,
    `Not handling the migration from AsyncStorage (W1/W2) to SQLite (W3). Your existing users (just yourself at this point) have data in AsyncStorage. Write a migration function that runs on first launch after the update: reads AsyncStorage, inserts into SQLite, clears AsyncStorage.`,
  ],

  debug_help: `SQLite query returns no results: log the query and parameters. Use db.getAllAsync('SELECT * FROM completions') to verify the table has data. Check column names — SQLite is case-insensitive for keywords but exact for column names. Calendar component shows wrong dates: react-native-calendars uses 'YYYY-MM-DD' string keys for the marked dates object. If your dates are in a different format, they will not match. Streak calculation is off by one: print each date in your streak walk and the corresponding completion data. The most common mistake is inclusive/exclusive boundary in the date range or the comparison direction (walking forwards vs backwards). Tab bar is showing but screens are not rendering: each tab screen must be a valid React component. Check that your component exports are correct. The bottom tab navigator uses screen: Component, not screen: <Component />.`,

  ai_assist: [
    `"Write the SQLite setup for Hydra using expo-sqlite. Create the habits and completions tables (schema above) in a function that runs on app startup. Include the migration logic: check if tables exist before creating them (CREATE TABLE IF NOT EXISTS). Return the database instance."`,
    `"Write a JavaScript function getStreak(db) that queries the SQLite database and returns the current streak count. A streak is consecutive days (ending today or yesterday) where all habits were completed. Use async/await and handle the case where there are no habits."`,
    `"Set up a React Navigation bottom tab bar with three screens: Today (HabitList), History (calendar), and Settings. Show icons for each tab using @expo/vector-icons. The Today screen should show a badge with the number of incomplete habits."`,
  ],

  stretch: [
    `Add a "longest streak" record. Query the database to find the longest streak ever achieved. Show it alongside the current streak. This requires walking all completion history and finding the longest consecutive run.`,
    `Add a habit creation flow with validation. The user taps a + button, sees a modal with a text input for the habit name and a colour picker (to colour-code the habit in the list). Validate that the name is not empty and not a duplicate. Insert into SQLite on confirm.`,
    `Implement the full date-range query for the calendar view. Show completion percentage per day (0%, partial, 100%) as different visual states. Test edge cases: a day with 0 habits, a day before any habits were created.`,
  ],
});

rewriteWeek("mobile-engineering", 4, {
  context: `Hydra v0.4 refactors the entire codebase to TypeScript and introduces the architectural patterns that make mobile apps maintainable as they grow. Up to this point, you have been building features quickly; now you pay off the technical debt by typing everything and organising the code properly.

TypeScript on React Native is the same TypeScript you have seen before with a few mobile-specific types. The React Native type definitions come from @types/react-native (or are bundled with the library). Expo SDKs are typed. The types you will add this week: explicit prop types for every component, typed navigation params (what data is passed between screens), typed database query results, typed AsyncStorage values.

Typed navigation is one of the most valuable additions to a React Native + TypeScript codebase. React Navigation provides a way to define the type of parameters each screen accepts: type RootStackParamList = { HabitDetail: { habitId: number }; Settings: undefined }. Once you define this, the navigate function is type-checked — you cannot navigate to HabitDetail without providing a habitId. And in HabitDetail, useRoute<RouteProp<RootStackParamList, 'HabitDetail'>>() gives you typed params.

Code organisation: by W4, Hydra has enough screens and logic that a flat file structure becomes hard to navigate. Standard React Native project structure: /screens (one file per screen), /components (reusable components), /hooks (custom React hooks for shared logic), /services (database, notifications, AsyncStorage abstractions), /utils (pure functions: date formatting, streak calculation), /types (shared TypeScript interfaces and types). Move code into this structure this week.

Custom hooks encapsulate stateful logic. The useHabits hook manages the habits list state and provides functions (addHabit, toggleHabit, deleteHabit). The useStreak hook queries the database and returns the current streak. Components just call these hooks and render — they contain no business logic.`,

  pre_flight: `Ensure your project has TypeScript configured (it was set up in W1 with the TypeScript template). Check tsconfig.json — set strict: true. Install @types/react-native if not already present (it may be bundled). Read the React Navigation TypeScript guide for typed navigation. Understand what a generic is in TypeScript: a function or type parameterised by another type, e.g. Array<T>.`,

  mastery_questions: [
    `What does strict: true in tsconfig.json enable and why does it matter? strict: true enables a set of strict checks: strictNullChecks (null and undefined are not assignable to other types — you must handle them explicitly), noImplicitAny (every variable must have an explicit or inferable type), strictFunctionTypes, and others. Without strictNullChecks, a function that returns string | null is treated as always returning string — you do not get errors when you forget to handle the null case. With strictNullChecks, the compiler forces you to check. This catches a large class of runtime errors at compile time.`,
    `You have a useHabits hook that returns { habits, addHabit, toggleHabit, deleteHabit }. A component calls const { habits, toggleHabit } = useHabits(). TypeScript says toggleHabit is (id: number) => void. A developer later changes the hook to make id a string. What happens? The TypeScript compiler errors on every call site where toggleHabit is called with a number. This is the value of typed interfaces — changing a function signature surfaces all the places that need to be updated, at compile time, before the code runs. Without TypeScript, the same change would produce a runtime bug that only appears when that specific code path runs.`,
    `You store habit data in SQLite and query it with db.getAllAsync<{ id: number; name: string; isCompleted: number }>('SELECT ...'). Why is isCompleted typed as number? SQLite does not have a boolean type. Boolean values are stored as integers: 0 for false, 1 for true. When you query them in JavaScript, they come back as numbers. You must convert: const isCompleted = row.isCompleted === 1. Your TypeScript type should reflect the actual shape of the data coming from SQLite — number for booleans, string for dates — and your business logic layer converts to proper TypeScript types.`,
    `What is the difference between a type alias and an interface in TypeScript? For object shapes, they are mostly interchangeable. type Habit = { id: number; name: string } and interface Habit { id: number; name: string } behave the same in most cases. The differences: interfaces can be extended (interface ExtendedHabit extends Habit { streakCount: number }) and can be merged (declaring the same interface name twice merges the declarations). Type aliases can represent unions (type Status = 'active' | 'completed') and mapped types. Convention in React Native: use interfaces for component props and object shapes, use type for unions and utility types.`,
  ],

  common_mistakes: [
    `Adding types to only some parts of the codebase. TypeScript with many "any" types gives false confidence. Use strict: true and avoid any. If you are getting an any from a library that has no types, use unknown and narrow it explicitly.`,
    `Duplicating type definitions instead of sharing them. If Habit is defined in HabitList.tsx and also in HabitDetail.tsx, they can drift. Define shared types in a central /types directory and import from there.`,
    `Not typing navigation params. Without typed navigation params, TypeScript cannot tell you that you forgot to pass a required parameter when navigating. Set up the RootStackParamList and RootTabParamList types for full type safety across navigation.`,
    `Using as any to silence TypeScript errors. This disables type checking for that expression. Understand why the type error is occurring and fix it properly. as any is almost always the wrong solution.`,
    `Typing state as the specific initial value type instead of the union. useState([]) gives you type never[] unless you explicitly type it: useState<Habit[]>([]). Always provide explicit types to useState when the initial value does not convey the full type.`,
  ],

  debug_help: `TypeScript errors in React Navigation: make sure you have passed the typed param list to the navigator and screen. The TypeScript guide in the React Navigation docs shows the exact generic syntax. "Property does not exist on type '{}'" for custom hooks: you are destructuring a hook but the hook return type is inferred as empty object. Add an explicit return type to the hook function. "Type 'null' is not assignable to type 'string'": you have strictNullChecks on and are not handling the null case. Use the nullish coalescing operator (value ?? '') or a type guard (if (value !== null) { ... }). Expo TypeScript errors in app.json: app.json is not typed, but app.config.ts is — migrate your configuration to app.config.ts for type-checked Expo config.`,

  ai_assist: [
    `"Refactor this Hydra codebase to TypeScript. Here are the files: [paste files]. Add type annotations to all functions, components, and hooks. Define a Habit interface and a Completion interface. Type the SQLite query results correctly (booleans as number, dates as string). Set up typed navigation params."`,
    `"Write a custom React hook useHabits() in TypeScript that: initialises from SQLite on mount, provides habits: Habit[], addHabit(name: string): Promise<void>, toggleHabit(id: number): Promise<void>, and deleteHabit(id: number): Promise<void>. Use proper TypeScript types throughout."`,
    `"Reorganise this React Native project into the folder structure: /screens, /components, /hooks, /services, /utils, /types. Show me which files go where and any exports that need to be updated."`,
  ],

  stretch: [
    `Add ESLint and Prettier to the project. Configure ESLint with the TypeScript plugin and React Native plugin. Configure Prettier for consistent formatting. Add a pre-commit hook with Husky that runs lint and format checks before every commit.`,
    `Write unit tests for the streak calculation utility using Jest (bundled with Expo). The function is pure (no database calls in the test) — mock the completion data as JavaScript objects. Test edge cases: no completions, streak of 1, streak broken by a missed day, streak on the first day of the year.`,
    `Add a Zustand store for Hydra's global state instead of prop-drilling from the root component. The store holds habits, completions summary, and the reminder settings. Components read from the store directly. Compare the experience to the useHabits hook approach.`,
  ],
});

rewriteWeek("mobile-engineering", 5, {
  context: `Forms and keyboard handling are where most mobile apps fall apart. On web, a form is straightforward — the browser handles keyboard appearance and the page scrolls automatically. On mobile, the keyboard covers half the screen, can obscure the active input, and has OS-specific behaviour (auto-capitalisation, auto-correct, return key labelling). Getting forms right on mobile is a skill that takes explicit attention.

TextInput is the React Native input component. Its props control every aspect of keyboard and input behaviour: keyboardType ('numeric', 'email-address', 'phone-pad'), autoCapitalize ('none', 'words', 'sentences'), autoCorrect (disable for usernames, email), returnKeyType ('next', 'done', 'search'), secureTextEntry (for passwords), autoFocus (focus on mount). Ignoring these makes your forms feel unpolished.

KeyboardAvoidingView is the component that moves content up when the keyboard appears. It has platform-specific behaviour: on iOS, use behavior='padding'; on Android, use behavior='height'. Often combined with ScrollView so the user can scroll through the form. For simple forms (2-3 fields), a single KeyboardAvoidingView with padding is fine. For longer forms, nest inside a ScrollView.

Focus management: the user should be able to Tab (or press Next on the keyboard) through fields in order without lifting their fingers from the keyboard. Implement this by calling ref.current.focus() on the next field when the user presses the return key (onSubmitEditing on each TextInput calls focus on the next ref). The last field's returnKeyType is 'done' and its onSubmitEditing submits the form.

Form validation: validate on submit (shows errors all at once when the user finishes filling in the form) or validate on blur (shows an error when the user leaves a field). Validate-on-submit is less intrusive. Validate-on-blur for fields with specific format requirements (email, password strength). Never validate while the user is typing — it is annoying and often wrong (an email address is technically invalid while you are typing it).

react-hook-form is the standard library for form state management in React Native. It handles field registration, validation, error messages, and submission with minimal re-renders.`,

  pre_flight: `Install react-hook-form: npm i react-hook-form. Install @hookform/resolvers and zod: npm i @hookform/resolvers zod. Know the TextInput props: keyboardType, autoCapitalize, autoCorrect, returnKeyType, secureTextEntry, onChangeText, onSubmitEditing, blurOnSubmit. Understand React refs: useRef creates a mutable reference that persists across renders. TextInput ref.current.focus() programmatically focuses an input.`,

  mastery_questions: [
    `You have a form with three fields: name, email, password. How do you implement keyboard tab-through so the user can press Next to move between fields without lifting their hands? Create a ref for each field: const emailRef = useRef<TextInput>(null); const passwordRef = useRef<TextInput>(null). On the name field, set returnKeyType='next' and onSubmitEditing={() => emailRef.current?.focus()}. On the email field, set returnKeyType='next' and onSubmitEditing={() => passwordRef.current?.focus()}. On the password field, set returnKeyType='done' and onSubmitEditing={handleSubmit(onSubmit)}. Set blurOnSubmit={false} on all fields except the last to prevent the keyboard from dismissing between fields.`,
    `Your form has a phone number field. The user types "123abc456". How do you validate this? There are two layers. Input constraint: use keyboardType='phone-pad' to show a numeric keyboard. This prevents most non-numeric input but is not enforced — Android users can still type letters. Validation: in your zod schema, use z.string().regex(/^[0-9]{10}$/, 'Phone number must be 10 digits'). This rejects the field if it contains non-digit characters. Report the error message below the field.`,
    `The keyboard covers the password field when the user taps it (the field is near the bottom of the screen). The KeyboardAvoidingView does not seem to be working. What might be wrong? Common causes: the KeyboardAvoidingView behavior prop is wrong for the platform (iOS needs 'padding', Android usually needs 'height'). Use Platform.OS to switch: behavior={Platform.OS === 'ios' ? 'padding' : 'height'}. The KeyboardAvoidingView must be the root view of the screen (not nested inside another view). On iOS, also check keyboardVerticalOffset — if you have a navigation header, the offset should match the header height. Add keyboardVerticalOffset={Platform.OS === 'ios' ? 64 : 0}.`,
    `Explain the difference between controlled and uncontrolled TextInput components in React Native. Controlled: the value prop and onChangeText handler keep the React state and input value in sync. const [text, setText] = useState(''); <TextInput value={text} onChangeText={setText} />. Uncontrolled: no value prop; the native input manages its own value. You access the current value via a ref or onSubmitEditing. react-hook-form uses a controlled approach under the hood (it stores values in a ref, not React state, for performance). For most forms, use react-hook-form and follow its patterns instead of managing state manually.`,
  ],

  common_mistakes: [
    `Not setting keyboardType, autoCapitalize, and autoCorrect appropriately. An email field should have keyboardType='email-address' and autoCapitalize='none' and autoCorrect={false}. A name field should have autoCapitalize='words'. A username should have autoCapitalize='none' and autoCorrect={false}. Every input has a correct configuration — apply it.`,
    `Wrapping forms in a ScrollView without KeyboardAvoidingView (or vice versa). You usually need both: KeyboardAvoidingView as the outer wrapper (pushes content up), ScrollView as the inner wrapper (lets the user scroll to lower fields). The order matters: KeyboardAvoidingView outside, ScrollView inside.`,
    `Validating the entire form on every keystroke. This causes a re-render on every character typed. Use react-hook-form's mode: 'onBlur' or 'onSubmit' for validation timing, not 'onChange'.`,
    `Dismissing the keyboard on scroll. Adding dismissKeyboard on scroll makes it hard to scroll through a form while the keyboard is open. Only dismiss the keyboard when the user submits or taps outside the form area (use TouchableWithoutFeedback wrapping the form, calling Keyboard.dismiss() onPress).`,
    `Not handling the case where form submission fails. If the API call fails, show an error message in the UI — not just console.log. The user needs to know what went wrong and whether they should try again.`,
  ],

  debug_help: `Keyboard covers inputs on iOS but not Android: use Platform.OS to set the correct KeyboardAvoidingView behavior. iOS needs 'padding'. Android's keyboard pushes the layout up natively (android:windowSoftInputMode="adjustResize" in AndroidManifest.xml, which Expo sets for you). react-hook-form errors not showing: make sure you are passing the errors object from formState to the field: const { formState: { errors } } = useForm(). Check that the field name in the errors object matches the name in register(). onSubmitEditing not firing: check blurOnSubmit on the field. If blurOnSubmit={true} (the default), the keyboard dismisses and onSubmitEditing may not fire. Set blurOnSubmit={false} on all fields except the last one.`,

  ai_assist: [
    `"Write a sign-up form in React Native using react-hook-form and zod. Fields: name (required, min 2 chars), email (valid email format), password (min 8 chars, must contain a number). Use keyboard tab-through between fields. Show error messages below each field. On submit, call an async onSubmit function and show a loading spinner on the button."`,
    `"Write a KeyboardAvoidingView + ScrollView wrapper component for React Native forms that handles iOS and Android correctly, accounts for the navigation header height, and dismisses the keyboard when the user taps outside a field."`,
    `"I have a phone number TextInput. Write the input component with the correct keyboardType, maxLength (10 digits), and a controlled value that filters out non-numeric characters as the user types. Use react-hook-form's Controller component."`,
  ],

  stretch: [
    `Build a multi-step form for habit creation: Step 1 (habit name and description), Step 2 (reminder time), Step 3 (colour and icon selection). Use React Navigation's stack navigator for the steps, passing form state forward. On Step 3 completion, write to SQLite. This introduces the pattern of multi-screen form flows, common in mobile onboarding.`,
    `Add inline form autosave: when the user is editing a habit name, debounce the onChangeText and save to SQLite after 500ms of inactivity (without the user pressing a save button). Show a subtle "Saved" indicator. This is the mobile equivalent of a doc editor's autosave.`,
    `Implement a PIN code entry UI: 4 TextInput components side by side, each accepting one digit. When a digit is entered, auto-advance focus to the next field. On the fourth digit, auto-submit. This is a common UI pattern for authentication and security.`,
  ],
});
