import { rewriteWeek } from "../rewrite-week";

// mobile-engineering W11-W15

rewriteWeek("mobile-engineering", 11, {
  context: `Push notifications are the most powerful re-engagement tool in mobile. Done right, they bring users back to your app at the right moment with the right message. Done wrong, they are spam that makes users disable notifications or uninstall the app. The right way: use them sparingly, make every notification relevant to the individual user, and give users control over what they receive.

There are two types of notifications. Local notifications (covered in W2) are scheduled by the app and delivered by the OS without a network request. Push notifications (this week) originate from a server, are delivered through Apple Push Notification service (APNs) on iOS and Firebase Cloud Messaging (FCM) on Android, and arrive even when the app is not running.

Expo Push Notification Service (EPNS) is the simplest path. It abstracts APNs and FCM behind a single API. Your server sends a POST request to Expo's push endpoint with the Expo Push Token and the message payload. Expo routes it to the correct platform service. You do not need to configure APNs or FCM certificates during development — Expo handles it. In production (when you submit to the App Store), you configure the certificates in Expo's dashboard.

Expo Push Token: a unique identifier for a specific app install on a specific device. Get it with Notifications.getExpoPushTokenAsync(). Store it on your server associated with the user. When you want to send a notification to a user, look up their push token and send to it.

Notification handling: when a notification arrives, your app may be in three states. Foreground (app open and active): the OS does not show a system notification; you handle it in your app's notification listener. Background (app not active): the OS shows the notification; tapping it brings the app to the foreground. Killed (app not running): the OS shows the notification; tapping it launches the app.

Deep linking via notifications: the notification payload can include data (a JSON object). When the user taps the notification, your app receives this data. Use it to navigate to the specific screen relevant to the notification — a new message, an order update, a friend request.`,

  pre_flight: `You need a development build (not Expo Go) because push notifications require configuring APNs entitlements, which Expo Go does not support. Run npx eas build --profile development --platform ios (or android). Install EAS CLI: npm i -g eas-cli. Create an Expo account if you do not have one. Install expo-notifications: npx expo install expo-notifications. Read the Expo push notifications guide end-to-end before starting.`,

  mastery_questions: [
    `A user gets a push notification "Your order is ready." They tap it. What should happen in your app? The app opens (or comes to the foreground). The notification payload contains data: { orderId: '456', type: 'ORDER_READY' }. Your notification tap handler (Notifications.addNotificationResponseReceivedListener) fires with this data. Your handler reads the orderId and calls navigation.navigate('OrderDetail', { orderId: '456' }). The user lands directly on their order detail screen. Without deep linking, they land on the home screen and have to find the order themselves — a significantly worse experience.`,
    `You send 1000 push notifications. Expo's response says 50 have a "DeviceNotRegistered" error. What does this mean and what do you do? DeviceNotRegistered means the push token is no longer valid — the user uninstalled the app, logged out, or reset their device. If you keep sending to invalid tokens, Expo and Apple/Google mark your push credentials as abusive. Remove these tokens from your database immediately. Set up a push receipt checker: after sending, wait 15 minutes, check the receipt endpoint, find DeviceNotRegistered tokens, delete them from your database.`,
    `How do you send a push notification to all users of your app simultaneously (a broadcast)? You do not hit the push endpoint once — you batch. The Expo push API accepts up to 100 messages per request. Fetch all push tokens from your database in batches of 100, send each batch to the Expo push endpoint, collect the ticket IDs, then check receipts 15 minutes later. For 100,000 users, this is 1000 API requests — run them concurrently but rate-limited. Never send personalised content in a mass push from a single template without personalisation.`,
    `A user receives many irrelevant notifications and turns off notifications for your app entirely. What could you have done differently to prevent this? Fine-grained notification preferences. Instead of one on/off toggle, give users control over notification types: "Order updates" (essential, on by default), "Promotions and discounts" (optional, off by default), "New features" (optional, off by default). Store preferences server-side per user. Before sending a notification, check the user's preference for that notification type. Only send if they have opted in. The users who stay subscribed are genuinely interested — higher engagement, better push credentials reputation.`,
  ],

  common_mistakes: [
    `Storing push tokens in your database without updating them. Push tokens can change (app reinstall, OS update). On each app launch, re-fetch the token and update your database if it has changed. A stale token causes delivery failures.`,
    `Not handling the push receipt check. Expo's response to your push send is a ticket, not a confirmation of delivery. The actual delivery status (success, DeviceNotRegistered, error) is in the push receipt, available 15 minutes later. Check receipts. Delete stale tokens. This is not optional for a production app.`,
    `Sending notifications too frequently. More than 2-3 push notifications per day per user is aggressive. Users tune out or disable notifications. Reserve push for genuinely important, time-sensitive events.`,
    `Not requesting permission before the user understands why. The OS permission dialog appears once on iOS. If you request before the user understands the value of notifications, they deny. Explain the benefit first.`,
    `Ignoring notification categories and actions. iOS and Android support rich notifications with action buttons (without opening the app). "Mark as read", "Reply", "Dismiss" — these let users interact with your notification without opening the app. Unimplemented, you leave engagement on the table.`,
  ],

  debug_help: `Push token is null: check that you are running a development build (not Expo Go) and that notification permissions are granted. getExpoPushTokenAsync() requires a project ID — pass projectId: Constants.expoConfig.extra.eas.projectId. Notification is sent but not received: check the push receipt endpoint for errors. Common causes: DeviceNotRegistered (token stale), InvalidCredentials (APNs/FCM cert issue), MessageTooBig (payload over 4KB). Notification tap handler not firing: check that you added the listener before the app enters the background. Add it in a useEffect at the root App component. On a killed app (notification taps that launch the app), use Notifications.getLastNotificationResponseAsync() to retrieve the notification that launched the app — addNotificationResponseReceivedListener fires too late for kill-state taps.`,

  ai_assist: [
    `"Write the complete Expo push notification setup for a React Native app: request permission, get the Expo push token, store it to a backend API, listen for foreground notifications (show an in-app banner), and handle notification taps (navigate to the relevant screen based on data.type). Use TypeScript."`,
    `"Write a Node.js function that sends a push notification to a list of Expo push tokens using the Expo push API. Batch tokens into groups of 100, send each batch, collect ticket IDs, and return them. Include a second function that checks receipts for a list of ticket IDs and returns tokens to delete (DeviceNotRegistered)."`,
    `"Write a notification preference system: a Settings screen where the user can toggle 'Order updates', 'Promotions', and 'Weekly summary' notifications. Store preferences in the backend. A server-side check function that takes a userId and notificationType and returns whether the user wants to receive it."`,
  ],

  stretch: [
    `Implement rich notifications with images. The Expo push payload supports attachmentUrl for iOS (an image URL). When an order is placed, include the restaurant's image in the notification. The image appears in the expanded notification view on the lock screen.`,
    `Build a notification inbox: every push notification is also stored in a database table (userId, message, data, readAt, createdAt). In-app, show a notification bell with an unread count badge. The inbox screen lists all notifications. Tapping one marks it as read and navigates to the relevant screen.`,
    `Implement silent push notifications (background refresh). Send a silent push (content-available: 1 on iOS) that wakes the app in the background, fetches fresh data, and updates the local cache. The user opens the app and sees fresh data without any visible loading state.`,
  ],
});

rewriteWeek("mobile-engineering", 12, {
  context: `React Native runs JavaScript, but most device capabilities (camera, Bluetooth, NFC, advanced sensors) are implemented in native code. Native modules are the bridge between JavaScript and native APIs — they expose native functionality as JavaScript functions. Most of the time, you use pre-built native modules from the Expo SDK or the React Native community. Sometimes, you need to write one yourself.

The old native module API required writing separate implementations in Objective-C/Swift (iOS) and Java/Kotlin (Android), then writing a JavaScript wrapper. The new React Native Architecture uses JSI (JavaScript Interface) — native modules register C++ functions that can be called directly from JavaScript without the asynchronous bridge. This is faster and synchronous.

Expo Modules API is the recommended way to write native modules for Expo projects. It provides a TypeScript-first API that generates the boilerplate and handles the bridge. You write the native code (Swift/Kotlin) and the TypeScript interface; Expo Modules handles the wiring. An Expo module is a local package in your project, not a separate npm package.

When you do NOT need a custom native module: most hardware interactions are covered by Expo SDKs. Before writing native code, search the Expo SDK, the React Native community packages, and expo.dev/packages. Expo's managed APIs cover: camera, location, sensors, notifications, secure storage, biometrics, haptics, audio, video, network, brightness, and many more.

When you DO need a custom native module: you need a third-party SDK that only provides a native library (a Bluetooth hardware SDK, a proprietary payment terminal SDK, a specific enterprise MDM integration). Or you need to squeeze performance out of a computation that is too slow in JavaScript. Or you need synchronous access to a native API that only supports async in the available modules.

This week: you write a small Expo Module that exposes the native device battery API — not because you need it (expo-battery covers this), but to understand the pattern. Then you integrate an existing native library.`,

  pre_flight: `Ensure you are using a development build (required for native modules). Run npx expo eject or use the bare workflow if you are not already. Install the Expo Modules API: npx expo install expo-modules-core. Read the Expo Modules API "Get started" guide for creating a local native module. Know the basics of Swift (iOS) and Kotlin (Android) — you need to read and write simple functions. Install Xcode (for iOS development, macOS only) and Android Studio.`,

  mastery_questions: [
    `What is the React Native bridge and what are its performance limitations? The bridge is a serialised, asynchronous, batched channel between JavaScript and native code. Every native call is serialised to JSON, sent across the bridge, deserialised, executed, the result serialised and sent back. This round trip takes microseconds in the best case but the serialisation overhead means you cannot call native functions thousands of times per second. The bridge is also asynchronous — you cannot synchronously read a native value and use it in the same JavaScript expression. JSI (the new architecture) replaces the bridge with direct C++ function calls — synchronous, faster, no serialisation.`,
    `You find an npm package that wraps a native Bluetooth SDK. It has native code for iOS and Android. Your Expo project is in managed workflow (using Expo Go). Can you use this package? No. Managed workflow apps run in Expo Go, which cannot load custom native code. You must switch to a development build: run npx expo run:ios or npx expo run:android, or use EAS Build. A development build compiles your app with the native module included. After building, you use the development build app on your device instead of Expo Go. Everything else (JavaScript, hot reload) works the same.`,
    `You are writing an Expo Module that exposes a function getBatteryLevel() that returns a float. How does the JavaScript see the function? You define the module in Swift/Kotlin with the function registered as a module function. The Expo Modules API generates the JavaScript bindings. From JavaScript: import { getBatteryLevel } from './my-module'; const level = await getBatteryLevel();. The function is async because native module calls go through the event loop even with JSI. If you need synchronous access, the Expo Modules API has synchronous function support — the function runs on the JavaScript thread synchronously.`,
    `A native module function throws an error in native code. How does the error surface in JavaScript? In Expo Modules API, you throw an exception in Swift/Kotlin: throw Exception("Error message"). The module API catches it and rejects the JavaScript Promise. In JavaScript: try { await myNativeFunction() } catch (error) { console.error(error.message) }. The error.message contains the string from the native exception. You can also throw typed exceptions (by subclassing Exception) and include error codes for programmatic handling.`,
  ],

  common_mistakes: [
    `Writing a native module when an existing Expo SDK covers the use case. Always check expo.dev/packages and the React Native community packages first. Native module development is significantly more complex than JavaScript — only do it when necessary.`,
    `Forgetting to rebuild after native changes. Unlike JavaScript, native code changes require a full rebuild. After modifying Swift or Kotlin code, run npx expo run:ios or run:android again. Hot reload does not apply to native code.`,
    `Not handling threading correctly. UIKit (iOS) must only be called on the main thread. Most Expo Module function callbacks run on a background thread. If you access UIKit from a background thread, you get crashes. Use DispatchQueue.main.async for UI operations.`,
    `Returning non-serialisable types from native modules. The bridge serialises return values. You can return primitive types (number, string, boolean), arrays of primitives, and dictionaries. You cannot return native objects directly — convert them to primitive representations first.`,
    `Not cleaning up native resources in the module's onDestroy lifecycle. Native resources (Bluetooth connections, file handles, timers) must be released when the module is deallocated. Implement the onDestroy function in your module to clean up.`,
  ],

  debug_help: `"NativeModule is null" at runtime: the native module was not compiled into the app. Ensure you ran npx expo run:ios after adding the module, not just restarting the Metro bundler. Swift compilation error: check the Xcode build log (in the Xcode IDE or in the terminal output of npx expo run:ios). Swift errors are often type mismatches or missing imports. Kotlin compilation error: check the Android Studio build output or the terminal output of npx expo run:android. Module function not found in JavaScript: check that the module name in the Expo Modules definition matches the import name in JavaScript. The name is case-sensitive.`,

  ai_assist: [
    `"Create an Expo Module that exposes a single function getDeviceModel() returning the device model string (e.g., 'iPhone 15 Pro'). Show the Swift implementation (iOS) and Kotlin implementation (Android), the Expo Module definition file, and the TypeScript import."`,
    `"I need to integrate the [specific SDK] native library into my Expo bare workflow app. Show me how to: add the dependency (CocoaPods for iOS, Gradle for Android), write an Expo Module wrapper that exposes the key SDK functions, and import them in TypeScript."`,
    `"Explain the difference between Expo Modules API, the old React Native NativeModule API, and Turbo Modules. When should I use each?"`,
  ],

  stretch: [
    `Write a native module that exposes the device's thermal state (normal, fair, serious, critical) using iOS's ProcessInfo.thermalState and Android's PowerManager thermal status. Expose it as a getDeviceThermalState() function and a thermal state change listener. Use this to throttle background operations when the device is hot.`,
    `Integrate react-native-vision-camera (a popular community native module for advanced camera features). Add real-time barcode scanning to a screen. Vision Camera uses JSI frame processors — JavaScript functions that run synchronously on every camera frame at 60fps — which is only possible with the new architecture.`,
    `Write a benchmark comparing native module call overhead (in microseconds) to a pure JavaScript function. Call each 10,000 times, measure total time. The difference illustrates when native module overhead matters and when it does not.`,
  ],
});

rewriteWeek("mobile-engineering", 13, {
  context: `Mobile apps live on unreliable networks. Cellular connections drop in tunnels. Users switch between Wi-Fi and 4G. A user in a rural area might have 2G for an hour. Your app must degrade gracefully when the network is unavailable and catch up when it returns. An app that shows a blank screen when offline is not a production app.

Network state detection: expo-network provides NetInfo.fetch() and NetInfo.addEventListener for network state changes. But detecting "connected to Wi-Fi" does not mean the internet is actually reachable — the user might be connected to a hotel Wi-Fi with a captive portal. A real connectivity check pings a known server.

Optimistic updates: when the user takes an action (checks off a habit, sends a message), update the UI immediately without waiting for the server response. Then send the network request in the background. If it fails, roll back the UI change and show an error. This makes the app feel instant even on slow networks.

Request queuing: for actions taken offline (the user adds a habit while on a plane), queue the request and execute it when connectivity returns. expo-task-manager with a background fetch can process the queue when the app is in the background.

Caching API responses: for data that does not change frequently (menu items, user profile), cache the last successful response locally. When the app loads, show the cached data immediately while fetching fresh data in the background. This is the stale-while-revalidate pattern — the app never shows a blank loading state.

react-query (also called TanStack Query) is the standard library for server state management in React Native. It handles: caching, background refetching, deduplication (multiple components requesting the same data get one request), optimistic updates, error boundaries, and offline support. It replaces most of the custom networking code you would otherwise write.`,

  pre_flight: `Install @tanstack/react-query: npm i @tanstack/react-query. Install expo-network: npx expo install expo-network. Read the TanStack Query "Getting Started" guide for React. Understand the difference between client state (what is in your app: which tab is active, form values) and server state (what comes from the server: user data, list of habits from a sync). react-query manages server state; Zustand or React Context manages client state.`,

  mastery_questions: [
    `You have a query that fetches the user's habits from the server. The user opens the app with no internet connection. What does the user see? With react-query and a cache: the cached result from the last successful fetch, immediately. The query re-fires (status: 'loading' but data is available from the cache), fails silently (isFetching: true, isError: true, but data still shows), and the UI shows stale data with an optional indicator that it could not refresh. Without a cache: a loading spinner, then an error state. The difference in user experience is significant — cached data gives the user something to work with even offline.`,
    `How does the stale-while-revalidate pattern work in react-query? Every query has a staleTime (how long the data is considered fresh) and a cacheTime (how long the data is kept in memory after the component unmounts). Default staleTime is 0 — data becomes stale immediately after fetching. When a component mounts and the query data is stale, react-query returns the stale data immediately (no loading state) while firing a background refetch. When the refetch succeeds, the UI updates with fresh data. Set staleTime to match how often the data actually changes: menu items that change once a day can have staleTime: 60 * 60 * 1000 (1 hour).`,
    `The user toggles a habit as complete. You want to update the UI immediately without waiting for the network response. How do you implement this with react-query? Optimistic updates. In the mutation's onMutate callback: call queryClient.cancelQueries(['habits']) to prevent a background refetch from overwriting your optimistic update. Snapshot the current cache: const previousHabits = queryClient.getQueryData(['habits']). Apply the optimistic update: queryClient.setQueryData(['habits'], updateFn). Return { previousHabits } as context. In onError: roll back to previousHabits using queryClient.setQueryData(['habits'], context.previousHabits). In onSettled: call queryClient.invalidateQueries(['habits']) to refetch and get the server's truth.`,
    `You send 5 API requests simultaneously when a screen mounts. With react-query, one component fetches user data, one fetches habits, one fetches completions, one fetches settings, one fetches notifications. How does react-query help with this? react-query deduplicates requests by query key — if two components both use useQuery(['user']), only one request fires. For the 5 different queries, all 5 run concurrently (no sequential waterfall). Compare to a single component that awaits each fetch in sequence — 5 × 300ms = 1500ms vs 300ms max (whichever is slowest). react-query's deduplication and concurrent fetching significantly improve perceived performance.`,
  ],

  common_mistakes: [
    `Treating server state as client state. Storing API responses in useState and managing loading/error states manually is reimplementing react-query poorly. Use react-query for all server state.`,
    `Mutating the react-query cache directly instead of using setQueryData. The cache is immutable — always create new arrays and objects, not modify existing ones. queryClient.setQueryData(['habits'], (old) => [...old, newHabit]) is correct; old.push(newHabit) is not.`,
    `Not handling retry logic. On mobile, transient network errors are common. react-query retries failed queries 3 times by default with exponential backoff. Do not wrap every request in your own retry logic — let react-query handle it. Configure retry: 3, retryDelay: (attempt) => Math.min(1000 * 2 ** attempt, 30000).`,
    `Not using query keys correctly. query keys must be stable serialisable values that uniquely identify the data. ['habits', userId] is correct — it changes when the user changes. ['habits', new Date()] is wrong — creates a new query on every render because the Date object is a different reference each time.`,
    `Making API requests on every render instead of in useQuery. Fetch in a useQuery hook; react-query ensures it only fires when the data is stale, not on every re-render.`,
  ],

  debug_help: `useQuery is refetching on every render: check your query key — if it contains an object or array that is re-created on every render, react-query sees a new key and refetches. Memoize the key: const queryKey = useMemo(() => ['habits', userId], [userId]). Mutation succeeds but UI does not update: you need to invalidate the query after the mutation. In onSuccess: queryClient.invalidateQueries(['habits']). Or use setQueryData for an immediate optimistic update. Network request fires but react-query shows isLoading: true: the queryFn might be throwing an error. Check the isError and error fields. react-query catches thrown errors and sets the error state. Offline handling not working: react-query 5 has built-in network mode options: networkMode: 'offlineFirst' pauses queries when offline. Make sure you have configured the QueryClient with the correct networkMode for your use case.`,

  ai_assist: [
    `"Set up react-query in a React Native app. Create a QueryClient with default options: staleTime 5 minutes, retry 3 times with exponential backoff, network mode 'offlineFirst'. Write a useHabits hook that fetches habits from an API and a useAddHabit mutation with optimistic updates that rolls back on error."`,
    `"Write a request queue for offline actions in React Native. When the user is offline and takes an action (add habit, toggle completion), add it to an MMKV queue. When connectivity is restored (detected via expo-network event listener), process the queue in order. Each item has a type, payload, and retry count."`,
    `"Implement the stale-while-revalidate pattern for a menu items list in React Native. The first load shows a skeleton. After the first successful fetch, subsequent loads show cached data immediately while re-fetching in the background. If offline, show cached data with an 'Offline' indicator."`,
  ],

  stretch: [
    `Implement full offline sync for Hydra. All habit completions are written to SQLite immediately (regardless of network). A background sync job runs every time connectivity is restored, sending the unsynced completions to the server. Mark each local row with a synced boolean. This is the local-first architecture pattern used by apps like Notion, Linear, and Obsidian.`,
    `Add request prioritisation. Mark some API calls as critical (auth, user data) and others as deferrable (analytics, non-urgent sync). When on a slow connection (2G detected via NetInfo), skip deferrable requests and only send critical ones.`,
    `Build an offline indicator component. When the device is offline, show a banner at the top of the screen: "You are offline — changes will sync when you reconnect." Animate it in and out using reanimated. Dismiss automatically when connectivity returns.`,
  ],
});

rewriteWeek("mobile-engineering", 14, {
  context: `Authentication on mobile has unique challenges compared to the web. There is no browser cookie jar. Sessions must be stored securely. The user expects to stay logged in for weeks or months without being asked to re-authenticate. And mobile adds capabilities the web does not have: biometric authentication (Face ID, Touch ID, fingerprint) as a convenient and secure unlock mechanism.

Token storage: after a successful login, you receive an access token (short-lived, e.g., 15 minutes) and a refresh token (long-lived, e.g., 30 days). Store both in expo-secure-store (iOS Keychain, Android Keystore). Never store them in AsyncStorage or MMKV (plaintext). The access token goes in the Authorization header of every API request. The refresh token is used to get a new access token when the current one expires.

Axios interceptors: configure an Axios instance with a request interceptor that adds the Authorization header, and a response interceptor that detects 401 responses, refreshes the token, and retries the original request. The user never knows the token was refreshed — they stay logged in transparently.

OAuth on mobile uses the device browser (not a WebView) for the OAuth flow. This is a security requirement — WebViews allow the app to read the credentials the user enters, defeating the purpose of OAuth. expo-auth-session handles this: it opens the system browser for the OAuth flow and uses a deep link to return the authorization code to your app. Configure your app's URL scheme in app.json.

Biometric authentication is not a replacement for your primary auth — it is a local unlock mechanism. The user's credentials (password or token) live in secure storage. When they open the app, instead of showing a login screen, you show a "Unlock with Face ID" prompt. If they authenticate with biometrics, you read the token from secure storage and use it. If biometrics fail or are unavailable, fall back to password.

Session management: decide when the user should be logged out. Options: never log out (refresh token rotates on use, revoke on explicit logout), log out after N days of inactivity (track lastActiveAt), log out when the app is uninstalled (secure store persists across reinstalls on iOS unless you clear it — decide whether you want this behaviour).`,

  pre_flight: `Install expo-secure-store: npx expo install expo-secure-store. Install expo-local-authentication: npx expo install expo-local-authentication. Install expo-auth-session: npx expo install expo-auth-session expo-web-browser. Install axios: npm i axios. Read the expo-local-authentication API (biometrics). Read the expo-auth-session guide for OAuth with Google. Configure your app's URL scheme in app.json (scheme: "hydra"). Build a development build — most of these features require native code.`,

  mastery_questions: [
    `A user's access token expires while they are in the middle of using the app. How does the Axios interceptor handle this transparently? The interceptor catches the 401 response. It calls the refresh token endpoint with the stored refresh token. If the refresh succeeds, it gets a new access token, stores it in secure store, and retries the original request with the new token. From the user's perspective, the request that failed with 401 completes successfully a few hundred milliseconds later — they see no error. If the refresh fails (refresh token expired), the interceptor clears the stored tokens and redirects to the login screen.`,
    `You want to add "Sign in with Apple" to your iOS app. Why is this required and what does it involve? Apple's App Store guidelines require offering "Sign in with Apple" as an option whenever you offer any third-party social login (Google, Facebook). expo-auth-session handles the flow: your app redirects to the Apple auth flow (in the system browser), Apple returns an authorization code via a deep link, your server exchanges the code for an ID token, and you create or find the user account. The tricky part: Apple only returns the user's name and email on the first login — subsequent logins only return the user ID (sub claim). Store the name and email on first login.`,
    `A user enables Face ID to unlock Hydra. The next day they open the app. Describe the full authentication flow from app open to seeing their data. AppState changes to 'active'. Your app checks secure store for an access token. It finds one. It checks whether it is still valid (parse the JWT expiry claim). It is valid. Before showing the data, your authentication gate component checks whether biometric lock is enabled (a flag in MMKV). It is. It calls LocalAuthentication.authenticateAsync(). Face ID prompt appears. User authenticates. authenticateAsync returns success. The gate unmounts and the main app renders. The access token is used for API calls. The user sees their data.`,
    `What is the difference between expo-secure-store and the Keychain Access Group on iOS? By default, expo-secure-store stores values in the app's own Keychain — inaccessible to other apps. Keychain Access Groups allow multiple apps from the same developer to share Keychain items. If you have a companion iOS widget (built with WidgetKit) that needs to read the user's auth token, both the main app and the widget extension must share a Keychain Access Group. Configure this in the Expo entitlements.`,
  ],

  common_mistakes: [
    `Storing auth tokens in AsyncStorage or MMKV. These are plaintext storage. On a rooted/jailbroken device, any app can read the file system. Tokens in plaintext are credentials. Use expo-secure-store.`,
    `Not implementing token refresh. If the access token expires and you do not refresh, the user is logged out unexpectedly. Implement the Axios interceptor or equivalent for your HTTP client.`,
    `Using a WebView for OAuth. WebViews allow the host app to intercept credentials. The correct approach is the system browser (expo-auth-session). Apple and Google both require the system browser for their OAuth flows.`,
    `Not handling biometric auth failures. LocalAuthentication.authenticateAsync can return success: false with a reason (user cancelled, too many attempts, hardware unavailable). Always check the success field and handle failure — offer password fallback.`,
    `Persisting the access token without checking its expiry on app start. If the user's session expires while the app is in the background for a week, you should detect the expired token before making API calls and silently refresh or redirect to login.`,
  ],

  debug_help: `SecureStore returns null for a key that was set: this sometimes happens after a development build reinstall on iOS — the Keychain is not cleared on uninstall by default, but signing key changes (during development) can make the old entry inaccessible. Clear the Keychain manually during development. Biometric authentication always returns success: false on simulator: biometrics require a real device. The iOS Simulator supports a simulated Face ID (Simulator > Features > Face ID), but it is not representative of real hardware. expo-auth-session deep link not returning to the app: check that your URL scheme is registered in app.json and that the redirect URI matches exactly what is registered in the OAuth provider's settings. The redirect URI for Expo is typically scheme://auth or a custom scheme.`,

  ai_assist: [
    `"Write an Axios instance for React Native that: attaches the Bearer token from SecureStore to every request, intercepts 401 responses, refreshes the token using a refresh token from SecureStore, retries the original request with the new token, and redirects to the login screen if the refresh fails."`,
    `"Write the biometric authentication gate component for Hydra. When the app comes to the foreground (AppState change), show a lock screen with Face ID / fingerprint prompt if biometric lock is enabled. On success, show the main app. On failure, show a 'Use password instead' option. Use expo-local-authentication."`,
    `"Implement Sign in with Google on React Native using expo-auth-session. Show the auth flow: redirect to Google in the system browser, receive the code via deep link, exchange the code for tokens on the backend, store the access token in SecureStore. Include error handling."`,
  ],

  stretch: [
    `Implement automatic logout after 30 days of inactivity. Track lastActiveAt in MMKV — update it every time the app comes to the foreground. On app open, check if lastActiveAt is more than 30 days ago. If so, clear the tokens and show the login screen. This is a security requirement for many enterprise apps.`,
    `Add multi-account support. Let the user store credentials for multiple accounts (e.g., personal and work). Store each account's token under a different SecureStore key. The account switcher reads all stored accounts and lets the user choose the active one.`,
    `Implement end-to-end encrypted notes in Hydra. Generate a per-user encryption key, derived from their password using PBKDF2, stored nowhere — regenerated on each login. Encrypt habit notes using AES-256-GCM before storing in SQLite. The server never sees plaintext notes.`,
  ],
});

rewriteWeek("mobile-engineering", 15, {
  context: `Background tasks on mobile are heavily restricted. The operating system aggressively kills background processes to preserve battery life. Understanding what you can and cannot do in the background is essential for building features that work reliably.

iOS background modes: apps can run in the background for specific, declared purposes: audio playback, location updates, background fetch, push content (VoIP, remote notifications with content-available). You declare these in app.json (UIBackgroundModes). Background fetch is the most generally useful — iOS allocates a short window (30 seconds) for your app to run when the OS decides to (typically when the device is charging, on Wi-Fi, and other apps are not actively using resources). You cannot control when this fires.

Android background tasks: more permissive than iOS but increasingly restricted in newer versions. WorkManager (the recommended Android background API) schedules deferrable, guaranteed background work. It respects battery optimisation, runs on device idle when connected to power, and guarantees execution even if the device reboots.

expo-task-manager wraps both platforms' background task systems. You define tasks with TaskManager.defineTask and trigger them with BackgroundFetch.registerTaskAsync (periodic) or Location.startGeofencingAsync (location-triggered). Tasks must complete within the allotted time.

Local notifications as background substitutes: for many "background task" use cases, scheduled local notifications are more reliable. Instead of running background code to check a condition and then show a notification, pre-schedule the notification at a known time. The OS delivers it without waking your app. For reminders (the W2 case), this is always the right approach.

Background fetch realistic expectations: iOS decides when to run background fetch. It uses adaptive scheduling based on how often your app's background fetch updates content that the user then accesses. If users frequently open the app right after a background fetch, iOS schedules it more often. If not, it schedules rarely or never. Do not build features that depend on reliable background fetch timing.`,

  pre_flight: `Install expo-background-fetch: npx expo install expo-background-fetch. Install expo-task-manager: npx expo install expo-task-manager. Add the UIBackgroundModes: ['background-fetch'] to app.json (iOS). Build a development build — background tasks require native code. Read Apple's documentation on "Background Execution" to understand the constraints. Read the expo-background-fetch documentation including the "Limitations" section.`,

  mastery_questions: [
    `You want to sync Hydra's habit completions to a server every hour in the background. Can you rely on expo-background-fetch for this? No. Background fetch is unreliable for scheduled, time-critical tasks. iOS decides when to run it based on its own heuristics — it may run every hour or once a day. The reliable alternative: when the user makes a change (checks off a habit), sync immediately in the foreground. If the sync fails (offline), queue it locally (SQLite with a synced=false flag) and retry when the app next comes to the foreground (AppState active event). Background fetch can be used as an opportunistic sync to catch anything missed, but not as the primary sync mechanism.`,
    `What happens to an async JavaScript function that is running when iOS suspends your app mid-execution? iOS suspends the app process when it moves to the background. Any running JavaScript code is frozen. Pending Promises are frozen. Network requests are paused (on iOS, NSURLSession background sessions can continue but expo-managed requests do not). When the app returns to the foreground, code resumes from where it was paused. For background tasks (registered with expo-task-manager), the task runs in a separate context that iOS wakes briefly — the task must complete within 30 seconds and call BackgroundFetch.BackgroundFetchResult to inform iOS whether new data was fetched.`,
    `You need to play audio continuously while the app is in the background (a meditation timer, music player). What configuration is required? Declare the audio background mode: add 'audio' to UIBackgroundModes in app.json (iOS). Configure the audio session category to allow background audio: Audio.setAudioModeAsync({ staysActiveInBackground: true, playsInSilentModeIOS: true }). iOS will not kill your app while audio is playing (as long as the audio session is active). On Android, use a Foreground Service — a service that shows a persistent notification while running, which prevents the OS from killing it.`,
    `A user reports that their Hydra daily reset did not happen — they woke up and all their habits were still checked from yesterday. The reset was supposed to happen at midnight via background fetch. What likely happened and what is the reliable fix? The background fetch did not run at midnight — iOS chose not to wake the app. The reliable fix: do not use background fetch for the reset. Instead, check the date on every app foreground event (AppState change to 'active'). If today's date is different from the last-reset date (stored in MMKV), perform the reset. This runs reliably every time the user opens the app, even after days of not using it.`,
  ],

  common_mistakes: [
    `Building features that depend on background fetch running at predictable times. Background fetch is best-effort. Design features so they work correctly even if background fetch never runs. Use foreground checks as the primary mechanism.`,
    `Running long operations in background tasks. iOS gives you 30 seconds. If you exceed it, the task is killed and your data may be left in a corrupt state. Keep background tasks short: download a small data payload, update a local cache, schedule a notification.`,
    `Not calling the completion handler in background tasks. iOS requires you to call BackgroundFetch.BackgroundFetchResult.(NewData | NoData | Failed) to inform the OS whether new data was available. If you do not call it, iOS marks the fetch as failed and may reduce the frequency of future background fetch opportunities.`,
    `Using background tasks as a substitute for proper offline support. Background tasks are unreliable. If your app needs to work offline and sync when back online, use a local-first architecture with foreground sync — not background tasks.`,
    `Not testing background tasks on a real device. Background fetch behaviour is not accurately simulated in simulators. Test on a physical device. Use the Xcode Debug > Simulate Background Fetch menu item to trigger a background fetch manually for testing.`,
  ],

  debug_help: `Background fetch never fires: this is expected during development. iOS schedules background fetch based on usage patterns — apps that are barely used get scheduled rarely. Use the Xcode simulator's "Simulate Background Fetch" or expo-background-fetch's setMinimumIntervalAsync(1) (minimum interval of 1 second, for testing only). Background task is killed before completing: reduce the work done in the task. Log the start time and completion time — if the task takes more than 25 seconds, you are cutting it close. Move heavy work to a foreground operation. AppState events not firing: make sure you call AppState.addEventListener (not AppState.addChangeListener, which is deprecated) and store the subscription to remove it on unmount.`,

  ai_assist: [
    `"Write the complete background fetch setup for Hydra using expo-task-manager and expo-background-fetch. Define a task that: checks the last sync date, fetches habit updates from the server if more than 6 hours have passed, updates SQLite, and returns BackgroundFetch.BackgroundFetchResult.NewData or NoData. Register the task with a minimum interval of 15 minutes."`,
    `"Write a foreground sync trigger for Hydra. When the app comes to the foreground (AppState becomes 'active'): check if more than 5 minutes have passed since the last sync (stored in MMKV), if so, call syncHabits() which posts any unsynced completions to the server and marks them as synced in SQLite."`,
    `"Show how to implement background audio in a React Native meditation app. Configure the audio session for background playback, play audio from a URI with expo-av, and add a now-playing notification (lock screen controls) for play/pause."`,
  ],

  stretch: [
    `Implement a Widgets extension for iOS using react-native-widgetkit (or a native Swift widget). The widget shows today's habit completion count on the home screen. It reads data from the shared App Group container (a shared storage area between the main app and the widget). This requires native code.`,
    `Add Siri Shortcuts integration. Register Hydra's "Check off habit" as a Siri Shortcut. The user can say "Hey Siri, check off my morning run in Hydra." This uses expo-intent-launcher and native Siri Intents configuration. A rare feature in indie apps that makes a strong impression.`,
    `Implement a live activity for iOS 16+ using ActivityKit. When the user starts a timed habit (e.g., a 20-minute meditation), show a Live Activity on the lock screen and Dynamic Island with a countdown timer. This is native-only and requires Swift.`,
  ],
});
